### ISSUE TITLE
`"Unable to load module core.completion .. attempt to call field 'get_language_list' (a nil value)"` error after updating to latest commit

### ISSUE THREAD

**Issue by xfzv** [nvim-neorg/neorg#1002]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Neorg setup

```lua
        {
		"nvim-neorg/neorg",
		ft = "norg",
		dependencies = { "nvim-treesitter/nvim-treesitter" },
		build = ":Neorg sync-parsers",
		config = function()
			require("neorg").setup({
				load = {
					["core.defaults"] = {},
					["core.clipboard"] = {},
					["core.clipboard.code-blocks"] = {},
					["core.completion"] = {
						config = {
							engine = "nvim-cmp",
						},
					},
					["core.concealer"] = {
						config = {
							dim_code_blocks = {
								enabled = true,
								conceal = true,
								content_only = true,
								adaptive = true,
							},
							icon_preset = "diamond",
						},
					},
				},
			})
		end,
	},

```

### Actual behavior

After updating to 5706f1efdcf55f273de8f52deeb35375a303be72, I'm always getting the following error when Neorg is loaded:

![image](https://github.com/nvim-neorg/neorg/assets/78810647/57d75fda-ca04-483a-afb3-99c3d5074810)

Reverting to e76f0cb6b3ae5e990052343ebb73a5c8d8cac783 with

```lua
{
		"nvim-neorg/neorg",
		commit = "e76f0cb6b3ae5e990052343ebb73a5c8d8cac783",
-- ..
```

fixes the issue on my end.

### Expected behavior

No error is printed.

### Steps to reproduce

1. Update to 5706f1efdcf55f273de8f52deeb35375a303be72
2. The error always appear
3. Revert to e76f0cb6b3ae5e990052343ebb73a5c8d8cac783
4. The error is gone

### Help

None

**Comment by roland-5** [comment]
Yup, I wanted to report this too.

```
[neorg] (22:13:07)
.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:438
Unable to load module core.completion - .../lazy/neorg/lua/neorg/modules/core/completion/module.lua:127: attempt to call field 'get_langu
age_list' (a nil value)
Press ENTER or type command to continue
[neorg] (22:13:07)
/home/roland/.local/share/nvim/lazy/neorg/lua/neorg.lua:95
Recovering from error...
Press ENTER or type command to continue
```

https://github.com/nvim-neorg/neorg/commit/5706f1efdcf55f273de8f52deeb35375a303be72 Did something bad.

**Comment by Groctel** [comment]
This breakage is part of the #999 project. The first commit (#1001) is going to be the biggest one and it had chances to break things. @roland-5, please paste your config so that I can reproduce your error and fix it properly.

**Comment by roland-5** [comment]
@Groctel Ups, my bad. I updated my comment with my neorg configuration now.

**Comment by roland-5** [comment]
Thank you @Groctel. <3
