### ISSUE TITLE
E434: Can't find tag pattern when using :h neorg

### ISSUE THREAD

**Issue by Fissium** [nvim-neorg/neorg#1009]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Neorg setup

```
return {
  "nvim-neorg/neorg",
  build = ":Neorg sync-parsers",
  dependencies = { "nvim-lua/plenary.nvim" },
  event = "VeryLazy",
  opts = {
    load = {
      ["core.defaults"] = {}, -- Loads default behaviour
      ["core.concealer"] = {}, -- Adds pretty icons to your documents
      ["core.keybinds"] = {}, -- Adds default keybindings
      ["core.completion"] = {
        config = {
          engine = "nvim-cmp",
        },
      }, -- Enables support for completion plugins
      ["core.journal"] = {}, -- Enables support for the journal module
      ["core.dirman"] = { -- Manages Neorg workspaces
        config = {
          workspaces = {
            notes = "~/Documents/Notes",
          },
          default_workspace = "notes",
        },
      },
    },
  },
}
```

### Actual behavior

Hi. https://github.com/nvim-neorg/neorg/issues/994 
There's the same error, but now only with `:h neorg`. Everything else works fine, for example `:h neorg-math`.
![image](https://github.com/nvim-neorg/neorg/assets/35971213/6dceb50c-bb75-45c9-8292-0d0f14090fa7)

### Expected behavior

No errors

### Steps to reproduce

run `:h neorg`

### Other information

I use Astronvim Neovim config

### Help

None

**Comment by vhyrro** [comment]
Fixed fully now! :D
