### ISSUE TITLE
auto-indent stopped working

### ISSUE THREAD

**Issue by snomics** [nvim-neorg/neorg#1011]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-761+g3d3ec27d5

### Neorg setup

```
require('neorg').setup {
  load = {
    ['core.defaults'] = {},
    ['core.summary'] = {},
    ['core.ui.calendar'] = {},
    ['core.highlights'] = {},
    ['core.keybinds'] = {},
    ['core.dirman'] = {
      config = {
        workspaces = {
          perso = '~/neorg/perso',
          pro = '~/neorg/pro'
        },
        autochdir = false,
      }
    },
    ['core.completion'] = {
      config = {
        engine = 'nvim-cmp'
      },
    },
    ['core.integrations.nvim-cmp'] = {},
    ['core.concealer'] = {},
      ['core.esupports.metagen'] = {},
      ['core.journal'] = {
        config = {
          workspace = 'perso',
          strategy = 'flat',
        },
      },
      ['core.export'] = {},
      ['core.integrations.telescope'] = {},
    }
}



```

### Actual behavior

![2023-08-04-123814_381x215_scrot](https://github.com/nvim-neorg/neorg/assets/106830543/d69a9009-92ad-4d75-aadc-72c7c4bb420b)

returning in `insert mode` on the line or using `=` don’t have any effect.

### Expected behavior

behavior as before 5706f1efdcf55f273de8f52deeb35375a303be72

![2023-08-04-124153_582x221_scrot](https://github.com/nvim-neorg/neorg/assets/106830543/7e48b053-9ac2-4c3a-ab5e-50b31124e50c)

### Steps to reproduce

Write about your holidays in a norg file (using headings)

### Other information

I don’t know if the refactor introduce the need to change something in the config, as there is no breaking-change information for low skilled end-user like me. :)

### Help

None

**Comment by vhyrro** [comment]
Has since been fixed in the latest commit! Some things were simply missed in the big refactor, the codebase is pretty large so there were bound to be some things left over :p
