### ISSUE TITLE
Add mention to `awesome-neorg` in the README

### ISSUE THREAD

**Issue by pysan3** [nvim-neorg/neorg#1018]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I recently discovered https://github.com/NTBBloodbath/awesome-neorg, which lists lot of external modules and links to other useful contents as well.

I thought it would be nice if you could mention this repo in the README.

For example I believe awesome-neorg is doing a better job than this section: [# External Modules](https://github.com/nvim-neorg/neorg#external-modules).

Thanks in advance!

### Help

No

**Comment by vhyrro** [comment]
Great idea, done! :)
