### ISSUE TITLE
Adding Glyphs or icons Support for Neorg files [nerd fonts]

### ISSUE THREAD

**Issue by noornee** [nvim-neorg/neorg#1019]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

First and foremost, I want to express my excitement about discovering Neorg and its incredible note-taking capabilities within NeoVim. As a newcomer, I've been truly impressed with the features I've seen so far, and I'm eager to dive deeper into its other features!

As someone who hasn't extensively used Emacs org-mode(i haven't even used it at all), Neorg is already perfect for my needs. ;)

In line with the already exceptional design of Neorg, I'm opening this issue to propose the inclusion of glyphs or icons for Neorg files. While the existing interface is already visually appealing, the addition of icons could further enhance the aesthetic and user experience.

## Screenshot
![neorg_missing_glyph](https://github.com/nvim-neorg/neorg/assets/71889751/9fe67adc-c5ed-404e-9053-48603c3cdc5f)

### Help

No

### Implementation help

I'm not familiar with the technical aspects of making icons but i believe we are going to leverage a font library like nerd fonts (^_^)'

**Comment by pysan3** [comment]
Duplicate: https://github.com/nvim-neorg/neorg/issues/792

**Comment by noornee** [comment]
> Duplicate: #792

ouuu my bad!
i didn't realize there was an existing issue about this already. Thanks ^^

**Comment by pysan3** [comment]
As I said in the above issue, neorg has an official color but has no independent icon added in nerd font. 

If you have some knowledge, I'd be more than happy if you could submit a PR upstream to add an icon.

**Comment by pysan3** [comment]
And here's the official icon. 

The problem we only have here is that it's not added to nerd font. 

https://github.com/devicons/devicon/pull/1346

**Comment by noornee** [comment]
> As I said in the above issue, neorg has an official color but has no independent icon added in nerd font.

yess, i saw!

> If you have some knowledge, I'd be more than happy if you could submit a PR upstream to add an icon.

and no, i have no knowledge on how to add icons to nerd fonts :/
