### ISSUE TITLE
README lazy.nvim configuration not working

### ISSUE THREAD

**Issue by hu-shuwei** [nvim-neorg/neorg#1024]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-575+ge59cf3b3a

### Neorg setup

```lua
-- init.lua:

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  print(vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }))
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " " -- Make sure to set `mapleader` before lazy so your mappings are correct

require("lazy").setup({
  "rebelot/kanagawa.nvim",
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = { "c", "lua", "vim", "python" },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
  {
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.concealer"] = {},
          ["core.dirman"] = {
            config = {
              workspaces = {
                notes = "~/notes",
              },
            },
          },
        },
      }
    end,
  }
})

vim.cmd.colorscheme('kanagawa')
```

### Actual behavior

No highlights, bold, underline, etc.
![image](https://github.com/nvim-neorg/neorg/assets/141699393/c1b7076c-f32f-4fc6-9524-1980c19d549e)
![image](https://github.com/nvim-neorg/neorg/assets/141699393/ca2e1361-40a1-4f3b-b5d5-ea153ba1eaf7)

### Expected behavior

With highlights, bold, underline, etc.

### Steps to reproduce

`nvim test.norg`, then type what's in the above screenshot.
Or `:help neorg`

### Help

None

**Comment by fmuhic** [comment]
I have the same issue after switching from packer to lazy. Some highlights work, like headlines, others like bold, italic etc. don't.
Also some symbols don't work either (like todos done symbol)

**Comment by vhyrro** [comment]
Should now be fixed! Update Neorg and let me know if it works :)

**Comment by hu-shuwei** [comment]
I confirm that the problem is fixed. Thanks!
