### ISSUE TITLE
Calendar plugin not working because of Tempus error

### ISSUE THREAD

**Issue by SteveWolligandt** [nvim-neorg/neorg#1035]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.1

### Neorg setup

``` lua
return {
  "nvim-neorg/neorg",
  opts = {
    load = {
      ['core.defaults'] = {},
      ['core.neorgcmd'] = {},
      ['core.summary'] = {},
      ['core.journal'] = {},
      ['core.autocommands'] = {},
      ['core.export'] = {config={}},
      ['core.export.markdown'] = {config={}},
      ['core.integrations.treesitter'] = {config={}},
      ['core.ui'] = {},
      ['core.ui.calendar'] = {},
      ['core.dirman'] = {
        config = {
          workspaces = {
            notes = '~/notes',
          },
          default_workspace='notes'
        }
      },
      ['core.qol.todo_items'] = {
        config = {
          create_todo_items = true,
          create_todo_parents = true,
        },
      },
      -- ['core.esupports.hop'] = {
      --   config = {}
      -- },
      ['core.concealer'] = {
        config={
          icons={
            code_block = {
              conceal=true,
            },
          },
        }
      },
      -- ['core.keybinds'] = {
      --   config = {}
      -- },
      -- ['core.presenter'] = {
      --   config = { zen_mode = 'zen-mode' }
      -- }
    }
  },
  dependencies = {
    'nvim-lua/plenary.nvim',
    'folke/zen-mode.nvim',
    'lukas-reineke/headlines.nvim',
  },
  build = ":Neorg sync-parsers",
  keys = {
    { '<leader>ni', "<cmd>Neorg index<cr>",   desc = "Open Index" },
    { '<leader>nj', "<cmd>Neorg journal<cr>", desc = "Journal" },
    { '<leader>nt', "<cmd>Neorg toc<cr>",     desc = "TOC" },
  },
}
```

### Actual behavior

Getting these errors when opening a .norg file for nvim 0.9

   Error  14:48:27 notify.error [neorg] (14:48:27)
...ta/Local/nvim-data/lazy/neorg/lua/neorg/core/modules.lua:438
Unable to load module core.tempus - ...data/lazy/neorg/lua/neorg/modules/core/tempus/module.lua:18: attempt to index field 're' (a nil value)
   Error  14:48:27 notify.error [neorg] (14:48:27)
...ta/Local/nvim-data/lazy/neorg/lua/neorg/core/modules.lua:330
Unable to load module core.ui.calendar.views.monthly, required dependency core.tempus did not load successfully
   Error  14:48:27 notify.error [neorg] (14:48:27)
...ta/Local/nvim-data/lazy/neorg/lua/neorg/core/modules.lua:330
Unable to load module core.ui.calendar, required dependency core.ui.calendar.views.monthly did not load successfully

### Expected behavior

No errors in Tempus

### Steps to reproduce

Just add `['core.ui.calendar'] = {},` to the `load` field.

### Help

None

**Comment by salkin-mada** [comment]
Switching to 0.10 resolves the issue.
```
❯ nvim --version                  
NVIM v0.10.0-dev-978+g7c4d317a66
Build type: RelWithDebInfo
LuaJIT 2.1.1692616192
```

**Comment by Diego-Llanes** [comment]
I still have this issue and cannot move to this version of nvim.

**Comment by vhyrro** [comment]
Hey, as @salkin-mada said this is because you're not on 0.10+. I just pushed a change which should give you a much more informative error message whenever you try loading tempus without the appropriate nightly build! :)
