### ISSUE TITLE
add syntax for external file with relative path

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1039]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently one can specify an external file with `{file:///absolute/path}', but URI with file scheme can only represent an absolute path.

It would be nice if one can specify an external file with relative path as well, for example `{./relative/path/text.docx}'.

### Help

Yes

**Comment by vhyrro** [comment]
Already doable! `{/ myfile.docx}` is a relative filepath by default :)

**Comment by champignoom** [comment]
Sorry I wasn't clear that I was looking for a syntax that is opened with xdg-open. `{/ myfile.docx}` will be opened with neovim and is unreadable.

**Comment by vhyrro** [comment]
The `{/ }` syntax is also opened by xdg-open, however Neorg has an internal list of formats that it opens this way. currently i think pdfs and images are on that list only, so adding other things like docx would be useful. Either that, or we could approach the problem the other way around and open everything with xdg-open unless it's a known text format in which case it's opened by Neovim.

**Comment by champignoom** [comment]
Or just add a an event like "hop-link-external" together with a keybinding, so that the users can open in either way they want.
