### ISSUE TITLE
more keybindings for traverse-heading mode

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1043]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently we have
- `j` for moving to the next heading
- `k` for moving to the previous heading

More keybindings could be helpful as well, for example:
- `J` for moving to the next sibling at the same level
- `K` for moving to the previous sibling at the same level
- `h` for moving to the parent
- `l` for moving to the last child from which we jumped to the current heading using `h`

### Help

Yes

**Comment by benlubas** [comment]
Traverse heading mode was recently deprecated
