### ISSUE TITLE
Can't fold headings in new norg file

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1047]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-575+ge59cf3b3a

### Neorg setup

```lua
require("lazy").setup({
  {
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {}, -- Loads default behaviour
          ["core.concealer"] = {}, -- Adds pretty icons to your documents
          ["core.dirman"] = { -- Manages Neorg workspaces
            config = {
              workspaces = {
                notes = "~/notes",
              },
            },
          },
        },
      }
    end,
  },
})
```

### Actual behavior

E490: No fold found

### Expected behavior

The heading should be folded.

### Steps to reproduce

`nvim new-note.norg`, type

```
* heading
  something
```

then press `zc` at the heading.

### Help

Yes

**Comment by max397574** [comment]
if it does work if you do `:w` and `:e` then that's just from nvim-treesitter side

**Comment by champignoom** [comment]
Yeah it seems so.

**Comment by max397574** [comment]
you can close this as wontfix then
there are already issues for this
https://github.com/nvim-neorg/neorg/issues/965
perhaps this as well https://github.com/nvim-neorg/neorg/issues/832

**Comment by champignoom** [comment]
Oh true sorry I missed that one
