### ISSUE TITLE
Calendar UI corrects to current weekday instead of selected one

### ISSUE THREAD

**Issue by KodyVB** [nvim-neorg/neorg#1059]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-953+g1635c9e75

### Neorg setup

```lua
return {
	"nvim-neorg/neorg",
	build = ":Neorg sync-parsers",
	event = "VeryLazy",
	dependencies = {
		"folke/zen-mode.nvim",
		"nvim-lua/plenary.nvim",
	},
	opts = {
		load = {
			["core.defaults"] = {},
			-- ["core.gtd.base"] = {},
			["core.integrations.nvim-cmp"] = {},
			["core.completion"] = {
				config = {
					engine = "nvim-cmp",
				},
			},
			["core.concealer"] = {
				config = {
					icon_preset = "basic",
				},
			},
			["core.qol.toc"] = {
				config = {
					close_after_use = true,
				},
			},
			["core.presenter"] = {
				config = {
					zen_mode = "zen-mode",
				},
			},
			-- ["core.qol.toc"] = {},
			["core.dirman"] = {
				config = {
					workspaces = {
						norg = "~/Documents/neorg",
					},
					default_workspace = "norg",
				},
			},
			["core.summary"] = {},
			["core.ui.calendar"] = {},
			["core.syntax"] = {},
			["core.esupports.metagen"] = {
				config = {
					type = "empty",
				},
			},
		},
	},
}
```

### Actual behavior

If picking a Sunday while the current day is Wednesday, for example, it will fill in Wednesday instead of Sunday.

### Expected behavior

It fills in to the selected day instead of the current day.

### Steps to reproduce

1.  Write `{@ Aug 6}` in a norg file
2. In normal mode, press `<CR>` while in the `{}`
3. Select August 6th, which should be a Sunday
4. If the current day is not Sunday, see that it selected the current day instead

### Other information

If you type `{@ Sat Aug 6}` and repeat steps 2-4, it'll fill in `{@ Saturday 6 August 2023}` instead of Sunday, too.

### Help

None

**Comment by max397574** [comment]
https://github.com/nvim-neorg/neorg/pull/1058
this?

**Comment by KodyVB** [comment]
Yup. Sorry about that - I woke up, saw your suggestion to report the issue, searched for open issues with "calendar" in it, didn't see one, and posted it. I should have checked pull requests, too.

**Comment by max397574** [comment]
no worries
it's still good if there also is an issue

**Comment by vhyrro** [comment]
Should now be fixed with the latest commit! Feel free to reopen if something is still not right :)
