### ISSUE TITLE
Toggle multiple todo-s

### ISSUE THREAD

**Issue by kflak** [nvim-neorg/neorg#1089]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hi,

Just wondering if there is a way to toggle all selected items or toggle with movement? Say, for example I'm on item 3 in a todo list, and I'd like to set everything until the end of the list to `not done`?

Or, at the very least, be able to repeat the toggling action with the dot operator...?

### Help

No

**Comment by Anrock** [comment]
Checkboxes for todo items are usual characters and you can change they status by changing character to corresponding status (space for not done). So you can move your cursor over the character and replace it with space by pressing `r<SPC>`. This is repeatable with dot. Also you can use block mode (`^v`) to select multiple items and change their status at once.

**Comment by max397574** [comment]
ig it would also be possible to add a visual mode keybinding
or also operator pending (so you can use it with a motion)
where you just subsitute
`vim.keymap.set("v","<localleader>td","<cmd>s/( )/(x)<cr>")`

**Comment by kflak** [comment]
Thanks both! Can't believe I got so blinded by the flashy formatting that I didn't realize immediately that it's just a space or an x in disguise...
