### ISSUE TITLE
Clone Git repositories as workspaces

### ISSUE THREAD

**Issue by linguini1** [nvim-neorg/neorg#1090]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

## Proposal
Workspaces are a great feature of Neorg for keeping notes separated and organized. Like (I would imagine) many Neorg users, I keep my notes synced across devices by making the workspace directories Git repositories. Unfortunately, whenever I use my configuration on a new machine or add a new workspace based on one of my notes repositories, I have to set up the Git repository again from scratch. It would be nice if Neorg allowed you to initialize workspaces with Git repos.

I'm imagining that when providing your workspace names, you also provide a Git repo link for it to clone from:
```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.dirman"] = {
            config = {
                workspaces = {
                    my_ws = {
                        dir = "~/neorg",
                        git = "https://github.com/nvim-neorg/neorg.git" -- Supply full link for private repo
                    },
                    my_other_notes = {
                        dir = "~/work/notes",
                        git = "linguini1/notes" -- Supply public git like package manager (or full link)
                    },
                },
                index = "index.norg",
            }
        }
    }
}
```

Then Neorg would automatically perform the clone when the directory is set up.

## Flaws

I can see that this idea may be flawed as it is only necessary to set up these git repos when creating the directories initially. Users could just do as I have done and create their desired folder structure manually with the git repos cloned, and then point Neorg to those create directories in the workspace configuration. It may take more work to maintain this than Neorg would like to take responsibility for.

On the other hand, it would be a great quality of life improvement to have Neorg handle this behind the scenes so that users don't have to repeat this manual setup for their Git repos across multiple devices.

### Help

Yes

### Implementation help

I could take a look at the current workspace implementation to see about changing this. I would like advice on how to implement this so as not to break the existing configuration interface (i.e. as in my example where tables are provided for workspaces instead of strings).

**Comment by max397574** [comment]
the title of this issue is very missleading. I expected it to be about `git init` which it isn't
I think this is a duplicate of https://github.com/nvim-neorg/neorg/issues/989

**Comment by linguini1** [comment]
> the title of this issue is very missleading. I expected it to be about `git init` which it isn't I think this is a duplicate of #989
You're right! Somehow I missed that issue when searching. Thanks for pointing that out!
