### ISSUE TITLE
Auto-indent/format with `=` doesn't work with some code blocks

### ISSUE THREAD

**Issue by leongjs98** [nvim-neorg/neorg#1100]
mentioned by @pysan3 in this [issue](https://github.com/nvim-neorg/neorg/issues/874#issuecomment-1734763766)

### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.2

### Neorg setup

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {},
    ["core.concealer"] = {
      config = {
        icon_preset = "diamond"
      }
    },
    ["core.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.summary"] = {},
    ["core.presenter"] = {
      config = {
        zen_mode = "zen-mode"
      }
    },
    ["core.dirman"] = {
      config = {
        workspaces = {
          main = "~/Documents/notes",
          personal = "~/Documents/notes/personal",
          work = "~/Documents/notes/work",
        },
        default_workspace = "work"
      },
    },
    ["core.journal"] = {
      config = {
        workspace = "personal"
      }
    },
    ["core.keybinds"] = {
      config = {
        hook = function(keybinds)
          keybinds.remap_event("norg", "n", "<LocalLeader>t ", "core.qol.todo_items.todo.task_cycle")
        end,
      }
    }
  },
}

```

### Actual behavior

```norg
@code bash
#!/bin/bash

for number in {1..5}; do
    echo "Number: $number"
done
@end
```

### Expected behavior

```norg
@code bash
#!/bin/bash

for number in {1..5}; do
echo "Number: $number"
done
@end
```

### Steps to reproduce

Indent the bash code blocks with `=`

### Other information

Tested some other languages and these are the result

| code | auto-indent result |
|:---- |:------:|
| Bash | not working |
| Go | working |
| JavaScript | working |
| Lua | working |
| Norg | not working |

I have lsp installed for all of them

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I am not familiar with lua or neovim ecosystem. So, it will take some time to learn it. I may also need someone to guide me when I am hard stuck.

But I am a keen learner and I am passionate about neorg and neovim. So, I can probably solve it, and if I get stuck, I will ask for help in the discord.

**Comment by max397574** [comment]
I think we just try to use treesitter indentation (or that's what used automatically when you have injections) inside code blocks.
So you should install the bash parser and I think for norg we just have to write better indent queries.

**Comment by vhyrro** [comment]
Languages that use the off-side rule tend to break because they rely on indentation levels moreso than free-form languages like JS or lua or whatever. This is a core limitation of the current treesitter injection engine that simply can't be fixed from our end, sorry :/

Closing the issue as wontfix for the time being. If there ever is a solution I'll be sure to implement it :)

**Comment by austinbutler** [comment]
Is there a way to exclude a code block from being reformatted? 

It's not so bad that it won't automatically format it correctly, but the indentation getting wrecked every time you format the Neorg file makes it to where adding code snippets for these languages is just about untenable.
