### ISSUE TITLE
"LanguageTree:for_each_child() is deprecated, use LanguageTree:children() instead."

### ISSUE THREAD

**Issue by sekomidev** [nvim-neorg/neorg#1104]
### Prerequisites

- [ ] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-5f4f83b

### Neorg setup

{
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    dependencies = { "nvim-lua/plenary.nvim", { "laher/neorg-exec" } },
    config = function()
      require("neorg").setup({
        load = {
          ["core.defaults"] = {}, -- Loads default behaviour
          ["core.concealer"] = {
            config = {
              icons = {
                todo = {
                  urgent = {
                    icon = "!",
                  },
                },
              },
            },
          }, -- Adds pretty icons to your documents
          ["core.dirman"] = { -- Manages Neorg workspaces
            config = {
              workspaces = {
                notes = "~/notes",
                diary = "/mnt/crypt/diary",
              },
              default_workspace = "notes",
            },
          },
          ["core.ui.calendar"] = {
            config = {
              strategy = "nested",
            },
          },
          ["core.esupports.metagen"] = {
            config = {
              template = {
                {
                  "title",
                  function()
                    return vim.fn.expand("%:t:r")
                  end,
                },
                { "description", "" },
                {
                  "authors",
                  function()
                    return vim.fn.getenv("USER")
                  end,
                },
                { "categories", "" },
                {
                  "created",
                  function()
                    return os.date("%Y-%m-%d %H:%M %z")
                  end,
                },
                {
                  "updated",
                  function()
                    return os.date("%Y-%m-%d %H:%M %z")
                  end,
                },
              },
            },
          },
          ["external.exec"] = {},
        },
      })
    end,
  },

### Actual behavior

Upon saving a file with any metadata in it, these two warnings appear:
- LanguageTree:for_each_child() is deprecated, use LanguageTree:children() instead. :help deprecated
This feature will be removed in Nvim version 0.11
- stack traceback:
	...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:466: in function 'for_each_child'
	...eorg/lua/neorg/modules/core/esupports/metagen/module.lua:248: in function 'update_metadata'
	...eorg/lua/neorg/modules/core/esupports/metagen/module.lua:338: in function <...eorg/lua/neorg/modules/core/esupports/metagen/module.lua:337>

![image](https://github.com/nvim-neorg/neorg/assets/68436279/54295068-9b3e-4365-b4be-4b16932c96ed)

Since this is a deprecation warning, it doesn't seem to affect the functionality for now.

### Expected behavior

I expected to see no such warnings.

### Steps to reproduce

- Create a new file with .norg extension
- Run the following command in neovim: `Neorg inject-metadata`
- Try to save the file

### Other information

It seems that these warnings only occur in the metagen module. While I do have a custom template, it shouldn't affect the presence of the warning in any way.

Not sure if this is really a bug, since the plugin still works, but I didn't see anyone mention this issue before.

### Help

None

**Comment by max397574** [comment]
this issue will occur to anyone using a relatively new neovim-nightly. There is no replacement function for this one which actually makes things easier because we don't have to check if a new function exists. There are some examples of how this function can be replaced in the pr which deprecated it. I just haven't found the time to do that yet.

**Comment by vhyrro** [comment]
This has since been fixed in the latest commit, check it out! :)
