### ISSUE TITLE
Module `core.summary` ignores metadata

### ISSUE THREAD

**Issue by austinbutler** [nvim-neorg/neorg#1108]
### Prerequisites

- [ ] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.10.0-dev-6823fdb

### Neorg setup

	require("neorg").setup({
		load = {
			["core.defaults"] = {},
			["core.concealer"] = {},
			["core.dirman"] = {
				config = {
					workspaces = {
						notes = "~/notes",
					},
				},
			},
			["core.presenter"] = { config = { zen_mode = "truezen" } },
			["core.summary"] = {},
			["core.integrations.telescope"] = {},
		},
	})

### Actual behavior

`Neorg generate-workspace-summary` generates a summary where everything is under `Uncategorized` and it seems to ignore the title field, too.

### Expected behavior

`Neorg generate-workspace-summary` uses the metadata.

### Steps to reproduce

Add metadata to a note using `inject-metadata`.

```
@document.meta
title: My title
description: My description
authors: austin
categories: Tickets
created: 2023-10-08T13:52:16-0800
updated: 2023-10-08T13:52:16-0800
version: 1.1.1
@end
```

Run `generate-workspace-summary`.

### Other information

Possibly a different issue with the same module: https://github.com/nvim-neorg/neorg/discussions/1085.

### Help

None

**Comment by snomics** [comment]
To add some information, categories are taken into account once a file has been opened. For this file only.

**Comment by caprilesport** [comment]
Is the behaviour commented by @snomics supposed to be the default?

I'm also suffering a bit with it, as sometimes new files are added in a workspace and when i re-generate the summary I have to open all files to have the correct indexing.

**Comment by aswa2ds** [comment]
I met the same situation. And I solved by modified the `get_document_metadata` function in "neorg/lua/neorg/modules/core/integrations/treesitter" like this, and sovled  your question at the same time @caprilesport :
```
    get_document_metadata = function(buf, no_trim)
        buf = buf or 0

        local languagetree = vim.treesitter.get_parser(buf, "norg_meta")

        if not languagetree then
            return
        end

        local result = {}

        -- for _, tree in ipairs(languagetree:children()) do
            -- if tree:lang() ~= "norg_meta" then
            --     return
            -- end
            local tree = languagetree

            ...

                    result[key_content] = (
                        node:next_named_sibling() and parse_data(node:next_named_sibling()) or vim.NIL
                    )
                end
            end
        -- end

        return result
    end,
```

**Comment by definitelynotrazu** [comment]
> I met the same situation. I found that Neorg try to find `norg_meta` in `norg:children()` to parse *.norg files' metadata. While a file is closed, the norg_meta parser will not be found. So they will be Uncategoried. I solved by modified the `get_document_metadata` function in "neorg/lua/neorg/modules/core/integrations/treesitter" like this, and sovled your question at the same time @caprilesport :
> 
> ```
>     get_document_metadata = function(buf, no_trim)
>         buf = buf or 0
> 
>         local languagetree = vim.treesitter.get_parser(buf, "norg_meta")    <======
> 
>         if not languagetree then
>             return
>         end
> 
>         local result = {}
> 
>         -- for _, tree in ipairs(languagetree:children()) do   <======
>             -- if tree:lang() ~= "norg_meta" then   <======
>             --     return   <======
>             -- end   <======
>             local tree = languagetree   <======
> 
>             ...
> 
>                     result[key_content] = (
>                         node:next_named_sibling() and parse_data(node:next_named_sibling()) or vim.NIL
>                     )
>                 end
>             end
>         -- end   <======
> 
>         return result
>     end,
> ```

Having the same issue myself, if your patch fixes it without any side effects, maybe your could make a PR?

**Comment by aswa2ds** [comment]
> > I met the same situation. I found that Neorg try to find `norg_meta` in `norg:children()` to parse *.norg files' metadata. While a file is closed, the norg_meta parser will not be found. So they will be Uncategoried. I solved by modified the `get_document_metadata` function in "neorg/lua/neorg/modules/core/integrations/treesitter" like this, and sovled your question at the same time @caprilesport :
> > ```
> >     get_document_metadata = function(buf, no_trim)
> >         buf = buf or 0
> > 
> >         local languagetree = vim.treesitter.get_parser(buf, "norg_meta")    <======
> > 
> >         if not languagetree then
> >             return
> >         end
> > 
> >         local result = {}
> > 
> >         -- for _, tree in ipairs(languagetree:children()) do   <======
> >             -- if tree:lang() ~= "norg_meta" then   <======
> >             --     return   <======
> >             -- end   <======
> >             local tree = languagetree   <======
> > 
> >             ...
> > 
> >                     result[key_content] = (
> >                         node:next_named_sibling() and parse_data(node:next_named_sibling()) or vim.NIL
> >                     )
> >                 end
> >             end
> >         -- end   <======
> > 
> >         return result
> >     end,
> > ```
> 
> Having the same issue myself, if your patch fixes it without any side effects, maybe you could make a PR?

Yeah, I'm considering make a PR. But this patch did not solve the problem that summary ignores the title field of metadata. And today I rewrote the get_document_metadata function and taste good. I'll make a PR later.

**Comment by pysan3** [comment]
Can this issue be closed? @aswa2ds @vhyrro

**Comment by austinbutler** [comment]
All seems to be working now, so I'll close this.
