### ISSUE TITLE
Heading + Todo + Folding (+ concealer?) = trouble

### ISSUE THREAD

**Issue by j-xella** [nvim-neorg/neorg#1121]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-1361+g0892c1cd9

### Neorg setup

```lua
-- neorg support
-- https://github.com/nvim-neorg/neorg

return {
  {
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons",
    },
    cmd = { 'Neorg', },
    ft = { 'norg', },
    config = function(_,_)
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.dirman"] = {
            config = {
              default_workspace = "dev",
              workspaces = {
                personal = "hidden",
                dev      = "hidden",
              },
            },
          },
          ["core.keybinds"] = { -- https://github.com/nvim-neorg/neorg/wiki/User-Keybinds
            config = {
              hook = function(keybinds)
                keybinds.remap_event( "norg", "n", "<C-1>", "core.qol.todo_items.todo.task_cycle" ) -- Like in OneNote

                vim.opt.conceallevel = 2
              end,
            },
          },
          ["core.qol.todo_items"] = {
            config = {
              order = {
                { "undone", " " },
                { "pending", "-" },
                { "done", "x" },
              },
            },
          },
          ["core.concealer"] = {},
          ["core.summary"] = {},
          ["core.ui.calendar"] = {},
        }
      }
    end,
  },
}
```

### Actual behavior

Watch the second-level heading on line 32.  In insert mode, as is:

![image](https://github.com/nvim-neorg/neorg/assets/8959819/196b934a-10e2-4e0d-8fc2-412207562893)

Now in normal mode, concealed. Unfolded - looks OK:

![image](https://github.com/nvim-neorg/neorg/assets/8959819/4799f6e3-ba3f-4de9-9836-93f433c20cbb)

Same heading, folded. **Looks BAD**:

![image](https://github.com/nvim-neorg/neorg/assets/8959819/ce947276-be27-4547-b1cc-297419638e4f)

### Expected behavior

Now removing the TODO marker:

![image](https://github.com/nvim-neorg/neorg/assets/8959819/21d44d47-a631-44e3-ac61-13451af57e2c)

Normal, unfolded:

![image](https://github.com/nvim-neorg/neorg/assets/8959819/a17c3cce-38d5-4a46-8ec3-ccb449b04e6d)

Folded - GOOD:

![image](https://github.com/nvim-neorg/neorg/assets/8959819/c8f39f57-ee02-4376-96fb-6e14ee31a9a3)

### Steps to reproduce

1. Create a heading
2. Make it a todo item, let's say done state
3. Fold it

The fold description should look very similar to the unfolded version, but in reality I can see both textual representation of TODO items and iconic one, shifted and overwriting the heading text.

### Help

None

**Comment by Anrock** [comment]
I always thought it was becase of wrong unicode handling but it seems like it's because of todo marker with concealer. Anyways, same here, almost always had this bug.

**Comment by OHANAN1** [comment]
I have the same issue. It makes me avoid using todos in headings. So a bugfix would be very nice.
