### ISSUE TITLE
Inconsistent icon spacing

### ISSUE THREAD

**Issue by yoplat** [nvim-neorg/neorg#1122]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.4

### Neorg setup

```
load = {
    ["core.defaults"] = {}, -- Loads default behaviour
    ["core.concealer"] = {}, -- Adds pretty icons to your documents
    ["core.dirman"] = { -- Manages Neorg workspaces
      config = {
        workspaces = {
          notes = "~/Notes",
        },
        default_workspace = "notes",
      },
    },
 },
```

### Actual behavior

<img width="705" alt="Screenshot 2023-10-19 at 15 43 41" src="https://github.com/nvim-neorg/neorg/assets/98645146/0526e45e-66f0-4547-8a24-a47f73fd01d0">

Icons location is too much to the right

### Expected behavior

Centered icons

### Steps to reproduce

Create a todo list and toggle between states

### Other information

I know it might be a problem with my font / terminal, but it would be cool if there was a way to fix it in neovim by changing the render function (I've looked through it but it seems that these icons already use the render_left function.
I've messed around a bit with the fonts and it looks correctly with the Mono variant of fonts, but this results in all icons looking too small for my liking tbh.

**Comment by max397574** [comment]
yes this is a terminal and/or font issue. Nothing we can do about that except you changing the icons

**Comment by yoplat** [comment]
> The visual widths of certain characters are probably beyond what neorg could/should learn with the lua APIs, but in any case, you can always [change](https://github.com/nvim-neorg/neorg/wiki/Concealer#todo) the characters to those that are visually pleasing.

Yeah I know but given the fact that the icons need to stay between to parenthesis, if you use non monospaced fonts like I do it is almost impossibile to find an icon that fits, is there maybe a way to use the concealer to remove the parenthesis around the icons and just leave the icons themselves? Or maybe I just need to wait for neovim to support non monospaced font rendering (which might be never). Do you know of any non monospaced font that render correctly in neorg?

**Comment by max397574** [comment]
not sure
couldn't you just patch a nerd font with monospaced icons though?
also
eventually (ig after 0.10 release) we can rely on people having anti-conceal and then we could perhaps allow concealing the parentheses

**Comment by yoplat** [comment]
> not sure couldn't you just patch a nerd font with monospaced icons though? also eventually (ig after 0.10 release) we can rely on people having anti-conceal and then we could perhaps allow concealing the parentheses

I have monospaced icons, but the problem is that monospaced icons are too small for my liking apart from in Neorg, so I would need to have monospaced icons only for neorg and it might be a bit difficult
