### ISSUE TITLE
Create note with differing filename and metadata title

### ISSUE THREAD

**Issue by Dynge** [nvim-neorg/neorg#1126]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

# Goal

Create an API that makes it simple to extend Neorg file creation.

# Why

My motivation stems from a desire to create my files with a timestamp template for the filename (e.g. YYMMDD-HHMMSS.norg), however I do not want the file to get auto generated the same timestamp into the title - because then I always need to edit the metadata.

I believe this feature would make file creation in Neorg better suited to extension and make it easier for anyone to modify it to their own needs.

# Proposed Solution

I am thinking about something like:
```lua
require("neorg").get_module("core.dirman").new_note(
    "notes",
    "path/filename",
    { title="awesome note" }
)
```

The above code would then create a file `path/filename.norg` in the workspace `notes`, prefilled with metadata with the title `awesome note`.
The table i am thinking about not just adding a title but potentially also other metadata fields.

### Help

Yes

### Implementation help

I would like to help implement a lua function to call in order to accomplish this.

I am thinking the proper place for this would by in the dirman module, but i may be wrong :)

If you can help me with where best to place this functionality (assuming it aligns with the vision for the project) - that would be great :)

**Comment by max397574** [comment]
I definitely think this could be useful. Not sure whether it should be in the dirman module (which creates new notes) or the metagen module though
I think it should be a parameter of `new_note` like you proposed but the question is whether this should be then passed on to metagen (which imo it should be but idk how extensible that api is)

**Comment by Dynge** [comment]
I agree that it seems most logical to add the metadata updates for the note into metagen, however that would make dirman depend on metagen, right?

I am not sure how to avoid such dependencies..


Maybe its better to make a two-step solution.

One method in dirman to create a note (assume it already exists) and another in metagen to update with custom defaults.

What do you think?

**Comment by Dynge** [comment]
Alright. Thats good.

I can take a look at the code for dirman and metagen soon and see if i can come up with some more concrete suggestions.

Thanks for your feedback so far, @max397574 !

Do you know if there is any code besides the module files that i should look at relating to this?

**Comment by max397574** [comment]
afaik there are no important things outside of the module files
