### ISSUE TITLE
Adding support for roman numerals

### ISSUE THREAD

**Issue by ssossah** [nvim-neorg/neorg#1136]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

It would be a really nice add to provide support for roman numerals similar to the structure provided within microsoft word:

I. Introduction
   a. thesis
   b. some other point
   c. something else
II. First paragraph
   a . ..
   b. ...
        i. more subpoints 
etc

### Help

No

**Comment by max397574** [comment]
are you talking about headings or ordered lists?

**Comment by ssossah** [comment]
@max397574 Whichever one is easiest, though headings might be a nice approach

**Comment by max397574** [comment]
we don't have numbered headings
so implementig that could be difficult

**Comment by Anrock** [comment]
And for numbered list you can already override how they are displayed with [concealer override](https://github.com/nvim-neorg/neorg/wiki/Concealer#ordered)

**Comment by ssossah** [comment]
I'll check it out, thanks!
