### ISSUE TITLE
FEATURE: Timestamp in UTC to Hide Local

### ISSUE THREAD

**Issue by pysan3** [nvim-neorg/neorg#1147]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Introduced by [this PR](https://github.com/nvim-neorg/neorg/pull/1052), now neorg updates metadata with time and timezone in the `updated` field.

However, when writing document to be published online ([example](https://github.com/pysan3/minorg)), I do not want to reveal my local due to privacy reasons.

It would be nice if I could set an option somewhere so that the timestamp uses UTC instead of printing the timezone. It would be awesome if I can configure this on per-document basis (I do want local timezone on my journals etc).

Could you give some insights @champignoom, @vhyrro about this issue?

Thanks in advance.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by champignoom** [comment]
I added a few options [here](https://github.com/nvim-neorg/neorg/pull/1152), but changing them on-the-fly or only for specific files would be orthogonal to the options and thus should be implemented in another PR and/or with your own customization.
