### ISSUE TITLE
Completion.nvim support

### ISSUE THREAD

**Issue by mrossinek** [nvim-neorg/neorg#116]
### Discussed in https://github.com/nvim-neorg/neorg/discussions/112

<div type='discussions-op-text'>

<sup>Originally posted by **ITHDevelopment** September 17, 2021</sup>
Another big completion engine is **completion.nvim** and it would be great to have support for it. Just that.</div>

**Comment by muniter** [comment]
Hello, Completion.nvim is no longer mantained https://github.com/nvim-lua/completion-nvim

**Comment by mrossinek** [comment]
Thanks for letting us know!
