### ISSUE TITLE
folder creation broken when linking to a new file

### ISSUE THREAD

**Issue by babakou9** [nvim-neorg/neorg#1166]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.10

### Neorg setup

require('neorg').setup {
    load = {
        ["core.defaults"] = {},
	["core.concealer"] = {},
	["core.export"] = {},
	["core.pivot"] = {},
	["core.itero"] = {},
	["core.promo"] = {},
	["core.summary"] = {},
	["core.ui.calendar"] = {},
	["core.completion"] = { config = { engine = "nvim-cmp", name = "[Norg]"}},
	["core.integrations.telescope"] = {},
	["core.integrations.nvim-cmp"] = {},
	["core.keybinds"] = { 
            config = { 
        neorg_leader = ","}
    },
	["core.qol.toc"] = {
		config = { 
			close_after_use = true 
		}
	},
	["core.dirman"] = { 
		config = { 
			workspaces = { 
				cours = "/home/bbk9/nextcloud/Documents/notes/cours",
				journal = "/home/bbk9/nextcloud/Documents/notes/journal",
			},
			default_workspace = "journal",
		  }
	    }
      }
}

local neorg_callbacks = require("neorg.core.callbacks")

neorg_callbacks.on_event("core.keybinds.events.enable_keybinds", function(_, keybinds)
    -- Map all the below keybinds only when the "norg" mode is active
    keybinds.map_event_to_mode("norg", {
        n = { -- Bind keys in normal mode
            { "<C-s>", "core.integrations.telescope.find_linkable" },
        },

        i = { -- Bind in insert mode
            { "<C-l>", "core.integrations.telescope.insert_link" },
        },
    }, {
        silent = true,
        noremap = true,
    })
end)

### Actual behavior

in index.norg

{:new_folder/new_file:}[new file]

opens a new file but when i hit :w  it can’t save : E212: Can't open file for writing: no such file or directory 

### Expected behavior

creation of new_folder and new_file.norg inside new_folder

### Steps to reproduce

up to date neorg 
in the index of a workspace 
type : ** {:new_folder/new_file:}[new file]

### Potentially conflicting plugins

no idea

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I never worked on neovim plugins but I code in python, R and webdev

**Comment by pysan3** [comment]
Currently norg does not auto-create a folder nor a file and just opens a buffer with the name (nothing happens on the disk). When you save the file, vim simply tries to save the file at this moment, and when parent directory does not exist, vim will fail to write the file.

You may want to look at something like this instead of neorg to fix this issue.
https://github.com/neovim/neovim/issues/19884

**Comment by babakou9** [comment]
thank you, my bad I was quite persuaded it was doing it before. 
And I just had to add somo  autocmd BufWritePre ...
Sorry for the disturbance

**Comment by pysan3** [comment]
No worries. It would be nice if you could share your autocmd here for others who might stumble across this issue ;)

**Comment by babakou9** [comment]
gladly! found it there : https://vi.stackexchange.com/questions/678/how-do-i-save-a-file-in-a-directory-that-does-not-yet-exist
