### ISSUE TITLE
Dynamic template for journal creation

### ISSUE THREAD

**Issue by aadi58002** [nvim-neorg/neorg#1169]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hello there,
I recently switched from emacs org mode to using neovim neorg. It is a very pleasant experience and thanks for the great package.
There is a template file which can be created for the journal pages `:Neorg journal template` but that template is static is not very useful ( acc to me ). I think it can be a better idea to add a autocmd event in with which the user can trigger a relevent action which they want for example i wanted to use the :Neorg inject-metadata on the journal for today the first time i create it.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by pysan3** [comment]
https://github.com/pysan3/neorg-templates

**Comment by aadi58002** [comment]
Thanks

**Comment by chnoack** [comment]
This one somehow addresses the same problems: https://github.com/nvim-neorg/neorg/issues/714
At least some of them
