### ISSUE TITLE
conceal numeric footnote reference to superscript

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1189]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Conceal for example `{^ 123}` to `¹²³`.

### Help

Yes

**Comment by Anrock** [comment]
That's very nice. At least brings some reason to use footnotes instead of plain headers. Maybe that behaviour should be mentioned in documentation?
