### ISSUE TITLE
Add dynamic text (changes on variable modification)

### ISSUE THREAD

**Issue by danymat** [nvim-neorg/neorg#121]
On the new selection prompt feature (#108), the text is static.

I would want a text to update itself when the content of the data (I saw that there's a basic support for selection:data()) changes.

**Comment by danymat** [comment]
Hello @vhyrro , what's the state of this ?

**Comment by vhyrro** [comment]
Once i fully figure out the current issues with module loading this should be a very easy thing to add :)
