### ISSUE TITLE
Error when opening link-not-found

### ISSUE THREAD

**Issue by Rik034** [nvim-neorg/neorg#1215]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.4

### Neorg setup

```lua
require("neorg").setup({
	load = {
		["core.defaults"] = {}, -- Loads default behaviour
		["core.concealer"] = { -- Adds pretty icons to your documents
			config = {
				icon_preset = "diamond",
			},
		},
		["core.dirman"] = { -- Manages Neorg workspaces
			config = {
				workspaces = {
					main = "~/Documents/neorg/main",
				},
				default_workspace = "main",
			},
		},
	},
})
```

### Actual behavior

I get an error when pressing enter on a link which doesn't exist.
![Watershot_10-12-2023_08:04](https://github.com/nvim-neorg/neorg/assets/60218806/958073f1-c238-4e35-ac4c-e31449636858)

### Expected behavior

The 'link-not-found' buffer should open

### Steps to reproduce

Press enter on a link which doesn't exist

### Potentially conflicting plugins

Maybe [barbar.nvim](https://github.com/romgrk/barbar.nvim) messes with the buffers?

### Help

No

**Comment by pysan3** [comment]
@vhyrro This is coming from this commit: https://github.com/nvim-neorg/neorg/commit/603b633b8df231fe37a338856b1dea7cd955a969 where you added the the second argument `keybind_buffer` to `core.ui.selection_popup.begin_selection`.

As you can see here:
https://github.com/nvim-neorg/neorg/blob/baaf13a3145534144b795ad37db22bfffd2ad343/lua/neorg/modules/core/esupports/hop/module.lua#L208

`core.ui.create_split` returns two values `tuple[buf, window]` where with the old code, the second value `window` was ignored, but with the new change, window is passed as `keybind_buffer` which is definitely not intended.

What I'm confused tho is that even though you added this change, I don't see a place that calls the above function with two arguments, so this change was only added to introduce this error lol.

Could you explain why you made this change @vhyrro ?

Second move verbose code is always better and we should've done something like this, especially when we silently ignore a return value (purposely).

```lua
local link_not_found_buf = module.required["core.ui"].create_split("link-not-found")

local selection = module.required["core.ui"]
    .begin_selection(link_not_found_buf)
    :listener({
    "<Esc>",
    }, function(self)
      ...
```

---

Reference:

```lua
local function foo(a, b)
    vim.print(string.format([[a: %s]], vim.inspect(a)))
    vim.print(string.format([[b: %s]], vim.inspect(b)))
    vim.print(string.format([[b or a: %s]], vim.inspect(b or a)))
end

local function two_rets()
    return 10, 20
end

local args = two_rets()
foo(args)       -- a = 10, b = nil

foo(two_rets()) -- a = 10, b = 20
```

**Comment by vhyrro** [comment]
Should be fixed now! @pysan3 the change was introduced as it's necessary for the upcoming GTD implementation which  can be found in the not-so-hidden `gtd` branch. That's where the new function invocation syntax was used :)

**Comment by pysan3** [comment]
I see. Yah, can't wait to see gtd coming!

Thanks for fixing it.
