### ISSUE TITLE
Conceal code blocks

### ISSUE THREAD

**Issue by aabbccddeeffggj** [nvim-neorg/neorg#1227]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

The current behavior of code blocks looks like this:
![image](https://github.com/nvim-neorg/neorg/assets/133555950/6428a02e-9f16-43fa-986a-9b38f83b2b47)
I would like it to look like this:
![image](https://github.com/nvim-neorg/neorg/assets/133555950/753f229e-f88b-4371-95e6-78d5a9fb77d3)

### Help

No

### Implementation help

I believe it's pretty easy to implement considering the concealing module already exists.
The distinct code block background highlight already gives an indicative of a code block existing there; when the cursor is within the bounds of the code block, or where the line that has `@code` or `@end` is, the concealing could cease and the text show again.

**Comment by champignoom** [comment]
Are you looking for `icons = { code_block = { conceal = true } }`

See [wiki/Concealer](https://github.com/nvim-neorg/neorg/wiki/Concealer)
