### ISSUE TITLE
TODO indicators in TOC

### ISSUE THREAD

**Issue by Anrock** [nvim-neorg/neorg#1237]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Thanks to @champignoom cursor PRs TOC is now 10x cooler.

Would be even cooler if `** (-) Subheader` is displayed as `** (-) Subheader` in TOC window. Right now it's stripped of TODO marker.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I have near 0 knowledge of neorg codebase and some basic lua knowledge.

**Comment by champignoom** [comment]
please check the latest commit of https://github.com/nvim-neorg/neorg/pull/1221
