### ISSUE TITLE
Concealer: freeze on norg file reopen

### ISSUE THREAD

**Issue by aorith** [nvim-neorg/neorg#1258]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.4

### Neorg setup

```lua
    require("neorg").setup({
      load = {
        ["core.defaults"] = {},
        ["core.dirman"] = {},

        -- Freezes Neorg when reopening a norg file
        ["core.concealer"] = {},
      },
    })
```

### Actual behavior

Nvim freezes when reloading a norg file.

### Expected behavior

File is reloaded

### Steps to reproduce

1. Open any `norg` file
2. Reopen with `:e`
3. Nvim completely freezes for ~10 minutes

### Other information

It doesn't happen on the commit 2e12d182206adc372aad732fde6f6f0b4061709f so either 53cbffb7ecfcb60f19c10c72c4162978e8021959 or 5921cc48cb3be616db0071fa058cfa4d6633c8a6 or both are causing the issue I think.

### Help

None

**Comment by tomlidobnik** [comment]
I have the same issue, is there any work around? I did :e so the folding would work. Is there a way to refresh and fix the folding or do i need to completely exit and enter back in.

**Comment by kbwhodat** [comment]
Having the same problem. I have logic where I use `:e` and its causing the freezing. Very rarely does it happen but most of the times the freezing does.

**Comment by FireSquid6** [comment]
having the same problem as well

**Comment by Anthony-E-B** [comment]
I'm experiencing the same issue, nvim 0.9.2

**Comment by champignoom** [comment]
I remember having this problem days ago, but now I can't reproduce it with either v0.10 or v0.9.5/4/2 from https://github.com/neovim/neovim/releases/.

**Comment by aorith** [comment]
Strange... I reproduce the issue always in both Linux and MacOS with v0.9.4.
I'll test again when v0.9.5 is available in Fedora and brew.

**Comment by cybermelons** [comment]
On v0.9.4 it would hang and spin the CPU really hard whenever I ran `:Neorg journal today` or any neorg file. It would only happen when I also had [bookmarks.nvim](https://github.com/tomasky/bookmarks.nvim) installed as well. Disabling the plugin resumed normal operations.

Upgrading to v0.9.5 fixed any issues. I can run both bookmarks and neorg without trouble.

**Comment by celfred** [comment]
Neovim v0.9.4 for me, Linux Mint 21.2 and I have the same behavior as @cybermelons (without bookmars.nvim) : Noerg journal today (or yesterday) freezes my system with high CPU usage, fan going wild… :(
