### ISSUE TITLE
error executing  vim.schedule  on Neorg export

### ISSUE THREAD

**Issue by 777uliahshafar** [nvim-neorg/neorg#1277]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

nvim v0.9.5

### Neorg setup

require("neorg").setup {
  load = {
    ["core.defaults"] = {
      config = {
        disable = {
          "core.autocommands",
          "core.itero",
        },
      },
    }, -- Loads default behaviour
    ["core.concealer"] = {
      config = {
        icons = {},
      },
    },
    ["core.qol.todo_items"] = {
      config = {},
    },
    ["core.dirman"] = { -- Manages Neorg workspaces
      config = {
        workspaces = {
          main = "~/notes/main",
        },
        default_workspace = "main",
      },
    },
    ["core.highlights"] = {
      config = {
        highlights = {
          anchors = {
            declaration = "+Underlined",
          },
          headings = {},
          links = {},
          todo_items = {},
        },
      },
    },
    ["core.integrations.telescope"] = {},
    ["core.integrations.treesitter"] = {},
    ["core.integrations.nvim-cmp"] = {},
    ["core.completion"] = {
      config = {
        engine = "nvim-cmp",
      },
    },
    ["core.summary"] = {},
    ["core.export"] = {},
    ["core.esupports.metagen"] = {
      config = {
        tab = "  ",
        template = {more ...},
      },
    },
    ["core.keybinds"] = {
      config = {
        hook = function(keybinds)
          keybinds.remap_event("norg", "n", "<Tab>", "core.integrations.treesitter.next.heading")
          more..
        end,
      },
    },
  },
}

### Actual behavior

Hello, I hope I find you well everybody. I want to export my neorg to markdown, but the error shows. 

![norg](https://github.com/nvim-neorg/neorg/assets/67497706/aa245d24-332e-4ec5-8f13-497b1d8e2a21)
![norg2](https://github.com/nvim-neorg/neorg/assets/67497706/9e626587-c287-42b8-aaca-70d3a62e21e7)

1. 

### Expected behavior

Export my norg notes. 

### Steps to reproduce

1. run command `Neorg export to-file ~/out.md` (result first image)
1.1 run command `Neorg export to-file out.md` (result second image)
3. error shows.

I guess that it would be solve if I use Neovim nightly version like module.calendar. However, I also find trouble on install Neovim nightly through scoop in Windows. Any solution? thank you.

### Help

No

**Comment by pysan3** [comment]
This is not a fix but you've got other methods to export, just until nvim v0.10 gets to stable. 

https://github.com/pysan3/Norg-Tutorial/blob/main/norg_tutorial.md#export--import

**Comment by ALVAROPING1** [comment]
can you post the file you are trying to export? I can see where the export is failing, but i need a test case to figure out why it can reach that point and test fixes

**Comment by 777uliahshafar** [comment]
Awesome, after removing metadata or parameter, I have successfully exported it. Thank for your info. I'll close this issue.
