### ISSUE TITLE
Problem with rendering images in .norg files using image.nvim

### ISSUE THREAD

**Issue by drmoc** [nvim-neorg/neorg#1291]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.10

### Neorg setup
```lua
require("neorg").setup({
			load = {
				["core.defaults"] = {}, -- Loads default behaviour
				["core.concealer"] = {}, -- Adds pretty icons to your documents
				["core.dirman"] = { -- Manages Neorg workspaces
					config = {
						workspaces = {
							notes = "~/medicine",
						},
					},
				},
			},
		})
	end,
}
```
### Actual behavior

 I am facing a problem when trying to render images in .norg files using the image.nvim plugin in Neovim. I followed the configuration instructions provided in the plugin documentation and was able to render images in .md files without any problems. However, when I try to do the same in a .norg file, the image is not rendered. Here are some details about my configuration: I am using Neovim and have the Neorg plugin installed and configured correctly. I am using the Kitty terminal and have the latest version.

### Expected behavior

Exemple on .md file
![01⁄30⁄24_1](https://github.com/nvim-neorg/neorg/assets/141449993/364d0ff9-728f-4b43-b95f-e875aa300ada)

### Steps to reproduce

The plugin is configured for markdown and neorg
Syntax for displaying images:
![alternative name](path/to/the/image)
Working perfectly on .md files.

### Help

Yes

**Comment by benlubas** [comment]
Can you share your image.nvim configuration and the `.norg` file that you expect to render an image?

**Comment by FalcoGer** [comment]
Works fine for me.
![image](https://github.com/nvim-neorg/neorg/assets/16250196/10ffea8e-11b7-4fbc-bc9b-c17bb5d36ef8)

**Comment by drmoc** [comment]
image.lua:
return {
	"3rd/image.nvim",
	config = function()
		-- default config
		require("image").setup({
			backend = "kitty",
			integrations = {
				markdown = {
					enabled = true,
					clear_in_insert_mode = false,
					download_remote_images = true,
					only_render_image_at_cursor = false,
					filetypes = { "markdown", "vimwiki" }, -- markdown extensions (ie. quarto) can go here
				},
				neorg = {
					enabled = true,
					clear_in_insert_mode = false,
					download_remote_images = true,
					only_render_image_at_cursor = false,
					filetypes = { "norg" },
				},
			},
			max_width = nil,
			max_height = nil,
			max_width_window_percentage = nil,
			max_height_window_percentage = 50,
			window_overlap_clear_enabled = false, -- toggles images when windows are overlapped
			window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
			editor_only_render_when_focused = false, -- auto show/hide images when the editor gains/looses focus
			tmux_show_only_in_active_window = false, -- auto show/hide images in the correct Tmux window (needs visual-activity off)
			hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp" }, -- render image files as images when opened
		})
	end,
}

**Comment by benlubas** [comment]
@drmoc you can share formatted code in markdown (and therefore github comments) by putting the code inside of a code block. 

```lua
local x = "hi, this is a lua string"
print(x .. ". it get's highlighted")
```

The markdown for that looks like this:

````markdown
```lua
-- lua code here
```
````

---

Also could you share the bit of `.norg` syntax that you're expecting to have render an image? Norg and markdown have different ways to specify an image. You can see the norg way in the comment from FalcoGear above.

**Comment by drmoc** [comment]
```lua
return {
	"3rd/image.nvim",
	config = function()
		-- default config
		require("image").setup({
			backend = "kitty",
			integrations = {
				markdown = {
					enabled = true,
					clear_in_insert_mode = false,
					download_remote_images = true,
					only_render_image_at_cursor = false,
					filetypes = { "markdown", "vimwiki" }, -- markdown extensions (ie. quarto) can go here
				},
				neorg = {
					enabled = true,
					clear_in_insert_mode = false,
					download_remote_images = true,
					only_render_image_at_cursor = false,
					filetypes = { "norg" },
				},
			},
			max_width = nil,
			max_height = nil,
			max_width_window_percentage = nil,
			max_height_window_percentage = 50,
			window_overlap_clear_enabled = false, -- toggles images when windows are overlapped
			window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
			editor_only_render_when_focused = false, -- auto show/hide images when the editor gains/looses focus
			tmux_show_only_in_active_window = false, -- auto show/hide images in the correct Tmux window (needs visual-activity off)
			hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp" }, -- render image files as images when opened
		})
	end,
}
```

**Comment by benlubas** [comment]
> Also could you share the bit of .norg syntax that you're expecting to have render an image? Norg and markdown have different ways to specify an image. You can see the norg way in the comment from FalcoGear above.

**Comment by drmoc** [comment]
```norg
.image ~/image.png
```

**Comment by benlubas** [comment]
Yeah that's really strange that it's not working for norg but does for markdown.

The only thing that I could think is that sometimes (most times) is that image.nvim doesn't continuously check for new images, it mainly just adds them when the file is opened. You can trigger a re-render by running the command `:e` after `.image ~/image.png` is in the document.

If that still doesn't work, I guess make sure that you're running the latest version of the image.nvim plugin. and if that doesn't work I'm really just lost.

**Comment by pysan3** [comment]
If you are using lazy, make sure the plugin _is_ loaded with `ft = "norg"`.

**Comment by benlubas** [comment]
Integrations.image doesn't do anything here. But not having the plugin loaded/TS parser installed would cause issues.

**Comment by pysan3** [comment]
I think it does cuz integrations run `pcall(require, "image")` which will force load image.nvim into rtp thanks to lazy's overload with require if it was not activated yet.

**Comment by drmoc** [comment]
```txt
Has anyone here had success installing and configuring using Lazy as a plugin manager?
Because then I could take a look at the repository. I'm testing on Mac and Linux [Ubuntu23.1]. I'll start from the beginning.
```

**Comment by drmoc** [comment]
> If you are using lazy, make sure the plugin _is_ loaded with `ft = "norg"`.
> 
> Or add `["core.integrations.image"]` to neorg's load module table.

```md
# I added ["core.integrations.image"] on my neorg configuration file. Didn't change anything.

**Comment by drmoc** [comment]
> If you are using lazy, make sure the plugin _is_ loaded with `ft = "norg"`.
> 
> Or add `["core.integrations.image"]` to neorg's load module table.

```md
# I added ["core.integrations.image"] on my neorg configuration file. Didn't change anything.
```

**Comment by drmoc** [comment]
Guys, the problem was the operating system.
Everything worked fine on an Ubuntu VM.
Mac Problem:
```bash
❯ luarocks install magick --check-lua-versions

magick not found for Lua 5.4.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.3...

Error: No results matching query were found for Lua 5.4.
magick supports only Lua 5.1 but not Lua 5.4.
```
When trying to use the image.nvim plugin for neovim, Luarocks magick is one of the prerequisites.
I can even install it using the command : 
```bash
> luarocks --local --lua-version=5.1 --force install magick
```
Didn't work.
Maybe there's an expected update. 
Thank you all very much for helping me resolve the issue.
