### ISSUE TITLE
[FEATURE REQUEST] Allow to set document.meta: author

### ISSUE THREAD

**Issue by CantoroMC** [nvim-neorg/neorg#132]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

The author key is automatically set to os.getenv('USER'), should not be a good idea to allow to define it in the setup function?
Thanks

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

In which module should this be implemented?

**Comment by vhyrro** [comment]
Hey dude! This is actually configurable in the unstable branch already (we'll be merging `unstable` to `main` pretty soon so if you're using `main` you'll have to wait it out for a bit). You need to configure the `core.norg.esupports.metagen` module:
```lua
["core.norg.esupports.metagen"] = {
    config = {
        template = {
                {
                   "title",
                    function()
                        return vim.fn.expand("%:p:t:r")
                    end,
                },
                { "description", "" },
                { "author", "static_value" }, -- Make the change here
                -- OR optionally: { "author", function() return "value" end },
                { "categories", "" },
                {
                    "created",
                    function()
                         return os.date("%Y-%m-%d")
                    end,
                },
                { "version", require("neorg.config").version },    
        }
    }
}
```

Hope this helps! We don't have up-to-date docs as of right now so it's not your fault you don't know about this stuff :P

**Comment by CantoroMC** [comment]
No problem, I have seen there are a lot of branches and meat on the melting pot.
I'll wait till things get merged.
Thanks
