### ISSUE TITLE
Error opening journal from a buffer that is not a file

### ISSUE THREAD

**Issue by 0xErwin1** [nvim-neorg/neorg#1321]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.5

### Neorg setup

		"nvim-neorg/neorg",
		enabled = true,
		build = ":Neorg sync-parsers",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"max397574/neorg-contexts",
			"nvim-neorg/neorg-telescope",
		},
		config = function()
			require("neorg").setup({
				load = {
					["core.defaults"] = {},
					["core.concealer"] = {
						config = {
							icon_preset = "varied",
							icons = {
								delimiter = {
									horizontal_line = {
										highlight = "@neorg.delimiters.horizontal_line",
									},
								},
								code_block = {
									content_only = true,
									width = "content",
									padding = {
										left = 20,
										right = 20,
									},
									conceal = true,

									nodes = { "ranged_verbatim_tag" },
									highlight = "CursorLine",
									-- render = module.public.icon_renderers.render_code_block,
									insert_enabled = true,
								},
							},
						},
					},
					["core.esupports.indent"] = {},
					["core.dirman"] = {
						config = {
							workspaces = {
								work = "~/.notes/work",
								personal = "~/.notes/personal",
							},
						},
					},
					["core.export"] = {},
					["core.export.markdown"] = {},
					["core.integrations.telescope"] = {},
					["external.context"] = {},
				},
			})
		end,

### Actual behavior

When I run the command `:Neorg journal today` with the focus on the neo-tree buffer, it returns this error:

```
Error executing Lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(write):E382: Cannot write, 'buftype' option is set
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...nvim/lazy/neorg/lua/neorg/modules/core/dirman/module.lua:345: in function 'create_file'
	...vim/lazy/neorg/lua/neorg/modules/core/journal/module.lua:136: in function 'open_diary'
	...vim/lazy/neorg/lua/neorg/modules/core/journal/module.lua:161: in function 'diary_today'
	...vim/lazy/neorg/lua/neorg/modules/core/journal/module.lua:482: in function 'on_event'
	.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:794: in function 'broadcast_event'
	...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:298: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:205>
```

The file opens, and works fine.

### Expected behavior

Do not return this error

### Steps to reproduce

Open neo-tree and run `:Neorg journal today`.

### Other information

This is a similar case to this PR to open #1320, in this case I did not find how to solve it.

### Help

None

**Comment by pysan3** [comment]
This is a neo-tree issue (where I'm one of the maintainers).

Please make an issue over on their repo and ping me there.

Neotree actively denies buffer overwriting itself (called steal prevention) and sends the buffer to a different location so that neo-tree stays at the left (or whereever you specified) always.

I am doing a big rewrite which should fix this issue, but will take more than a month so please be patient.

Or if you use `Neotree float`, you shouldn't get this issue.

**Comment by BasileusErwin** [comment]
@pysan3 Thank you for your comment. As it is not an annoying error, I don't see the need to report it.
