### ISSUE TITLE
:Neorg sync-parsers should pin parser to the version that corresponds to neorg version

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1323]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

irrelevant

### Neorg setup

as in tl;dr

### Actual behavior

Doesn't work

### Expected behavior

Highlighting works.

### Steps to reproduce

Pinning neorg to older version in lazy.nvim config won't work without also pinning the corresponding parser version.

See https://github.com/nvim-neorg/neorg/issues/292#issuecomment-1962665587

### Help

None

**Comment by vhyrro** [comment]
Neorg already pins the parser to the corresponding version (see [here](https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/integrations/treesitter/module.lua#L120-L137)). The issue mentioned is an nvim-treesitter issue :)
