### ISSUE TITLE
Jump on the only link in line with CR

### ISSUE THREAD

**Issue by danymat** [nvim-neorg/neorg#133]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I would want to have the ability to jump on the link in the line, at any cursor position, only if there's one link in that line.

### Help

Yes

**Comment by mrossinek** [comment]
@vhyrro will this also be fixed by #178 ?

**Comment by vhyrro** [comment]
Yup, this issue will be resolved once that branch is merged :)

**Comment by mrossinek** [comment]
@vhyrro is this still a thing or planned to become a thing?

**Comment by max397574** [comment]
This is already implemented

**Comment by max397574** [comment]
I can enter this link with cr if I'm at the beginning of the line
```
  this is some text {:startup/startup_ideas:* Theme creator}[Theme Creator]
```

**Comment by mrossinek** [comment]
Awesome, thanks for confirming! :+1:
