### ISSUE TITLE
Links are not being concealed.

### ISSUE THREAD

**Issue by dzerus3** [nvim-neorg/neorg#1330]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.0-beta3 Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include     system vimrc file: "/etc/vim/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Neorg setup

    require("neorg").setup {
      load = {
        ["core.defaults"] = {}, -- Loads default behaviour
        ["core.concealer"] = {}, -- Adds pretty icons to your documents
        ["core.dirman"] = { -- Manages Neorg workspaces
          config = {
            workspaces = {
              notes = "~/Documents/notes",
            },
          },
        },

### Actual behavior

Links do not get concealed; they display the name plus the full link.

Following along with the [video example](https://www.youtube.com/watch?v=Bi9JiW5nSig&list=PLx2ksyallYzVI8CN1JMXhEf62j2AijeDa):
![image](https://github.com/nvim-neorg/neorg/assets/60197566/0e3c58ee-d817-4f5b-ac62-39f2f0d978f0)

### Expected behavior

![image](https://github.com/nvim-neorg/neorg/assets/60197566/70acf440-bcc0-4696-8f7d-47e5dc792517)

### Steps to reproduce

1. Create a link.
2. Move to another line.
3. Observe it not being concealed.

### Potentially conflicting plugins

Reproduced without plugins, except Neorg, Treesitter, and a color theme.

### Other information

Neorg `tag` was set to `v7.0.0`. Concealer otherwise seems to be working correctly. Installed using `lazy.nvim`.

### Help

No

**Comment by pysan3** [comment]
What is your `set conceal?` value?

**Comment by dzerus3** [comment]
@pysan3 
![image](https://github.com/nvim-neorg/neorg/assets/60197566/59b2975f-4385-41db-8a82-95c20953d7a3)

**Comment by pysan3** [comment]
Shoot. It's `conceallevel`. My bad.

**Comment by dzerus3** [comment]
`conceallevel` was set to 0. Setting it to 1 seems to have resolved the issue.

**Comment by pysan3** [comment]
I'd recommend 2 but it's a personal preference anyways. 

Did you read `:h conceallevel`?

**Comment by dzerus3** [comment]
I have now, yes, though I have not used the option before, and I'm not sure how it applies outside Neorg.

Is it documented anywhere that this option needs to be set for concealer to work properly? I'm not excluding the possibility that I just missed it, but I've not found any mention of it myself.

**Comment by dzerus3** [comment]
It is [right here](url). I believe it would be better to specify a little within the wiki how exactly not setting the variable would break neorg, but my issue is fixed. Closing.

**Comment by pysan3** [comment]
You can of course set it only for norg files in ftplugin or after/ftplugin. 

I'm pretty sure it was mentioned somewhere but I can't remember where.
