### ISSUE TITLE
Multi-line math do not get exported

### ISSUE THREAD

**Issue by Darth-218** [nvim-neorg/neorg#1337]
### Discussed in https://github.com/nvim-neorg/neorg/discussions/1336

<div type='discussions-op-text'>

<sup>Originally posted by **Darth-218** March 16, 2024</sup>
Just found out about neorg and I really like it as a previous org-mode user and there seems to be nothing else as visually appealing as neorg. One thing tho i can't seem to quite figure out is how to export math blocks, normal text, code blocks and everything else seem to export just fine but multi-line math seems to just leave a blank space. Is there anything I'm doing wrong? (Both export modules are in the config)
![image](https://github.com/nvim-neorg/neorg/assets/64696569/8e68cae9-b4bd-467d-8ba9-b7e9aad98068)
</div>

**Comment by pysan3** [comment]
Export module is definitely flaky. You may get better results with other methods and you might want to give them a try. 

https://github.com/pysan3/Norg-Tutorial/blob/main/norg_tutorial.md#export--import

**Comment by pysan3** [comment]
Did it work? Which one did you end up using?
