### ISSUE TITLE
"On Hold" todo should get inherited

### ISSUE THREAD

**Issue by simonhughxyz** [nvim-neorg/neorg#1339]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

When having nested todo's, where everything is done but a "on hold", the parent todo should inherit the "on hold" instead of pending.

For example:
At the moment this is what happens:
``` norg
* (-) parent todo
** (x) Done child todo 
** (x) Done child todo2
** (=) On hold child todo 3
```

But it I think it should inherit so it would look like this:
``` norg
* (=) parent todo
** (x) Done child todo 
** (x) Done child todo2
** (=) On hold child todo 3
```

Unless there is a active task, the parent should inherit the "on hold" from the child todo since the parent is effectively "on hold" untill something happend with the child todo.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I know enough lua but it has been a while since I looked into the Neorg plugin code.

**Comment by vhyrro** [comment]
Good idea! Added this to the TODO list, shouldn't be too difficult to implement :)

**Comment by vhyrro** [comment]
Implemented this in the latest commit! I'll be pushing 8.2.0 soon so it should land in the stable release too :)
