### ISSUE TITLE
[BUG] Autocommand Errrors on unstable branch running linux

### ISSUE THREAD

**Issue by AndOrangutan** [nvim-neorg/neorg#136]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

0.5.1

### Branch

unstable

### Loaded modules

``` lua
-- Neorg config
equire('neorg').setup {
    -- Tell Neorg what modules to load
    load = {
        ["core.defaults"] = {}, -- Load all the default modules
        ["core.norg.concealer"] = {}, -- Allows for use of icons
        ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
                workspaces = {
                    my_workspace = "~/Dropbox/Neorg"
                },
                autodetect = true,
                autochdir = true,
            }
        },
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp"
            }
        }
    },
}
```

### Expected behavior

I don't have an error and I can test the unstable branch.

### Actual behavior

Any time I open or do almost anything in a `.neorg` file, I get 
```
Error detected while processing TextChanged Autocommands for "*.norg":
E5108: Error executing lua ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:362: attempt to call method 'prev_named_sibling' (a nil value)
```

### Other information

Here is what I got for the parser in my treesitter config, before treesitter's setup
``` lua
local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

parser_configs.norg = {
    install_info = {
        url = "https://github.com/nvim-neorg/tree-sitter-norg",
        files = { "src/parser.c", "src/scanner.cc" },
        branch = "main"
    },
}

```

**Comment by mrossinek** [comment]
The function `prev_named_sibling` is only present in Neovim nightly (https://github.com/neovim/neovim/commit/140084180e82bea3afafa32a33fee37e6e9473ca). So you will need to update your Neovim for this to work as expected. We will need to update our Neovim version requirements...

**Comment by AndOrangutan** [comment]
Many Thanks :D
