### ISSUE TITLE
:Neorg journal wipes existing journal files

### ISSUE THREAD

**Issue by Ladas552** [nvim-neorg/neorg#1365]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.5

### Neorg setup

```
      require("neorg").setup({
        load = {
          ["core.defaults"] = {},
          ["core.concealer"] = {
            config = {
              icon_preset = "diamond",
            },
          },
          ["core.summary"] = {},
          ["core.esupports.metagen"] = { config = { timezone = "implicit-local", type = "empty", undojoin_updates = "false"} },
          ["core.completion"] = { config = { engine = "nvim-cmp", name = "[Norg]" } },
          ["core.keybinds"] = {
            config = {
              default_keybinds = true,
              neorg_leader = "<Leader><Leader>",
            },
          },
          ["core.journal"] = {
            config = {
              workspace = "journal",
            },
          },
          ["core.dirman"] = {
            config = {
              workspaces = {
                general = "~/Documents/Norg/",
                life = "~/Documents/Norg/Life/",
                work = "~/Documents/Norg/Study/",
                journal = "~/Documents/Norg/Journal/",
              },
              default_workspace = "general",
            },
          },
        },
      })
```

### Actual behavior

When entering a journal entry using the :cmd command, it gets wiped. No correlation to template file. Just blank. 
Creating a new file works as expected, but entering it will wipe it. 

Works with every type of file that can be entered with Neorg journalc command. Entries, toc, template.

Also, cannot be reversed with “undo” command even with swap file options enabled in init.lua

https://github.com/nvim-neorg/neorg/assets/94762349/9c905f67-74cb-4329-ae2a-9038be9826fe

### Expected behavior

It would enter a file without modifying its content. And not wiping my 100 lines of enlightening text that can't be returned now.

### Steps to reproduce

Be on the latest Neorg release. 
Use journal module.
Reenter existing journal entry with a command `Neorg journal`
(entering with telescope or in file manager will not reproduce the issue)

### Other information

It bug may be caused by one of the yesterdays or today's commits. Because yesterday I could edit the same file several times using the cmd to enter it. 

### Help

No

**Comment by pysan3** [comment]
I am very sorry. There was a bug in pathlib.nvim.

I'll fix it asap.
