### ISSUE TITLE
Readd kickstart config to wiki

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorg/neorg#1366]
I'm away for the next three days from any sort of PC so I'm brainstorming ideas.

The kickstart Neovim configuration to get Neorg up and running has temporarily disappeared when simplifying the README.

We should absolutely improve this kickstart configuration to also include luarocks.nvim.

This kickstart should be in the wiki and should be referenced from the readme for anyone who wants things to just work :)

**Comment by ewanm89** [comment]
I just installed the lua 5.1 and added the following to lazy installs in init.lua:
```lua
  {
    'vhyrro/luarocks.nvim',
    priority = 1000, -- We'd like this plugin to load first out of the rest
    config = true, -- This automatically runs `require("luarocks-nvim").setup()`
  },
  {
    'nvim-neorg/neorg',
    dependencies = { 'luarocks.nvim' },
    lazy = false,
    version = '*',
    -- put any other flags you wanted to pass to lazy here!
    config = function()
      require('neorg').setup {
        load = {
          ['core.defaults'] = {},
          ['core.concealer'] = {},
          ['core.dirman'] = {
            config = {
              workspaces = {
                notes = '~/Documents/notes/',
              },
              default_workspace = 'notes',
            },
          },
          ['core.ui.calendar'] = {},
        },
      }
    end,
  },
  ```

**Comment by vhyrro** [comment]
Kickstart is now available under https://github.com/nvim-neorg/neorg/wiki/Kickstart!

**Comment by pysan3** [comment]
You didn't even mention my tutorial a single time :pepehands:.
