### ISSUE TITLE
Neorg markup no longer renders after 8.0.0

### ISSUE THREAD

**Issue by Tvrt1e** [nvim-neorg/neorg#1374]
### Discussed in https://github.com/nvim-neorg/neorg/discussions/1373

<div type='discussions-op-text'>

<sup>Originally posted by **Tvrt1e** March 31, 2024</sup>
nvim ver:
NVIM v0.10.0-dev-2785+gfeaab21c7
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
Nothing in neorg log.(since reinstalling)
Main branch
Modlues:
- `core.concealer`
- `core.keybinds.keybinds`
- `core.clipboard`
- `core.clipboard.code-blocks`
- `core.esupports.hop`
- `core.esupports.indent`
- `core.esupports.metagen`
- `core.integrations.treesitter`
- `core.itero`
- `core.journal`
- `core.defaults`
- `core.mode`
- `core.dirman`
- `core.neorgcmd.commands.return`
- `core.autocommands`
- `core.ui`
- `core.storage`
- `core.dirman.utils`
- `core.keybinds`
- `core.concealer.preset_diamond`
- `core.ui.text_popup`
- `core.concealer.preset_varied`
- `core.concealer.preset_basic`
- `core.neorgcmd`
- `core.tangle`
- `core.qol.todo_items`
- `core.qol.toc`
- `core.promo`
- `core.pivot`
- `core.highlights`
- `core.ui.selection_popup`
- `core.looking-glass`
Just to make sure I uninstalled all other nvim plugins and reverted changes to init.vim since installing neorg. After reverting these changes I got the same behavior.
Steps to reproduce:
1. Install neorg via :Rocks install neorg
2. Make nvim/lua/plugins/neorg.lua
3. Paste basic config(shown below)
4. Open a .norg file with neorg markdown syntax

:Neorg works fine so the plugin is installed, but in .norg files no Neorg features work except for a few. I installed neorg using vim-plug, so I removed it and installed via rocks.nvim, but still nothing worked. Any ideas as to why? Maybe I misunderstood the configuration.
Example:
![Neorg-help](https://github.com/nvim-neorg/neorg/assets/78752428/1a32a7e7-453a-4027-a324-7336ff14fb4b)

neorg.lua:
```
require('neorg').setup {
    load = {
        ["core.defaults"] = {}, 
        ["core.concealer"] = {}, 
        ["core.dirman"] = { 
            config = {
                workspaces = {
                    notes = "~/Documents/notes",
                },
            },
        },
    },
}
```
notes:
I reverted to 7.0.0 and got the same behavior. 
When removing core.concealer everything including headers become plain text regardless of cursor position.

**Comment by max397574** [comment]
do you 1. have a colorscheme installed and 2. have conceallevel set correctly?

**Comment by Tvrt1e** [comment]
1. Yes I do, but as stated I got rid of it just to make sure it wasn't the issue, and it was not.
2. :set conceallevel=3 changes nothing.  Also as I understand it, the basic functionality of neorg should work fine without the concealer module. I will note that what I said in my issue was the wrong way around. I get no rendering whatsoever without concealer, but with concealer I only get headers.

**Comment by max397574** [comment]
well regarding the colorscheme
neorg doesn't define the highlights it uses
it just links to some normally defined by a colorscheme so you actually need one

**Comment by Tvrt1e** [comment]
So could my issue have something to do with my colorscheme as opposed to neorg itself?

**Comment by Drew-Daniels** [comment]
I started noticing the same issue maybe a few days ago. Not sure what could have changed, but fwiw, I'm still using `lazy` as my PM and have the following configuration as recommended in the docs (and which was working for awhile):

```lua
{
  "vhyrro/luarocks.nvim",
  priority = 1000,
  config = true,
},
{
  "nvim-neorg/neorg",
  dependencies = { "luarocks.nvim" },
  lazy = false,
  version = "*",
  config = true,
},
```

I've tried running `:Neorg sync-parsers` to see if that fixes the issue, and it runs, but still get the same result:

![image](https://github.com/nvim-neorg/neorg/assets/62859552/ad5192e3-4bc7-4208-b9bb-989f829eeb22)

![image](https://github.com/nvim-neorg/neorg/assets/62859552/1cb5920b-aec0-428a-ac04-caf140f74a9d)

![image](https://github.com/nvim-neorg/neorg/assets/62859552/6cae6da7-3fb1-44b9-b98b-84dc466b3d6f)

**Comment by Tvrt1e** [comment]
I decided to switch to lazy.nvim because I fell like I've tried everything else, and I'm getting the exact same behavior as I was using rocks.nvim. 
Drew-Daniels I think our problems are a bit different. When I type headers they render like normal but the text itself does not change from plain text. Your text is changing color as it should but the markdown isn't being concealed.

**Comment by TheLeoP** [comment]
@Tvrt1e  use `:Inspect` on any part of the document that should be highlighted to check which highlight groups are being applied.

**Comment by Tvrt1e** [comment]
@TheLeoP :Inspect on text returns No items found at position 25,5, in buffer 1(text surrounded by asterisks).

**Comment by TheLeoP** [comment]
@Tvrt1e What does `:InspectTree` show?

**Comment by Tvrt1e** [comment]
@TheLeoP `:InspectTree` shows  `(bold)))) ; [25, 5] - [25, 11]`.

**Comment by TheLeoP** [comment]
@Tvrt1e is that the whole output? For me, with a document containing only `*algo*`, it shows the following (take into account that I pressed `I` to show which parser is producing which parts of the tree):

```scheme
(document ; [0, 0] - [1, 0] norg
  (paragraph ; [0, 0] - [1, 0] norg
    (paragraph_segment ; [0, 0] - [0, 6] norg
      (bold)))) ; [0, 0] - [0, 6] norg
```

Are both `norg` and `norg_meta` treesitter parsers installed correctly? Does your local installation of `neorg` not contain `queries/norg/highlights.scm` or `queries/norg_meta/highlights.scm` for some reason?

**Comment by Tvrt1e** [comment]
Sorry I just pasted the line that was highlighted when I ran the command. If I make a .norg file with only `*algo*` I get this:
```
(document ; [0, 0] - [1, 0]
  (paragraph ; [0, 0] - [1, 0]
    (paragraph_segment ; [0, 0] - [0, 6]
      (bold)))) ; [0, 0] - [0, 6]
```
I have on my system both `norg` and `norg_meta` treesitter parsers and `highlights.scm` for both.

**Comment by Tvrt1e** [comment]
As a note after switching to lazy.nvim horizontal lines now also work, (they didn't before.) So any syntax that changes the form/appearance of text works, but any syntax that keeps the text but changes its quality(color, etc.) does not work.

**Comment by pysan3** [comment]
BTW will `:e!` apply highlights by any chance? If it does, it'll be easier to spot the problem.

**Comment by Tvrt1e** [comment]
`:e!` does nothing.

**Comment by Tvrt1e** [comment]
Reverting to 7.0.0 fixes the issue entirely. Still would like to see this figured out so that I can keep up to date in the future.

**Comment by vhyrro** [comment]
@Drew-Daniels your issue stems from the fact that you're invoking `config = true` (which does not load the concealer by default). The concealer module has to be enabled separately :)

@Tvrt1e it really does seem like there's some sort of issue on your end. Are you lazy loading nvim-treesitter in any way? What if you make nvim-treesitter a dependency of Neorg? I.e:
```lua
{
    "nvim-neorg/neorg",
    dependencies = { "nvim-treesitter" },
    -- rest of config goes here
}
```

Post 8.0 we did remove a snippet related to highlighting. It was a very hacky bit of code that tried forcefully restarting nvim-treesitter's highlight cache to get things to display just in case. We can't rely on such hacks in our codebase though, and thus decided to remove it. The root cause of things not being displayed properly are either:

- The colourscheme isn't loaded on time (give your colourscheme a high priority in lazy.nvim to make it work) OR the colourscheme isn't being loaded at all.
- nvim-treesitter is being loaded too late (tbh this is unlikely)\

I haven't found any way of reproducing your issues though which makes the situation harder than it otherwise would be :sweat_smile:

**Comment by Tvrt1e** [comment]
I did install neorg with the treesitter dependency, and at the time I was still using vim-plug for my colorscheme. Yesterday I started using the kickstart.nvim config and after updating neorg to the latest version it worked just fine. The issue was likely that I called my colorscheme after loading lazy plugins. Thank you.

**Comment by vhyrro** [comment]
Awesome, happy to hear it got resolved! :)

**Comment by Drew-Daniels** [comment]
Thanks @vhyrro ! That was exactly it. I had followed the docs after the `luarocks` change and had forgotten was setting `config` did  🤦🏻‍♂️
