### ISSUE TITLE
Error when deleting last line of a file

### ISSUE THREAD

**Issue by flexagoon** [nvim-neorg/neorg#1375]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev+2791-g99b3a068d

### Neorg setup

```lua
vim.opt.conceallevel = 2

require("neorg").setup({
  load = {
    ["core.defaults"] = {},
    ["core.concealer"] = {},
  },
})
```

### Actual behavior

When deleting the last line of a file, neorg throws the following error:

```
Error executing lua callback: ...ua/neorg/modules/core/integrations/treesitter/module.lua:544: Index out of bounds
stack traceback:
        [C]: in function 'nvim_buf_get_lines'
        ...ua/neorg/modules/core/integrations/treesitter/module.lua:544: in function 'get_first_node_on_line'
        ...eorg/lua/neorg/modules/core/todo-introspector/module.lua:66: in function <...eorg/lua/neorg/modules/core/todo-introspector/module.lua:64>
```

### Expected behavior

There is no error

### Steps to reproduce

1. Open a norg file
2. Press `G` to go to the last line
3. Press `dd` to delete it

### Help

Yes

### Implementation help

Seems pretty easy to fix, just need to add a check in this function https://github.com/nvim-neorg/neorg/blob/89f9a79179e179e9e0d96d6adce14473bed896bc/lua/neorg/modules/core/integrations/treesitter/module.lua#L533 whether the line index exists.

However, I'm not really sure how this function is used in the todo-introspector module, so maybe this'll break something?

**Comment by vhyrro** [comment]
Solved in the latest commit!
