### ISSUE TITLE
Telescope integration for searching notes

### ISSUE THREAD

**Issue by paulfrische** [nvim-neorg/neorg#1385]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I think searching workspaces and files in workspaces via telescope would be pretty usefull but autochdir is really anoying in my opinion

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I never developed a neorg module and could use some help with the dirman api (are there any docs?)

**Comment by pysan3** [comment]
https://github.com/nvim-neorg/neorg-telescope

**Comment by paulfrische** [comment]
ok nvm, I didn't find that one

**Comment by pysan3** [comment]
https://github.com/nvim-neorg/awesome-neorg
