### ISSUE TITLE
introspector not working.

### ISSUE THREAD

**Issue by Klemenceo** [nvim-neorg/neorg#1405]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-2995+ga1550dbf0-Homebrew

### Neorg setup

```
   config = function()
            require("neorg").setup {
                load = {
                    ["core.defaults"] = {},
                    ["core.todo-introspector"] = {},
                    ["core.concealer"] = {},
                    ["core.dirman"] = {
                        config = {
                            workspaces = {
                                work = "~/.work_notes/",
                            },
                            default_workspace = "work",
                        },
                    },
                },
            }

        end,
```

### Actual behavior

No summary of child tasks using the example below :

```
$cat index.norg
* ( ) Hello World!

  Important things to do bozo:
  - ( ) Shopping
  - ( ) other things
```

Result : 
<img width="311" alt="Screenshot 2024-04-24 at 18 46 35" src="https://github.com/nvim-neorg/neorg/assets/146014434/3e7ad87d-8166-46e4-9f39-1a86fef69848">

### Expected behavior

Summary of done / total tasks should be added at header levels.

### Steps to reproduce

nvim index.org  with index.org being the file above.

### Other information

Contrary to prerequisites this is run using nvim nightly as the todo-introspector module is only loading using that version.

### Help

None

**Comment by vhyrro** [comment]
Hey, this is expected behaviour. The introspector only accumulates information from things of the same type. For instance:
```
- ( ) Test
-- ( ) Subtest
-- ( ) Another subtest
```

Will display the introspector popup, because these items are all lists. Similary for headings:
```
* ( ) Heading
** ( ) Other heading
** ( ) Another heading
```

The introspector won't show up for intermingled types :)

**Comment by Klemenceo** [comment]
Ah yes makes sense, complet misunderstood of the feature on my side. My bad.
