### ISSUE TITLE
Error running `TSUpdate`

### ISSUE THREAD

**Issue by rodhash** [nvim-neorg/neorg#1411]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-a84b454

### Neorg setup

    -- luarocks version
    {
      "nvim-neorg/neorg",
      dependencies = { "luarocks.nvim" },
      lazy = true, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
      ft = "norg",
      version = "*", -- Pin Neorg to the latest stable release
      -- config = true,
      config = function ()
        require("neorg").setup (
        {
          load = {
            ["core.looking-glass"] = {},
            ["core.ui"] = {},
            ["core.defaults"] = {
              config = {
                default_keybinds = false,
              },
            },
            ["core.journal"] = {
              config = {
                -- journal_folder = "/Users/rodhash/journaling/"
              }
            },
            -- Loads default behaviour
            ["core.integrations.treesitter"] = {},
            ["core.completion"] = { config = { engine = "nvim-cmp" } },
            ["core.export"] = {},
            ["core.concealer"] = {
              config = {
                icons = {
                  code_block = {
                    conceal = true,
                    content_only = true,
                  },
                  list = {
                    icons = { "" }, -- •  •
                  }
                },
              }
            }, -- Adds pretty icons to your documents
            ["core.dirman"] = { -- Manages Neorg workspaces
              config = {
                workspaces = {
                  notes = "~/notes",
                },
              },
            },
            ["core.keybinds"] = {
              config = {
                default_keybinds = false,
                hook = function(keybinds)
                  -- Unmaps any Neorg key from the `norg` mode
                  keybinds.unmap("norg", "n", "gtd")
                end,
              }
            },
          },

        }
)
      end
    }

### Actual behavior

ps: interesting that this error happens when opening nvim with any file except `.norg` files. Now if we open a `.norg` file the command `TSUpdate` says `All parsers are up-to-date!` .. this is confusing to me.

The actual error happens when opening any other filetype, for instance `.js` and trying to update the parsers, in this case Treesitter says: `nvim-treesitter[norg]: Error during compilation`

Running `TSUpdate` returns the following error:

```lua
2024-04-28T13:22:23 Messages   INFO In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/_types.h:32,
                 from /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13/include-fixed/stdint.h:61,
                 from /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13/include/stdint.h:9,
                 from ./src/tree_sitter/parser.h:9,
                 from src/parser.c:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/cdefs.h:554:30: error: missing ')' after "__has_attribute"
  554 | #if __has_cpp_attribute(clang::unsafe_buffer_usage)
      |                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/cdefs.h:554:31: error:  ':' without preceding '?'
  554 | #if __has_cpp_attribute(clang::unsafe_buffer_usage)
      |                               ^
make: *** [parser.o] Error 1
```

### Expected behavior

No error should return when running `TSUpdate`

### Steps to reproduce

1. Open nvim with any file (except .norg files)
2. Run `TSUpdate`
3. The error should pop up

ps: interesting that this error happens when opening nvim with any file except `.norg` files. Now if we open a `.norg` file the command `TSUpdate` says `All parsers are up-to-date!` .. this is confusing to me.

The actual error happens when opening any other filetype, for instance `.js` and trying to update the parsers, in this case Treesitter says: `nvim-treesitter[norg]: Error during compilation`

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I have basics lua knowledge so I can definitely try to help with guidance.

**Comment by rodhash** [comment]
Updated to latest neovim nightly and still having error to compile `norg`.

Nvim `NVIM v0.10.0-dev-3020+g435dee74b`

**Comment by mikemc** [comment]
I'm on a Mac, and I started having a problem with nvim-treesitter being unable to compile the norg parser, and fixed it by telling nvim-treesitter to use the GCC compiler I've installed via homebrew, rather than clang.

```
  {
    "nvim-treesitter/nvim-treesitter", 
    build = ":TSUpdate",
    init = function()
      -- Set parser for custom filetypes
      vim.treesitter.language.register('markdown', 'telekasten')
      require('nvim-treesitter.install').compilers = { 'gcc-13' }
    end,
    main = "nvim-treesitter.configs",
    opts = {
# rest of nvim-treesitter config below here
```

**Comment by rodhash** [comment]
Yeah in fact I have always used another GCC compiler too, now it's fixed after upgrading to gcc-14 .. before I was on gcc-13

I have no idea of what happened to my previous version of gcc but now it looks all good.
