### ISSUE TITLE
Recent update broke things

### ISSUE THREAD

**Issue by AndOrangutan** [nvim-neorg/neorg#143]
Just ran PackerSync and Neorg is doing something funky.
![NeorgErrors](https://user-images.githubusercontent.com/40435989/136290944-37a90ae8-cf1c-47d8-9580-68e89362d378.png)

**Comment by vhyrro** [comment]
Yo, could you try updating the TS parser too? Whenever you see these sort of errors it usually means a desync between Neorg's highlighting queries and the parser itself. `:TSUpdate` should do the trick

**Comment by AndOrangutan** [comment]
My bad, I thought I had something auto doing that. Whoops.
