### ISSUE TITLE
(Upstream) Concealed formula width incorrectly identified as non-concealed when linewrapping

### ISSUE THREAD

**Issue by glyh** [nvim-neorg/neorg#1444]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478 

### Neorg setup

    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.export"] = {},
          ["core.export.markdown"] = {},
          ["core.concealer"] = {},
          ["core.completion"] = {
            config = {
              engine = "nvim-cmp",
            },
          },
          ["core.dirman"] = {
            config = {
              workspaces = {
                notes = "~/Documents/notes/neorg",
              },
              default_workspace = "notes",
            },
          },
          ["core.integrations.image"] = {},
          ["core.latex.renderer"] = {},
        },
      }
      -- TODO: Set fold level only for neorg files
      vim.wo.foldlevel = 99
      vim.wo.conceallevel = 2

### Actual behavior

![image](https://github.com/nvim-neorg/neorg/assets/12870742/9b218313-b1e3-4d2d-bda8-4bd54b4698c6)

The green line is the right border of the window. 

### Expected behavior

The `hi` should fit in one line. 

### Steps to reproduce

Write the below
```neorg
* Benefits of z-Transform
  - Analysis of LTI systems
  - Solving difference equations
  - Determining system stability
  - Finding frequency response of stable systems
* Eigen-functions of LTI Systems
  $|e^{j\omega n}|$ are eigen-functions, so are $|x[n] = z^n = r^n e^{j\omega n}|$ hi.

```

### Potentially conflicting plugins

None	

### Other information

Is this a neovim bug?

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

Tell me where should I start.

**Comment by glyh** [comment]
So this is an upstream bug? How should I formulate it to upstream then?

**Comment by glyh** [comment]
You mean this? https://github.com/neovim/neovim/issues/18282

**Comment by max397574** [comment]
especially this https://github.com/neovim/neovim/issues/25718 ig

**Comment by glyh** [comment]
Ok, I guess I'll just leave this here as upstream tracker.

**Comment by max397574** [comment]
not needed
duplicate of/related to:
https://github.com/nvim-neorg/neorg/issues/1065
https://github.com/nvim-neorg/neorg/issues/929
https://github.com/nvim-neorg/neorg/wiki/Dependencies#ugly-line-wraps-when-concealing-text
https://github.com/nvim-neorg/neorg/issues/292#issuecomment-1004201966
https://github.com/nvim-neorg/neorg/issues/292#issuecomment-1008865803

I'm quite sure there are even more who were already closed and perhaps even some more open ones but ig you got my point already

**Comment by glyh** [comment]
Great, let me close this then.
