### ISSUE TITLE
Clarify rocks.nvim install instruction

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1459]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

> ...
> Add the following to your config's `lua/plugins/neorg.lua`
> ...

Please clarify the meaning of "your config's `lua/plugins/neorg.lua`". Either "your config" should be defined, or the precise location of `lua/plugins/` should be given.

One would otherwise be very confused when reading "your config" as the file `~/.config/nvim/init.lua`.

### Help

Yes

**Comment by max397574** [comment]
imo this is clear
because obviously `lua/plugins/neorg.lua` is a filepath
and if you don't know where your config is you will have a lot of issues before even getting here

**Comment by champignoom** [comment]
> ... you will have a lot of issues before even getting here

Why? None of the previous steps ever mentioned this filepath, so I had no problem proceeding with the instructions, until this very step.

> it definitely doesn't make sense to tell users where the config is for different operating systems

It makes even less sense not to tell users at all how to find or create the config in any operating system.

**Comment by TarunDaCoder** [comment]
> It makes even less sense not to tell users at all how to find or create the config in any operating system.
I think it's up to the user where they want to configure neorg, if it's in their `init.lua` itself or in a directory like `lua/plugins/neorg.lua`. And the config file could be located in different places based on the operating system also. So I don't think neorg can list all the places where you can put the config file. Therefore, it just lists the most common place to put it.

**Comment by max397574** [comment]
> Why? None of the previous steps ever mentioned this filepath, so I had no problem proceeding with the instructions, until this very step.

where did you install your plugin manager?

> It makes even less sense not to tell users at all how to find or create the config in any operating system.

then every plugin should do this or what?
imo it isn't the job of every single plugin to do this
you can find that at multiple places in the helpfile

**Comment by champignoom** [comment]
> where did you install your plugin manager?

This is irrelevant. To be clear, I was referring to the following instructions in the README:

https://github.com/nvim-neorg/neorg/blob/51be06957fc6cc7140b310abd30be6682041962a/README.md?plain=1#L86-L91

>  you can find that at multiple places in the helpfile

It's not obvious where to find them, and I believe it's not the users' obligation to go down such rabbit hole. Please add `please refer to [this helpfile](url/to/the/helpful/part)` at very least.

**Comment by max397574** [comment]
or just add `:= vim.fn.stdpath("config")` after "config"?

**Comment by champignoom** [comment]
@TarunDaCoder 

> I think it's up to the user where they want to configure neorg, if it's in their init.lua itself or in a directory like lua/plugins/neorg.lua.

You're right, and I believe this crucial information currently missing from the README --- it's fine to put the code inside `init.lua`.

I'd suggest to change

>  Add the following to your config's `lua/plugins/neorg.lua`

into something like

>  Add the following to `init.lua` (or `lua/plugins/neorg.lua` if you know what this means)

**Comment by champignoom** [comment]
@max397574 

> or just add := vim.fn.stdpath("config") after "config"?

`:echo stdpath("config")` gives me `$HOME/.config/nvim`, and there's no `$HOME/.config/nvim/lua/plugins`, so "your config's `lua/plugins/neorg.lua`" would still be confusing.

**Comment by max397574** [comment]
then
add to the lua/plugins/neorg.lua file in your config directore (echo: stdpath("config"))
?

**Comment by TarunDaCoder** [comment]
> add to the lua/plugins/neorg.lua file in your config directore (echo: stdpath("config"))

No I think it should just be "add this to your neovim configuration"
Since neorg may not be their first plugin, they'll know what to do.

**Comment by champignoom** [comment]
@max397574 

I'd say "add the following to `init.lua`" would already be good enough in the README.

"Add the following to anywhere under your config directory, like `lua/plugins/neorg.lua`" would still be fine, if that's what you mean.

Any other phrasing like "add the following to SOMEPATH ..." would suggest that SOMEPATH pre-exists and is a defacto standard place to store plugins according to neovim's or rocks.nvim's or whatever's best practice.

**Comment by champignoom** [comment]
@TarunDaCoder 

>  Since neorg may not be their first plugin, they'll know what to do. This isn't a how to setup neovim tutorial 🤣

This really should be, since the recommended installation process of neorg is coupled with a specific plugin management system (rocks.nvim) that not everyone has already used.

**Comment by max397574** [comment]
> I'd say "add the following to init.lua" would already be good enough in the README.

but I think with rocks-config it matters
the file would be automatically loaded

> Any other phrasing like "add the following to SOMEPATH ..." would suggest that SOMEPATH pre-exists and is a defacto standard place to store plugins according to neovim's or rocks.nvim's or whatever's best practice.

afaik it is according to rocks

**Comment by max397574** [comment]
paths don't have to pre-exist
everybody who uses neovim from the commandline should be able to create a folder

**Comment by vhyrro** [comment]
A little extra verbosity doesn't hurt. I can clarify that for newcomers :)

**Comment by champignoom** [comment]
> paths don't have to pre-exist everybody who uses neovim from the commandline should be able to create a folder

Yeah I can create a folder under `~/.local/share/nvim` and celebrate the creation of a random folder if I wasn't creating for making neorg works.

**Comment by vhyrro** [comment]
Done!

**Comment by TarunDaCoder** [comment]
> @TarunDaCoder
> 
> > Since neorg may not be their first plugin, they'll know what to do. This isn't a how to setup neovim tutorial 🤣
> 
> This really should be, since the recommended installation process of neorg is coupled with a specific plugin management system (rocks.nvim) that not everyone has already used.

The installation may be a first, but not the configuration, right? Anyways, the issue is closed.
