### ISSUE TITLE
Add CI test for highlighting

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1460]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

(Somehow) add a test for syntax highlighting and make it part of CI.

Context: I installed neorg, kanagawa, tokyonight with rocks.nvim, and --- for like 6th time of my own experience --- syntax highlighting works under neither coloscheme. Nor is there any other recommended colorscheme given in the README.

It might not always be a problem from neorg "itself", like the last time it turned out to be kanagawa that not catching up treesitter's breaking changes. It might even be a problem of neovim nightly. But in anyway, if the ability of figuring out such technicalities is a prerequisite for using neorg, then neorg's UX would be practically broken.

Therefore, I'd suggest to let neorg take some of the responsibility and contribute to the stability of neorg's UX. And since such annoyance of one of neorg's core functionality has occurred and been reported way too often and systematic than a random bug since my experience with neorg, I'd suggest to add a test for highlighting under the recommended colorschemes, at least for the part not concerning termcap, like bold/slant.

![Screenshot_20240611_165556](https://github.com/nvim-neorg/neorg/assets/66909116/c04389a7-6b2c-4e45-8d13-1943ec150e7e)
![Screenshot_20240611_165658](https://github.com/nvim-neorg/neorg/assets/66909116/90d3196f-5fd3-4074-aac8-e5f8f8926d60)

### Help

Yes

**Comment by champignoom** [comment]
More info about the current bug:
- `InspectTree` works as expected
- `Inspect` works nowhere, always giving "No items found at position ... in buffer ..."
- markdown highlighting works as expected

So I guess this time it's not about the highlighting module but the syntax file.

**Comment by max397574** [comment]
really weird
are you sure you have treesitter highlighting enabled?
because the highlighting is done by treesitter and if the tree is correct highlighting should also work if it's enabled

**Comment by champignoom** [comment]
You're right, the problem is solved when treesitter highlighting is enabled.

But I guess such config should be appended to the installation sinppet, immediately after

https://github.com/nvim-neorg/neorg/blob/5239a98c462fb24201e76305d9d6265e4742a31e/README.md?plain=1#L93-L96
