### ISSUE TITLE
Inline markup not working

### ISSUE THREAD

**Issue by VictorLemosR** [nvim-neorg/neorg#1461]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.10

### Neorg setup

Lazy config
```
    "nvim-neorg/neorg",
    dependencies = { "luarocks.nvim" },
    lazy = false,
    version = "*",
    config = function ()
        local paths = require("victor.paths")
        local notes_folder = paths.notes_folder
        require("neorg").setup {
            load = {
                ["core.defaults"] = {},
                ["core.concealer"] = {
                    config = {
                        folds = true,
--                        icon_preset = "basic",
--                        init_open_folds = "always"
                    },
                },
        }
     end
```

Neorg configs inside ftplugin:
```
vim.opt_local.wrap = true
vim.opt_local.colorcolumn = "120"
vim.opt_local.textwidth = 120
vim.opt_local.spelllang = 'pt,en_us'
vim.opt_local.expandtab = false
vim.opt_local.foldenable = true
vim.opt_local.conceallevel = 2
vim.opt_local.concealcursor = "nv"
```
Treesitter lazy config:
```
    { 'nvim-treesitter/nvim-treesitter', build = ':TSUpdate' },
    { 'nvim-treesitter/playground' },
    { 'nvim-treesitter/nvim-treesitter-context' },

    config = function ()
        require'nvim-treesitter.configs'.setup {
            ensure_installed = { "python", "lua", "query", "rust", "norg" },

            -- Install parsers synchronously (only applied to `ensure_installed`)
            sync_install = true,

            -- Automatically install missing parsers when entering buffer
            -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
            auto_install = true,

            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
        }

    end

```
My colorscheme config:
```
    {"sainnhe/sonokai", priority = 1000, lazy = false,
    config = function()
        -- check for other colors, they are all good
        vim.g.sonokai_style = "andromeda"
        vim.g.sonokai_better_performance = 1
        vim.g.sonokai_colors_override = {
            yellow = {'#d5b359', '107'},
        }
        vim.cmd('colorscheme sonokai')

    end

```

### Actual behavior

Heading's formats works:
![image](https://github.com/nvim-neorg/neorg/assets/124196236/073e5988-f644-4876-8b33-0b651406596b)
Inline markups don't:
![image](https://github.com/nvim-neorg/neorg/assets/124196236/1f2c8dbf-f9dd-4ac4-b430-833700eb9c56)

As a side bug, To-do hotkeys don't work: <C-space> or <leader>td, for example

### Expected behavior

To work.

### Steps to reproduce

1. Installation was done via lazy.
2. My terminal is wezterm
3. I'm on windows
4. Neovim 0.10
5. Latest neorg (8.7.0 - even updated to the lastest version launched today 11-jun).

### Other information

What I checked/tried:
1. Treesitter highlight is enabled.
2. Bold and itallic works in .md:
![image](https://github.com/nvim-neorg/neorg/assets/124196236/8a2ed0d9-519a-421f-af4f-cc5f72317bea)
3. Checkhealth does not show any error and says concealer is ok:
![image](https://github.com/nvim-neorg/neorg/assets/124196236/835e555c-3c78-42c8-96e4-1fb4e0fe8af2)

**Comment by ha5h6r000wn** [comment]
same here, can somebody fix it?

**Comment by max397574** [comment]
try `:Inspect` when you're on it with the cursor and send the output

**Comment by ha5h6r000wn** [comment]
sorry ,i missed out the line "vim.wo.conceallevel = 2", now it looks good?
<img width="662" alt="image" src="https://github.com/nvim-neorg/neorg/assets/170237072/d98c2261-d880-49a0-9e1a-e22973471190">
Still, i find that the todo-item icons seems not aligned to the center. Is there any config to solve this issue? @max397574

**Comment by max397574** [comment]
no
this just depends on your terminal and font

**Comment by max397574** [comment]
both of these seem completely wrong
The first one just seems like treesitter isn't attached correctly or sth (try :InspectTree)
the second one either seems like a really bad bug or a mistake on your side
could you send the whole code snippet for the second one?

**Comment by VictorLemosR** [comment]
For the first one with :InspectTree
![image](https://github.com/nvim-neorg/neorg/assets/124196236/316660dd-1402-4672-a5c4-6830963a2ca3)

For the second one, here is the full photo:
![image](https://github.com/nvim-neorg/neorg/assets/124196236/79a12009-d3dd-45ac-8ef4-0eff1e0fa690)

**Comment by max397574** [comment]
well the second one is correct then afaik
injecting neorg into itself doesn't work

the first one seems really weird though
because the syntax tree looks correct
but just no highlights are applied

**Comment by enck** [comment]
@VictorLemosR: I had a very similar issue of bold, italic, and links. not working, but headings *did* work. After running `:TSConfigInfo`, I discovered that my treesitter config wasn't being read properly. Specifically, I noticed that `modules.highlight.enabled` was `false`, despite it being `true` in my config. Fixed my treesitter config to actually load, caused bold, italic, and links to started working.

Looking at your config above, the `config = function()` line for your nvim-treesitter config comes *after* the `}` of the nvim-treesitter-context package specification. I'm guessing your config isn't being loaded.

**Comment by VictorLemosR** [comment]
> @VictorLemosR: I had a very similar issue of bold, italic, and links. not working, but headings _did_ work. After running `:TSConfigInfo`, I discovered that my treesitter config wasn't being read properly. Specifically, I noticed that `modules.highlight.enabled` was `false`, despite it being `true` in my config. Fixed my treesitter config to actually load, caused bold, italic, and links to started working.
> 
> Looking at your config above, the `config = function()` line for your nvim-treesitter config comes _after_ the `}` of the nvim-treesitter-context package specification. I'm guessing your config isn't being loaded.

Thank you! That was exactly it. As you suggested, :TSConfigInfo showed my modules.highlight.enable was false. I just changed the initialization of my config for treesitter to the end of my initialization and it worked
