### ISSUE TITLE
no highlight in inline-codeblock

### ISSUE THREAD

**Issue by peter-lyr** [nvim-neorg/neorg#1464]
### Prerequisites

- [x] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0

### Neorg setup

-- neorg v8.6.0

require 'neorg'.setup {
  load = {
    ['core.defaults'] = {},
    ['core.concealer'] = {},
    ['core.esupports.metagen'] = {
      config = {
        update_date = false,
        type = 'empty',
        author = 'peter-lyr',
        timezone = 'implicit-local',
      },
    },
    ['core.export'] = {},
    ['core.export.markdown'] = {
      config = {
        extensions = 'all',
      },
    },
    ['core.ui'] = {},
    ['core.ui.calendar'] = {}, -- 解决中文乱码问题需要将Windows display language改为英文(美国)
    ['core.tempus'] = {},
    ['core.dirman'] = {
      config = {
        workspaces = {
          work = DepeiRepos .. '\\work',
          life = DepeiRepos .. '\\life',
          study = DepeiRepos .. '\\study',
        },
        default_workspace = 'work',
      },
    },
    ['core.integrations.telescope'] = {},
  },
}

### Actual behavior

![image](https://github.com/nvim-neorg/neorg/assets/55801796/30d6c36b-6cde-46dd-97e0-7195044d6368)

### Expected behavior

has highlight in inline-codeblock

### Steps to reproduce

open a .norg file in nvim.exe

### Help

None

**Comment by champignoom** [comment]
The `` `VERSIONID` `` part already looks highlighted to me.

What highlighting do you expect?

**Comment by vhyrro** [comment]
Hey,

Inline code blocks do not yet allow a language to be specified for them, therefore they cannot have any syntax highlight applied to them. Otherwise, the highlight looks good to me. Closing for now, but feel free to reopen if you still have any questions :)
