### ISSUE TITLE
[BUG] GTD issues with neovim 0.5

### ISSUE THREAD

**Issue by akinsho** [nvim-neorg/neorg#148]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.5.1 Build type: Release LuaJIT 2.1.0-beta3 Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -W shadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/config -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1 /src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/buil d/src/nvim/auto -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/include Compiled by brew@BigSur  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   falls-back for $VIM: "/usr/local/Cellar/neovim/0.5.1/share/nvim"  Run :checkhealth for more info

### Log Output

[ERROR Thu 29 Jul 15:17:58 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:18:04 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:19:52 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:20:38 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:20:43 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:20:46 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:23:50 2021] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:247: Unable to trigger keybind core.integrations.telescope.find_linkable - the keybind does not exist
[ERROR Thu 29 Jul 15:24:49 2021] .../nvim/site/pack/packer/start/neorg/lua/neorg/modules.lua:156: Unable to load module core.integrations.telescope - ...elescope/lua/telescope/_extensions/neorg/insert_link.lua:1: module 'telescope.actions' not found:
	no field package.preload['telescope.actions']
	no file './telescope/actions.lua'
	no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/telescope/actions.lua'
	no file '/usr/local/share/lua/5.1/telescope/actions.lua'
	no file '/usr/local/share/lua/5.1/telescope/actions/init.lua'
	no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/telescope/actions.lua'
	no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/telescope/actions/init.lua'
	no file '/Users/akinso/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/actions.lua'
	no file '/Users/akinso/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/actions/init.lua'
	no file '/Users/akinso/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/actions.lua'
	no file '/Users/akinso/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/actions/init.lua'
	no file './telescope/actions.so'
	no file '/usr/local/lib/lua/5.1/telescope/actions.so'
	no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/telescope/actions.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/akinso/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope/actions.so'
	no file './telescope.so'
	no file '/usr/local/lib/lua/5.1/telescope.so'
	no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/telescope.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/akinso/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope.so'
[FATAL Thu 29 Jul 15:24:49 2021] ...al/share/nvim/site/pack/packer/start/neorg/lua/neorg.lua:71: Halting loading of modules due to error...

### Branch

unstable

### Loaded modules

```lua
        require('neorg').setup {
          load = {
            ['core.defaults'] = {},
            ['core.integrations.telescope'] = {},
            ['core.keybinds'] = {
              config = {
                default_keybinds = true,
                neorg_leader = '<Leader>o',
              },
            },
            ['core.norg.completion'] = {
              config = {
                engine = 'nvim-cmp',
              },
            },
            ['core.norg.concealer'] = {},
            ['core.norg.dirman'] = {
              config = {
                workspaces = {
                  notes = '~/Dropbox/neorg/main/',
                  gtd = '~/Dropbox/neorg/gtd/',
                },
              },
            },
            ['core.gtd.base'] = {
              config = {
                workspace = 'gtd',
              },
            },
          },
        }

```

### Expected behavior

When running the command `:Neorg gtd capture` with the above config I get an error which says 
```
E5108: Error executing lua ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:556: attempt to call local 'callback' (a nil value)
```
I've ensured that the directories exist.

Hard to say what the right behaviour is since I haven't used the gtd mechanism yet but I assume some sort of popup rather than an error

### Actual behavior

Errors as described above complaining about a missing callback

### Potentially conflicting plugins

Nothing that I can think of

### Other information

Full packer spec

```lua
    use {
      'vhyrro/neorg',
      branch = 'unstable',
      requires = { 'vhyrro/neorg-telescope' },
      config = function()
        require('neorg').setup {
          load = {
            ['core.defaults'] = {},
            ['core.integrations.telescope'] = {},
            ['core.keybinds'] = {
              config = {
                default_keybinds = true,
                neorg_leader = '<Leader>o',
              },
            },
            ['core.norg.completion'] = {
              config = {
                engine = 'nvim-cmp',
              },
            },
            ['core.norg.concealer'] = {},
            ['core.norg.dirman'] = {
              config = {
                workspaces = {
                  notes = '~/Dropbox/neorg/main/',
                  gtd = '~/Dropbox/neorg/gtd/',
                },
              },
            },
            ['core.gtd.base'] = {
              config = {
                workspace = 'gtd',
              },
            },
          },
        }
      end,
    }
```

**Comment by danymat** [comment]
Okay I can reproduce the issue, it appears that nvim version is in cause here...

**Comment by akinsho** [comment]
@vhyrro the behaviour of `vim.tbl_deep_extend` did change I've hit this in my own config, see https://github.com/neovim/neovim/issues/14090#issuecomment-882660544, just to be clear though I'm not experiencing any telescope issues, or rather I don't actively use that feature, either way it's not something that I'm reporting in this issue (unless you meant @danymat not me)

**Comment by vhyrro** [comment]
Ahh right it did! So that seems to be the culprit then, and would also potentially explain why values are getting overwritten and emptied. I'll see what I can do about this in that case.

**Comment by akinsho** [comment]
This is all that is in my `inbox.norg` btw
```
@document.meta
        title: inbox
        description: 
        author: akinso
        categories: 
        created: 2021-10-08
        version: 0.1
@end

```
It still errors even when in the `inbox` file.

The `norg_files` prints `{ "inbox.norg", "index.norg" }`
