### ISSUE TITLE
Tree-sitter-norg build failed

### ISSUE THREAD

**Issue by GianmarcoAndreana** [nvim-neorg/neorg#1485]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0; Build type: Release; LuaJIT 2.1.1713484068

### Neorg setup

```
return {
  {
    "nvim-neorg/neorg",
    dependencies = { "luarocks.nvim" },
    lazy = false,
    version = "*",
    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.concealer"] = {},
          ["core.dirman"] = {
            config = {
              workspaces = {
                notes = "~/notes",
              },
              default_workspace = "notes",
            },
          },
        },
      }

      vim.wo.foldlevel = 99
      vim.wo.conceallevel = 2
    end,
  }
}
```

### Actual behavior

After upgrading to v 8.8.0, tree-sitter-norg fails to build. In the previous release, it worked fine.
I tried to sync the parser but the issue is still there.
I'm using Lazy-vim 12.20 on Windows 11.
<img width="731" alt="image" src="https://github.com/nvim-neorg/neorg/assets/42800762/a870a5bc-ddf8-480f-aa42-233755b8358d">

### Expected behavior

I expect that tree-sitter-norg build successfully

### Steps to reproduce

Upgrading Lazyvim automatically upgraded also Neorg to the latest version, causing the problem

### Potentially conflicting plugins

luarocks.nvim
nvim-treesitter

### Help

No

**Comment by joske** [comment]
I have the same issue. Arch Linux.

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

Lazy configuration:

```lua
return {
  "nvim-neorg/neorg",
  dependencies = { "luarocks.nvim" },
  lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
  version = "*", -- Pin Neorg to the latest stable release
  config = true,
}
```

**Comment by vhyrro** [comment]
This should be augmented in the latest minor release. Feel free to reopen if there are still issues :)
