### ISSUE TITLE
Config for todo_items - disable `[x/y] (z%)` count at parent todos

### ISSUE THREAD

**Issue by SuperCuber** [nvim-neorg/neorg#1512]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'd like to disable the virtual text at the end of a line for parent todo items that looks like `[1/2] (50%)` - I find it distracting and not helpful to me.

It would probably go as a configuration change in `core.qol.todo_items` module - at first I thought it was from the concealer module but it works after `toggle-concealer`.

### Help

Yes

### Implementation help

Hopefully it's a simple `if` away, would be nice to have a pointer to where it is in the code.

**Comment by max397574** [comment]
Well the module is the todo-introspector https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/todo-introspector/module.lua
It seems like it is part of the default modules. So you should be able to disable it like here https://github.com/nvim-neorg/neorg/wiki/Defaults

**Comment by SuperCuber** [comment]
Thanks for the swift reply! I couldn't find mention of this module in the wiki, perhaps this can be added to todo_items' page?
