### ISSUE TITLE
Which-key preventing core.keybinds default mappings

### ISSUE THREAD

**Issue by mtrajano** [nvim-neorg/neorg#1534]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0

### Neorg setup

  ```lua
  {
    'nvim-neorg/neorg',
    lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
    version = '*', -- Pin Neorg to the latest stable release
    config = true,
}
```

### Actual behavior

Currently with `which-key` installed none of the default key bindings are getting mapped. Uninstalling which-key fixes the issue and the checkhealth passes without any issues.

<img width="1702" alt="Screenshot 2024-07-23 at 10 56 08 AM" src="https://github.com/user-attachments/assets/6605c6eb-4891-44e5-b51c-9c1e198c8d99">

### Expected behavior

With which-key installed I would still expect the default key bindings to get mapped. There are no actual conflicts per se, the mappings it shows are from which-key  prefix that shows which keys are available by hitting the `<localleader>`  key

### Steps to reproduce

Install `which-key` and `neorg` with default config, neorg will not have any of the default key mappings and the checkhealth will report issues with conflicting key maps

### Potentially conflicting plugins

`which-key`

### Help

Yes

**Comment by mtrajano** [comment]
That is good to know, I guess I'm due for an upgrade then 😄 Possibly worth adding a note in the `core.keybind` wiki or some other place? It could be confusing for new users

**Comment by vhyrro** [comment]
Sounds like a good idea! I'll do that and close this issue.

**Comment by mtrajano** [comment]
Sounds good 👍 The upgrade to which-key v3 did work by the way
