### ISSUE TITLE
Default insert mode keybind for inserting date does not work

### ISSUE THREAD

**Issue by XavierChB** [nvim-neorg/neorg#1535]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1720049189

### Neorg setup

    {
        "nvim-neorg/neorg",
        lazy = false,
        version = "*",
        config = true
    },

### Actual behavior

When pressing the default keybind <M-d>, instead of showing a window to select dates, the literal string `"<Plug>(neorg.tempus.insert-date.insert-mode)"` is inserted into the buffer instead.

![image](https://github.com/user-attachments/assets/a2a38350-1a23-46d6-bc0c-98e9cdd34277)

All other insert mode keybinds seem to be fine.

### Expected behavior

Whatever `neorg.tempus.insert-date.insert-mode` is supposed to do.

### Steps to reproduce

Open a new neorg buffer and press the keybinding for `neorg.tempus.insert-date.insert-mode`. By default this should be <M-d>.

### Help

None

**Comment by vhyrro** [comment]
Hey, this has already been fixed as part of `9.0.3`. Please update and let me know if it's fixed :)

**Comment by XavierChB** [comment]
Hey, thanks for your quick response. I was on the latest version, and have confirmed it by explicitly syncing to version `9.0.3` on lazy.nvim. Unfortunately, the problem persists. You might notice that the literal string inserted is the one **after** the fix pushed in commit 87e55f3. Could it have something to do with `ui.calendar` or `tempus` not being loaded by default?

**Comment by vhyrro** [comment]
You're right, seems like this needed *two* fixes to work properly. What was happening was that the `<Plug>` mapping was being bound for normal mode, despite it not being usable there. It's fixed for me as part of `9.1.0` now :)

**Comment by XavierChB** [comment]
Good to know! Thanks for your prompt update!

**Comment by XavierChB** [comment]
Updated to `9.1.0`. It's fixed! Thanks!
