### ISSUE TITLE
Syntax highlighting for php doesn't work

### ISSUE THREAD

**Issue by sdifru** [nvim-neorg/neorg#1542]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.10.1

### Neorg setup

```
		neorg.setup({
			load = {
				["core.defaults"] = {},
				["core.concealer"] = {
					config = {
						folds = false,
						icons = {
							code_block = {
								conceal = true,
								width = "content",
							},
						},
					},
				},
				["core.export"] = {},
				["core.completion"] = {
					config = { engine = "nvim-cmp", name = "[Neorg]" },
				},
			},
		})
```

### Actual behavior

![screenshot-20240728-063923Z-selected](https://github.com/user-attachments/assets/12277c2f-95ce-4aaf-a22f-637af0dbf86f)

### Expected behavior

The php syntax would be highlighted.

### Steps to reproduce

Write php code in a neorg file.

### Other information

Code syntax such as javascript. typescript, and go are highlighted. It's only php syntax that doesn't get highlighted.

### Help

None

**Comment by max397574** [comment]
do you have the php treesitter parser installed?

**Comment by sdifru** [comment]
@max397574 yes.

![screenshot-20240728-102133Z-selected](https://github.com/user-attachments/assets/4eb46b3b-fb30-4eac-be12-9125daf4c2b1)

**Comment by sdifru** [comment]
I found why it didn't show syntax highlighting. I added `<?php` at the top of my file and it worked.
