### ISSUE TITLE
[BUG] No syntax highlighting 

### ISSUE THREAD

**Issue by kkharji** [nvim-neorg/neorg#155]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+1865-g3beea1fe1

### Log Output

Empty 

### Branch

unstable

### Loaded modules

```lua
local modules = {
  -- Load all the default modules
  ["core.defaults"] = {},
  -- Allows for use of icons
  ["core.norg.concealer"] = {},
  ["core.norg.completion"] = {
    config = {
      engine = "nvim-cmp",
    },
  },
  -- Manage your directories with Neorg
  ["core.norg.dirman"] = {
    config = {
      workspaces = {
        Uni = "~/uni",
      },
    },
  },
}
```
```lua
--- using packer
config = function()
  local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()

  require("neorg").setup {
    load = modules,
  }

  parser_configs.norg = {
    install_info = {
      url = "https://github.com/nvim-neorg/tree-sitter-norg",
      files = { "src/parser.c", "src/scanner.cc" },
      branch = "main",
    },
  }
end
```
### Expected behavior

Syntax highlighting for neorg

### Actual behavior

![Screen Shot 2021-10-12 at 6 19 44 PM](https://user-images.githubusercontent.com/65782666/136983837-016e4dd5-7ea6-498e-80bc-6981c773ffb8.png)

### Help

No

**Comment by tami5** [comment]
> Haha, glad to hear it at least works now :)

btw awesome work @vhyrro I'm exploring neorg right now. Though I'm trying to find a builtin way to jump to file/heading under the cursor
