### ISSUE TITLE
Only highlights help norg, not any I write

### ISSUE THREAD

**Issue by tungstengmd** [nvim-neorg/neorg#1551]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

10.0

### Neorg setup

load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "~/notes",
                        },
                        default_workspace = "notes",
                    },
                },
            },

### Actual behavior

The behaviour I experience is uhh... this.
![image](https://github.com/user-attachments/assets/8d28b840-8dbf-46d8-a11a-43d310135b1e)

### Expected behavior

I expect it to _also_ highlight my own file... but it doesn't.

### Steps to reproduce

1. Make a norg file.
2. Write in it.
3. It won't highlight or show pretty symbols or markup.

### Help

No

**Comment by max397574** [comment]
apart from `:h conceallevel` this looks completely fine to me

**Comment by max397574** [comment]
but except conceallevel the document looks completely normal

**Comment by tungstengmd** [comment]
wdym

**Comment by tungstengmd** [comment]
the top one is the help file, which is highlighted right
the bottom one is my file which isnt even highlighted

**Comment by max397574** [comment]
oh didn't see that there were two files

**Comment by tungstengmd** [comment]
![image](https://github.com/user-attachments/assets/3739bf2a-397a-49f1-accb-61da5666a230)
to make it significantly less confusing

**Comment by tungstengmd** [comment]
> oh didn't see that there were two files

fair

**Comment by max397574** [comment]
is treesitter highlighting enabled? (TSBufEnable highlight), and highlight={enabled=true} in treesitter config
also try `:InspectTree` to see if treesitter is attached and parsing works

**Comment by tungstengmd** [comment]
hmm
![image](https://github.com/user-attachments/assets/86f558a7-c37d-4d04-9734-e63162acc2e8)

**Comment by tungstengmd** [comment]
also highlight is enabled

**Comment by max397574** [comment]
`:set ft`
seems like norg filetype isn't recognized even though that's now builtin to neovim

**Comment by tungstengmd** [comment]
![image](https://github.com/user-attachments/assets/a938db7d-364d-43a2-acc7-225f34a39d60)

**Comment by tungstengmd** [comment]
on the norg fyi

**Comment by max397574** [comment]
there you have the problem
the filetype isn't recognized
which isn't a neorg issue
because filetype detection should now be done by core
can you send the whole output of `nvim --version`?

**Comment by tungstengmd** [comment]
![image](https://github.com/user-attachments/assets/72a747ed-a097-4e42-9b0d-a6ce75bebce0)

**Comment by tungstengmd** [comment]
prolly due to it being v10 not 11

**Comment by max397574** [comment]
no 0.10 should work, I also use it
do you by any chance use any special things for filetype detection?

**Comment by tungstengmd** [comment]
wdym

**Comment by tungstengmd** [comment]
alr ill load it clean

**Comment by tungstengmd** [comment]
my brother in christ it knows, this is a neorg issue
![image](https://github.com/user-attachments/assets/2f2bf480-816a-497e-ad09-3dd797a6a3be)

**Comment by max397574** [comment]
did you use nvim --clean? I'd also try to just remove the neorg plugin

**Comment by tungstengmd** [comment]
yeah i used nvim --clean

**Comment by tungstengmd** [comment]
![image](https://github.com/user-attachments/assets/1b6b7154-49b8-4853-a76f-a7f0aa0adbd0)
...

**Comment by tungstengmd** [comment]
after i remove neorg
what is the problem here

**Comment by tungstengmd** [comment]
im gonna try and find anything hold on

**Comment by max397574** [comment]
well not neorg 😄 
perhaps move this to a discussion since it's not related to neorg

**Comment by tungstengmd** [comment]
fair enough

**Comment by max397574** [comment]
I'd suggest you to just start disabling plugins like 5 at a time and like that figure out which one is messing things up here

**Comment by max397574** [comment]
@tungstengmd can close this issue

**Comment by tungstengmd** [comment]
so the problem was vim-polyglot, there should be a section in readme showing anything that may conflict with neorg

**Comment by tungstengmd** [comment]
1. at least put a list of what's known
2. vim-polyglot hasn't been updated in 2 years
