### ISSUE TITLE
Errors when using coq_nvim for autocompletion

### ISSUE THREAD

**Issue by LoCrealloc** [nvim-neorg/neorg#1594]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.10.2

### Neorg setup
```
require("neorg").setup({
  load = {
	["core.defaults"] = {},
	["core.concealer"] = {},
	["core.autocommands"] = {},
	["core.integrations.image"] = {},
	["core.integrations.coq_nvim"] = {},
	["core.pivot"] = {},
	["core.latex.renderer"] = {
		config = {
			conceal = true,
			render_on_enter = true,
			dpi = 450,
			scale = 1,
		},
	},
	["core.completion"] = {
		config = {
		 engine = "coq_nvim",
		},
	},
	["core.integrations.treesitter"] = {
		config = {
			install_parsers = false; -- handled by nix
		},
	},
	["core.dirman"] = {
		config = {
			workspaces = {
				uni = "~/Documents/Uni",
			},
		},
	},
  }
})
```

### Actual behavior

whenever I try linking to something in neorg, coq complains with an error like 
`coq_nvim/lua/coq/lsp-request.lua:373: NotImplementedError :: coq_3p.args->full_line` as soon as i type {:<any symbol>

### Expected behavior

coq should provide fitting auto completion suggestions for the links.

### Steps to reproduce

1. Install Neorg and setup coq_nvim
2. tell neorg to use coq_nvim for autocompletion
3. open a neorg file
4. try to link to something in neorg

### Other information

I tried also with Neorg v8.6.0 and coq_nvim from 2024-04-26.
I use NixOS unstable.

### Help

No

**Comment by benlubas** [comment]
You can also use https://github.com/benlubas/neorg-interim-ls, if this integration ever breaks again
