### ISSUE TITLE
Links not rendering as shortened version

### ISSUE THREAD

**Issue by Jellie06** [nvim-neorg/neorg#1611]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.10.2

### Neorg setup

```
-- File: plugins/neorg.lua
return {
  "nvim-neorg/neorg",
  dependencies = { "nvim-treesitter/nvim-treesitter" }, -- Ensure Tree-sitter is installed
  build = function()
    vim.cmd("Neorg sync-parsers") -- Ensure parsers are up-to-date
  end,
  config = function()
    require("neorg").setup({
      load = {
        ["core.defaults"] = {}, -- Load default settings
        ["core.concealer"] = {
          config = {
              icons = {
                  heading = {
                      enabled = true,
                  },
              },
          },
      },      
        ["core.ui"] = {}, -- General UI improvements
        ["core.qol.toc"] = {}, -- Enable Table of Contents module
        ["core.dirman"] = { -- Manage Neorg workspaces
          config = {
            workspaces = {
              my_workspace = "~/OneDrive/Documents/neorg", -- Set your workspace path
              journal = "~/OneDrive/Documents/neorg/Journal", -- Add the journal workspace
            },
          },
        },
        ["core.keybinds"] = {}, -- Enable default keybindings
      },
    })
  end,
}
```

### Actual behavior

Any links, whether that be URLs, files, norg files won't shorten despite giving them names. See below for example 

![image](https://github.com/user-attachments/assets/1dddc938-550a-466a-a83b-e546af2ea88e)

### Expected behavior

For the link to just show 2024 Journal

![image](https://github.com/user-attachments/assets/b044c5d5-df8e-4968-bca3-8d8e7c84cfe5)

### Steps to reproduce

It just happens every time with all links

### Other information

I'm on Windows

### Help

None

**Comment by max397574** [comment]
:h conceallevel

**Comment by benlubas** [comment]
You've set `conceallevel=2` and moved your cursor off of the link, and it still doesn't conceal? And you have treesitter installed and configured?

conceal works in the help pages, right?

**Comment by Jellie06** [comment]
> You've set `conceallevel=2` and moved your cursor off of the link, and it still doesn't conceal? And you have treesitter installed and configured?
> 
> conceal works in the help pages, right?

Sorry I've just done it again and it's working now. Sorry for the trouble.
