### ISSUE TITLE
Latex rendering matrix is not readable

### ISSUE THREAD

**Issue by sdifru** [nvim-neorg/neorg#1612]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

When rendering matrix, it shows small fonts such as follows:
![screenshot-20241202-041324Z-selected](https://github.com/user-attachments/assets/0253c1db-c0ee-4d5a-9dfc-465ca1e9675e)

It is not quite readable. It would be great if the matrix line could have the same font size as the second line such as in the picture.

### Help

No

**Comment by benlubas** [comment]
you can configure the height. It's janky, but just set the max height to 2 so it can take up two lines if the resulting image is large enough

**Comment by sdifru** [comment]
> you can configure the height. It's janky, but just set the max height to 2 so it can take up two lines if the resulting image is large enough

How do you configure the height? I couldn't find it on the documentation.

**Comment by benlubas** [comment]
scale

**Comment by sdifru** [comment]
@benlubas I've even changed the scale to 10 and it still doesn't work.
`["core.latex.renderer"] = {
					scale = 10,
				}`

**Comment by benlubas** [comment]
Sorry I didn't explain this part well enough:

> if the resulting image is large enough

The image that is generated needs to be taller than two rows to take up two rows. Image.nvim will not render an image larger than it actually is.
