### ISSUE TITLE
[BUG] Folds hides virtual text on todos stats

### ISSUE THREAD

**Issue by tami5** [nvim-neorg/neorg#174]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+1967-g427bac687

### Log Output

Irreverent

### Branch

unstable

### Loaded modules

```lua 
-- Load all the default modules
 ["core.defaults"]
 ["core.norg.concealer"] 
 ["core.norg.completion"] 
 ["core.norg.dirman"]
 ["core.integrations.telescope"]
 ["core.integrations.treesitter"] 
 ["core.keybinds"]
```

### Expected behavior

To show the virtual text when heading are folded.

### Actual behavior

Virtual text is hidden when the headings are folded.

**Comment by vhyrro** [comment]
I feel like the only way of realistically tackling this would be to make the foldexpr emulate whatever would be at the folded line at any given moment. I wonder if it's possible to "copy" extmarks 🤔, maybe then we'd be able to solve all of these issues with folds :D

**Comment by vhyrro** [comment]
This has now been fixed in the latest unstable branch! Should display everything now :)

If there's still any issues feel free to reopen this issue

**Comment by tami5** [comment]
> This has now been fixed in the latest unstable branch! Should display everything now :)
> 
> 
> 
> If there's still any issues feel free to reopen this issue

Amazing 🤩, Thanks @vhyrro
