### ISSUE TITLE
[BUG] Using neorg valid elements inside code blocks

### ISSUE THREAD

**Issue by shift-d** [nvim-neorg/neorg#175]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+479-g9086938f7

### Branch

unstable

### Loaded modules

core.ui
core.ui.text_popup
core.neorgcmd
core.mode
core.norg.qol.todo_items
core.norg.esupports
core.norg.esupports.metagen
core.neorgcmd.commands.module.load
core.norg.manoeuvre
core.autocommands
core.norg.concealer.preset_basic
core.defaults
core.norg.concealer
core.norg.dirman
core.neorgcmd.commands.return
core.norg.completion
core.norg.concealer.preset_varied
core.norg.concealer.preset_diamond
core.ui.selection_popup
core.keybinds
core.integrations.treesitter
core.integrations.nvim-cmp
core.scanner
core.highlights
core.keybinds.default_keybinds
core.neorgcmd.commands.module.list

### Expected behavior

Using `*` inside code block should not be recognised as header in neorg.

### Actual behavior

After typing `*` and `<Space>` `*` dissapears. Seems like neorg tries to make it behave as header, but it does not even being displayed like this. Instead it dissapears.

**Comment by mrossinek** [comment]
@shift-d Are you still experiencing this issue with the latest Neorg of the `main` branch + the latest tree-sitter parser?
If yes, please provide a minimal reproducible example.

I do not see the icons disappearing but I am noticing some odd indentation behavior. That will get fixed as part of #184 :+1:

**Comment by mrossinek** [comment]
Closing as this is likely fixed. Please re-open if needed.
