### ISSUE TITLE
[BUG] Combining text modifiers

### ISSUE THREAD

**Issue by shift-d** [nvim-neorg/neorg#176]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+479-g9086938f7

### Branch

unstable

### Loaded modules

core.ui
core.ui.text_popup
core.neorgcmd
core.mode
core.norg.qol.todo_items
core.norg.esupports
core.norg.esupports.metagen
core.neorgcmd.commands.module.load
core.norg.manoeuvre
core.autocommands
core.norg.concealer.preset_basic
core.defaults
core.norg.concealer
core.norg.dirman
core.neorgcmd.commands.return
core.norg.completion
core.norg.concealer.preset_varied
core.norg.concealer.preset_diamond
core.ui.selection_popup
core.keybinds
core.integrations.treesitter
core.integrations.nvim-cmp
core.scanner
core.highlights
core.keybinds.default_keybinds
core.neorgcmd.commands.module.list

### Expected behavior

`_/text/_`
text is italic
text is underlined

### Actual behavior

`_/text/_`
text is italic
/text/ is underlined

### Other information

This is concealer issue.

**Comment by mrossinek** [comment]
This is going to be fixed once we switch to the TS-based concealing as implemented in #117

**Comment by mrossinek** [comment]
@shift-d this should be fixed on the latest neorg + the latest TS parser. Please re-open if need be :+1:
