### ISSUE TITLE
Calendar and appointments

### ISSUE THREAD

**Issue by n3ry7** [nvim-neorg/neorg#18]
It would be super awesome if it could include something along the lines of calcurse to manage appointments and tasks.

I am currently looking into ways to get organized and calcurse is almost what I was looking for. Just wished it could be more easy to integrate with other programs.

I have never written a plugin for vim, but I could try and help on this idea.

**Comment by vhyrro** [comment]
I actually had to test out calcurse myself for a bit to check it out and i gotta say that a calcurseesque interface would be really neat. I'll play around with it a bit more to gain some extra potential inspiration

**Comment by molleweide** [comment]
when you say interface do you mean connect calcurse to neorg or do you mean create new cal implementation in neorg? I guess you gotta use for a while to be able to answer the question. i have it installd but have not yet learnt how to use it really..

**Comment by vhyrro** [comment]
They supposedly have scripts to be able to control parts of calcurse without the TUI. I think it'll be something along the lines of "integration", kind of like we will eventually have taskwarrior integration - our UIs and frontends will be ours, but you will be able to synchronize info between existing terminal apps and Neorg itself.

**Comment by n3ry7** [comment]
Integration would be nice, but ideally I would prefer something similar implemented in neorg. 

I think it would make it easier to customize and work with other vim plugins.

But maybe the integration works better than I think. I myself could not figure out a good way to use calcurse with my vim wiki.

**Comment by vhyrro** [comment]
Don't worry bout that, we will have our own native implementations. We're gonna try not to rely on third party apps. The integration would simply allow e.g. calcurse and Neorg to sync their data, but that's really it.

**Comment by molleweide** [comment]
> Don't worry bout that, we will have our own native implementations. We're gonna try not to rely on third party apps. The integration would simply allow e.g. calcurse and Neorg to sync their data, but that's really it.

Wow!!

**Comment by syntezoid** [comment]
@vhyrro After words like these, I can only say https://i.kym-cdn.com/photos/images/newsfeed/000/718/611/ab8.gif
I never before use org.mode, only heard about it, but I use neorg now for my todo list and tasks and I love it.

**Comment by molleweide** [comment]
Lol

**Comment by danymat** [comment]
I'm working (with @vhyrro) on a GTD implementation in Neorg (tasks management), here: #99 
We will support tasks with deadlines and start dates, and we plan to create some views showing you a week view for your tasks.

**Comment by molleweide** [comment]
> Hello everyone, you can start using GTD in the `unstable` branch from neorg. Feel free to check the instructions in #99. The next action in GTD will be to customize today view, and create a week view, that will likely meet your needs. Feel free to check out #145 for more updates
> 
> I am closing this issue as it's likely done

Cool! I'm gonna get into this now and try to help if I can.

**Comment by danymat** [comment]
No problem ! But since writing this, the `Neorg gtd views` have a lot more to offer, feel free to check it out !

**Comment by molleweide** [comment]
Yeah I have seen that you have done a massive work. I'm pretty excited!
