### ISSUE TITLE
[FEATURE REQUEST]: A command to generate diary like files

### ISSUE THREAD

**Issue by ashincoder** [nvim-neorg/neorg#180]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hi,
  I've started using neorg for about a week and I must say I am loving it :smile: . I have integrated it into my daily setup. 

If there was a command to generate files according to the date it would be great for people writing diaries or journals (like me). Vimwiki has such a command (`:VimwikiDiaryNextDay`, `:VimwikiDiaryPrevDay`, etc).

Thank you for such an amazing work. :+1: 

### Help

No.
I am in a very critical spot of my career. Which will be the deciding factor for my future. So I won't be helping or concentrating it for now. I might in the future ahead. I shall ping you if I am ready for the journey :smile: .

**Comment by vhyrro** [comment]
This sounds like a very nice feature to implement, one that is basic but powerful for many. I'm currently occupied a lil, there's a lot going on right now (a chunk of syntax changes, changing treesitter + writing new treesitter tests, making enter link on \<CR> work again, revamping indentation). Since writing the basics of a diary system isn't complex I'll see if I can cram it in somewhere inbetween those activities :)

I'll get back to you whenever I do!

**Comment by ashincoder** [comment]
Sure, Thank you so much for your attention. Would love to see this project grow :smile:

**Comment by mactep** [comment]
I just want to point out that a workaround may be using [wiki.vim](https://github.com/lervag/wiki.vim) alongside neorg to improve your workflow. Configure the plugin like this:

``` lua
vim.g.wiki_filetypes = {'norg'}
vim.g.wiki_link_extension = '.norg'
```

Then you can use `<leader>w<leader>w` to go to today's file and use `:WikiJournalNext` and `:WikiJournalPrev` to navigate between files.

**Comment by ashincoder** [comment]
Also completely unrelated,
But how can I fold a heading like in org mode ? I did search the wiki but couldn't find it. Is it specified somewhere ?

**Comment by shift-d** [comment]
@ashincoder Use `za` for folding whole header 😃

**Comment by ashincoder** [comment]
> @ashincoder Use `za` for folding whole header smiley

Can I change it to like `TAB` or something ?

**Comment by vhyrro** [comment]
`za` is a native vim/neovim keybind for folding, it's not something inherent to neorg :)

I personally don't know whether neovim requires you to do a remap or whether it has some other method of changing the fold keys, so can't help out with that 👀 sorry

**Comment by ashincoder** [comment]
> za is a native vim/neovim keybind for folding, it's not something inherent to neorg :)

Oh is it ! I didn't knew actually. Thank you for saying it. No worries.
Maybe adding folds to the headings can be a great additional feat. 
https://github.com/kristijanhusak/orgmode.nvim/blob/master/lua/orgmode/org/indent.lua

**Comment by danymat** [comment]
Hello, @max397574 is starting to work on a journal module.

He created a PR here: #182.
Be sure to subscribe if you want to keep updated with those changes

**Comment by ashincoder** [comment]
Also making the headings bold would make it more standout.
If there was something to generate TOC then it would also be great too . :+1:

**Comment by danymat** [comment]
> If there was something to generate TOC then it would also be great too .

TOC generation is being developed here: https://github.com/nvim-neorg/neorg/pull/159

**Comment by ashincoder** [comment]
> `za` is a native vim/neovim keybind for folding, it's not something inherent to neorg :)
> 
> I personally don't know whether neovim requires you to do a remap or whether it has some other method of changing the fold keys, so can't help out with that eyes sorry

Maybe adding folds to the headings can be a great additional feat. Since I use neorg(a lot) for managing my notes. I do like it more categorised and toggleable rather than doing `za`.

**Comment by mrossinek** [comment]
> Maybe adding folds to the headings can be a great additional feat.

This is already possible: all headings, ranged tags and lists are foldable objects. To ensure that this works as expected you need:
```vim
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
```

> Can I change it to like TAB or something ?

You can remap `za` to something else like so:
```vim
nnoremap <Tab> za
```

Is this what you had in mind?

**Comment by ashincoder** [comment]
No actually.

Like orgmode. The headings are toggled in orgmode. Builting behaviour



> > Maybe adding folds to the headings can be a great additional feat.
> 
> This is already possible: all headings, ranged tags and lists are foldable objects. To ensure that this works as expected you need:
> 
> ```viml
> set foldmethod=expr
> set foldexpr=nvim_treesitter#foldexpr()
> ```
> 
> > Can I change it to like TAB or something ?
> 
> You can remap `za` to something else like so:
> 
> ```viml
> nnoremap <Tab> za
> ```
> 
> Is this what you had in mind?

But this method is something bare. What I had in mind is something just toggled just like in orgmode.

**Comment by ashincoder** [comment]
> > The headings are toggled in orgmode. Builtin behaviour
> 
> I don't fully understand. I suppose you mean something like `foldlevel` and `foldlevelstart`? A quick test shows that `foldlevelstart` does not appear to be respected. I will need to investigate more whether this is a neorg or nvim-treesitter issue.

I will just show u a recording

https://asciinema.org/a/IxA1vmdm9TLJodvJNYV1H9RQA

**Comment by mrossinek** [comment]
As I said above, this is already possible. See below:
https://asciinema.org/a/t9yBeb57q6kw7ka3SPJmy6vse

This is achieved with builtin vim functionality. See help for `za`, `zM`, `zR` (or `folds` in general for that matter)

**Comment by ashincoder** [comment]
The problem for me is that I have setup TAB for buffer switching. Yeah that is not ur issue. 
Anyways thank you

**Comment by mrossinek** [comment]
> The problem for me is that I have setup TAB for buffer switching. Yeah that is not ur issue. Anyways thank you

I mean you were asking for `Tab` previously. My `nnoremap` example was based on that question. You can map it to anything you want. Personally, I use `\\` which on my keyboard layout is located quite conveniently :+1:

**Comment by danymat** [comment]
#182 is merged ! You can now try it out on unstable.

**Comment by ashincoder** [comment]
> #182 is merged ! You can now try it out on unstable.

I have just tried. Thank you very much max and all those who have contributed. Love to see this project growing. Thank you once again. This works lovely
