### ISSUE TITLE
[BUG] When writing italics (and maybe other markup), colons should not be a valid punctuation/separator.

### ISSUE THREAD

**Issue by emi2k01** [nvim-neorg/neorg#187]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

v0.6.0-dev+560-g1fdbd29df

### Branch

unstable

### Loaded modules

-

### Expected behavior

Writing `/The url https://google.com is not valid/` should result in:

_The url https://google.com is not valid_

### Actual behavior

Writing `/The url https://google.com is not valid/` results in:

_The url https:_//google.com is not valid

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I have no familiarity with the parser or whatever modules should be modified.

**Comment by mrossinek** [comment]
Thanks for the bug report! This will automatically get fixed once we merge switch to TS-based concealing (providing by #117).
