### ISSUE TITLE
[FEATURE REQUEST] Regex fallback for code blocks

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#188]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently this plugin relies on just treesitter to deal with nested syntaxes for code blocks. While this works completely fine, not all language have a TS parser. A way around this would be to use a nested syntax like how Vimwiki [does it](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/base.vim#L1103). It seems fairly straight forward, and would allow a ton more languages to be highlighted. It also doesn't seem to require additional user settings (`additional_vim_regex_highlighting` for instance)

However, in my rudimentary testing I have noticed somethings that would need to be addressed

1. I can only get 1 language to get recognized at all. I'm not sure if this is a TS thing or something Vimwiki needed to work around somehow
2. the highlight group `NeorgTagContent` overwrites the colors of the nested syntax. I'm assuming this group is intentional, a method around this would be needed to address how this group works with the greater plugin
3. Possible option for regex or TS highlighting in the code tag for languages that have both, perhaps an optional option for the begin code tag:
```
@code language regex
some regex highlighted code
@end
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I'm quite unfamiliar with the project structure and general programming standards for this project. I am more than willing to help implement this, but I would need some guidance on it

**Comment by katawful** [comment]
So I found where I would need to implement the fallback, but I have no idea how to tell if the end user has the necessary treesitter parser for the code block in question. I wouldn't want to run the regex fallback on top of TS highlighting

**Comment by danymat** [comment]
@vhyrro

**Comment by vhyrro** [comment]
@katawful oh my, I completely missed this issue somehow, so sorry! It would be nice to see regex highlighting within codeblocks as a fallback, I agree. I believe it may be possible to test for the existence of a parser using a `pcall()` and `vim.treesitter.get_parser(0, "name")`, and then optionally apply that regex highlighting on top.

I won't have time to play around with this idea today but if you don't get around to this first I'll give it a crack :)

**Comment by katawful** [comment]
Alright, this should put me on the right track. Thanks

**Comment by katawful** [comment]
#193 Opened a PR for this

**Comment by katawful** [comment]
Closed by #193
