### ISSUE TITLE
Fold using virtual text

### ISSUE THREAD

**Issue by tami5** [nvim-neorg/neorg#189]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'd like to see the highlights consistent across heading when it's folded. #157 made icon possible. but using virtual may enable having custom highlights and highlights that match the heading highlights. and perhaps show `@document.meta` is `Meta`

### Help

Yes

### Implementation help

Not sure yet, I never worked with virtual text before but first step is to set foldtext to empty string.

**Comment by vhyrro** [comment]
To my knowledge this unfortunately is not possible (unless someone proves me wrong). I've tried placing virtual text over folds but that is very odd to deal with and I don't even know whether it works :(

**Comment by tami5** [comment]
> To my knowledge this unfortunately is not possible (unless someone proves me wrong). I've tried placing virtual text over folds but that is very odd to deal with and I don't even know whether it works :(

hmmm even when the foldtext is empty string?, I never said it will be easy 😆 but I intend to work on it soon.

**Comment by vhyrro** [comment]
Sure thing! If it ends up working then imma be impressed 😳. Let me know if you manage to brew something up :)
