### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by oeyoews** [nvim-neorg/neorg#199]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.5.1

### Log Output

- ps: because my neorg.lgo file is empty. not upload this file

### Branch

master

### Loaded modules

- use nvim-cmp 

### Expected behavior

- when I creat a file, like crontab.norg、crontabs.norg, these files header not highlight, and when i input @ , i get this error tips.
![2021-11-21 17-27-06 的屏幕截图](https://user-images.githubusercontent.com/72405338/142756837-53a41d1d-0cde-4092-8718-b7645439b4f9.png)

- but when i creat anoter file(cron.norg), all is right
![2021-11-21 17-28-19 的屏幕截图](https://user-images.githubusercontent.com/72405338/142756871-a26b8986-c247-40ed-9066-efb480dae173.png)

- ps: because my neorg.lgo file is empty. not upload this file

### Actual behavior

- nothing

**Comment by vhyrro** [comment]
Well that's definitely not right :P. This kind of looks like an issue with nvim-treesitter not loading properly perhaps? Are you using packer, or some other plugin manager for Neovim? Are you lazy loading nvim-treesitter in any way as well? Seems like treesitter quite literally isn't loading the Neorg parser and is therefore failing to return information about the document back to Neorg.

There's also a slight chance that this may autofix itself once we merge the unstable branch into main (which'll happen in a few days, a week at worst). I'll definitely give this a closer look if it's not fixed until then tho :)
