### ISSUE TITLE
[GTD] Add customization options to projects view

### ISSUE THREAD

**Issue by esquires** [nvim-neorg/neorg#207]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+647-gb16b7021e Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/esquires3/repos/neovim/build/config -I/home/esquires3/repos/neovim/src -I/home/esquires3/repos/neovim/.deps/usr/include -I/usr/include -I/home/esquires3/repos/neovim/build/src/nvim/auto -I/home/esquires3/repos/neovim/build/include Compiled by esquires3@esquires-pc2  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Log Output

The file is empty.

### Branch

unstable

### Loaded modules

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.norg.concealer"] = {}, -- Allows for use of icons
    ["core.norg.dirman"] = { -- Manage your directories with Neorg
      config = {
        workspaces = {
          my_workspace = "~/norg"
        }
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.gtd.base"] = {},
    ["core.gtd.ui"] = {},
    ["core.keybinds"] = { -- Configure core.keybinds
        config = {
            default_keybinds = true, -- Generate the default keybinds
            neorg_leader = "<Leader>o" 
        }
    },
  },
}

local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

parser_configs.norg = {
    install_info = {
        url = "https://github.com/nvim-neorg/tree-sitter-norg",
        files = { "src/parser.c", "src/scanner.cc" },
        branch = "main"
    },
}

require('nvim-treesitter.configs').setup {
    ensure_installed = { "norg", "cpp", "c", "python" },
    highlight = { -- Be sure to enable highlights if you haven't!
        enable = true,
    }
}

```

### Expected behavior

I am expecting that "A Section That Is Not a Project" does not show up when running `:Neorg gtd views` and then typing `p` (for projects list)

### Actual behavior

```
*Projects*

- /2 tasks don't have a project assigned/

| /Projects with no Area Of Focus/

* My Project (0/2 done)
   [          ] 0% done

* A Section That Is Not a Project (0/0 done)
   [          ] 0% done

```

### Other information

When I put the above file into `inbox.norg` I get no output for the project list. When I put it in `actions.norg` I get the above output.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by danymat** [comment]
I don't quite understand the problem here, why don't you expect the project to be in projects list ?

**Comment by esquires** [comment]
Perhaps I am not understanding the spec, but it seems like `*` designates both a project and a heading. In my use case I have a bunch of sections with no tasks under them so when I look at the project list I get a bunch of projects with no tasks underneath. Is it intended for every section (e.g. those with just notes) to be treated as a project?

**Comment by danymat** [comment]
@esquires Exactly, it treats every heading 1 as a gtd project.
That's why we can create a dedicated gcd workspace so that your tasks doesn't mess up with your notes.

We were discussing with @mrossinek about adding an option to not show projects with no tasks in it. What do you think ?

At the moment you can specify a different workspace like this:

```
		["core.gtd.base"] = {
			config = {
				workspace = "gtd",
				exclude = { "gtd.norg", "neogen.norg", "kenaos.norg" },
			},
		},
```

**Comment by esquires** [comment]
Thanks for the clarification! Adding an option to not show projects with no tasks would be great.

On my end, switching workspaces seems like it would add overhead to workflow since I would need to switch between them just to add tasks (and then switch back).

**Comment by esquires** [comment]
Looks like you might be working on this. Thanks! If so, it may also be nice to be able to not show completed projects as well to further simplify the interface.

**Comment by danymat** [comment]
Hello, I added the two configuration options that you can use like this:

```
["core.gtd.base"] = {
	config = {
                ...
                displayers = {
                      projects = {
                             show_completed_projects = true, -- put false if you don't want to see completed projects
                            show_projects_without_tasks = true,  -- put false if you don't want to see projects without tasks
                      },
                },
	},
},
```

**Comment by esquires** [comment]
Thanks! I just tested it out and it works great.

What do you think about moving the configuration to the user interface so a user can easily switch between the views? Something like the following (where the defaults you have above change the initial view when a user enters the buffer).

I tried to pick keys that aren't relevant to the buffer. Assumedly the user isn't modifying text in this buffer so `c` (for completed) and `s` (for show) shouldn't be reserved already in this view. 

```
*Projects*

Options:
c - toggle showing completed tasks
s - toggle showing projects without tasks

- /2 tasks don't have a project assigned/

| /Projects with no Area Of Focus/

* My Project (0/2 done)
   [          ] 0% done

* A Section That Is Not a Project (0/0 done)
   [          ] 0% done

```

**Comment by danymat** [comment]
> What do you think about moving the configuration to the user interface so a user can easily switch between the views? Something like the following (where the defaults you have above change the initial view when a user enters the buffer).

Maybe, that can be a little tricky because we will need to re-display the view. I close this issue if it works for you, and maybe you could create an other issue for this particular demand.

**Comment by esquires** [comment]
No problem. I didn't realize it would be involved so this solution works great. Thanks for the fix!
