### ISSUE TITLE
[BUG] Neorg leader breaks when quitting with `:q`

### ISSUE THREAD

**Issue by esquires** [nvim-neorg/neorg#209]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+651-gcaf41a7ac Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/esquires3/repos/neovim/build/config -I/home/esquires3/repos/neovim/src -I/home/esquires3/repos/neovim/.deps/usr/include -I/usr/include -I/home/esquires3/repos/neovim/build/src/nvim/auto -I/home/esquires3/repos/neovim/build/include Compiled by esquires3@esquires-pc2  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Log Output

none

### Branch

unstable

### Loaded modules

```lua
-- neorg
require('neorg').setup {
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.norg.concealer"] = {}, -- Allows for use of icons
    ["core.norg.dirman"] = { -- Manage your directories with Neorg
      config = {
        workspaces = {
          my_workspace = "~/neorg"
        },
        autochdir = true,
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.gtd.base"] = {},
    ["core.gtd.ui"] = {},
    ["core.keybinds"] = { -- Configure core.keybinds
        config = {
            default_keybinds = true, -- Generate the default keybinds
            neorg_leader = "<Leader>o" 
        }
    },
  },
}

local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

parser_configs.norg = {
    install_info = {
        url = "https://github.com/nvim-neorg/tree-sitter-norg",
        files = { "src/parser.c", "src/scanner.cc" },
        branch = "main"
    },
}

require('nvim-treesitter.configs').setup {
    ensure_installed = { "norg", "cpp", "c", "python" },
    highlight = { -- Be sure to enable highlights if you haven't!
        enable = true,
    }
}

```

### Expected behavior

For the following file `actions.norg`, when I press "<space>otv" (for `:Neorg gtd views) and then `s` (for the weekly summary), I get the normal summary page. If I hit <esc> to close the summary buffer and then try to run `<space>otv` again it does not open the gtd views pane (although `:Neorg gtd views` command still works).

```
@document.meta
    title: actions
    description: 
    author: esquires3
    categories: 
    created: 2021-11-29
    version: 0.0.8
@end

- [ ] first task not in a project

* My Project
  - [x] first task in project
  - [x] second task in project

* A Section That Is Not a Project

Here is some information about stuff.

===
getting out of the section

- [ ] second task not in project

```

### Actual behavior

I was expecting to be able to run <space>o multiple times but it only works the first time.

### Other information

Interestingly, if don't have `inbox.norg` open I get the following error:

`[neorg] [ERROR 12:15:06] .../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:94: No files found in default workspace.`

In this case the log output is 

```
[ERROR Tue 30 Nov 2021 12:15:06 PM EST] .../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:94: No files found in default workspace.
[ERROR Tue 30 Nov 2021 12:15:06 PM EST] .../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:94: No files found in default workspace.
```

If I then open `inbox.norg` (without opening `actions.norg`) with the following information and try to run `<space>otv` I get the same error.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by danymat** [comment]
Huh this is weird, and I think this has to do with key binds module. What happens if you try to do the same thing without doing with key binds, but using `:Neorg gtd views` instead (and only) ?

**Comment by danymat** [comment]
> Interestingly, if don't have `inbox.norg` open I get the following error:
> 
> `[neorg] [ERROR 12:15:06] .../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:94: No files found in default workspace.`
> 
> In this case the log output is
> 
> ```
> [ERROR Tue 30 Nov 2021 12:15:06 PM EST] .../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:94: No files found in default workspace.
> [ERROR Tue 30 Nov 2021 12:15:06 PM EST] .../neorg/lua/neorg/modules/core/gtd/queries/retrievers.lua:94: No files found in default workspace.
> ```
> 
> If I then open `inbox.norg` (without opening `actions.norg`) with the following information and try to run `<space>otv` I get the same error.

from what I see, it is because by default, neorg GTD is using the default workspace (aka the one that you just entered). Maybe it causes some bugs weirdly.

Can you do:
`:lua print(vim.inspect(module.required["core.norg.dirman"].get_norg_files("default")))` and see if the content changes when you don't open `inbox.norg` and when you open it ?

In order to quickly fix this, I suggest you add a stable workspace to the GTD module, like so:

```lua
 ["core.gtd.base"] = {
   configs = {
      workspace = "my_workspace_name"
   }
},
```

**Comment by esquires** [comment]
> Huh this is weird, and I think this has to do with key binds module. What happens if you try to do the same thing without doing with key binds, but using `:Neorg gtd views` instead (and only) ?

Good question. It works fine using the command directly.

> Can you do:
> :lua print(vim.inspect(module.required["core.norg.dirman"].get_norg_files("default"))) and see if the content changes when you don't open inbox.norg and when you open it ?

The output is an error. What should `module` be?

```
E5108: Error executing lua [string ":lua"]:1: attempt to index global 'module' (a function value)
stack traceback:
        [string ":lua"]:1: in main chunk
``` 

>In order to quickly fix this, I suggest you add a stable workspace to the GTD module, like so:
>
> ["core.gtd.base"] = {
>   configs = {
>      workspace = "my_workspace_name"
>   }
> },

I didn't find that this fixed it (I changed the `workspace` above to `my_workspace`).

**Comment by danymat** [comment]
> The output is an error. What should `module` be?

Ouch sorry, it should be 

```
:lua print(vim.inspect(neorg.modules.get_module("core.norg.dirman").get_norg_files("default")))
```

**Comment by esquires** [comment]
>Ouch sorry, it should be
>
> :lua print(vim.inspect(neorg.modules.get_module("core.norg.dirman").get_norg_files("default")))

No problem! The output is `{}`

**Comment by esquires** [comment]
The previous output was after opening just `actions.norg`. After additionally opening `inbox.norg` I get `{ "actions.norg", "inbox.norg" }`. When I just have `inbox.norg` open I get `{}`

**Comment by danymat** [comment]
This is weird indeed (@vhyrro any intakes ?)... What is the output of:

```
:lua print(vim.inspect(neorg.modules.get_module("core.norg.dirman").get_workspace("default")))
```

**Comment by esquires** [comment]
After some more digging it seems like when I hit <esc> (as the prompts indicate one should!) I don't lose the neorg leader but when I close the buffer with ":q" the problem arises.

**Comment by esquires** [comment]
Based on the observation that the error only arises when `:q` is run but not when `<esc>` is run, I looked into what is run when `<esc>` is hit. 

As I understand it, the close event is defined in `default_keybinds.lua` which sets `<Esc>` to send a `"core.gtd.ui.close"` event. This is subscribed to in `gtd/ui/module.lua` which calls `close_buffer` defined in `gtd/ui/displayers.lua`.  From here I tried removing lines from the `close_buffer` function (called when I hit `<esc>`) but I wasn't able to create the error (short of removing the line `vim.cmd(":bd")` at which point I needed to run `:q` which gives the problem).

This made me think that perhaps there is an autocommand being run when a window or buffer is closed. Looking at `core/autocommands/module.lua` the relevant definitions seem to be the `bufdelete` and `winclosed` events. When I grep the code for those events though I don't see any subscribers to these events.

**Comment by danymat** [comment]
> Based on the observation that the error only arises when :q is run but not when <esc> is run, I looked into what is run when <esc> is hit.

Okay I think I get it now.
When you press <esc>, as you saw there is a call to `core.gtd.ui.close` that performs some actions on closing. I should then supercharge `:q` to do the same action

**Comment by esquires** [comment]
Clarifying, should it be a different mode than `i`? Looking at `default_keybinds.lua` it seemed like `all` was an option. I tried it there as well but it didn't call `close_buffer` either.

**Comment by esquires** [comment]
looks great! Thanks for the fix. I'll go ahead and close the issue.
