### ISSUE TITLE
Can't have multiple gtd view buffers open

### ISSUE THREAD

**Issue by esquires** [nvim-neorg/neorg#210]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+651-gcaf41a7ac Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/esquires3/repos/neovim/build/config -I/home/esquires3/repos/neovim/src -I/home/esquires3/repos/neovim/.deps/usr/include -I/usr/include -I/home/esquires3/repos/neovim/build/src/nvim/auto -I/home/esquires3/repos/neovim/build/include Compiled by esquires3@esquires-pc2  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Log Output

none

### Branch

unstable

### Loaded modules

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.norg.concealer"] = {}, -- Allows for use of icons
    ["core.norg.dirman"] = { -- Manage your directories with Neorg
      config = {
        workspaces = {
          my_workspace = "~/neorg"
        },
        autochdir = true,
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.gtd.base"] = {},
    ["core.gtd.ui"] = {},
    ["core.keybinds"] = { -- Configure core.keybinds
        config = {
            default_keybinds = true, -- Generate the default keybinds
            neorg_leader = "<Leader>o" 
        }
    },
  },
}

local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

parser_configs.norg = {
    install_info = {
        url = "https://github.com/nvim-neorg/tree-sitter-norg",
        files = { "src/parser.c", "src/scanner.cc" },
        branch = "main"
    },
}

require('nvim-treesitter.configs').setup {
    ensure_installed = { "norg", "cpp", "c", "python" },
    highlight = { -- Be sure to enable highlights if you haven't!
        enable = true,
    }
}


```

### Expected behavior

Given `inbox.norg` and `actions.norg` with them open in two different tabs (i.e., opening them with `nvim -p actions.norg inbox.norg`), run `:Neorg gtd views` in `actions.norg` and keep it open. Then in the tab with `inbox.norg` run `:Neog gtd views` again. The following error results:

```
                                                 E5108: Error executing lua .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:187: Vim:E95: Buffer with this name already exists
stack traceback:                                                                                                                                                                                              
        [C]: in function 'nvim_buf_set_name'
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:187: in function 'create_split'
        ...neorg/lua/neorg/modules/core/gtd/ui/selection_popups.lua:23: in function 'show_views_popup'
        ...r/start/neorg/lua/neorg/modules/core/gtd/base/module.lua:101: in function 'on_event'
        ...e/nvim/site/pack/packer/start/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
        ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:291: in function 'on_event'
        ...e/nvim/site/pack/packer/start/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
        ...r/start/neorg/lua/neorg/modules/core/neorgcmd/module.lua:347: in function 'function_callback'
        [string ":lua"]:1: in main chunk
```

I have noticed this happen a few times outside of the particular situation where I didn't necessarily have two tabs open with the views buffer open in each but this seems to demonstrate the error consistently.

I think the issue may be to check if a buffer already exists and either switch to that one or create a new buffer with a unique name.

### Actual behavior

see above

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by danymat** [comment]
> I think the issue may be to check if a buffer already exists and either switch to that one or create a new buffer with a unique name.

Suppose we create an other buffer to view the tasks. What happens if you:

1. Open the first gtd views
2. In the other tab, modify a task
3. Open the second gtd views

At this point we will have two different outputs, because we modified a task before creating an other views display.
I don't think it's a good idea to let the user open multiple views at the same time. Maybe jumping to it could be a fix, or just logging some pretty error.

**Comment by esquires** [comment]
Great point! I hadn't considered this case. Can we just open the previous buffer in a new window though?

For instance, if I have `actions.norg` and `inbox.norg` open in two different tabs, I can run ":vs actions.norg" in the `inbox.norg` tab to open the `actions.norg` buffer, make edits, and have it reflect in the buffer in the `actions.norg` tab. In other words, it seems like they are mirrors of each other so there wouldn't be a conflict.

If that isn't possible, a message seems like it would be safest.

**Comment by danymat** [comment]
@esquires What's the state of this with latest commits?

**Comment by esquires** [comment]
The bug is still there unfortunately. One more observation...

In the case above where I open the two files with the `:Neorg gtd views` as above (to get an error), I then close the views windows and delete the buffers (so that I only have `action.norg` and `inbox.norg` in the `:ls` command) and run `:Neorg gtd views` again and still get the error. It appears that there is some state that gets messed up by opening the second view somehow.

**Comment by danymat** [comment]
Hello @esquires, I added some logs to stop execution of creating multiple views for the same selection popup. Can you try it ?

**Comment by esquires** [comment]
Thanks! It looks like there are a couple of issues:

* It looks like it overwrites the current file. For instance, if I have the views open in the tab `actions.norg` and then run `:Neorg gtd views` in the `inbox.norg` I get the following. Since the buffer is changed I then hit `u` to undo but it says the buffer is not modifiable:

![overwriting_buffer](https://user-images.githubusercontent.com/9272110/145209697-7d54fac9-b963-4f31-8439-f105f2e94e9b.png)

* After the above, when I then go into the `actions.norg` tab to close the `Quick Actions` buffer and get the same error as above (it says the `Quick Actions` buffer already exists and modifies the file as above). It doesn't appear that the buffer shows when running `:ls` so it wasn't clear how to remove the buffer

**Comment by danymat** [comment]
@esquires I think last commit fixes this bug, can you try it ?

**Comment by esquires** [comment]
Thanks. It looks like the first problem is now fixed but the 2nd still remains. This is the one that still exists:

> After the above, when I then go into the actions.norg tab to close the Quick Actions buffer and get the same error as above (it says the Quick Actions buffer already exists and modifies the file as above). It doesn't appear that the buffer shows when running :ls so it wasn't clear how to remove the buffer

**Comment by danymat** [comment]
Hmm I don't quite understand how to reproduce it

**Comment by esquires** [comment]
Sure. Here is `action.norg`:

```
@document.meta
    title: actions
    description: 
    author: esquires3
    categories: 
    created: 2021-11-29
    version: 0.0.8
@end

- [ ] first task not in a project

* My Project
  - [x] first task in project
  - [x] second task in project

* A Section That Is Not a Project

Here is some information about stuff.

===
getting out of the section

- [ ] second task not in project

```

Here is `inbox.norg`:

```
@document.meta
    title: inbox
    description: 
    author: esquires3
    categories: 
    created: 2021-11-29
    version: 0.0.8
@end
```

Here are the steps I am going through:

1. `nvim actions.norg`
2.  `:tabnew inbox.norg`
3. `gt` to get back to `actions.norg`
4. `:Neorg gtd views`
5. `gt` to open `inbox.norg`
6. `:Neorg gtd views` (see logging error that the Quick Views buffer already exists)
7. `gt` to go back to `actions.norg`, close the views window
8. In either `actions.norg` or `inbox.norg`, run `:Neorg gtd views` and it will give an error that the Quick Views buffer is already open.

**Comment by esquires** [comment]
I just tried to do the above steps on the latest `main` branch (4d4fed7) and the issue does not seems resolved (it closes the old buffer and opens a new one). Seems like this issue can be closed. Let me know what you think.

**Comment by danymat** [comment]
> And the issue does not seems resolved

If the issue is not resolved, I can try looking at it when I finish with #259.

**Comment by esquires** [comment]
sorry, I meant "issue seems resolved"

**Comment by danymat** [comment]
Nice, thanks !
