### ISSUE TITLE
Awesome Neorg site

### ISSUE THREAD

**Issue by elmarsto** [nvim-neorg/neorg#215]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'm struggling to figure out all the cool things that Neorg can do from me -- it's just that powerful.

Yet the documentation is still a bit scant, and anyway, what I really want are examples! So I figured I'd do an 'Awesome Neorg' list.

[So I made one!](https://github.com/elmarsto/awesome-neorg)

We take donations :)  I will be adding my own examples over the holiday. In the meantime, send me your drool-worthy examples of Neorg awesomeness, and I will link.

### Help

Yes

### Implementation help

Send me your favourite examples of neorg awesomeness as a PR to the README. 

Thank you!

**Comment by danymat** [comment]
Hello! Thanks for contributing !

What type of examples do you have in mind to add in the awesome suite ?

**Comment by elmarsto** [comment]
My plan is to create a gallery of beautiful neorg demos. The syntax is not well-documented at present, and while I don't know enough to write docs, I can do the work of a magpie: collecting bright/shiny things so other people can appreciate and/or copy from them.

Besides, many of us learn better from example anyway :)

Aside from general demos of core neorg features -- links, sections, bullet lists -- I also want to pay special attention to:
- Examples of integration with other plugins, e.g. folding, completion, etc.
- Zettelkasten implementations
- GTD and similar systems
- A wiki-like system
- Tools that can be used to generate content from a .norg file, e.g. conversion to markdown

The thing about neorg that has me excited is that it's a non-prescriptive self-organization tool. I generally outgrow other people's ideas about how I should work every other week or so. Neorg feels like it can keep up with me. I want to showcase that.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by elmarsto** [comment]
Circling back because I left the lede buried: **If you have done something awesome in neorg and want to share, please let me know, so I can link to you!**

Even better: Add it to the README.md and shoot me a PR :)

**Comment by vhyrro** [comment]
I can throw some cool configs and not well known features in a few days' time if nobody ends up doing it first. Gotta get the ball rolling :D

**Comment by elmarsto** [comment]
Filling out awesome-neorg did not happen this weekend as human-life intervened. I am not flaking, just playing for time. :) 

If you have examples, please share them <3

**Comment by metalelf0** [comment]
Hey @elmarsto . I think this is something that would be really helpful for the neorg community. I'd arrange such a repo in "use cases".

Something like:
- how to use neorg to track project tasks
  - how to capture a new task
  - how to mark progress and complete tasks
  - how to archive completed tasks (is this possible?)
  - how to create sub-sections
  - etc.
- How to use neorg to take notes
   - how to create a main index file
   - how to create a link to a new page and start editing it right away
   - how to add backlinks
   - how to view a list of the last X notes you've edited

And so on. I'm still struggling to use neorg for anything more than editing a `todo.neorg` file, so a list of examples would be really helpful. If I can contribute anyhow, I'd be really happy to help.

PS: @vhyrro may I ask what's the colorscheme used in the neorg readme gifs?

**Comment by elmarsto** [comment]
Thanks! I am dealing with covid impact in my family right now. I will circle back in March.

**Comment by danymat** [comment]
Hello, closing this issue due for inactivity. Feel free to reopen if state is changed.
