### ISSUE TITLE
create_norg_buffer closes window switching windows

### ISSUE THREAD

**Issue by esquires** [nvim-neorg/neorg#228]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'd like to be able to create neorg buffers that don't auto close when switching windows. The use case is for this [extension](https://github.com/esquires/neorg-gtd-project-tags) where I would like to be able show a projects list and then keep it open while I move around in the other split. This would also allow me to add an autocommand where when I move the cursor in the projects view where it jumps in the other window to where the corresponding task is.

 `create_norg_buffer` [here](https://github.com/nvim-neorg/neorg/blob/unstable/lua/neorg/modules/core/ui/module.lua#L330) has the following line:

```
vim.cmd(([[
    edit
    autocmd BufDelete,BufLeave,BufUnload <buffer=%s> silent! bd! %s
]]):format(buf, buf))
```

However, when I change that line so that it doesn't auto close when leaving the buffer, e.g.,

```
vim.cmd(([[
    edit
    autocmd BufDelete,BufUnload <buffer=%s> silent! bd! %s
]]):format(buf, buf))
```

and then switch out of the projects view and back I get the following error:

```
Error detected while processing BufEnter Autocommands for "*.norg":
E5108: Error executing lua ...lua/neorg/modules/core/norg/esupports/metagen/module.lua:97: Buffer is not 'modifiable'                                                                                        
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...lua/neorg/modules/core/norg/esupports/metagen/module.lua:97: in function 'inject_metadata'
        ...lua/neorg/modules/core/norg/esupports/metagen/module.lua:123: in function 'on_event'
        ...e/nvim/site/pack/packer/start/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
        ...art/neorg/lua/neorg/modules/core/autocommands/module.lua:47: in function '_neorg_module_autocommand_triggered'
        [string ":lua"]:1: in main chunk
```

Any ideas on how we can create buffers (e.g. for `:Neorg gtd views`) and not have to require closing the buffer to switch between windows? Thanks!

Also, I wasn't sure what that line is ultimately there for? Any insights on what it is accomplishing?

### Help

Yes

**Comment by vhyrro** [comment]
Yeah the create_norg_buffer function was made for a specific usecase. Making it close when leaving the buffer was mostly a convenience thing vs a functional decision. Now that you bring it up though it does sound annoying. Thankfully it can be easily reverted.

As for the error, that's a separate bug that I'll have to squash. The metagen module is trying to place in an auto-generated `document.meta` tag into your norg buffer but can't since the buffer is not modifiable lol. I'll get to work on that as well.

**Comment by danymat** [comment]
Hello @esquires, 

- Added some checks to prevent metadata injection on no modifiable buffers
- Added some options to customize which auto commands you want to use in `create_norg_buffers`.

Tell me if it completes the issue as you liked !

**Comment by esquires** [comment]
Looks great! Thanks!
