### ISSUE TITLE
news module startup error

### ISSUE THREAD

**Issue by esquires** [nvim-neorg/neorg#235]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+715-g1f3c0593e Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/esquires3/repos/neovim/build/config -I/home/esquires3/repos/neovim/src -I/home/esquires3/repos/neovim/.deps/usr/include -I/usr/include -I/home/esquires3/repos/neovim/build/src/nvim/auto -I/home/esquires3/repos/neovim/build/include Compiled by esquires3@esquires-pc2  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Branch

unstable

### Loaded modules

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.norg.concealer"] = {}, -- Allows for use of icons
    ["core.norg.dirman"] = { -- Manage your directories with Neorg
      config = {
        workspaces = {
          my_workspace = "~/neorg"
        },
        autochdir = true,
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.gtd.base"] = {
      config = {
        displayers = {
          projects = {
            show_completed_projects = false,
            show_projects_without_tasks = false,
          },
        },
      },
    },
    ["core.gtd.ui"] = {},
    ["core.keybinds"] = { -- Configure core.keybinds
        config = {
            default_keybinds = true, -- Generate the default keybinds
            neorg_leader = "<Leader>o" 
        }
    },
    ["utilities.gtd-project-tags"] = {}
  },
}


```

### Actual behavior

After opening the following file:

```
@document.meta
  title: actions
  description: 
  author: esquires3
  categories: 
  created: 2021-12-12
  version: 0.0.8
@end


```

I get the following error:

```
Error executing vim.schedule lua callback: .../start/neorg/lua/neorg/modules/core/norg/news/module.lua:27: attempt to call field 'parse_version_string' (a nil value)
stack traceback:                                                                                                                                                                                            
        .../start/neorg/lua/neorg/modules/core/norg/news/module.lua:27: in function 'condition'
        .../start/neorg/lua/neorg/modules/core/norg/news/module.lua:144: in function 'parse_source'
        .../start/neorg/lua/neorg/modules/core/norg/news/module.lua:239: in function 'parse_all_sources'
        .../start/neorg/lua/neorg/modules/core/norg/news/module.lua:261: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

### Expected behavior

No error

### Other information

This bug was introduced in 341858e

### Help

Yes

### Implementation help

None

**Comment by vhyrro** [comment]
Oh man, this is why you don't push code before going to bed :P

I'm fairly sure I've fixed this in the latest commit, could you update Neorg and let me know whether things are okay now?

**Comment by esquires** [comment]
Thanks! It is working in 2fc9104.
