### ISSUE TITLE
Link concealing breaks

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#238]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

0.6.0

### Branch

master

### Loaded modules

--- PRINTING ALL LOADED MODULES ---                                                                      
core.ui.selection_popup                                                                                  
core.norg.dirman                                                                                         
core.neorgcmd                                                                                            
core.keybinds.default_keybinds                                                                           
core.ui.text_popup                                                                                       
core.norg.qol.todo_items                                                                                 
core.gtd.queries.creators                                                                                
core.gtd.queries.modifiers                                                                               
core.gtd.queries.retrievers                                                                              
core.keybinds                                                                                            
core.ui                                                                                                  
core.scanner                                                                                             
core.storage                                                                                             
core.highlights                                                                                          
core.neorgcmd.commands.module.load                                                                       
core.gtd.ui                                                                                              
core.gtd.ui.displayers                                                                                   
core.norg.concealer.preset_basic                                                                         
core.integrations.treesitter                                                                             
core.gtd.queries                                                                                         
core.norg.manoeuvre                                                                                      
core.gtd.base                                                                                            
core.norg.concealer                                                                                      
core.gtd.ui.views_popup_helpers                                                                          
core.autocommands                                                                                        
core.gtd.ui.edit_popup_helpers                                                                           
core.gtd.queries.helpers                                                                                 
core.norg.esupports.hop                                                                                  
core.norg.journal                                                                                        
core.norg.concealer.preset_varied                                                                        
core.norg.concealer.preset_diamond                                                                       
core.neorgcmd.commands.return                                                                            
core.mode                                                                                                
core.gtd.ui.selection_popups                                                                             
core.neorgcmd.commands.module.list                                                                       
core.norg.esupports                                                                                      
core.queries.native                                                                                      
core.defaults                                                                                            
core.norg.news                                                                                           
core.norg.esupports.metagen                               

### Actual behavior

When the conceal behavior updates in any capacity (say you moved to a new line or updated a todo list item), lines with a link will break. The HL group cease to exist, showing my bare terminal or the last NeoVim characters used
![2021-12-13~15:29:45](https://user-images.githubusercontent.com/45222045/145883986-b99d1fad-a352-4b01-a255-64fd67851ac5.png)

### Expected behavior

This shouldn't happen

### Help

Yes

### Implementation help

na

**Comment by danymat** [comment]
Hello, as we're going to investigate this bug, please disable concealing by commenting out in your setup so that you can still use your notes:

![Capture d’écran 2021-12-13 à 21 35 56](https://user-images.githubusercontent.com/5306901/145884747-4977af9c-f866-4e13-b127-0b67ad9a49dd.png)

**Comment by vhyrro** [comment]
Or at least disable the markup concealing thru:
```lua
["core.norg.concealer"]  = {
	config = {
		markup = { enable = false },
	}
}
```
We'll be working on a fix shortly :)

**Comment by mrossinek** [comment]
@katawful can you please share the contents of a file with which this issue can be reproduced reliably?

**Comment by katawful** [comment]
[test.txt](https://github.com/nvim-neorg/neorg/files/7707532/test.txt)
File that breaks readily for me

**Comment by mrossinek** [comment]
![screenshot_1639503449](https://user-images.githubusercontent.com/21973473/146050598-fbb79ac4-0d49-4a74-b7ba-f3f6d2959251.png)

Just for reference, this is what I get. Note that the awkwardly shifted colorcolumn is nothing we can do about for the time being (i.e. until neovim has a native implementation of TS based concealing)

It is true, that concealing can be a bit flaky while editing the file. There is not a whole lot that we can do to improve this unfortunately. But I have some partial ideas in mind.

**Comment by vhyrro** [comment]
We've temporarily disabled markup concealing due to the high amounts of problems it's been causing for certain people.

We'll be trying to figure out a solution in the meantime. We have several ideas, we just don't know which ones actually work yet :P

**Comment by mrossinek** [comment]
Hi @katawful! I refactored the concealing quite a bit and also implemented a `"safe"` variant which conceals with whitespace rather than the unicode word joiner. That will not look as good but hopefully won't break so in that regard look better if you're having trouble with the unicode approach.
Would you mind trying out #258 together with the following config?
```lua
        ["core.norg.concealer"] = {
            config = {
                markup_preset = "safe",
            },
        },
```
Alternatively, you can also try `"brave"` and see if it has gotten better for you (although I wouldn't think so since the word joiner stuff is likely related to your OS+terminal+font+color scheme+whatever combination :sweat_smile:)

**Comment by katawful** [comment]
'brave' is the same unfortunately, but 'safe' seems like a fine enough temporary solution

**Comment by mrossinek** [comment]
> 'brave' is the same unfortunately, but 'safe' seems like a fine enough temporary solution

Thanks for testing! Yes as I said there is likely a more fundamental issue unrelated to neorg itself with the hacky approach using the unicode word joiner. It is system/setup dependent and hard to track down because I am unable to reproduce it myself. Hopefully in the future we will have some neovim-native TS-based concealing and then this will become much simpler :crossed_fingers:
