### ISSUE TITLE
Code block breaks when using hash symbol

### ISSUE THREAD

**Issue by ram02z** [nvim-neorg/neorg#243]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev

### Loaded modules

--- PRINTING ALL LOADED MODULES ---
core.ui.selection_popup
core.integrations.treesitter
core.neorgcmd
core.keybinds.default_keybinds
core.norg.concealer.preset_diamond
core.norg.esupports
core.norg.concealer.preset_varied
core.norg.concealer.preset_basic
core.norg.qol.todo_items
core.norg.concealer
core.ui
core.norg.completion
core.storage
core.integrations.nvim-cmp
core.norg.manoeuvre
core.keybinds
core.norg.esupports.hop
core.mode
core.scanner
core.norg.news
core.neorgcmd.commands.return
core.ui.text_popup
core.neorgcmd.commands.module.load
core.neorgcmd.commands.module.list
core.defaults
core.autocommands
core.highlights
core.norg.dirman
core.norg.esupports.metagen

### Actual behavior

The following code block will break as the `#` symbol will be interpreted as a `carryover_tag`.
```
@code c
#define N 5
int main (int argc, char *argv[])
{
  return N;
}
@end
```

![image](https://user-images.githubusercontent.com/59267627/146010533-56fbb0a7-3a07-4077-9a1e-119d80ff8402.png)

### Expected behavior

I have commented out the `#define N 5` line to demonstrate the expected behaviour.
![image](https://user-images.githubusercontent.com/59267627/146010660-32dd7896-65eb-4890-9337-59c5e3736cd5.png)

### Steps to reproduce

Use the code block I show above.

### Help

No

### Implementation help

Sorry, I have no idea how to fix this treesitter behaviour.

**Comment by vhyrro** [comment]
Hey! Just fixed this and from my tests it works fine. Be sure to run `:TSUpdate`, if something still doesn't work then do let me know :)

**Comment by ram02z** [comment]
> Hey! Just fixed this and from my tests it works fine. Be sure to run `:TSUpdate`, if something still doesn't work then do let me know :)

Thanks for the quick fix! Seems to work as expected now.
