### ISSUE TITLE
Super/subscript in a word

### ISSUE THREAD

**Issue by p00f** [nvim-neorg/neorg#251]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently subscript only works for entire words, which means you can't have something like f<sub>1</sub>(x)

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by vhyrro** [comment]
Hey! For having markup inbetween words you can use the link modifier, which is `:`.

This means you can do `f:,1,:(x)`. This works everywhere, and for all markup types. So I can do `t:*hi*:s` to render the text as t**hi**s.

Our idea for doing this stemmed from [this post](https://talk.commonmark.org/t/beyond-markdown/2787) about some common problems with markdown. I recommend reading the "Emphasis" section if ya feel like it :)

**Comment by p00f** [comment]
oo thanks

**Comment by p00f** [comment]
Could this also be concealed?

**Comment by vhyrro** [comment]
We've been trying to make subscript and superscript work, however unicode doesn't support the whole alphabet of sub/superscript characters, meaning that it's impossible to make super/subscripting work for all use cases in a TUI I'm afraid.
