### ISSUE TITLE
completed task report

### ISSUE THREAD

**Issue by esquires** [nvim-neorg/neorg#260]
### Discussed in https://github.com/nvim-neorg/neorg/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **esquires** December 14, 2021</sup>
I often would like to see a report of what has been done over the last `n` days. What do you think about adding a "#done.date" to the task tags so we can generate that type of report?</div>

**Comment by danymat** [comment]
As said in #242:

- We plan this feature for 0.2 release
- I propose using `#time.done` instead, so that it feels coherent with others time related tags (`time.start`...)

**Comment by esquires** [comment]
sorry. I should have updated the wording. github auto copies from the original post when creating an issue.

**Comment by eddiebergman** [comment]
Something to help in the meantime, works on Linux at least using `$date -Idate`.

Navigate to your task, hover over it and use `gtd` as you normall would, except now it adds the `#time.done ...` above it.

```lua
["core.keybinds"] = {
    config = {
        ...,
        hook = function(keybinds)
            keybinds.remap(
                "norg",
                "n",
                "gtd",
                'k:r!echo "\\#time.done $(date -Idate)"<cr>j:execute "Neorg keybind norg core.norg.qol.todo_items.todo.task_done"<cr>'
            )
        end
    }
}
```

**Comment by danymat** [comment]
> For an extensible solution for Neorg, I think having a time.status_update would be the most flexible. The status can be taken from the task itself and then use the time as needed for whatever views and filters :)

What is your idea about `time.status_update` ? Adding a new tag `status_update` everytime we change task state ?

**Comment by eddiebergman** [comment]
Yup, essentially this means we have two pieces of information, the state of the task and then when that state occurred, giving a comprehensive current state of everything a long when those states occured.

Just a suggestion however, I'm sure a longer time user could have different ideas on what's an extensible enough solution

**Comment by danymat** [comment]
Can be useful to read:

- https://orgmode.org/manual/Tracking-TODO-state-changes.html#FOOT43
