### ISSUE TITLE
Grammar checking and word meanings

### ISSUE THREAD

**Issue by zim0369** [nvim-neorg/neorg#261]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

A grammar checker or language server would be nice to have. I'm using null-ls with write_good which suggests me words and only a few grammar suggestions.

- This is how write_good suggest me words:
https://i.imgur.com/JP2Fgzr.png

- This is how write_good suggest me grammar corrections:
https://i.imgur.com/4qJyZ6W.png

My current setup lags word meanings like how we get function definitions when using language servers for programming. It also lags better grammar suggestions. There's also `LanguageTool` plugin for vim but in the demonstration it looked like it worked when you enter the commands. While taking notes I'd like real time grammar suggestions instead.

### Help

No

**Comment by mrossinek** [comment]
I'm not fully sure I understand what you're suggesting here. How is this related to the `norg` file format or `neorg` as a plugin wrapping that specific file format with extended functionality?

**Comment by zim0369** [comment]
> I'm not fully sure I understand what you're suggesting here. How is this related to the `norg` file format or `neorg` as a plugin wrapping that specific file format with extended functionality?

I too am not sure if I ask for an LSP or extended neorg functionality. I think you're the smarter person to figure that out.

I'll just mention the functionality I need:
- Word suggestions
- Spelling corrections(linting)
- Grammar corrections(linting)
- Word meanings(like how LSPs show function documentation)

This would significantly help in writing notes.

**Comment by mrossinek** [comment]
Those are all things which have nothing to do with neorg so this is nothing that will be provided by this plugin.
This rather sounds like you are looking for some sort of LSP for plain language/prose. This will probably then be language dependent, too.

I am not aware if anything like that exists but I'm sure some googling will get you some results.
