### ISSUE TITLE
Cannot reopen gtd views after closing with :bd or :close

### ISSUE THREAD

**Issue by jakobkhansen** [nvim-neorg/neorg#268]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+755-g1062ea2cc

### Neorg setup
```lua
require("neorg").setup({
	-- Tell Neorg what modules to load
	load = {
		["core.defaults"] = {}, -- Load all the default modules
		["core.norg.dirman"] = { -- Manage your directories with Neorg
			config = {
				workspaces = {
					gtd = "~/Documents/GTD",
				},
			},
		},
		["core.norg.completion"] = {
			config = {
				engine = "nvim-cmp", -- We current support nvim-compe and nvim-cmp only
			},
		},
		["core.norg.concealer"] = {}, -- Allows for use of icons
		["core.keybinds"] = { -- Configure core.keybinds
			config = {
				default_keybinds = false, -- Generate the default keybinds
				--neorg_leader = "<Leader>o", -- This is the default if unspecified
			},
		},
		["core.gtd.ui"] = {},
		["core.gtd.queries"] = {},
		["core.gtd.base"] = { config = {
			workspace = "gtd",
            default_lists = {
                inbox = "inbox.norg",
                someday = "someday.norg"
            }
		} },
	},
})
```

### Actual behavior

When you open a gtd view, for example `:Neorg gtd views`, then close the buffer with `:close` or `:bd`, running `:Neorg gtd views` gives an error saying the buffer is already open. I have checked that the buffer does not exist when running `:buffers`

### Expected behavior

I would expect Neorg to be able to reopen the gtd view.

I prefer to close buffers with a keybind which does `:close`, it would be nice if Neorg could support closing the gtd views with this command.

### Steps to reproduce

1. Start Neovim and Neorg
2. Run `:Neorg gtd views`
3. Run `:close`
4. Run `Neorg gtd views` again

This should give the error
[neorg] [ERROR 16:51:22] .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:182: Buffer 'Quick Actions' already exists

### Help

No

### Implementation help

.

**Comment by danymat** [comment]
Hello, this should be quick to fix, I will take a look !
