### ISSUE TITLE
`.org` extension support?

### ISSUE THREAD

**Issue by nchase** [nvim-neorg/neorg#27]
Is Neorg intended to have file format compatibility with org mode? 

If so, is there some way to support files with the `.org` extension, in addition to (or instead of) `.norg` files?

**Comment by vhyrro** [comment]
Neorg is not intended to work with org files (that's not its goal), however somewhere in version 0.2/0.3 we plan on adding support for converting to/from org files to the .norg format statically (hopefully with pandoc)

**Comment by shift-d** [comment]
This issue was stale for a while. Maybe it should be closed..?

**Comment by vhyrro** [comment]
I could get the discussion rolling a bit by saying that Simre has been working on a haskell parser for Neorg (https://github.com/Simre1/neorg-haskell-parser)! They seem to have a nice pace going, if they keep it up we may end up getting pandoc support faster than you'd think :D

I've been heavily thinking about compatibility with certain org tools, but for that to be possible we'd have to have very accurate conversion between .org and .norg which may be difficult. The process would have to look something like: .norg -> .org -> piped through org tool -> converted back to .norg. Wondering what that'd look like :thinking:

**Comment by danymat** [comment]
Closing this issue as it's stale for a while. Please check out https://github.com/nvim-neorg/neorg/issues/27#issuecomment-957344923
