### ISSUE TITLE
Inline comments/tags

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#28]
As far as I can tell, comments are implemented by using certain tags, such as `@comment ... @end`. But according to the docs, these need to be at the beginning of the line. Is there any way to do inline comments? I currently use markdown a lot and extensively use `<!-- -->` to write comments to myself about individual sentences that require editing.

**Comment by vhyrro** [comment]
There is no way as of right now to create comments that are inline in the document. For them to exist they would need to do a few things:
- Strictly adhere to the attached modifier rules
- Preferably consist of a single character/max two characters (unlike whatever `<!--` is supposed to represent lol)
- Not be able to span over a single paragraph (just like regular modifiers can't)

If people feel like creating inline comments is something necessary then we can add them in, I'm open to ideas for their syntax. We can try things like `#` etc. :)

**Comment by jghauser** [comment]
Thanks for considering this :). I don't really have any strong preferences regarding the syntax. If you want to go with a single character, then `#` is probably best. It's a character that isn't used much in prose, exists on pretty much all keyboards, and isn't yet in use for other purposes in neorg. I might be missing something though.

And thanks for this project! I'm very excited about it progressing :)

**Comment by vhyrro** [comment]
Yeah, I'll be trying out different things and see whether i especially like any of them, we'll see how it goes. Currently # is still the candidate

**Comment by vhyrro** [comment]
Gave this a `0.1` milestone so I can be sure that I don't accidentally miss it at some point before release :)

**Comment by mrossinek** [comment]
I just added support for this using the `#`-attached modifier (as discussed above and on discord) to the `unstable` branch. Once this gets merged into `main`, this issue should be closed automatically :+1:
