### ISSUE TITLE
Use dimming highlight instead of entire conceal

### ISSUE THREAD

**Issue by danymat** [nvim-neorg/neorg#280]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hello,

Using the conceal method provided by @mrossinek, I quite don't like them because it messes up with the Neorg views, take a look:

<img width="353" alt="Capture d’écran 2021-12-28 à 11 46 32" src="https://user-images.githubusercontent.com/5306901/147558491-44131f05-baad-4f1d-aa9c-c6f838f2e9bf.png">
 
The idea I have is to allow the user to use some dimming highlights (such as the comment highlights) instead of blank spaces when concealing.

### Help

No

**Comment by roland-rollo** [comment]
@danymat is this the same problem? https://asciinema.org/a/AMRhin29Zcm9j5Wyw9AwfhEzb

**Comment by danymat** [comment]
It is, I want to use dimming highlights, like here:
<img width="506" alt="Capture d’écran 2022-01-01 à 22 34 47" src="https://user-images.githubusercontent.com/5306901/147860630-f2be8601-e81a-4bb2-af9c-e0d2fb72466e.png">

**Comment by danymat** [comment]
@mrossinek any intakes on this ?

**Comment by mrossinek** [comment]
> @mrossinek any intakes on this ?

I will be looking into this later this week.

**Comment by mrossinek** [comment]
You can now use this via:
```lua
        ["core.norg.concealer"] = {
            config = {
                markup_preset = "dimmed",
            },
        },
```
