### ISSUE TITLE
Link to file not recognized anymore

### ISSUE THREAD

**Issue by danymat** [nvim-neorg/neorg#281]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+763-gd2f62b316

### Neorg setup

```
require("neorg").setup({
	load = {
		["core.defaults"] = {},
		["core.keybinds"] = {
			config = {
				default_keybinds = true,
				neorg_leader = "<Leader>o",
			},
		},
		["core.norg.concealer"] = {
			config = {
				icon_preset = "diamond",
			},
		}, -- Allows for use of icons
		["core.norg.dirman"] = { -- Manage your directories with Neorg
			config = {
				workspaces = {
					gtd = "~/Documents/000 Meta/00.03 gtd",
					work = "~/Documents/000 Meta/00.04 work/",
					insa = "~/Documents/101 Personnel/40-49 Insa/46 5A/101.46.00 Notes",
					hack = "~/Documents/000 Meta/00.05 hack",
				},
			},
		},

		["core.gtd.base"] = {
			config = {
				workspace = "gtd",
				-- workspace = "test",
				exclude = { "gtd.norg", "neogen.norg", "kenaos.norg" },
				-- custom_tag_completion = true,
			},
		},
		["core.presenter"] = {
			config = {
				zen_mode = "truezen",
			},
		},

		["core.integrations.telescope"] = {},
		["core.norg.completion"] = {
			config = {
				engine = "nvim-cmp",
			},
		},
		-- ["core.zettelkasten"] = {},
        ["core.norg.journal"] = {},
		["core.norg.qol.toc"] = {},
        -- ["core.norg.snippet"] = {}
	},
	-- logger = {
	-- 	level = "info", -- Show trace, info, warning, error and fatal messages
	-- },
})
```

### Actual behavior

`- {:neorg:}` Is not hoping to the `neorg.norg` file I have

### Expected behavior

It should hop to the file.

### Steps to reproduce

1. Create 1 neorg file called `neorg`.
2. Create a link to this file from `index`
3. Try hopping with `<CR>`

### Other information

It seems that the query capture does not get it (`iter_captures` is void).

### Help

No

### Implementation help

/

**Comment by vhyrro** [comment]
Yo, fixed this now! Please double check :)

**Comment by max397574** [comment]
It works for me

**Comment by danymat** [comment]
Wonderful, thanks !
