### ISSUE TITLE
Proposal: Optimize startup time?

### ISSUE THREAD

**Issue by glyh** [nvim-neorg/neorg#282]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently starting up with a norg file is slow. It would be good if we can investigate into it after all APIs are stable. 

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

While, I don't know how to profile this, but I can feel this(compared to not openning norg files, as I have lazy loaded this).

**Comment by danymat** [comment]
Hello, this is being worked on #267, you can try it out by changing the branch.

**Comment by glyh** [comment]
@danymat Thanks! Since this has already been working on, I'm closing this.
