### ISSUE TITLE
Provide highlights for footnotes

### ISSUE THREAD

**Issue by danymat** [nvim-neorg/neorg#295]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Footnotes links don't yet provide highlights

![](https://user-images.githubusercontent.com/5306901/148053564-a3052fab-a104-4944-a327-b42e60fbfae5.png)

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by mrossinek** [comment]
What highlight do you suggest? There is already `NeorgLinkLocationFootnote` but it is empty by default because footnotes themselves do not have a color by default (their titles are just bold, same as definitions).

**Comment by danymat** [comment]
Do we provide different highlights for each type of link?

**Comment by mrossinek** [comment]
> Do we provide different highlights for each type of link?

Yes. See `:hi NeorgLink<Tab>`:
![screenshot_1641334242](https://user-images.githubusercontent.com/21973473/148130735-043808a7-2ba8-4cb2-8c24-69f518b8599c.png)

**Comment by danymat** [comment]
I guess we can just do bold text, as it's the same as the footnote by itself
