### ISSUE TITLE
List of supported syntax?

### ISSUE THREAD

**Issue by sgalizia** [nvim-neorg/neorg#30]
Hi! I have been trying to find a note-taking plugin for neovim that will work for me, and I think this may be it. I am excited to see how this progresses and would even like to try and help contribute if possible. Right now, though, what I am struggling with is understanding what the syntax is to do even just the basics. 

Is the syntax a superset/modified version of Markdown?

**Comment by vhyrro** [comment]
The [spec](https://github.com/vhyrro/neorg/blob/main/docs/NFF-0.1-spec.md) should have you covered in terms of syntax. I understand that there's no videos or tutorials or anything right now, and i will change that as soon as the 0.1 release comes close. When i do that i will close the pinned issue #14 and give links in the README to those videos :)

**Comment by sgalizia** [comment]
> 
> 
> The [spec](https://github.com/vhyrro/neorg/blob/main/docs/NFF-0.1-spec.md) should have you covered in terms of syntax. I understand that there's no videos or tutorials or anything right now, and i will change that as soon as the 0.1 release comes close. When i do that i will close the pinned issue #14 and give links in the README to those videos :)

Thanks! I was looking through the spec and definitely got a few tips on some of the syntax, just wasn't sure if there was a compiled list of the basic syntax! Would it be worth setting up a wiki page with basic syntax and just marking it as "subject to change"? I would be willing to help with that :)

**Comment by vhyrro** [comment]
I think that creating a wiki entry along the lines of "Getting Started with Neorg's Format" sounds like a great idea for newcomers. Something that kind of just explains the basics like creating headings, what tags are, etc.

**Comment by mrossinek** [comment]
Be sure to checkout the [self-documenting example](https://github.com/nvim-neorg/neorg/blob/main/doc/neorg.norg) or try `:help neorg` after installing it!

**Comment by danymat** [comment]
I'm closing the issue as @mrossinek did point the current documentations
