### ISSUE TITLE
Error in creating conceal for NeorgHeading

### ISSUE THREAD

**Issue by danymat** [nvim-neorg/neorg#300]
now i am getting below error
```
[neorg] [ERROR 18:01:14] ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:513: Unable to create custom conceal for highlight: NeorgHeading1 - end_row value outside
range
```
i tried to use neovim provided by arch repo but same results,
version i tired 
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```

_Originally posted by @hardfau18 in https://github.com/nvim-neorg/neorg/issues/299#issuecomment-1005650484_

**Comment by hardfau18** [comment]
This can be closed, while debugging i had specific commit pinned in packer, may be that caused this issue. No longer reproducible.
