### ISSUE TITLE
Path Completion for norg files in workspace

### ISSUE THREAD

**Issue by alextylor-e2x** [nvim-neorg/neorg#301]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Creating a link to a another norg in a workspace using {:$/goats/cheese.norg:}[cheese from goats notes]
Is great as you can be in the goats dir, and norg knows to open the file from the workspace root.
However as the path is prefixed with `$/` I can't rely on the built in C^xC^F path completion.

Please extend the completion engine, so that path completion can be used when linking files

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Time is my biggest constraint, but I'd be happy to take a look, any pointers would be grand though

**Comment by max397574** [comment]
I don't know if you use neorg-telescope (if not I'd recommend it)
If so there is `Telescope neorg insert_link` atm it only searches links for heading, markers etc.
you could create a link and remove everything but the file
But I also want to add links to files only in the future

**Comment by terrortylor** [comment]
@max397574 yeah I was being lazy though :P But fair enough, I've extended the telescope plugin, PR linked above

**Comment by max397574** [comment]
so you could close this issue?
@terrortylor

**Comment by alextylor-e2x** [comment]
appologies, yes the neorg-telescope repo now supports this, the README details its use
