### ISSUE TITLE
v0.2 Panadoc Export

### ISSUE THREAD

**Issue by erwin** [nvim-neorg/neorg#303]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Export to Panadoc will also allow conversion to HTML, PDF, and EPUB and many other formats.

There is an existing issue about export formats where @vhyrro said that Panadoc Export is going planned for a future `v0.2` release. 

Just wanted to create an issue so that we can get notified about when the Panadoc integration hits!

Super exciting project. Going to be a gamechanger for tech writing in NeoVim.j

See: https://github.com/nvim-neorg/neorg/issues/4

### Help

No

**Comment by mrossinek** [comment]
Hi @erwin! Thanks for starting this tracking issue! :+1: 

There is actually already some work being started on this over here: https://github.com/Simre1/neorg-haskell-parser/
I have not tested it myself but I am watching the repo closely
