### ISSUE TITLE
subheadings are also considered as sub projects of that task and To complete a project sub projects needs to be completed

### ISSUE THREAD

**Issue by hardfau18** [nvim-neorg/neorg#318]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

If I have project with sub heading, That is also considered as another project.
![image](https://user-images.githubusercontent.com/39230006/149794733-37857111-497a-4b0e-92cd-5b8868ad2a07.png)

If I am done with one task in that project except for sub headings tasks then project is considered as done.
![image](https://user-images.githubusercontent.com/39230006/149795104-bae7f78f-16fe-4116-b4e4-0aba4debc222.png)
but I was hoping it to be completed when all the subheadings tasks are completed. I can use level2 unordered list but I am doing note taking as well as project management through neorg and it would be cool to have both in one.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I am new to lua, have a hard time in navigating the code, If you could point me where to poke and give some hints, i can try it, hoping to contribute in future issues/features

**Comment by danymat** [comment]
Currently, it seems that the completion of a heading 1 is directly related to tasks directly in heading1, as you saw. I think it's a limitation of the concealer, maybe @vhyrro can enlighten us in that regard.

If you use Neorg for managing projects, be sure to try out Neorg GTD, as its main role is to manage tasks and projects through the GTD workflow

**Comment by hardfau18** [comment]
> if you use Neorg for managing projects, be sure to try out Neorg GTD, as its main role is to manage tasks and projects through the GTD workflow

I do use GTD, but there few more features that I am hoping they will come, like there is todays task, also I would be awesome to review yesterday's task and move the pending ones. also past week tasks reviews

**Comment by danymat** [comment]
> I do use GTD, but there few more features that I am hoping they will come, like there is todays task, also I would be awesome to review yesterday's task and move the pending ones. also past week tasks reviews.

I guess this will be added to the Clarify popup, but we are planning to integrate this for 0.2 release

> Also i forgot to mention in gtd's project view I can see them correctly as expected

Nice, glad it works as expected !
