### ISSUE TITLE
WIki not working

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/neorg#327]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

v0.7.0-dev

### Neorg setup

-

### Actual behavior

**When press on any link on the right in the wiki:**

![Screenshot-20220122231218-2246x1526](https://user-images.githubusercontent.com/13056013/150654218-90d40a0e-74e7-4fb1-a3e8-bfbb9467d1d0.png)

**the next error raizes and no wiki page is opened:**

![Screenshot-20220122231246-1012x318](https://user-images.githubusercontent.com/13056013/150654135-ef875922-81e3-42ec-93f6-005c4bec1ef3.png)

### Expected behavior

Wiki page will open.

### Steps to reproduce

-

### Help

No

**Comment by danymat** [comment]
Hmm, Yeah right 😭 our automatic wiki generator did mess up at some point and deleted all static wiki files that were created some time ago. We cannot browse with the sidebar for the moment, and some links are down.
You can still go on the modules pages, they seem to work

**Comment by danymat** [comment]
This is solved, feel free to reopen if not 🥳
