### ISSUE TITLE
Java code blocks not using Treesitter highlighting.

### ISSUE THREAD

**Issue by AndOrangutan** [nvim-neorg/neorg#340]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

v0.7.0

### Neorg setup

```lua
require('neorg').setup {
    -- Tell Neorg what modules to load
    load = {
        ["core.defaults"] = {}, -- Load all the default modules
        ["core.norg.concealer"] = {
            config = {
                markup_preset = "dimmed",
                --markup = { enable = true},
                --icon_preset = "dimmed",
            }
        }, -- Allows for use of icons
        ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
                workspaces = {
                    my_workspace = "~/Dropbox/Neorg"
                },
                audodetect = true,
                autochdir = true,
            }
        },
        ["core.keybinds"] = {
            config = {
                default_keybinds = true,
                neorg_leader = "<Space>o",
            },
        },
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp"
            }
        },
        ["core.integrations.telescope"] = {}

    },
}
```

### Actual behavior

Looks like normal regex highlighting, if even.
![2022-01-27_21-48](https://user-images.githubusercontent.com/40435989/151494513-feebbc13-8a61-4920-bdb0-a0a79f546b6c.png)

### Expected behavior

Should be highlighted like the java file.

### Steps to reproduce

idk.

### Help

No

**Comment by vhyrro** [comment]
Hey! It seems to work on my end :thinking:, even with your exact document layout. Are you certain you have the java treesitter parser installed (`:TSInstall java`)?

**Comment by vhyrro** [comment]
Aha! Just after writing this I seem to have figured it out. You have a space after `java`, which is tripping up the injection code. I'd consider this a bug personally so imma try and fix it up.

**Comment by vhyrro** [comment]
Mind trying it out now? Works on my end :D

**Comment by AndOrangutan** [comment]
Thank you so much, that was silly on my part.
