### ISSUE TITLE
neorg not automatically generating metadata anymore

### ISSUE THREAD

**Issue by sseneca** [nvim-neorg/neorg#342]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {},
    ["core.keybinds"] = {
      config = {
        default_keybinds = true,
      }
    },
    ["core.norg.concealer"] = {},
    ["core.norg.dirman"] = {
      config = {
        workspaces = {
          my_workspace = "~/nextcloud/documents/neorg"
        }
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.norg.journal"] = {}
  },
}
```

### Actual behavior

Opens an empty buffer.

### Expected behavior

Metadata is automatically generated in the buffer.

### Steps to reproduce

Open a file (e.g. `nvim test.norg` or opening a new journal entry)

### Potentially conflicting plugins

n/a

### Other information

This stopped working maybe a week or so ago

### Help

No

**Comment by mrossinek** [comment]
This is expected as the default behavior was changed to disable this. You can turn this back on by specifying the following in your config:
```lua
        ["core.norg.esupports.metagen"] = {
            config = {
                type = "auto",
            },
        }
```
For more information see the corresponding wiki page: https://github.com/nvim-neorg/neorg/wiki/Metagen
