### ISSUE TITLE
GTD today view not listing task due today

### ISSUE THREAD

**Issue by alextylor-e2x** [nvim-neorg/neorg#346]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+984-g2870311a3

### Neorg setup

require('neorg').setup {
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.keybinds"] = { -- Configure core.keybinds
      config = {
        neorg_leader = "<Leader>o", -- This is the default if unspecified
      }
    },
    ["core.norg.concealer"] = {
      config = {
        icons = {
          todo = {
            undone = { icon = " " },
            pending = { icon = "P" },
            done = { icon = "X" },
            hold = { icon = "H" },
            cancelled = { icon = "C" },
          },
        },
      },
    }, -- Allows for use of icons
    ["core.norg.dirman"] = { -- Manage your directories with Neorg
      config = {
        workspaces = {
          gtd_wksp = "~/gtd",
        }
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp"
      }
    },
    ["core.gtd.base"] = {
      config = {
        workspace = "gtd_wksp",
      },
    },
    ["core.integrations.telescope"] = {},
  },
}

### Actual behavior

Capture a task and add to project with a due date of today, this item will not be displayed in Today's Task view.
If a context is added then it is displayed, but the criteria does not indicate that this should be the case:

* Today's Tasks

For a pending or undone task to appear here, it must meet one of these criterias:
- Task marked with `today` context, and already started
- Task starting today
- Task due for today
- Task marked as pending

### Expected behavior

Task listed in Today's Task view

### Steps to reproduce

Capture a task and add to project with a due date of today and no context

### Potentially conflicting plugins

NA

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by danymat** [comment]
Hello, you're right, they were treated as unclarified tasks because they did not have a context. From experience, due/start dates should be "hard" deadlines, that means they ave to show up whenever they have contexts or not. 
I fixed it, an added some comments in the `unclarified tasks` view

**Comment by alextylor-e2x** [comment]
So It picks up tasks with due date today in under a project in a file seperate to inbox.norg
given:
```~/personnal-workspace/notes (master) > tree  gtd/
gtd/
├── inbox.norg
└── work.norg

0 directories, 2 files

cat gtd/inbox.norg 
* Refile
  #time.due 2022-02-04
  - [ ] refile today task

cat gtd/work.norg 
* Infrastucture
  #time.due 2022-02-04
  - [ ] project today task
```

I'll get today's view output off:
```
* Today's Tasks

For a pending or undone task to appear here, it must meet one of these criterias:
- Task marked with `today` context, and already started
- Task starting today
- Task due for today
- Clarified task marked as pending

** /(No contexts)/
- project today task, `due for today`
```

**Comment by danymat** [comment]
@alextylor-e2x it's not showing `refile today task` in your output, can you confirm ?

**Comment by danymat** [comment]
Right, I poorly missed the conditional. Can you try again ?

**Comment by alextylor-e2x** [comment]
Yep working as expected now, pulling tasks due for today from various files in the gtd workspace.

Thanks
