### ISSUE TITLE
Wrong highlight group for `definition.multi_suffix` in concealer wiki page

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/neorg#347]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

-

### Neorg setup

-

### Actual behavior

Wrong highlight group for `definition.multi_suffix` in concealer [wiki page](https://github.com/nvim-neorg/neorg/wiki/Concealer): should be `NeorgDefinitionEnd`
```lua
definition = {
    multi_suffix = {
        enabled = true,
        icon = "⋘ ",
        highlight = "NeorgDefinition", -- Here shuold be NeorgDefinitionEnd
    },
},
```

### Expected behavior

-

### Steps to reproduce

-

### Help

No

**Comment by vhyrro** [comment]
Thanks for making me aware of this!

Turns out the same issue was present for footnotes as well - good catch. Should be fixed now
