### ISSUE TITLE
Can't set highlighting for `NeorgMarkupVerbatim` group

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/neorg#348]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev

### Neorg setup

-

### Actual behavior

Neither
```vim
highlight! link NeorgMarkupVerbatim Red
```
nor
```vim
highlight! NeorgMarkupVerbatim guifg=#8bba7f gui=bold
```
doesn't work.

`:filter Neorg highlight` gives me that it set direct:
```
NeorgMarkupVerbatim xxx guifg=#b4a387
```
but not linked like others.

And according to [wiki](https://github.com/nvim-neorg/neorg/wiki/Treesitter-Integration#configuration) there is no `[""]` key for verbatim table:

```lua
Variable = {
 [""] = "+NeorgInsertionVariable",
 Delimiter = "+NonText",
},
Verbatim = {
 Delimiter = "+NonText",
},
```

### Expected behavior

-

### Steps to reproduce

-

### Help

No

**Comment by vhyrro** [comment]
Thanks a lot for letting me know about this. To my knowledge this is entirely fixed now, mind checking that out?

I'll close the issue for now but feel free to reopen in case something doesn't work as expected.

**Comment by anuvyklack** [comment]
Works now. Thank you!
