### ISSUE TITLE
Separate highlighting groups for the content of each type of task

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/neorg#349]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

There are different highlighting groups for different types of tasks like: `NeorgTodoItem1Undone`, `NeorgTodoItem1Canceled`. But only one `NeorgTodoItem1Content` for all types of tasks.  It would be nice to have also highlighting groups for the content of each type of task.  `NeorgTodoItem1CanceledContent` could be used, for example, to dim the content of the canceled task or `NeorgTodoItem1DoneContent` to strikeout done task.

### Help

No

**Comment by danymat** [comment]
Hello, thanks for the (long) patience lol.
I just added this feature with the name:

`NeorgTodoItem1<state>Content`.

Feel free to update and tell me if you like it!
