### ISSUE TITLE
Clocking in

### ISSUE THREAD

**Issue by pbutler** [nvim-neorg/neorg#351]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

One of the killer apps in org mode is the ability to keep track of time spent in tasks or "clocking in".  I currently use it to track and invoice hours spent on consulting jobs so it's a very important use case to me.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Questions
1) Start a new module or patch a current module?
2) How to best store the clock in/out times?  (a task might have multiple clock ins and outs)

I am a fairly capable programmer but I haven't done any neovim/lua development really so advice on setting up a dev workspace might also be helpful but not required.

**Comment by danymat** [comment]
Im fairly sure we can support this with GTD module
However there are some important stuff I want to tackle before hand (in gtd module), if you're interested in contributing, best suggestion is already to take a look and try gtd module, and before coding anything, we could discuss on a syntax we could use for this feature

**Comment by NickHu** [comment]
I think the syntax for this is stable, but I'm wondering if there are any default/user contributed keybindings that would allow me to 'clock in' and 'clock out'?

**Comment by max397574** [comment]
no

**Comment by danymat** [comment]
Right now, no. I recommend you looking at https://github.com/nvim-neorg/neorg/issues/695 for more details
