### ISSUE TITLE
Better softwrap for neorg lists

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#371]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Softwrap for neorg lists usually doesn't work well at all, but today I realised that it can be tremendously improved by setting the following options. I suggest neorg sets this automatically for the `norg` filetype.

Settings:
```{lua}
vim.opt_local.breakindentopt = 'list:-1'
vim.opt_local.formatlistpat = [[^\s*[-~\*]\+\s\+]]
```

Before:
![20220215_21h41m37s_grim](https://user-images.githubusercontent.com/10319377/154145658-448b4e57-607c-4e17-bb6f-ece39e608dfe.jpeg)

After:
![20220215_21h42m17s_grim](https://user-images.githubusercontent.com/10319377/154146110-be2ee7ba-4030-411b-930e-f6230d430c46.jpeg)

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

This should be easy to do. I can probably write a PR. Would you simply set this in a `ftplugin/norg.lua` or do u have some other way of setting this? Would you prefer a `.lua` or a `.vim`?

EDIT: changed `formatlistpat` to correctly handle headings and lines that start with `*`, `-`, or `~` but shouldn't be indented in softwrap.

**Comment by danymat** [comment]
@vhyrro This seems a good idea, however I'm not sure this can be natively done with indenting, or is it separated

**Comment by vhyrro** [comment]
Wow, this is one relic of the past :p

This has been fixed a long time back thanks to the indent engine, which handles the softwrapping in a more sophisticated manner as soon as the user presses `<CR>` or `<Esc>`. Closing!
