### ISSUE TITLE
Neorg events do not use opened file when using a file picker like FZF or Telescope

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#377]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

n/a

### Actual behavior

When opening a Neorg file with internal NeoVim methods, such as `:e file.norg`, Neorg will detect a new file and update its filesystem events based on this new file. This will let Neorg configure the newly opened Neorg file

When opening a Neorg file with a plugin file picker (FZF and Telescope were the only ones tested), Neorg will instead update its filesystem events based on the file you're opening *from* instead of the file you have just opened and focused. This means the file that is open gets updated and configured by Neorg with the raw text information present from the first file

This behavior is apparent regardless of workspace

### Expected behavior

When using a plugin file picker, Neorg should behave like with internal NeoVim file pick methods and update its filesystem events based on the newly opened file

### Steps to reproduce

Using the attached concealer module that I have been working that demonstrates this behavior cleanly, open a Neorg file with a clean NeoVim session. When you open a second Neorg file with `:e` the buffers printed to messages should be the same. If you use a file picker like FZF (either June's original or the Lua remake) or Telescope to go to this second file, the buffers printed to messages will **not** be the same

[the concealer module.lua file in text format](https://github.com/nvim-neorg/neorg/files/8117446/module.txt)

### Help

Yes

**Comment by katawful** [comment]
This is manifesting in the concealer module. When said module tries to set the foldexpr, the window id it receives is invalid. Specifically line 1843 as of this comment

**Comment by vhyrro** [comment]
Hey, are you on the latest Neorg? I believe I fixed this a few hours before you made the comment, so check that out and see if it's fixed your problems.

Here's the current code snippet from Neorg main:
```lua
        if module.config.public.folds and vim.api.nvim_win_is_valid(event.window) then
            vim.api.nvim_win_set_option(event.window, "foldmethod", "expr")
            vim.api.nvim_win_set_option(event.window, "foldexpr", "nvim_treesitter#foldexpr()")
            vim.api.nvim_win_set_option(
                event.window,
                "foldtext",
                "v:lua.neorg.modules.get_module('core.norg.concealer').foldtext()"
            )
        end
```

**Comment by katawful** [comment]
Seems to be fixed now, thanks!
