### ISSUE TITLE
When I click "Installation Guide" on the Github's wiki It redirects to the start wiki page

### ISSUE THREAD

**Issue by pragmaticmero** [nvim-neorg/neorg#379]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

This is what I'm trying to do LOL
Install neorg following the guide, but there's no guide.
I'm trying to install it using neovim native plugin manager.

This is what i've pasted in my init.lua

```
require('neorg').setup{
    load = {
        ["core.defaults"] = {} ,
        ["core.norg.dirman"] = {}
    }
}
```

### Actual behavior

This is about a redirect error.
This:
https://github.com/nvim-neorg/neorg/wiki/Installation
Redirects to this:
https://github.com/nvim-neorg/neorg/wiki/

And gives **NO** information about Installation.
I've seen that also happens with another links. Specifically all the ones from here.
![image](https://user-images.githubusercontent.com/100187381/155578127-1851ce66-1c80-4569-81e2-67e0c62da3f7.png)

### Expected behavior

To redirect to the correct guide

### Steps to reproduce

- Install neovim (I've used pacman)
- Install nvim-treesitter (It installs correctly)
- Install neorg
- Get **CATHASTROPHIC ERROR** when trying to open a .norg file
```
[neorg] (12:38:21)
...nvim/site/pack/plugins/start/neorg/lua/neorg/modules.lua:238
Unable to load module core.norg.dirman - module 'neorg.modules.core.norg.dirman' not found:
^Ino field package.preload['neorg.modules.core.norg.dirman']
^Ino file './neorg/modules/core/norg/dirman.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/neorg/modules/core/norg/dirman.lua'
^Ino file '/usr/local/share/lua/5.1/neorg/modules/core/norg/dirman.lua'
^Ino file '/usr/local/share/lua/5.1/neorg/modules/core/norg/dirman/init.lua'
^Ino file '/usr/share/lua/5.1/neorg/modules/core/norg/dirman.lua'
^Ino file '/usr/share/lua/5.1/neorg/modules/core/norg/dirman/init.lua'
^Ino file './neorg/modules/core/norg/dirman.so'
^Ino file '/usr/local/lib/lua/5.1/neorg/modules/core/norg/dirman.so'
^Ino file '/usr/lib/lua/5.1/neorg/modules/core/norg/dirman.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './neorg.so'
^Ino file '/usr/local/lib/lua/5.1/neorg.so'
^Ino file '/usr/lib/lua/5.1/neorg.so'
```
I'm trying to solve it using the guide, but there's no guide.

### Potentially conflicting plugins

Nah.

### Other information

N/A.

### Help

No

**Comment by pragmaticmero** [comment]
Duplicate of #327

**Comment by pragmaticmero** [comment]
Well, after 3 hours of trying (I'm new to nvim / lua / rust / anything programming related, I'm in a search for a mentor in RustLang plz help) 

I've managed to install neorg.
The links are still broken tho. Valve plz fix.

**Comment by danymat** [comment]
Hello, links should be fixed. I removed the Installation link because the README is self-explanatory.
