### ISSUE TITLE
neuron.nvim-like Zettelkasten module

### ISSUE THREAD

**Issue by AnatoleLucet** [nvim-neorg/neorg#390]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

👋 
First of all, thanks for this plugin. It's really awesome to see the commitment and all the work you do to make a great note-taking+++ plugin.

Although, I feel like there's one thing that's currently missing: a good [Zettelkasten note-taking methodology](https://writingcooperative.com/zettelkasten-how-one-german-scholar-was-so-freakishly-productive-997e4e0ca125) support.

The best option for nvim users is to use [neuron.nvim](https://github.com/oberblastmeister/neuron.nvim) which uses Neuron as a backend. But Neuron is now being ~deprecated, and you cannot use the Neorg syntax with Neuron.
That's why I think it'd be nice to have a Neorg module which provides similar features to neuron.nvim (mainly keymaps and unique notes IDs, I think the rest is already here 🙂).

### Help

No

**Comment by max397574** [comment]
this is planned for 0.2
there is already a module for it which does nothing atm

**Comment by vhyrro** [comment]
Closing this to keep everything in one place. [This](https://github.com/nvim-neorg/neorg/issues/745) is the official tracking issue for zk!
