### ISSUE TITLE
On event issue in split

### ISSUE THREAD

**Issue by baileyn** [nvim-neorg/neorg#392]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+1063-ga7321e37a

### Neorg setup
```lua
require("neorg").setup({
	load = {
		["core.defaults"] = {},
		["core.keybinds"] = {
			config = {
				neorg_leader = " ",
			},
		},
		["core.gtd.base"] = {
			config = {
				workspace = "home",
			},
		},
		["core.presenter"] = {
			config = {
				zen_mode = "zen-mode",
			},
		},
		["core.norg.completion"] = {
			config = {
				engine = "nvim-cmp",
			},
		},
		["core.norg.concealer"] = {},
		["core.norg.dirman"] = {
			config = {
				workspaces = {
					home = "~/notes/home",
				},
			},
		},
		["core.norg.qol.toc"] = {},
		["core.integrations.telescope"] = {},
	},
})
```

### Actual behavior

Split opens, but displays the following error:

```text
Press ESC to exit without saving          Error executing vim.schedule lua callback: ...\opt\neorg/lua/neorg/modules/core/norg/dirman/module.lua:537: Vim(lcd):E472: Command failed
stack traceback:
        [C]: in function 'cmd'
        ...\opt\neorg/lua/neorg/modules/core/norg/dirman/module.lua:537: in function 'on_event'
        ...vim-data\site\pack\packer\opt\neorg/lua/neorg/events.lua:159: in function <...vim-data\site\pack\packer\opt\neorg/lua/neorg/events.lua:146>
```

Spamming <CR> (between 4-7 times) causes a flood of messages, but eventually everything seems to work as expected.

Image for completeness:

![image](https://user-images.githubusercontent.com/6194343/156422480-0ffd59de-7671-45c5-aa60-0de16952254d.png)

### Expected behavior

No error messages to be printed.

### Steps to reproduce

1. `:NeorgStart`
2. `:Neorg gtd views` > t

### Other information

I am experiencing this on both my Windows 11 machine and M1 MacBook Pro machine. Pinning Neorg to Versoin `0.0.11` causes the issue to go away. I wasn't experiencing this when I was messing around yesterday after finding Neorg, so I think it could be a recent regression.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

Discussions on possible causes and general guidance.

**Comment by danymat** [comment]
@vhyrro Seems to be a event issue, instead of GTD. Did you modify event handling recently ?

**Comment by danymat** [comment]
Hello ! Seems like d877687036b6a7610dab9eac15ecf5819022b5da was at stake ! I reverted it while waiting for a stabler implementation. Maybe it's more subtle than it seems. I will re-open the issue if it's the case 🥳
