### ISSUE TITLE
GTD Module assumes that workspace index file name is "index.norg"

### ISSUE THREAD

**Issue by mSiotniHS** [nvim-neorg/neorg#395]
When using GTD Module in workspace with changed index file name, the module is creating new "index.norg" file. The problem is in this line:

https://github.com/nvim-neorg/neorg/blob/d4212a0e68bcfc9486457a802a7ba75287cfba22/lua/neorg/modules/core/gtd/base/module.lua#L131

So I guess GTD Module should either somehow find out actual name of a workspace index file, or not bother creating index file at all.

**Comment by danymat** [comment]
Sure, sorry for this bug, will fix it asap

**Comment by danymat** [comment]
> with changed index file name

Do you mean you changed the name with `dirman` module ?

**Comment by mSiotniHS** [comment]
Yes, exactly --- there is the config parameter "index" in Dirman module.

**Comment by danymat** [comment]
Hello, can you test with latest commit ?

**Comment by mSiotniHS** [comment]
Yep, it's fine now! Thank you!
