### ISSUE TITLE
Links stop working

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/neorg#396]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

neovim nightly

### Neorg setup

```lua
require('neorg').setup({
   load = { -- what modules to load
       ...
      ["core.norg.dirman"] = { config = { -- Manage your directories with Neorg.
         workspaces = {
           -- Format: <name_of_workspace> = <path_to_workspace_root>
            notes = "~/notes",
         },
         index = "index.norg", -- The name of the main (root) .norg file.
         -- Automatically change the directory to the current workspace's root
         -- every time.
         autochdir = true,

         -- The location to write and read the workspace cache file.
         last_workspace = vim.fn.stdpath("cache").."/neorg_last_workspace.txt"
      }},
      ...
   }
})
```

### Actual behavior

I have file `index.norg` in the root of my current workspace. I put cursor on the line:
```norg
  -- {:$/software/git:* git}[git]
```

press Enter, and get the next error:

```lua
Error executing vim.schedule lua callback:
...eorg/lua/neorg/modules/core/norg/dirman/utils/module.lua:11: attempt to call field 'get_current_workspace' (a nil value)
stack traceback:
        ...eorg/lua/neorg/modules/core/norg/dirman/utils/module.lua:11: in function 'expand_path'
        ...org/lua/neorg/modules/core/norg/esupports/hop/module.lua:364: in function 'locate_link_target'
        ...org/lua/neorg/modules/core/norg/esupports/hop/module.lua:62: in function 'follow_link'
        ...org/lua/neorg/modules/core/norg/esupports/hop/module.lua:757: in function 'on_event'
        ...are/nvim/site/pack/packer/opt/neorg/lua/neorg/events.lua:159: in function <...are/nvim/site/pack/packer/opt/neorg/lua/neorg/events.lua:146>
```

Previously everithing was fine.

### Expected behavior

-

### Steps to reproduce

-

### Help

No

**Comment by vhyrro** [comment]
Oh wow, I don't know how I missed this 😅. I believe it's because of some changes to dirman which I'm unaware of - I'll take a look at it later today when I get home. Sorry for taking so long to get back to ya!

**Comment by vhyrro** [comment]
Heyo! It should be fixed :). I'll close the issue for now, if you still encounter any issues then feel free to reopen this issue and let me know!
