### ISSUE TITLE
Any GTD window doesn't set scrolloff back to user settings

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#400]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

      {:load {:core.defaults {}
              :core.norg.concealer {:config {:markup_preset :dimmed
                                             }}
              :core.keybinds {:config {:neorg_leader :<Leader>n}}
              :core.norg.dirman {:config
                                 {:workspaces
                                  {:...}
                                  :index "main.norg"
                                  :autodetect true
                                  :autochdir true}}
              :core.gtd.base {:config {:workspace :programming}}
              :core.norg.qol.toc {}
              :core.norg.journal {:config {:workspace :personal
                                           :journal_folder "journal"
                                           :use_folders false
                                           }}
              :core.norg.completion {:config {:engine :nvim-cmp}}
              }

### Actual behavior

Any GTD window will keep it's `scrolloff` value of 999 when returning to the norg file

### Expected behavior

The value set/default Vim value should be used after closing the GTD window

### Steps to reproduce

Open any GTD window then close it, `scrolloff` is now 999

### Help

No

**Comment by danymat** [comment]
hello, should be fixed !

**Comment by jghauser** [comment]
I'm getting the following error now when opening gtd views. I'm guessing it has to do with the fix for this issue as it's about scrolloff.

```
Error detected while processing BufLeave Autocommands for "<buffer=17>":                                                                                        
E5108: Error executing lua vim/_meta.lua:170: Value for option 'scrolloff' is out of range                                                                      
stack traceback:                                                                                                                                                
        [C]: in function 'nvim_set_option'                                                                                                                      
        vim/_meta.lua:170: in function '__newindex'                                                                                                             
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155: in function 'delete_window'                                                            
        [string ":lua"]:1: in main chunk                                                                                                                        
        [C]: in function 'nvim_buf_delete'                                                                                                                      
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:253: in function 'destroy'                                                                  
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:333: in function <...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:329>          
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:22: in function 'invoke_key_in_selection'                                                   
        [string ":lua"]:1: in main chunk                                                                                                                        
Error detected while processing WinLeave Autocommands for "<buffer=17>":                                                                                        
E5108: Error executing lua vim/_meta.lua:170: Value for option 'scrolloff' is out of range                                                                      
stack traceback:                                                                                                                                                
        [C]: in function 'nvim_set_option'                                                                                                                      
        vim/_meta.lua:170: in function '__newindex'                                                                                                             
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155: in function 'delete_window'                                                            
        [string ":lua"]:1: in main chunk                                                                                                                        
        [C]: in function 'nvim_buf_delete'                                                                                                                      
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:253: in function 'destroy'                                                                  
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:333: in function <...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:329>          
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:22: in function 'invoke_key_in_selection'                                                  
```
In my `init.lua` I have `vim.opt.scrolloff = 10`.

**Comment by danymat** [comment]
Hello, I just added a info log. Can you enable info logs and try again ? You should have some values returning:

```
require('neorg').setup {
	logger = {
		level = "info" -- Show trace, info, warning, error and fatal messages
	}
}
```

**Comment by jghauser** [comment]
OK, yeah something fishy is going on:
```
[neorg] (13:28:57)                                                                                        
.../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155                                           
scrolloff: 94024078501440    
```

**Comment by danymat** [comment]
Can you output the result of: `:set scrolloff?` ? Both before entering in a gtd view, and inside a gtd view ?

**Comment by jghauser** [comment]
Sure!
- Before entering a gtd view, it's 10.
- When opening the Quick Actions view, it's 999.
- When selecting from there e.g. the 'Today's tasks' the error appears. Scrolloff in that window is also 999.
- When closing that view, it's still set to 999.

**Comment by danymat** [comment]
Hmm, I don't understand..
Does `:lua print(vim.o.scrolloff)` return the same ?

**Comment by jghauser** [comment]
I have no idea what is going on here either, and I'm even more confused now.
`:lua print(vim.o.scrolloff)` returns  `1.4068050233843e+14` and that value is different each time i open neovim. It doesn't change when I go to 'Quick actions', nor when i open 'Today's tasks'. Actually, I just realise this seems to happen sometimes as well when opening files other than `norg` files.

Maybe this is a bug in neovim. Or in my setup, though I don't understand why `:lua print(vim.o.scrolloff)` should return a different value from `:set scrolloff?`. It happens even if I disable the scrolloff setting in my `init.lua`. I'm on the latest release of neovim stable.

I'll investigate some more when I get time and open an issue with neovim.

**Comment by danymat** [comment]
This is very weird, can you guys try it out now? I use `nvim_get_option` instead, hoping it'll be better

**Comment by jghauser** [comment]
This solved it for me! No more errors and scrolloff is correctly set and reset.

No idea what causes the weirdness, but once I get some time I'll investigate some more.

**Comment by danymat** [comment]
Nice ! Very weird, seems to be a neovim bug we just found. I'm closing it as it seems solved, feel free to reopen if the issue still persists
