### ISSUE TITLE
Provide support for nVim's native completion

### ISSUE THREAD

**Issue by diktomat** [nvim-neorg/neorg#403]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

The completion module currently only works with compe (and cmp?). Users accustomed to nVim's native `^X^foo` can use file, keyword, spelling … completion of course, but it would be great if Neorg could ship omnifunc and tags completion for use without any completion plugin, too.

### Help

No

### Implementation help

Sorry, but my Lua skills are barely enough for Neovim config..

**Comment by benlubas** [comment]
Native completion is supported by: https://github.com/benlubas/neorg-interim-ls
