### ISSUE TITLE
Non-neorg file links are not opened relative to current file

### ISSUE THREAD

**Issue by camdencheek** [nvim-neorg/neorg#405]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

0.7.0

### Neorg setup

```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {}, -- Load all the default modules
        ["core.keybinds"] = {
            config = {
                default_keybinds = false,
                hook = function(keybinds)
                    keybinds.map_event_to_mode("norg", {
                        n = {
                            { "<CR>", "core.norg.esupports.hop.hop-link" },
                            { "<M-CR>", "core.norg.esupports.hop.hop-link", "vsplit" },
                        },
                    })
                end,
            }
        },
        ["core.export"] = {
            config = {},
        },
        ["core.export.markdown"] = {
            config = {},
        },
        ["core.norg.concealer"] = {
            config = {
                icons = {
                    todo = { enabled = false },
                    list = { enabled = false },
                    link = { enabled = false },
                    ordered = { enabled = false },
                    ordered_link = { enabled = false },
                    heading = { enabled = false },
                    marker = { enabled = false },
                    definition = { enabled = false },
                    footnote = { enabled = false },
                    delimiter = { enabled = false },
                },
            },
        },
        ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
                workspaces = {
                    default = "~/notes"
                },
                autochdir = true,
                index = "index.norg",
                last_workspace = vim.fn.stdpath("cache") .. "/neorg_last_workspace.txt",
            }
        },
        ["core.gtd.base"] = { config = { workspace = "default" } },
    },
}
```

### Actual behavior

With a link like `{@ file.pdf}` referring to another non-neorg file in the same directory, following the link with `core.norg.esupports.hop.hop-link` opens the file relative to nvim's CWD rather than relative to the current neorg file.

### Expected behavior

The file that is opened should be relative to the file that contains the link, not neovim's current directory.

### Steps to reproduce

- `:e /tmp/test.norg`
- `:cd ~`
- Insert `{@ testfile.pdf}`
- Place cursor on `{@ testfile.pdf}` and `<CR>`
- The opened file is `~/testfile.pdf`, not `/tmp/testfile.pdf`

### Other information

This issue is the same as https://github.com/nvim-neorg/neorg/pull/391, except it applies to non-neorg file links rather than neorg file links.

### Help

Yes

### Implementation help

I'm happy to work on a fix for this, but last time I made a PR for a similar issue, it sounded like the code in this area [needed some general cleanup](https://github.com/nvim-neorg/neorg/pull/391#issuecomment-1056994205).

If these concerns are no longer a problem, I'll dig in. If there are remaining structural issues, I'm still happy to look at refactoring a bit, but would likely need some direction.

**Comment by vhyrro** [comment]
Oops, the issue got autoclosed by github, sorry. I think I've managed to fix it now, mind giving it a crack?

If anything's still wrong then feel free to reopen this issue :P

**Comment by camdencheek** [comment]
It works beautifully now. Thanks for the quick turnaround 🚀
