### ISSUE TITLE
Neovim segmentation fault

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#406]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

require('neorg').setup {
    load = {
        ["core.defaults"] = {}
    }
}

### Actual behavior

Neovim segmentation faults

### Expected behavior

The file open normally

### Steps to reproduce

Open a file with the following content:

```
#contexts test
#time.start 2022-05-08
#time.due 2022-05-15
* test

#contexts test
#time.start 2022-06-10
#time.due 2022-06-30
* test

#contexts test
#time.start 2022-05-15
#time.due 2022-06-01
* test

#contexts test
#time.start 2022-04-20
#time.due 2022-04-30
* test

#contexts test
#time.start 2022-04-05
#time.due 2022-04-15
* test
```

### Other information

This is the most minimal file I could come up with. It seems removing any of the lines gets rid of the segmentation fault.

### Help

No

**Comment by vhyrro** [comment]
Hey! I think I've managed to resolve the problem. Mind checking it out? :)

**Comment by jghauser** [comment]
Yes, that fixes it! Thanks :)
