### ISSUE TITLE
Undefined gtd gtd command

### ISSUE THREAD

**Issue by Aceticia** [nvim-neorg/neorg#413]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

v0.6.1

### Neorg setup

```
require('neorg').setup {
    ensure_installed = { "norg", "norg_meta", "norg_table", "python", "latex", "markdown" },
    highlight = {enable = true},
    load = {
        ["core.defaults"] = {},
        ["core.norg.dirman"] = {config={workspaces={all="~/Dropbox/all"}}},
        ["core.norg.concealer"] = {},
        ["core.gtd.base"] = {config={workspace="all"}},
        ["core.norg.completion"] = {config={engine="nvim-cmp"}}
    }
}
```

### Actual behavior

When I use any gtd related command, e.g. `:Neorg gtd views`, I get the error message `.../neorg/lua/neorg/modules/core/neorgcmd/module.lua.289: Unable to execute command :Neorg gtd gtd - such a command does not exist`.

### Expected behavior

Show views of the gtd/capture.

### Steps to reproduce

I encountered this error after creating an empty workspace. This same error appears when there is an entry with 1 todo item.

### Potentially conflicting plugins

I'm trying out LunarVim which I just installed today, which I'm not terribly familiar with...

### Help

No

**Comment by danymat** [comment]
Hello, try doing `:NeorgStart` before doing GTD related commands

**Comment by Aceticia** [comment]
My apologies - this was indeed why. What would be a suggested way to automate this? Autocommand when launching sounds good, but I wonder whether there will be a builtin version of this? Will this requirement ever change with future versions of Neorg? Many thanks.
