### ISSUE TITLE
Heading deletes spaces if I change from insert mode to normal, even without editing anything

### ISSUE THREAD

**Issue by roland-rollo** [nvim-neorg/neorg#418]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+1383-g2a4660014

### Neorg setup

```
-- Neorg ----------------------------------------------------------------------------------------------------------------
require('neorg').setup {
    -- Tell Neorg what modules to load
    load = {
        ["core.defaults"] = {}, -- Load all the default modules
	["core.gtd.base"] = {
            config = {
                -- workspace =   "example_gtd" , -- assign the workspace,
                workspace = "dokumenty",
		workspace = "example_gtd",
                exclude = { "notatki/" }, -- Optional: all excluded files from the workspace are not part of the gtd workflow
                projects = {
                show_completed_projects = true,
                show_projects_without_tasks = true,
                },
                custom_tag_completion = true,
            },
	    inbox = "inbox.norg",
        },
	["core.keybinds"] = {
            config = {
                default_keybinds = true,
            }
        },
        ["core.norg.concealer"] = {}, -- Allows for use of icons
	["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp"
                }
            },
        ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
                workspaces = {
                    dokumenty = "~/Dokumenty",
		    example_gtd = "~/Dokumenty/example_workspaces/gtd",
		    notatki = "~/Dokumnety/neorg"
                }
            }
        },
	["core.norg.journal"] = {}
    },
}
```

### Actual behavior

https://asciinema.org/a/afpUkLsQSHzAD2HHhP0hzd7Ha

So, it's little strange, but if I change mode to `insert mode` in line with heading (any level) and back to normal mode, it will `eat` all space keys, that were before * sign.  So second level from
```
 ** something
```
Will change to
```
** something
```
and forth level from
```
   **** something
```
to
```
**** something
```

Things from lists doesn't seem to have this problem: If I change mode to insert in
```
 - something
```
It's still like was before, and I can close neovim and don't see in that in buffer are any changes.

### Expected behavior

Umm. Doesn't do like this?

### Steps to reproduce

Try to change to insert mode and back to normal mode in any heading. Sad part is, I didn't do anything with Neorg about few days, so I'm not sure when it started.

### Help

No

### Implementation help

I would love to, but don't know lua, but If I can do something just tell me.

**Comment by max397574** [comment]
This is the expected behavior.
This comes from the indenting with treesitter.
You can configure this I just don't know how at the moment.
Perhaps @vhyrro can help you with it.

**Comment by jghauser** [comment]
I think you might find [the following discussion](https://github.com/nvim-neorg/neorg/discussions/411) useful. Basically, you need to add a tweaks config table specifying the desired indent. More information in the discussion.

**Comment by roland-rollo** [comment]
Ow yeah, that's it!
