### ISSUE TITLE
Popup help window with relevant combinations

### ISSUE THREAD

**Issue by premell** [nvim-neorg/neorg#419]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I think its very helpful to have some common bindings right in neorg, so you dont have to go to github to check the syntax. I use neorg about once a month and I always find myself coming here to see how to do basic stuff, like filling in a todo list.

I think it would be nice to have a quick look up right in neorg with relevant bindings. I am thinking something like this. ![image](https://user-images.githubusercontent.com/65544203/161428989-799072d5-23a3-4ca0-bb44-85981d372278.png)

I also find nvchads keybinding list very helpful and it could be some inspiration: 
![image](https://user-images.githubusercontent.com/65544203/161429065-f8e8d67c-81fd-4980-9bf6-51ad435dac4e.png)

You could also use treesitter to figure out what binding the user wants to look up. For instance here you can see that user is hovering a todo list, and so you can show the various options for todos (ie [x] for done).
![image](https://user-images.githubusercontent.com/65544203/161429145-7d80fc67-0293-4128-a6ca-1a0438248a70.png)

In this example the user is hovering a bold text. You could create categories with relevant combinations, like "important text". So if they hover bold text, you could give them a list of the different headers etc.
![image](https://user-images.githubusercontent.com/65544203/161429168-c12659a4-eb7d-4262-a9b7-7998101347c1.png)

### Help

No

**Comment by max397574** [comment]
I'll add a cheatsheet module for this

**Comment by vhyrro** [comment]
While this used to be a great idea back in the day, nowadays this should ideally be delegated to some sort of `which-key` implementation (there are a few out there right now), such a feature would just bloat modern neorg :p

Closing!
