### ISSUE TITLE
core.gtd.base error at views and capture when `inbox.norg` has no metadata

### ISSUE THREAD

**Issue by Xystel** [nvim-neorg/neorg#425]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

minimal example of a whole Neovim Config:
```lua
require('packer').startup(function(use)
	-- manage itself
	use { 'wbthomason/packer.nvim' }

  use {
      "nvim-treesitter/nvim-treesitter",
      before = "neorg",
      config = function()
        -- setup parser source for neorg
        local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

        parser_configs.norg = {
            install_info = {
                url = "https://github.com/nvim-neorg/tree-sitter-norg",
                files = { "src/parser.c", "src/scanner.cc" },
                branch = "main"
            },
        }
        require('nvim-treesitter.configs').setup {
          highlight = {
            enable = true,
            use_languagetree = true,
          },
          -- preinstall parser
          ensure_installed = { 'norg' },
        }
      end,
      as = 'treesitter',
      run = ':TSUpdate',
  }

  use {
      "nvim-neorg/neorg",
      as = "neorg",
      config = function()
          require('neorg').setup {
            load = {
              ["core.defaults"] = {},
              ["core.norg.concealer"] = {},
              ["core.norg.dirman"] = {
                config = {
                  workspaces = {
                    example = "~/example",
                  },
                },
              },
              ["core.gtd.base"] = {
                config = {
                  workspace = "example"
                },
              },
            },
          }
      end,
      requires = "nvim-lua/plenary.nvim"
  }
end)
```

### Actual behavior

When calling `Neorg gtd views` it outputs an error, if there is no metadata in the `inbox.norg` file.

When the file is automatically created, the metadata isn't injected. 

The error message does not imply this.

This also failes with `Neorg gtd capture` at the step of adding it to a project.

### Expected behavior

1. the gtd module should work without the metadata (preferred IMHO)
2. the metadata is automatically injected for the `inbox.norg` file.

### Steps to reproduce

views error:
1. use my provided config, maybe change the folder for the `example` workspace to your liking.
2. type in terminal `nvim +NeorgStart` or `:NeorgStart` in Neovim. It should create empty `inbox.norg` and `index.norg`.
4. `:Neorg gtd views` should output the error

capture error:
1. use my provided config, maybe change the folder for the `example` workspace to your liking.
2. type `nvim +NeorgStart` in the shell or `:NeorgStart` in Neovim. It should create empty `inbox.norg` and `index.norg`.
3. `:Neorg gtd capture`
4. add a task name and press enter
5. press `p` (Add to project): Outputs also an error, **but a different one**.

### Potentially conflicting plugins

None, as I tested it with a minimal example.

### Help

No

**Comment by danymat** [comment]
Hello, can you provide a screenshot of those errors ?

**Comment by Xystel** [comment]
36bffcb37e0d9ae5bec069e13bea22840f1a5aa3 fixed the problem for me.
