### ISSUE TITLE
Start neorg depending on filetype instead of file extension (or both)

### ISSUE THREAD

**Issue by z4m1n0** [nvim-neorg/neorg#435]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I have files which have to end with `.txt`, but I would like to use the Neorg 's syntax and highlighting. So I tried to set the file type to `norg`, but Neorg didn't start. So I looked into the code. At the moment Neorg only starts if the file end in `.norg` and ignores the filetype. The file type of file ending with `.norg` is automatically set to `norg` with ftdetect. So I would be possible to only look at the filetype of the buffer, or at least both (extension and filetype).

The current code in `lua/neorg.lua` is this:
``` lua
    -- If the file we have entered has a .norg extension
    if vim.fn.expand("%:e") == "norg" then
        -- Then set the filetype and boot up the environment
        neorg.org_file_entered(false)
    else
    ...
```
The comment about the filetype is misleading, because it is not dependent on the if-statement.

I would chance it to:
``` lua
    -- If the buffer we have entered has the filetype "norg"
    if vim.tbl_contains(vim.split(vim.bo.filetype, ".", {plain=true}), "norg") then
        -- Then boot up the environment
        neorg.org_file_entered(false)
    else
    ...
```

### Help

No

**Comment by z4m1n0** [comment]
After working with the change I noticed the the keymaps only work in files ending with `.norg`. I think it is because of the autocommands, but I didn't looked into it.

**Comment by max397574** [comment]
First of all
why don't u just change the extension to .norg?

And you can create an autocmd with `NeorgStart`

**Comment by z4m1n0** [comment]
Hello, thx fore the reply.
I use other programs, which doesn't know the `.norg` extension. For example my program for sharing notes across my devices only works with `.txt` files.

The autocmds are created with my change, but they only look at buffers with the extension `.norg`. As some of my files ends with `.txt`, the autocommands doesn't trigger.

**Comment by z4m1n0** [comment]
I'm not really solid in lua and how it interact with neovim, but think it would be possible to create a function `has_ft_norg` and have a if-statement in the autocommand instead of the path regex.
Example function:
```lua
function has_ft_norg()
    return vim.tbl_contains(vim.split(vim.bo.filetype, ".", {plain=true}), "norg")
end
```
The autocommands could be changed like this:
```
autocmd BufAdd *.norg ++once :lua require('neorg').org_file_entered(false)
```
```
autocmd BufAdd * ++once :lua if has_ft_norg() then require('neorg').org_file_entered(false) end
```

**Comment by z4m1n0** [comment]
I made three small changes.
First i add a function in `lua/neorg.lua`
```lua
function neorg.has_ft_norg()
    return vim.tbl_contains(vim.split(vim.bo.filetype, ".", {plain=true}), "norg")
end
```
Then i change the autocmd in the same file to:
```lua
			autocmd BufAdd * ++once :lua if require('neorg').has_ft_norg() then require('neorg').org_file_entered(false) end
```
and changed the creation of autocmd in `lua/neorg/modules/autocommands/module.lua` from:
```lua
            elseif vim.fn.exists("#Neorg#" .. autocmd .. "#*.norg") == 0 then
                vim.cmd(
                    "autocmd "
                        .. autocmd
                        .. ' *.norg :lua _neorg_module_autocommand_triggered("core.autocommands.events.'
                        .. autocmd
                        .. '", true)'
                )
            end
```
to:
```lua
            elseif vim.fn.exists("#Neorg#" .. autocmd .. "#*.norg") == 0 then -- TODO change lookup for norg specific autocmd
                vim.cmd(
                    "autocmd "
                        .. autocmd
                        .. ' * :lua if require("neorg").has_ft_norg() then _neorg_module_autocommand_triggered("core.autocommands.events.'
                        .. autocmd
                        .. '", true) end'
                )
            end
```

Now it seems to work. (Except some autocmds get created multiple times)

**Comment by z4m1n0** [comment]
I divided the autocmd into two groups. The first which has `dont_isolate` set to `true` is `NeorgGlobal` and the second stays at `Neorg`. So the whole if-statement looks like this:
```lua
            if dont_isolate then
                if vim.fn.exists("#NeorgGlobal#" .. autocmd .. "#*") == 0 then
                    vim.cmd("augroup NeorgGlobal")
                    vim.cmd(
                        "autocmd "
                            .. autocmd
                            .. ' * :lua _neorg_module_autocommand_triggered("core.autocommands.events.'
                            .. autocmd
                            .. '", false)'
                    )
                    vim.cmd("augroup END")
                end
            else
                if vim.fn.exists("#Neorg#" .. autocmd .. "#*") == 0 then
                    vim.cmd("augroup Neorg")
                    vim.cmd(
                        "autocmd "
                            .. autocmd
                            .. ' * :lua if require("neorg").has_ft_norg() then _neorg_module_autocommand_triggered("core.autocommands.events.'
                            .. autocmd
                            .. '", true) end'
                    )
                    vim.cmd("augroup END")
                end
            end

```

Now every autocmd is created once.

**Comment by z4m1n0** [comment]
Can I create a pull request? I could even use the new nvim api for autocmds.

**Comment by vhyrro** [comment]
Hiya, sorry for taking so long to get to you.

It would be very easy to make it dependent on filetype (as you said), however I don't know whether it will achieve what you want either way - there are many places in the Neorg codebase that rely on the current file having a `.norg` extension (for example the presenter module, GTD, and more), so I don't know whether the simple change you're proposing would work in the way you'd expect. We'd have to rewrite quite a bit of code to get it working.

**Comment by vhyrro** [comment]
There is a way in treesitter to have .txt files be highlighted as `.norg` files, but then that's all you get - just syntax highlighting. I assume you want all the features of Neorg to work as well, right?

**Comment by z4m1n0** [comment]
At the moment I only really use the syntax, highlighting and keymaps, there wasn't more when I started to use it ^^. I will have a look at the other modules and if it is possible to change them to use filetype. I think it is better to use filetype than filename, for example with a new buffer. At the moment I have a little spare time and would give it a try, if its ok. :D
