### ISSUE TITLE
Support for Questions and answer like Todo list

### ISSUE THREAD

**Issue by hardfau18** [nvim-neorg/neorg#439]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Most of the time workflow revolves around looking into somethings,  some queries that needs answered with single sentence or a paragraph. 

##### Possible work arounds:
one way i can do that is using like L6 headings, but headings are considered as project. Another way Could be having special list items, If i am not wrong currently list items are just normal sentences.

If Anyone has any other solution also for this that will also work

And thank you for great work❤️

I looked at  #232 its not these two are not same 😅

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by max397574** [comment]
If you're just looking for something to write that down I'd use
```
- question?
  answer to question
- another question
  second answer
```

**Comment by vhyrro** [comment]
Hey @hardfau18, I don't think I quiite get the question, but I think you might be interested in definitions?

They should fit your use case most, since it's a query with a sentence/paragraph as a response. The syntax is as follows:
  ```
  $ Recrudescent
    Breaking out again after temporary abatement or supression.
  ```
  It's equivalent to:
  ```md
  Recrudescent
  : Breaking out again after temporary abatement or supression.
  ```
  In some flavours of markdown, and renders in a special, more compact way. Hope I got your question right :p

**Comment by hardfau18** [comment]
It works, right now i am using definitions. But correct me if am wrong, we can't use definition in lists and todo's

**Comment by hardfau18** [comment]
> If you're just looking for something to write that down I'd use
> 
> ```
> - question?
>   answer to question
> - another question
>   second answer
> ```

This is ok, So closing the issue

**Comment by mrossinek** [comment]
FWIW once we release version 0.1 of Neorg you will get all the nice new syntax which we have been developing. This will allow you to use so called "indent segments" allowing you to place e.g. definitions inside of list items. This will look something along the lines of this:
```norg
- \
  $ Recrudescent
  Breaking out again after temporary abatement or supression.
  ---
```
The `---` ends the indent segment but is optional if you follow immediately with another list item of the same level.
