### ISSUE TITLE
Attempt to call nil field `tree_map_rec` when trying to use TOC features

### ISSUE THREAD

**Issue by zdcthomas** [nvim-neorg/neorg#442]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0

### Neorg setup

```lua 
require("neorg").setup({
	load = {
		["core.defaults"] = {},
		["core.norg.qol.toc"] = {},
		["core.norg.concealer"] = {},
		["core.norg.esupports.metagen"] = {
			config = {
				template = {
					{
						"title",
						function()
							return vim.fn.expand("%:p:t:r")
						end,
					},
					{ "description", "" },
					{ "authors", "Zachary Thomas" },
					{ "categories", "" },
					{
						"created",
						function()
							return os.date("%Y-%m-%d")
						end,
					},
					{ "version", require("neorg.config").version },
				},
			},
		},
		["core.integrations.nvim-cmp"] = {},
		["core.norg.journal"] = {
			config = {
				strategy = "flat",
			},
		},
		["core.norg.completion"] = {
			config = {
				engine = "nvim-cmp",
			},
		},
		["core.norg.dirman"] = {
			config = {
				workspaces = {
					wiki = "~/irulan",
				},
			},
		},
	},
})
```

### Actual behavior

In a `.norg` file which contains an `= TOC`, when I run `Neorg toc inlilne/split/toqflist` I get an error which doesn't appear in the `norg.log` file in `stdpath('data'). The error text is 
```
Error executing vim.schedule lua callback: ...art/neorg/lua/neorg/modules/core/norg/qol/toc/module.lua:253: attempt to call field
 'tree_map_rec' (a nil value)
stack traceback:
        ...art/neorg/lua/neorg/modules/core/norg/qol/toc/module.lua:253: in function 'generate_toc'
        ...art/neorg/lua/neorg/modules/core/norg/qol/toc/module.lua:281: in function <...art/neorg/lua/neorg/modules/core/norg/qo
l/toc/module.lua:267>
        ...art/neorg/lua/neorg/modules/core/norg/qol/toc/module.lua:390: in function 'on_event'
        ...e/nvim/site/pack/packer/start/neorg/lua/neorg/events.lua:155: in function <...e/nvim/site/pack/packer/start/neorg/lua/
neorg/events.lua:142>
```

<img width="1680" alt="Screen Shot 2022-04-30 at 1 50 18 PM" src="https://user-images.githubusercontent.com/36716240/166120597-3d455148-a967-46ec-8f36-fd359e19ca58.png">
 

### Expected behavior

When I run `:Neorg toc inline/split/toqflist` a table of contents would be generated and displayed in the desired location

### Steps to reproduce

Run `:Neorg toc split/inline/toqflist` in a norg file with `= TOC` present. 

### Other information

* The `norg` and `norg_meta` treesitter parsers are both installed successfully according to `:TSInstallInfo`
* I'm on MacOs 12.2.1
* I've installed and linked a newer version of gcc, as described [here](https://github.com/nvim-neorg/neorg#troubleshooting-treesitter)

### Help

No

**Comment by max397574** [comment]
can confirm this
this function got removed here
https://github.com/nvim-neorg/neorg/commit/12f82bcc59fe6de18288fe5a20868691034783ea
I hope @vhyrro will readd it soon

**Comment by vhyrro** [comment]
Why does github keep autoclosing issues lmao

Either way this should be fixed now, mind giving it a shot? If it's still broken then feel free to reopen

**Comment by max397574** [comment]
for me it's fixed

**Comment by zdcthomas** [comment]
Yup! It's fixed for me too! Thanks for such a quick response!
