### ISSUE TITLE
Abnormal luasnip

### ISSUE THREAD

**Issue by denstiny** [nvim-neorg/neorg#446]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0

### Neorg setup

```lua
local has_ts, neorg = pcall(require, "neorg")
if not has_ts then return end

neorg.setup {
  -- Tell Neorg what modules to load
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.norg.concealer"] = {}, -- Allows for use of icons
    ["core.keybinds"] = {config={default_keybinds=false}},
    ["core.norg.dirman"] = { -- Manage your directories with Neorg
      config = {
        workspaces = {
          my_workspace = "~/neorg"
        }
      }
    },
    ["core.norg.completion"] = {
      config = {
        engine = "nvim-cmp" -- We current support nvim-compe and nvim-cmp only
      }
    },
    ["core.norg.journal"] = {
      config = { -- 生成日记
      }
    },
    ["core.norg.qol.toc"] = {
      config = { -- 生成目录
        toc_split_placement='left',
        default_toc_mode = "split",
      }
    },
  },
}



```

### Actual behavior

![图片](https://user-images.githubusercontent.com/57088952/166961984-fd521be1-bb23-4148-bd66-0fd58012e58d.png)

### Expected behavior

![图片](https://user-images.githubusercontent.com/57088952/166962153-f21794a3-0cca-4844-ad5f-f1bfcc55100f.png)

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/57088952/166962237-9de47b71-97d2-49ea-ab27-cd8c5fa19724.png)

https://user-images.githubusercontent.com/57088952/166962455-f747e366-7503-47c0-bf53-ae27d3a3f940.mp4

### Potentially conflicting plugins

luasnip

### Other information

Temporarily considered indentation causes

### Help

Yes

**Comment by max397574** [comment]
can you send the snippets

**Comment by d-r-a-b** [comment]
Can this issue be closed since the OP has not responded to a request for more information in ~1 year?
