### ISSUE TITLE
[NOT A BUG] update `completion` wiki

### ISSUE THREAD

**Issue by ofirgall** [nvim-neorg/neorg#453]
First, I'm sorry its a "bug" issue, I couldn't figure a way to contribute/issue about the wiki.\

The [completion](https://github.com/nvim-neorg/neorg/wiki/Completion) wiki isn't informative, it says `compe` is the only engine but it now supports, `nvim-cmp` and `nvim-compe` (different name).

It missing the part of adding `neorg` as source for `nvim-cmp` (I don't know what is the corresponding step for `nvim-comp`)

**Comment by danymat** [comment]
Hello, should be done now !
