### ISSUE TITLE
export to file results in: "Unable to export file - did not find exporter for filetype 'markdown'."

### ISSUE THREAD

**Issue by GiuseppeCesarano** [nvim-neorg/neorg#454]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version
```
NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  
Features: +acl +iconv +tui 
See ":help feature-compile"     
system vimrc file: "$VIM/sysinit.vim"   
fall-back for $VIM: "/usr/share/nvim"
```
### Neorg setup

```lua 
require('neorg').setup {
  load = {
        ["core.defaults"] = {},
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    work = "~/Documents/norg/work",
                    notes = "~/Documents/norg/notes",
                    gtd = "~/Documents/norg/gtd",
                }
            }
        },
    ["core.gtd.base"] = {config= {
	workspace = "gtd",
	}},
        ["core.norg.concealer"] = {},
	["core.export"] = {}
    }
}
```

### Actual behavior

Running `:Neorg export to-file f.md` or `:Neorg export to-file file.md markdown` results in:  
```:Neorg export to-file f.md      [neorg] (12:07:49)
...m/plugged/neorg/lua/neorg/modules/core/export/module.lua:115
Unable to export file - did not find exporter for filetype 'markdown'.
Press ENTER or type command to continue
Error executing luv callback:
...m/plugged/neorg/lua/neorg/modules/core/export/module.lua:245: bad argument #2 to 'fs_write' (data must be string or table of strings, got nil)
stack traceback:
        [C]: in function 'fs_write'
        ...m/plugged/neorg/lua/neorg/modules/core/export/module.lua:245: in function <...m/plugged/neorg/lua/neorg/modules/core/export/module.lua:239>
``` 
  
But an empty file with the given name is created

### Expected behavior

Successfully export the current neorg buffer to markdown

### Steps to reproduce

I'm not exactly sure why the export doesn't work, but on my machine this bug happens every time i try to run the export command.

### Other information

I can confirm that the file `[...]/neorg/modules/core/export/markdown/module.lua` exists and it's populated.

### Help

No

**Comment by jghauser** [comment]
For me it started working, when I explicitly loaded the `core.export.markdown` module as well.

**Comment by max397574** [comment]
yes
it isn't one of the default modules

**Comment by GiuseppeCesarano** [comment]
Oh it was actually that easy of a fix! I didn't even notice that there was a `core.export.markdown`!
