### ISSUE TITLE
Filter waiting.for in Today's tasks

### ISSUE THREAD

**Issue by AckslD** [nvim-neorg/neorg#462]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

In the Today's tasks view any `waiting.for` todos are show along others. Could they either:
* Not be shown
* Shown separately at the bottom
?

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

If this is desirable for others, I'd be happy to try to help with this but probably with some guidance :)

**Comment by vhyrro** [comment]
I'm going on an old-issue-closing spree and I kind of feel bad for all the issues I didn't respond to lol. Well GTD has been since nuked so closing this one! :)
