### ISSUE TITLE
Inconsistent contexts

### ISSUE THREAD

**Issue by AckslD** [nvim-neorg/neorg#463]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

v0.8.0-dev+227-g6613f58ceb

### Neorg setup

```lua
local M = {}

M.config = function()
  require('neorg').setup {
    load = {
      ["core.defaults"] = {},
      ["core.norg.concealer"] = {},
      ["core.export"] = {},
      ["core.gtd.base"] = {
        config = {
          workspace = 'home',
        },
      },
      ["core.gtd.ui"] = {},
      ["core.gtd.helpers"] = {},
      ["core.gtd.queries"] = {},
      ["core.norg.completion"] = {
        config = {
          engine = 'nvim-cmp',
        },
      },
      ["core.integrations.nvim-cmp"] = {},
      ["core.presenter"] = {
        config = {
          zen_mode = "zen-mode",
        },
      },
      ["core.export.markdown"] = {
        config = {
          extensions = "all",
        },
      },
      ["core.norg.dirman"] = {
        config = {
          workspaces = {
            home = "~/todo/neorg",
          },
        },
      },
    },
  }
  require('which-key').register({
    a = {
      name = '+neorg',
      g = {
        name = 'gtd',
        c = {'<Cmd>Neorg gtd capture<CR>', 'capture'},
        e = {'<Cmd>Neorg gtd edit<CR>', 'edit'},
        v = {'<Cmd>Neorg gtd views<CR>', 'views'},
      },
      n = {'<Cmd>Neorg news all<CR>', 'news'},
      p = {
        name = 'presenter',
        s = {'<Cmd>Neorg presenter start<CR>', 'start'},
        c = {'<Cmd>Neorg presenter close<CR>', 'close'},
      },
      w = {'<Cmd>Neorg workspaces<CR>', 'workspaces'},
    }
  }, {prefix = '<leader>'})
end

return M
```

### Actual behavior

I was to understand how contexts and carryover tags work. Lets say I have the following:
```
* test
  #contexts test
  #time.start 2022-05-23
  - [x] first
  - [ ] second
  - [x] third
  - [ ] fourth
```
If I then open the contexts popup (`Neorg gtd views<CR>c`) then the `test` contexts does not show up. Neither if moving the contexts one line below:
```
* test
  #time.start 2022-05-23
  #contexts test
  - [x] first
  - [ ] second
  - [x] third
  - [ ] fourth
```
However if I move it one more as:
```
* test
  #time.start 2022-05-23
  - [x] first
  #contexts test
  - [ ] second
  - [x] third
  - [ ] fourth
```
then `test` does show up in the contexts popup.

### Expected behavior

Not actually sure, but @vhyrro said on discord that it's at least probably not the intended behaviour :)

### Steps to reproduce

See above

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by danymat** [comment]
```
* test
  #contexts test
  #time.start 2022-05-23
  - [x] first
  - [ ] second
  - [x] third
  - [ ] fourth
```

The contexts only show tasks that are active. Here, the 4 tasks start on 23, which were some days after your post.

```
* test
  #time.start 2022-05-23
  - [x] first
  #contexts test
  - [ ] second
  - [x] third
  - [ ] fourth
```

Here, the `first` task starts on 23th, but not the others, which are active. You can take a look at the TreeSitter playground to see which tasks are inside the tags

**Comment by AckslD** [comment]
Thanks for your reply @danymat! I think I find it quite confusing how the `#contexts` "stops" the `#time` in the second case, even though those are independent concepts. But I guess that just how it works atm?
