### ISSUE TITLE
todo-comments highlight 

### ISSUE THREAD

**Issue by MyraBaba** [nvim-neorg/neorg#464]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Is there any way to use folke/todo-comment highlighters in neor files ?

Best

### Help

No

**Comment by xfzv** [comment]
See https://github.com/folke/todo-comments.nvim/issues/106

**Comment by mrossinek** [comment]
Discussion continued in that issue: https://github.com/folke/todo-comments.nvim/issues/106#issuecomment-1133882933

Closing this issue here, since it is working as expected and this is likely some user configuration issue.
