### ISSUE TITLE
norg.so  sysmbol not found 

### ISSUE THREAD

**Issue by MyraBaba** [nvim-neorg/neorg#466]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

0.8

### Neorg setup

```
`{
    "nvim-neorg/neorg",
    -- tag = "*",
    config = function()
      require('neorg').setup {
        load = {
          ["core.defaults"] = {},
          ["core.norg.concealer"] = {}, -- Allows for use of icons
          ["core.gtd.ui"] = {
            config = { -- Note that this table is optional and doesn't need to be provided
              -- Configuration here
            }
          },
          ["core.keybinds"] = { -- Configure core.keybinds
            config = {
              default_keybinds = true, -- Generate the default keybinds
              neorg_leader = "<Leader>o"
            }
          },

          ["core.gtd.helpers"] = {},
          ["core.gtd.queries"] = {},
          ["core.norg.qol.toc"] = {
            config = { -- Note that this table is optional and doesn't need to be provided
              -- Configuration here
            }
          },
          ["core.norg.completion"] = {
            config = { -- Note that this table is optional and doesn't need to be provided
              engine = "nvim-cmp"

            }
          },
          ["core.highlights"] = {
            config = {}
          },
          ["core.norg.dirman"] = {
            config = {
              workspaces = {
                work = "~/neorg/work",
                home = "~/neorg/home",
                gtd  = "~/neorg/gtd"
              },
              index = "index.norg",
              autochdir = true,

            }
          },
          ["core.gtd.base"] = {
            config = {
              workspace = "gtd",
            },
          },
        }

      }
    end,
    requires = "nvim-lua/plenary.nvim",
    require('nvim-treesitter.configs').setup {
      ensure_installed = { "norg", --[[ other parsers you would wish to have ]] },
      highlight = { -- Be sure to enable highlights if you haven't!
        enable = true,
      }
    }

  },
`
```

### Actual behavior

<img width="1291" alt="Screen Shot 2022-05-22 at 21 30 39" src="https://user-images.githubusercontent.com/17505439/169710360-ba678bf0-8e64-4701-b07d-21348065347c.png">

### Expected behavior

normal run

### Steps to reproduce

Mac os X catalina
latest neovim and neorg wth to-do plugin

### Help

No

**Comment by MyraBaba** [comment]
<img width="1292" alt="Screen Shot 2022-05-22 at 22 00 17" src="https://user-images.githubusercontent.com/17505439/169711478-1e4a79e1-ba86-44e7-9f70-470e6290c0d6.png">

**Comment by vhyrro** [comment]
Hi! Sorry for the incredibly late reply. This seems like a problem with your compiler, did you try following some of the troubleshooting steps in the README for MacOS systems?

Here's a quote:
> If on MacOS, ensure that the CC environment variable points to a compiler that has C++14 support. You can run Neovim like so: CC=/path/to/newer/compiler nvim -c "TSInstallSync norg" in your shell of choice to install the Neorg parser with a newer compiler. You may also want to export the CC variable in general: export CC=/path/to/newer/compiler.

Unfortunately macs are shipped with outdated compilers so you need to install a newer version and make Treesitter use the newer one.

**Comment by vhyrro** [comment]
Since there was no response on the issue I'll close it - if the issue still persists then feel free to reopen :)
