### ISSUE TITLE
bug: breaks tsplayground query editor

### ISSUE THREAD

**Issue by max397574** [nvim-neorg/neorg#468]
https://github.com/max397574/neorg/blob/c541c37a9683ac6751eaa1b0ad1e6fecf3d2a985/lua/neorg/modules/core/integrations/treesitter/module.lua#L23-L27

These lines break the tree-sitter-playground query editor

**Comment by vhyrro** [comment]
😳 that's not good, guess i have to fix it properly now 😅

**Comment by vhyrro** [comment]
Granted that it was fixed now I'll close down this issue :)
