### ISSUE TITLE
Export to markdown should omit the document metadata

### ISSUE THREAD

**Issue by ram02z** [nvim-neorg/neorg#469]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

The commonmark specification does not support metadata, so it would be best to omit it entirely when converting from norg to md. An extension should be to convert the norg metadata into yaml (embdedded into the markdown), which is supported by pandoc.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Took a quick look at the export module and didn't quite get how it worked, but I am willing to try.

**Comment by vhyrro** [comment]
Thanks for bringing this to my attention! I have some important exams coming up in 3 days, but I'll see if I can cram in some time tomorrow to fix this - this has been made even worse thanks to the fact that I've been rewriting my config for the past 2 days cause my old one broke :sweat_smile:

I'll be on it asap :)

**Comment by ram02z** [comment]
> Thanks for bringing this to my attention! I have some important exams coming up in 3 days, but I'll see if I can cram in some time tomorrow to fix this - this has been made even worse thanks to the fact that I've been rewriting my config for the past 2 days cause my old one broke 😅
> 
> I'll be on it asap :)

Good luck on your exams.

I finished finals last week so I have some time, so I will try to look into this further myself.

**Comment by vhyrro** [comment]
I think it should work like a charm now! Without any extensions the metadata is omitted, whereas when the `metadata` extension is enabled it uses `---` by default but can also be customized to use `---`/`...` etc.

Let me know if it works alright, I'll close the issue in the meantime but feel free to reopen.

I'm aware that the exporter gives rather ugly output rn in terms of human-readability and newlines but I'll only be working on that in the future :)
