### ISSUE TITLE
Neorg is not detecting TS parser on Windows 10 (not  wsl)

### ISSUE THREAD

**Issue by mr-majkel** [nvim-neorg/neorg#470]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

0.7.0

### Neorg setup

```
require("neorg").setup{}
```

### Actual behavior

TS errors when entering .norg file
If `load = { ["core.defaults"] = {} }` is added, neorg continues to reinstall TS parsers, but the files are not parsed.

<details>

```
Error detected while processing FileType Autocommands for "*":
Error executing lua callback: Failed to load parser: uv_dlopen: The specified procedure could not be found.

stack traceback:
        [C]: in function '_ts_add_language'
        ...rrent\share\nvim\runtime/lua/vim/treesitter/language.lua:33: in function 'require_language'
        ...neovim\current\share\nvim\runtime/lua/vim/treesitter.lua:39: in function '_create_parser'
        ...neovim\current\share\nvim\runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:136: in function 'start'
        ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:142: in function 'attach'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:465: in function 'attach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:488: in function 'reattach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:106: in function <...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:105>
```

</details>

### Expected behavior

Colorful .norg file

### Steps to reproduce

I'm using packer

1. Install neorg plugin.
2. Run `TSInstall norg` (success).
3. Enter .norg file (e.g. `:e test.norg`)
4. Errors

### Other information

I have added "norg" to required parsers in TS config.
Same steps and config runs ok on linux machine.

### Help

No

**Comment by vhyrro** [comment]
:thinking: well that's definitely not correct - unfortunately I can't help much with this issue as it's not a Neorg-specific problem :(

Your best bet would be to run `:checkhealth nvim-treesitter` and see whether there are any errors, these errors could be caused by some uninstalled or out of date compilers. Also make sure that if you're using e.g. mingw you're running a 64 bit version if you're on a 64 bit machine.

Also check the outputs of `gcc -v` and `clang -v` and make sure those versions support C++11 or later (as that's what tree-sitter-norg needs).

**Comment by mr-majkel** [comment]
A quick update: following troubleshooting section of the [Windows support](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#troubleshooting) page on nvim-treesitter I have changed the compiler to clang from llvm. Unfortunately norg parser is still the only one not working:

<details>

'''
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.16.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang" }
    Version: clang version 14.0.4
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - dockerfile     ✓ . . . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - norg           x . x . x 
  - http           ✓ . . . ✓ 
  - r              ✓ ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: norg(highlights): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    norg(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\modzmi01\AppData\Local\nvim-data\site\pack\packer\start\neorg\queries\norg\highlights.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: norg(folds): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    norg(folds) is concatenated from the following files:
    | [ERROR]:"C:\Users\modzmi01\AppData\Local\nvim-data\site\pack\packer\start\neorg\queries\norg\folds.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: norg(injections): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    norg(injections) is concatenated from the following files:
    | [ERROR]:"C:\Users\modzmi01\AppData\Local\nvim-data\site\pack\packer\start\neorg\queries\norg\injections.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
'''


</details>

**Comment by mr-majkel** [comment]
Ok, issue solved. I have been running nvim from under Git for Windows bash. After updating Git for Windows to ver 2.36.1 (I was on 2.31.1 before) and using its bash I was able to automagically get the norg parser to load. Not sure to what extent I had to recompile the parsers with llvm, but changing bash to something fresh on top, made it work.
