### ISSUE TITLE
Custom highlights not working

### ISSUE THREAD

**Issue by AckslD** [nvim-neorg/neorg#471]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.8.0-dev+340-gb7d70de345

### Neorg setup

```lua
require('neorg').setup {
  load = {
    ["core.highlights"] = {
      config = {
        CarryoverTag = {
          Begin = "+TSConstant",
          Name = {
            Word = "+TSConstant",
          },
        },
      },
    },
    ["core.defaults"] = {},
    ["core.norg.concealer"] = {},
    ["core.export"] = {},
    ["core.gtd.base"] = {
      config = {
        workspace = 'home',
      },
    },
    ["core.gtd.ui"] = {},
    ["core.gtd.helpers"] = {},
    ["core.gtd.queries"] = {},
    ["core.norg.completion"] = {
      config = {
        engine = 'nvim-cmp',
      },
    },
    ["core.integrations.nvim-cmp"] = {},
    ["core.presenter"] = {
      config = {
        zen_mode = "zen-mode",
      },
    },
    ["core.export.markdown"] = {
      config = {
        extensions = "all",
      },
    },
    ["core.norg.dirman"] = {
      config = {
        workspaces = {
          home = "~/todo/neorg",
        },
      },
    },
  },
}
```

### Actual behavior

I'm getting eg:
```
:highlight NeorgCarryoverTagBegin                                                                                                                                                    
NeorgCarryoverTagBegin xxx links to TSLabel
```

### Expected behavior

`NeorgCarryoverTagBegin` to be linked to `TSConstant`

### Steps to reproduce

Open a neorg file with the above config

### Other information

I've tried to put `core.defaults` both before and after `core.highlights` but both give the same.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by SenchoPens** [comment]
+1, NVIM 0.7.0

**Comment by vhyrro** [comment]
Hey, this is because you didn't provide the highlights key. It should look like this:
```lua
["core.highlights"] = {
    config = {
        highlights = { -- You missed this bit!
            CarryoverTag = {
                Begin = "+TSConstant",
                Name = {
                    Word = "+TSConstant",
                },
            },
        },
    },
},
```

I've accidentally done this many of times as well so no worries :p

I assume you might have made a mistake because of the wiki entry - sorry! I know it's a mess right now and our automatic documentation generator isn't that great, I'll work on that one day.

**Comment by AckslD** [comment]
Oh I see, thanks @vhyrro!
