### ISSUE TITLE
Error when selecting to add a new task to a project during a capture

### ISSUE THREAD

**Issue by akinsho** [nvim-neorg/neorg#472]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.8.0-dev+1802-g7380ebfc1

### Neorg setup

```lua  
require('neorg').setup({
    configure_parsers = true,
    load = {
      ['external.kanban'] = {},
      ['core.defaults'] = {},
      ['core.integrations.telescope'] = {},
      ['core.keybinds'] = {
        config = {
          default_keybinds = true,
          neorg_leader = '<localleader>',
          hook = function(keybinds)
            keybinds.unmap('norg', 'n', '<C-s>')
            keybinds.map_event('norg', 'n', '<C-x>', 'core.integrations.telescope.find_linkable')
          end,
        },
      },
      ['core.norg.completion'] = {
        config = {
          engine = 'nvim-cmp',
        },
      },
      ['core.norg.concealer'] = {},
      ['core.norg.dirman'] = {
        config = {
          workspaces = {
            notes = fn.expand('$SYNC_DIR/neorg/notes/'),
            tasks = fn.expand('$SYNC_DIR/neorg/tasks/'),
            work = fn.expand('$SYNC_DIR/neorg/work/'),
          },
        },
      },
      ['core.gtd.base'] = {
        config = {
          workspace = 'tasks',
        },
      },
    },
  })
```

### Actual behavior

When trying to add a new task using `Neorg gtd capture` when getting to the stage where I'm asked where to add the task and selecting a project trying to then select `<CR>` to submit the capture errors.

<img width="1435" alt="Screen Shot 2022-06-01 at 15 57 00" src="https://user-images.githubusercontent.com/22454918/171435256-626f8fec-77f9-4f87-969b-3dae73a82a1c.png">

```
E5108: Error executing lua ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:305: attempt to index local 'node_or_range' (a nil value)                                     
stack traceback:                                                                                                                                                                     
        ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:305: in function 'get_node_range'                                                                                
        ...rt/neorg/lua/neorg/modules/core/gtd/queries/creators.lua:235: in function 'insert_tag'                                                                                    
        ...rt/neorg/lua/neorg/modules/core/gtd/queries/creators.lua:62: in function 'create'                                                                                         
        ...rt/neorg/lua/neorg/modules/core/gtd/ui/capture_popup.lua:508: in function <...rt/neorg/lua/neorg/modules/core/gtd/ui/capture_popup.lua:491>                               
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:343: in function <...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:329>                               
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:22: in function 'invoke_key_in_selection'                                                                        
        [string ":lua"]:1: in main chunk
```

### Expected behavior

The expected behaviour is that the capture is completed, and the task is correctly added which it is not.

### Steps to reproduce

1. Create a gtd project somewhere and add some tasks, there is no space between the projects and the following tasks.
2. Go to another unrelated buffer (not sure this is relevant), run `Neorg gtd capture`
3. Add in all the data, at the point where it says where to add use `p` to choose your project
4. Press `<CR>` to confirm

### Help

No

**Comment by max397574** [comment]
is it perhaps the same as this?
https://github.com/nvim-neorg/neorg/issues/388

**Comment by akinsho** [comment]
It looks like the same error message although I didn't set a time on my task

**Comment by terrortylor** [comment]
I get the same issue, I'm able to replicate this by adding a task to a project in a norg file that:
- is the last project in a file
- has no blank or non-task related lines after it

I work around at the moment is to add the following to the end of any GTD norg files:

```

Prevent https://github.com/nvim-neorg/neorg/issues/472 with a extra line at end of file.
```

Whilst I know not a fix, may help replicate the issue in tests?

**Comment by torben-luedeking** [comment]
Another Workaround i found is to add a unclarified Task(no comments in front of task) as first Task in a project.

**Comment by d-r-a-b** [comment]
Hi there! Just a community member going through the old issues. It looks like this refers to features of the GTD module which was dropped recently. Would you mind closing this issue?

#695 provides rationale for the change and a plan for moving forward as the devs/contributers make sure to get things right before committing the community in a bad direction at this alpha stage. Lists and TODOs still work great and there is really cool work going on right now to advance the macro system, so there's lots of exciting stuff down the pipeline!
