### ISSUE TITLE
Markdown export does not export code blocks

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#482]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0

### Neorg setup

```fennel
{:load {:core.defaults {}
              :core.norg.concealer {}
              :core.export {}
              :core.export.markdown {}
              :core.keybinds {:config {:neorg_leader :<Leader>n}}
              :core.norg.dirman {:config
                                 {:workspaces
                                  {:blog "~/Documents/neorg/Blog"
                                   :fennel "~/Documents/neorg/Fennel"
                                   :oblivion "~/Documents/neorg/Oblivion"
                                   :personal "~/Documents/neorg/Personal"
                                   :programming "~/Documents/neorg/Programming"
                                   :obl-ref "~/Programs_and_Stuff/Git_Repos/oblivion-lang-ref/src"
                                   :wood "~/Documents/neorg/Woodworking"}
                                  :index "main.norg"
                                  :autodetect true
                                  :autochdir true}}
              :core.gtd.base {:config {:workspace :obl-ref}}
              :core.norg.qol.toc {}
              :core.norg.journal {:config {:workspace :personal
                                           :journal_folder "journal"
                                           :use_folders false}}}}
```

### Actual behavior

When exporting for markdown, code blocks do not seem to export anything inside of them, just exporting the header and footer

### Expected behavior

Data inside the code block should be visible

### Steps to reproduce

Simply export any Neorg file with a code block

### Help

Yes

**Comment by vhyrro** [comment]
Hey, should be fixed now, hopefully didn't break anything else in the meantime :p

**Comment by vhyrro** [comment]
@katawful did you have some time to test this out yet?

**Comment by katawful** [comment]
Been too busy to remember to test this out, I'll try to remember tonight

**Comment by katawful** [comment]
Seems to work now, thanks
