### ISSUE TITLE
(gtd) [not urget]: `<C-w>` when in insert mode editing eg. `context` exits insert mode.

### ISSUE THREAD

**Issue by molleweide** [nvim-neorg/neorg#487]
Hi guys,

I just noticed that using `<C-w>` which is standard for deleting work backwards, seems to escape insert mode when editing/capturing a task in `gtd`.

FYI, I am using `macos` and latest `doom-nvim`.

Minor issue. Add this one as I stumble upon it. I'll add more info later if necessary.

## edit
Lol, I have accidentally discarded pretty much every task I have been trying to capture because my muscle memory to press `<c-w>` twice is so strong.

**Comment by vhyrro** [comment]
Well not much to fix here since GTD has been nuked :joy:. Closing!
