### ISSUE TITLE
gtd: go back command for each section of capture/edit task, (not just for `views -> advanced`)

### ISSUE THREAD

**Issue by molleweide** [nvim-neorg/neorg#491]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I noticed that there is a goback button if you browse `gtd views -> advanced` and I think it should be added to each section of the gtd flow. For example if you press `c` for context but realize you should pressed something else.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

This is also probably not that difficult/good beginner task to implement so this is also a feature that I'll look into as I get deeper in neorg.

**Comment by vhyrro** [comment]
This issue boutta be dropped harder than the GTD nuke. Here it goes
