### ISSUE TITLE
Traverse heading should skip closed folds

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#498]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently, moving up or down in traverse-heading mode will visit each heading even if the heading is hidden in a closed fold. I think it would be more intuitive if headings within closed folds were skipped.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by max397574** [comment]
not sure how easy doable this is since we use treesitter to get headings
I hope it will be doable with `nvim_get_folds` (an open pr in neovim/neovim) but this has to be merged first and then we'll have to wait for the 0.8 release

**Comment by jghauser** [comment]
In my [fold-cycle.nvim](https://github.com/jghauser/fold-cycle.nvim), I have a function to check if a line is within a closed fold. I guess something like this could probably be used to check whether the headings returned by treesitter are within a closed fold. But I do understand if you want to wait until `nvim_get_folds` is implemented.

``` lua
local function is_fold_closed(line)
  local folded
  if fn.foldclosed(line) == -1 then
    folded = false
  else
    folded = true
  end
  return folded
end
```

**Comment by max397574** [comment]
I didn't rly think about it before writing it xD
I used the functions for fold before
I think it should be possible to implement this quite easily (get position of heading, check if inside fold and if so go to next one and repeat)

**Comment by max397574** [comment]
I can look at it later this week

**Comment by jghauser** [comment]
haha, no worries! great, looking forward to it :)

**Comment by vhyrro** [comment]
Should be done now! Works on my end, lemme know if it's the behaviour you want. Thanks for all the issues by the way, they're very helpful. Got back from holiday yesterday so I'm gonna go on a bug fixing spree :)

**Comment by jghauser** [comment]
It almost works as I imagine it, but now it skips a little too much :rofl:. Though that's also my fault for not being precise enough in my issue... What happens now is that folds are skipped entirely, but what would be elegant is if only *hidden* folds were skipped. 

Say you have a file like this:
```
* A heading
* Another heading
** A subheading
* More headings
```
And fold it like this:
```
* A heading [1]
* Another heading [<- folded here] [2]
* More headings [3]
```
Then i would like to move from [1] to [2] and to [3] whereas now it jumps from [1] to [3]. Let me know if it isn't clear.

You're very welcome about the issues! Given that you like them, I'm sure you'll be happy to hear that I have some more haha. I should get to writing them up soon!

**Comment by vhyrro** [comment]
Ahh okay I get it now lol. Will get to fixing that in a bit then!

About the new issues, I'm ready when you are :smile:

**Comment by vhyrro** [comment]
Alright, second time's the charm! Test it out now and see if it's the behaviour you desired :crossed_fingers:

**Comment by jghauser** [comment]
perfect! :tada:
