### ISSUE TITLE
neorg-roam telescope and improvement?

### ISSUE THREAD

**Issue by archaict** [nvim-neorg/neorg#50]
hello, this might be helpful for a simple telescope function for people to setup their notebook location, maybe people could also share what they used for neorg here:

``` lua
function neorg_roam()
  require('telescope.builtin').find_files({
    prompt_title = "Notebook";
    cwd = "~/path/to/neorg";
  })
end
```

and also I think https://github.com/folke/todo-comments.nvim plugin can also help with colorizing some stuff so it's more integrated as a notebook and as a little fancy notebook for others to start using it (maybe better than what emacs org did), I didn't know if it's mentioned elsewhere, but might be a good idea.

 thank you for this awesome plugin!

**Comment by vhyrro** [comment]
Thanks for the kind words man! If you're looking for extra telescope-related features you might wanna check out https://github.com/vhyrro/neorg-telescope which attempts to add some nifty fuzzy finding features like inserting links and jumping between headings.

I personally just enter a workspace and then invoke `find_files` on the cwd which will always be set to my workspace root anyway :)

As for extra highlights for things like `* TODO` etc. I can add those if you'd like. It won't add any extra functionality other than just looking good but that's usually enough for some people.

**Comment by archaict** [comment]
it seems I miss it somewhere for that link, thank you very much for your hard work!
yes, I think it is only useful to help me navigate neorg file, since sometimes fg_highlight alone isn't enough to make me realize that it is actually different section altogether. I hope there are better ways to implement it at later date. I hope the best for this project, hope to move all my files to .neorg soon!
