### ISSUE TITLE
command to increase/decrease nesting

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#501]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Sometimes I want to increase or decrease the nestedness of some item. For instance I would like:
```
- this
 -- list
```
to become:
```
 -- this
  --- list
```
It would be great if there were a command (especially in visual mode) that allowed me to do that (rather than having to s/foo/bar).

Also, now that I've reached the end of my issue opening spree, I want to thank you all for your hard work. Neorg is really a great piece of software -- I'm only reporting all these things because I like it so much ;).

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by katawful** [comment]
Handled by #183 for the most part. Doubt lists will be addressed specifically until then

**Comment by jghauser** [comment]
Yes, was just about to edit my message because it just now dawned on me I should probably check the PRs :facepalm:. I'm leaving this open for reference and until the feature is implemented.

**Comment by vhyrro** [comment]
Feature has indeed been implemented! Like 5 months ago or something :laughing:, closing!
