### ISSUE TITLE
recurring cyclical/frequency list

### ISSUE THREAD

**Issue by molleweide** [nvim-neorg/neorg#507]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

There is already a thread about recuring tasks (https://github.com/nvim-neorg/neorg/issues/457) but I didn't want to hijack it so I post an additional useful feature here that could add some extra thoughts on the matter.

Here's an additional idea for recurring task. You could call it `Recurring frequency list`.

I use cleaning house as an example.

1. You have a set of recurring tasks `vacuum, bathroom, empty-sink, clean-filters, etc.`
2. So now I want to have a reminder that makes sure I execute on at least one of these a day, on a recurring basis.
3. It would also be cool if tasks could be sorted on a last done basis so that you know which task is best to perform next.

Basically this type of list feature could be useful for any types of sets of tasks that need to be done on a regular basis but the order is not important. Good for maintaining real tangible stuff I am thinking. What do you think?

Another example is keeping track of your fitness routine and similar stuff. Make sure you have an even distribution of workout for all your muscles if you do body building or whatever.

```lua

#name chores@home
#cyclical every-second-day
-  empty-sink (empty sink is disgusting so I keep it first until I have energy to do it.)
-  vacuum (I do some vacuuming and it will go last on `<CR>`)
-  bathroom,
- clean out filters 
- move out trash
- clean my room
- make bed
- slay dragon
- get gold

#name 5-day-workout-split-routine
#cyclical every-day
#scheduled_block 06-08AM mornings
- upper push
- lower push
- upper pull 
- lower pull
- arms (l just did arms and so it should be placed last.)
```

### Help

No

**Comment by vhyrro** [comment]
This is a nice idea! It probably would use a completely different syntax but the idea itself is nice. Unsure how integrated it is into GTD, but I'm personally perfectly okay with adding stuff on top of the GTD implementation, after all neorg is supposed to be a generic and versatile tool. What do you think @danymat?
