### ISSUE TITLE
Various GTD

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#510]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.2

### Neorg setup

```
require("neorg").setup({
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
		["core.norg.dirman"] = { -- Manage your directories with Neorg
			config = {
				workspaces = {
					main = "~/testing/",
				},
			},
		},
		["core.gtd.base"] = {
			config = {
				workspace = "main",
				default_lists = {
					inbox = "inbox_gtd.norg",
				},
			},
		},
  },
})
```

### Actual behavior

Various bugs/feature requests regarding GTD. I hope it's ok to bundle them, I wanted to save some time writing them up. I know you're currently rewriting much of GTD, so some of this might not apply anymore I guess.

1. Unintuitive keybind
- When adding a task, we set the date to today with `d`, but when editing a task `d` removes the date. I have often mistakenly removed it when I wanted to set the date to today.

2. Explain custom date format
- When I first used gtd to capture a task, I didn't know that the correct date format is `2022-12-03`. Maybe adding that to the existing explanations would be useful.

3. cmp completion when adding new task
- Often (but not always), the first suggestion when I type `- [` is a `done` task, which is almost never what I want. Having the `undone` task be the first suggestion would make more sense. 

4. Editing tasks that are part of a project
- When the project has a context, then editing a tasks context with change the *project* context (above the project heading) and also indent that tag wrongly.
- When the task has a context (tag just above it), then editing the the task context with edit the right context, but the task and the context will be wrongly indented.

~~5. Time start doesn't show in today's tasks~~
~~- I think it would make sense that tasks with a `#time.start` date today or in the past show up in today's tasks. Or if that doesn't make sense for all use cases, maybe have it behind an option (if that's already the case, I would appreciate a pointer in the right direction).~~ [solved, see [down](https://github.com/nvim-neorg/neorg/issues/510#issuecomment-1179717837) [below](https://github.com/nvim-neorg/neorg/issues/510#issuecomment-1179793813)]

### Expected behavior

See above.

### Steps to reproduce

See above.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by AckslD** [comment]
@jghauser I had the same thought as your last point (I couldn't find how to share a link to a discord message on my phone, but you could find it as my latest message in the #neorg-gtd chat on discord). @danymat suggested me to both put a `#contexts today` and `#time.start` for such things which does seem to work well.

**Comment by jghauser** [comment]
@AckslD I don't think that would solve my particular use case. I often have tasks (like deadlines on which I need to submit something) that I want to start working on say 2 weeks before they are due. So what I thought I'd do is set a `#time.start` 2 weeks earlier than the `#time.due` so that neorg would remind me when I should start working on it. Your option only really helps if the starting date is today (correct me if I'm wrong).

**Comment by AckslD** [comment]
What I mean is that if you for example put today in contexts but also a start time at lets say 15th of July. The given task will only show up in today's task on the 15th of July. Does that make sense? :)

**Comment by jghauser** [comment]
Oh, I had no idea they interacted like that. Great, thanks!

**Comment by AckslD** [comment]
Me neither before :) No problem

**Comment by danymat** [comment]
Hello, thanks for all your input ! We will soon be reworking the gtd code, and I for sure will be using your insights during this time.
I will let you know when we start reworking on it by linking it to the dedicated PR

**Comment by danymat** [comment]
Hello, time has come lol: https://github.com/nvim-neorg/neorg/issues/695
