### ISSUE TITLE
Incorrect indentation when exporting code blocks to markdown

### ISSUE THREAD

**Issue by danilshvalov** [nvim-neorg/neorg#518]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.2

### Neorg setup

```lua
require("neorg").setup({
    load = {
        ["core.export"] = {},
        ["core.export.markdown"] = {},
    },
})
```

### Actual behavior

Incorrect indentation when exporting code blocks to markdown:

<details>
<summary>Neorg</summary> 

```neorg
* Title

  @code cpp
  #include <iostream>

  int main() {
    std::cout << "Hello World!" << std::endl;
  }
  @end
```
</details>

<details>
<summary>Markdown</summary> 

# Title

```cpp
#include <iostream>

  int main() {
    std::cout << "Hello World!" << std::endl;
  }
```
</details>

### Expected behavior

I was expecting the following file.
<details>
<summary>Markdown</summary> 

# Title

```cpp
#include <iostream>

int main() {
  std::cout << "Hello World!" << std::endl;
}
```
</details>

### Steps to reproduce

Export the above neorg file to markdown

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by vhyrro** [comment]
Heyo! On my end this should be fixed now! I'll close this issue now but if you still find any problems with this then feel free to reopen and let me know :)
