### ISSUE TITLE
Flexibility with GTD and workspaces

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#523]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I like using Neorg for a lot of things, both with the variety of my personal needs and for projects that need a lot of prose. For the latter, the tasks assigned to said project are generally confined to it, as it is for a public project and cannot be stored with my personal files. Currently, GTD will only let me view tasks from a single pre-defined workspace. I looked through GTD to see if it makes any mention on the structure of your GTD directory with this respect, but doesn't seem to make note of a situation like this where one has segmented workspaces

Instead, would it be possible to have the ability to look in the current workspace first when parsing for GTD, then with options to look into other workspaces?

### Help

Yes

**Comment by danymat** [comment]
What about having an option to get tasks and projects from all workspaces, instead of only one ? 

If you want to switch workspace when inside neorg, maybe @vhyrro can help you in telling if it exists a function to change a public setup during runtime (you would then be able to change gtd.setup.workspace to your desired one)

**Comment by katawful** [comment]
All would be nice, but an option for the current workspace only would still be nice to have

Workspace switching works perfectly as is, it just seems in-congruent with GTD currently. If I switch from my assigned workspace using `Neorg workspace blah-blah`, GTD will still always parse from the pre-defined workspace I set in `core.gtd.base.config.workspace`. Unless I am missing something, I would have to manually update said table each time I switch a workspace (or start Neorg in a workspace that isn't my GTD one), which would be easy enough with a custom command, but something that seems like should be built in
