### ISSUE TITLE
Display issue with headlines containing a special character

### ISSUE THREAD

**Issue by xfzv** [nvim-neorg/neorg#524]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Neorg setup

```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {
            config = {
                dim_code_blocks = {
                    enabled = true,
                    conceal = true,
                    content_only = true,
                    adaptive = true,
                },
                icon_preset = "diamond",
            },
        },
    },
}
```

### Actual behavior

In a `.norg` file,  if the headline contains a special character such as `$` ; `$` ; `µ` **and/or** an accent key such as `à` ; `à` ; `â` ; `ç` ; `é` ; `è` ; `ê` ; `ô` ; `û` ; `ü` or whatever, then the following display issue occurs when folding:

- Healine without any special character
![image](https://user-images.githubusercontent.com/78810647/179563135-b092c8de-7346-475d-af4f-45bb1f24a938.png)

- Headline with a special character (`é`)
![image](https://user-images.githubusercontent.com/78810647/179563179-6fbc096f-6bd0-4f1b-bed0-d8795ed34b1f.png)

### Expected behavior

The folded headline containing a special character should be displayed like the ones which do not.

### Steps to reproduce

1. Open a `.norg` file
2. Use the following second and third levels headlines combination and press `za` to quickly fold/unfold
```
* Test
** Cafe
*** Cafe

** Cafe
*** Café

** Café
*** Cafe

** Café
*** Café
```

3. Notice the display issue for the headlines containing a special character (`é` in this case)

### Help

No

**Comment by Anrock** [comment]
Something similar happens with russian letters
```
* Дежурства
* Попробовать выключить базелевый сендбокс
* Перевод base на cbor
```
When folded turns into this
![2022-07-20-133252_455x75_scrot](https://user-images.githubusercontent.com/1689392/179961416-776ebce9-53d4-470d-b6fc-9f44d73bba77.png)

**Comment by vhyrro** [comment]
Hey I fixed this on my end! Mind updating and checking if it works now?

**Comment by xfzv** [comment]
> Hey I fixed this on my end! Mind updating and checking if it works now?

Can confirm it's fixed here with https://github.com/nvim-neorg/neorg/commit /6998f79eb1e769e691160a3e9127019dc09c83de.

Thanks!
