### ISSUE TITLE
Avoid setting full width for codeblock

### ISSUE THREAD

**Issue by siduck** [nvim-neorg/neorg#526]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

![image](https://user-images.githubusercontent.com/59060246/180586143-9eddaa67-3733-418c-a7b1-d64e67e954ca.png)

@vhyrro Hi! would it be possible to avoid having full width for the code block and use width of the code only? It looks bad when Im on a split buffer. 

Also this : 

some inner padding like new line at the start/end of the code and 2 spaces at the left/right of the code. This would make it look like a padding 

![image](https://user-images.githubusercontent.com/59060246/180586886-26792d2f-ec55-4b4f-b1f1-2571634a585d.png)

Something like this but without extra right padding :p    

@max397574 

### Help

No

**Comment by vhyrro** [comment]
Interesting idea! Didn't think of making that customizable. Don't know how much time I'll have for Neorg today but if I do I'll implement that :)

**Comment by siduck** [comment]
no worries, take your time. Just lemme know when this gets done, I mainly use neorg for notes so the codeblocks styled perfectly is a msut need feature imo. Maybe @max397574  can work on this :thinking:

**Comment by vhyrro** [comment]
Hey @siduck, just finished implementing the non-fullwidth option.
You can enable it like so:
```lua
["core.norg.concealer"] = {
	config = {
		dim_code_blocks = {
			width = "content", -- Default is "fullwidth"
		}
	},
},
```

Now onto implementing the padding!

**Comment by siduck** [comment]
@vhyrro it works but my text overflows from the codeblock 

![image](https://user-images.githubusercontent.com/59060246/181920391-be4c573c-8b05-4e34-91a2-9669d2558848.png)

**Comment by vhyrro** [comment]
Wdym overflows? Under what conditions does it happen (so that I can reproduce)? Autoindent shouldn't let that happen tbh 😄

**Comment by siduck** [comment]
> Wdym overflows? Under what conditions does it happen (so that I can reproduce)? Autoindent shouldn't let that happen tbh smile

https://user-images.githubusercontent.com/59060246/181925277-e762099a-c468-4658-a495-44fb3d685bde.mp4

**Comment by vhyrro** [comment]
oh no, that's very bad lol

I can reproduce, i'll look into it!

**Comment by vhyrro** [comment]
Alright i wanted to finish off the padding feature first so here it is! You can apply padding to either the left *or* to the right of the code block, works well from my testing :)

**Comment by siduck** [comment]
> Alright i wanted to finish off the padding feature first so here it is! You can apply padding to either the left _or_ to the right of the code block, works well from my testing :)

wew, works fine!

**Comment by vhyrro** [comment]
@siduck aaand I think i fixed the indentation problem too! 3 in one go :p

**Comment by siduck** [comment]
@vhyrro is it possible to use the LSP server when Im in the code block?

**Comment by max397574** [comment]
it is possible with the looking-glass module
otherwise not

**Comment by siduck** [comment]
@vhyrro i keep getting this error when the `code` item is selected in cmp 

![image](https://user-images.githubusercontent.com/59060246/184088226-ee3591ff-195d-4b80-be5c-ed0a1624578d.png)
