### ISSUE TITLE
[Suggestion] Make default keybinds more vim idiomatic?

### ISSUE THREAD

**Issue by Anrock** [nvim-neorg/neorg#528]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Just a suggestion. I've noticed that at least some default keybinds are not vim-idiomatic thus bringing some conflicts with my (and probably others) muscle memory. As an additional benefit - there will be less norg-specific binds.

For example:
- `<CR>` to follow a link in place. More idiomatic would be to use `gd` \ `gD` \ `gf`  (which also works for imports\functions\etc in LSP and similar behaviour in other plugins)
- whatever used to open a TOC can be mapped to `gO` which is literally for `Show a filetype-specific, navigable "outline" of the current buffer.`

There are probably other examples but I've just started using neorg, so I haven't used them yet.

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by frasieroh** [comment]
It would be fine to create a new mode for default bindings but changing the defaults out from under those who use it productively as opposed to tinkering would find that very annoying.

**Comment by vhyrro** [comment]
I'm browsing through the old isuses to see what can be closed - Neorg has for a while supported `gO` as well as the idiomatic `gf`, `gd` keybinds :D. Closing!
