### ISSUE TITLE
new option for metagen

### ISSUE THREAD

**Issue by max397574** [nvim-neorg/neorg#529]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

would it be possible to make a new option for metagen
so it only adds it in empty/new files?

### Help

Yes

**Comment by vhyrro** [comment]
This should now be implemented! Set `type` to `"empty"` and it should work as intended :)
