### ISSUE TITLE
Reverted dim_code_blocks

### ISSUE THREAD

**Issue by roland-rollo** [nvim-neorg/neorg#531]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

As I very like idea of dimmed code blocks to see them better, there is one small problem. I use black color as background, so I don't see damn difference. :P Folks, is there any chances for revert option for this (brightened code blocks) or option to manually set color for code blocks?

### Help

No

**Comment by vhyrro** [comment]
Ooh interesting! Yeah that makes sense, I'll implement that once I'm finished solving the indent issue within code blocks first :)

**Comment by max397574** [comment]
you could just change the highlight of `NeorgCodeBlock`

**Comment by vhyrro** [comment]
Ooh actually good call. I'll add an entry to the concealer wiki with a tutorial on how to change the highlight and also dimming properties of code block contents.

**Comment by roland-rollo** [comment]
I just wanted to ask for an instruction on how to do this. : P

**Comment by max397574** [comment]
vim.api.nvim_set_hl(0, "NeorgCodeBlock", {bg=...})

**Comment by roland-rollo** [comment]
Thanks @max397574. This works like charm!

**Comment by roland-rollo** [comment]
@vhyrro @max397574 I didn't use files with code for some time and after update to last commit, I see that
```
    vim.api.nvim_set_hl(0, "NeorgCodeBlock", {bg="#504945"})
```
doesn't work.

Is there new option to change background color?

**Comment by max397574** [comment]
yes 
the highlight group names where changed
they are now called like the treesitter captures
so it would be `@neorg.tags.ranged_verbatim.code_block` now

**Comment by roland-rollo** [comment]
Thanks, now it's working.
