### ISSUE TITLE
Conceal Module breaks Treesitter highlighting on Session Load

### ISSUE THREAD

**Issue by ziontee113** [nvim-neorg/neorg#532]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

0.7

### Neorg setup

```lua
require("neorg").setup({
	load = {
		["core.defaults"] = {},
		["core.norg.dirman"] = {
			config = {
				autochdir = true,
				autodetect = true,
				workspaces = {
					home = "~/notes/",
				},
			},
		},
		["core.norg.concealer"] = {},
		["core.norg.completion"] = {
			config = { engine = "nvim-cmp" },
		},
		["core.gtd.base"] = {
			config = {
				workspace = "home",
			},
		},
		["core.integrations.telescope"] = {},
	},
})
```

### Actual behavior

Before, with `foldlevel=2`:
![Screenshot from 2022-08-03 04-51-36](https://user-images.githubusercontent.com/102876811/182479822-459ba87a-e537-459f-a074-141820c08af9.png)

After, with `foldlevel` set to `0`:
![Screenshot from 2022-08-03 04-53-23](https://user-images.githubusercontent.com/102876811/182480042-be944ffa-897b-4e33-829d-05a9142500a5.png)

### Expected behavior

Treesitter highlighting doesn't break when setting `foldlevel=0`

![Screenshot from 2022-08-03 04-55-52](https://user-images.githubusercontent.com/102876811/182480346-43940b7f-ff7f-4fb1-ad11-e407838b2e23.png)

### Steps to reproduce

1. Have some custom Treesitter conceal rule in `~/.config/nvim/after/queries/lua/highlights.scm`, something like:
```scheme
(("local"    @keyword) (#set! conceal "~"))
((function_call name: (identifier) @TSNote (#eq? @TSNote "require")) (#set! conceal ""))
```
2. Open a `lua` file on the left split, open a `norg` file, with `concealer module` turned on.
3. Set `foldlevel=2`
4. Save the session `:makesession Session.vim`
5. Quit nvim
6. Open nvim, `:source Session.vim`
7. Set `foldlevel=0`

### Help

No

**Comment by vhyrro** [comment]
I assume this has since been fixed, as I can't reproduce anymore, this was very likely a neovim issue :)
