### ISSUE TITLE
Better documentation for completion module

### ISSUE THREAD

**Issue by premell** [nvim-neorg/neorg#539]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I spent a few hours trying to get the completion module to work like it does in your demo. I followed the documentation but didnt get any completion
![image](https://user-images.githubusercontent.com/65544203/184168526-0963e593-b7f1-4c0d-a787-8e843539da7e.png)

Then I read this article about neorg https://alpha2phi.medium.com/new-neovim-plugins-you-should-try-18aac675f595, which included this snippet.
![image](https://user-images.githubusercontent.com/65544203/184168656-bd929ffb-e61a-4fc0-a3f2-f21212b69c06.png)
 After adding that snippet everything seems to work fine, so I think this should be added to the wiki.

I am sorry to bother you, I wanted to add this section to the wiki myself but couldnt figure out how to open a PR

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by vhyrro** [comment]
Hi! I believe the documentation provides everything you need? In <https://github.com/nvim-neorg/neorg/wiki/Completion#overview> it is said to visit the wiki for the completion engine of your choice, and the link (which takes you to <https://github.com/nvim-neorg/neorg/wiki/Nvim-Cmp>) shows that you should add it to your source list.

Should it be more clear to visit those links? I tried making it stand out so people don't miss it but I guess it failed :sweat_smile:

**Comment by vhyrro** [comment]
lol, to be fair you're right about people assuming that those are links to the actual repos, I didn't consider that! I'll update it to be a bit more explicit then, and after that we can close the issue :P

The nvim-cmp module is under the developer section because the user doesn't need to explicitly specify it (and it simply handles the heavy lifting between nvim-cmp and neorg's general interface, so nothing interesting to see here hah)

**Comment by vhyrro** [comment]
> This module is an intermediary between Neorg and the completion engine of your choice. After setting up this module, please read the corresponding neorg wiki page for the engine you selected ([nvim-cmp](https://github.com/nvim-neorg/neorg/wiki/Nvim-Cmp) or [nvim-compe](https://github.com/nvim-neorg/neorg/wiki/Nvim-Compe)) to complete setup.

This is now the new text that you'll find in the completion engine wiki. I think it's much more obvious about what it's asking users to do now lol! Closing the issue :)

**Comment by premell** [comment]
thank you!
