### ISSUE TITLE
Unable to export markdown when filename starts with "~"

### ISSUE THREAD

**Issue by doodleEsc** [nvim-neorg/neorg#540]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.2

### Neorg setup

    require('neorg').setup {
        load = {
            ["core.defaults"] = {},
            ["core.norg.dirman"] = {
                config = {
                    workspaces = {
                        work = "~/Documents/Notes/work",
                        home = "~/Documents/Notes/home",
                    }
                }
            },
            ["core.norg.concealer"] = {},
            ["core.norg.completion"] = {
                config = {
                    engine = "nvim-cmp"
                }
            },
            ["core.export"] = {
                config = {}
            },
            ["core.export.markdown"] = {
                config = {
                    extensions = "all"
                }
            }
        }
    }

### Actual behavior

`:Neorg export to-file /Users/doodleEsc/index.norg` works fine

`:Neorg export to-file ~/index.norg` does not work, and the error message is: "Failed to open file '~/index.md' for export: ENOENT: no such file or directory: ~/index.md"

### Expected behavior

both "/User/doodleEsc/index.md" and "~/index.md" works

### Steps to reproduce

:Neorg export to-file ~/index.norg

### Help

Yes

**Comment by danilshvalov** [comment]
Hi! Can you try patch #544?

**Comment by vhyrro** [comment]
This should now be fixed as per daniil's latest PR! Let me know if it works as expected.

**Comment by doodleEsc** [comment]
Thanks, It works fine now!
