### ISSUE TITLE
Github action bot replaces all `@xxxx` to the wiki link in Github wiki.

### ISSUE THREAD

**Issue by Syakhisk** [nvim-neorg/neorg#547]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

(irrelevant)

### Neorg setup

(irrelevant)

### Actual behavior

All block in the github wiki starting with `@` like `@code`, `@end`, `@document.meta`, etc are replaced with the literal link of the the github wiki (https://github.com/nvim-neorg/neorg). 

### Expected behavior

Probably don't replace them

### Steps to reproduce

Go to any wiki containing any blocks starting with `@` (at signs). For example the [Tangling module wiki](https://github.com/nvim-neorg/neorg/wiki/Tangling#mini-tutorial)

### Other information

Is this intentional? I was confused at the start and then I checked the [wiki revisions](https://github.com/nvim-neorg/neorg/wiki/Tangling/_compare/ffd310822d9876975224986900852f995d1e9ba1...965bb67d1a39add7662a2079fff001119a0447b9)
It seems that there are bugs somewhere in the github workflow (probably in `make ci-doc`)

### Help

No

**Comment by vhyrro** [comment]
Wow you have some very good timing :joy:. I realized this on my own around half an hour ago, but left to get something to eat.

I'm in the process of fixing it right now so this issue shouldn't be open for too long :p

**Comment by Syakhisk** [comment]
Wow 😂. Looking forward to it! Thanks for the plugin BTW, you rock! 👍

**Comment by vhyrro** [comment]
Alright, I think it should be fixed now! If you can't find any broken bits of code we can close the issue :)

**Comment by Syakhisk** [comment]
I think the code block bugs are fixed now, but I just noticed that there are several minor bugs in the github wiki like:

- Incorrect format for links, like in (https://github.com/nvim-neorg/neorg/wiki/Core-Presenter#configuration)
- Default value for configuration as empty code blocks, like in (https://github.com/nvim-neorg/neorg/wiki/Dirman#configuration)

But I think it should be on a separate issue, thanks for the quick fix!

**Comment by vhyrro** [comment]
Ah interesting, thanks for the heads up! Wasn't aware that links are broken in e.g. presenter. I was aware however that the default value stuff is broken - that's mostly because we need to implement a pretty complex engine to convert big tables into digestable markdown. It may take a while before we get that fixed 😅

**Comment by vhyrro** [comment]
Welp, just a short message and a notice. The broken links in the presenter module will probably stay broken cause i think the markdown renderer in github is borked lol
