### ISSUE TITLE
Error and core dump after updating to 0.0.013

### ISSUE THREAD

**Issue by xfzv** [nvim-neorg/neorg#557]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.2

### Neorg setup

```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        -- ["core.norg.concealer"] = {
        --     config = {
        --         dim_code_blocks = {
        --             enabled = true,
        --             conceal = true,
        --             content_only = true,
        --              -- Will adapt based on the `conceallevel` option.
        --              -- If `conceallevel` > 0, then only the content will be dimmed,
        --              -- else the whole code block will be dimmed.
        --             adaptive = true,
        --         },
        --         icon_preset = "diamond",
        --     },
        -- },
    },
}
```

### Actual behavior

```sh
❯ nvim todo.norg

There's some new Neorg news for you!

New news for versions: 0.0.13

Run `:Neorg news new <version>` to see the latest news for that specific version.
To view news for all new versions run `:Neorg news new` without arguments.

Press ENTER or type command to continue
W18: Invalid character in group name
```

At this point, pressing "ENTER" again, even multiple times does nothing. After pressing `Ctrl+Z`, I'm getting:

```
nvim: /var/tmp/portage/app-editors/neovim-0.7.2/work/neovim-0.7.2/src/nvim/message.c:2352: msg_scroll_flush: Assertion `pos_delta >= 0' failed.
                                                 [1]    643615 IOT instruction (core dumped)  nvim todo.norg
```

### Expected behavior

No errors

### Steps to reproduce

1. Update to recent commits
2. With all other Neovim plugins disabled, try to open a blank `.norg file`
3. The Neorg news message is displayed
4. Press "ENTER" once, `W18: Invalid character in group name` is displayed
5. Try to press "ENTER" multiple times, nothing happens
6. Press `Ctrl+Z, the core dump error appears

### Potentially conflicting plugins

I disabled all my other plugins to make sure another one wasn't conflicting with Neorg.

### Help

No

Edit: I'm getting the same issue on my Arch Linux install with identical Neovim / Neorg config

**Comment by VPerrollaz** [comment]
It does look like 0.0.13 require neovim 0.8+ apparently?
I had to go back to 0.0.12 with neovim 0.7.2

**Comment by max397574** [comment]
yes

**Comment by xfzv** [comment]
> It does look like 0.0.13 require neovim 0.8+ apparently (looking at the README)? I had to go back to 0.0.12 with neovim 0.7.2

I went back to 0.0.12 as well, all good now.
