### ISSUE TITLE
Make Indentation More Intelligent

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorg/neorg#56]
I've realized that as I use Neorg a lot of times the indentation is simply off. I blame this indentation engine to be so bad because of the TS parser (that is still in very early stage). If the TS parser was good, the indentation engine would use that instead of regex. It works, but it could work better. I also think that adding `Control + <CR>` and `Alt + <CR>` for special types of indentation would also be pretty cool.

I will probably have to put the current implementation to sleep in a few days' time. It will be reimplemented from scratch and will support more advanced lookback and maybe even lookahead if necessary. The goal is for it to be fairly trivial to set up _any_ kind of new indent for Neorg. I hope I can implement this in the coming week :crossed_fingers:

**Comment by danymat** [comment]
Hey @vhyrro, Whats the current state of this issue ? I'm still noticing some indentations issues when doing `=G`

**Comment by vhyrro** [comment]
An update on the situation - the indent engine in `nvim-treesitter` is getting more and more features as we speak. If it becomes stable enough we could very well use that to create good Neorg indents (not to mention injected indentation would work too for code blocks!)

I'm excited to try it out in the near future :)

**Comment by vhyrro** [comment]
Didn't realize this was still here lol. Indentation is much better nowadays than it was before. Although still not perfect I'd say it warrants a close of this issue :p
