### ISSUE TITLE
Nested list icons

### ISSUE THREAD

**Issue by arensonzz** [nvim-neorg/neorg#569]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

When I use lists that have mixed nested parts it becomes hard to know which level I am looking at even with the indentation.
I think using slightly different symbols for each list level would improve the look.

### Help

No

**Comment by max397574** [comment]
do you have suggestions for icons?
if we find icons it's easily doable

**Comment by arensonzz** [comment]
•◇▪-→⇒
These are the icons Cherrytree note taking application uses. What are the constraints for icons in Neorg? Can we use any Unicode symbol?

**Comment by vhyrro** [comment]
Fonts are always a difficult thing. Too dynamic to make something look good everywhere :/

Some good news - these "weird" characters will stop being used as soon as anticonceal gets merged in Neovim. One day :smiling_face_with_tear:.

In the meantime I quite like the cherrytree icons to be honest! The diamond does overlap with the heading icon in the "diamonds" preset though, so some extra thought would be required in that department. Keep the suggestions for icons coming!

**Comment by vhyrro** [comment]
Ooh my bad, when I read this i thought we were talking about ordered lists specifically, but you're talking about lists in general. I'm open to the idea for sure.
