### ISSUE TITLE
gtd - such a command does not exist.

### ISSUE THREAD

**Issue by Isos9** [nvim-neorg/neorg#575]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

v0.7.0

### Neorg setup

```lua
require('neorg').setup {
	load = {
		['core.defaults'] = {},
		['core.gtd.base'] = {},
		['core.norg.dirman'] = {
			config = {
				workspaces = {
					work = '~/notes/work',
					home = '~/notes/home',
				},
			},
		},
	},
}
```

### Actual behavior

when I try to use a gtd related command, e.g. `:Neorg gtd views`, (after `:NeorgStart`)  I get the error message. 
```
:Neorg gtd gtd - such a command does not exist.
```

### Expected behavior

Show views of gtd

### Steps to reproduce

`:Neorgstart`
`:Neorg gtd views`

### Other information

First I started with core.defaults and dirman, and run `:NeorgStart`, seems like it installed the modules at this point, but after I added the gtd module and `:NeorgStart` again, nothing new seemed to be loaded

### Help

No

**Comment by Isos9** [comment]
Same issue with

```lua
require('neorg').setup {
	load = {
		['core.defaults'] = {},
		['core.gtd.base'] = { config = { workspace = 'gtd' } },
		['core.norg.dirman'] = {
			config = {
				workspaces = {
					work = '~/notes/work',
					home = '~/notes/home',
					gtd = '~/notes/gtd',
				},
			},
		},
	},
}
```

If I understood well the config you showed me

**Comment by rheajt** [comment]
I am having the same problem. I also do not have the command `:NeorgStart` as an option.

**Comment by rheajt** [comment]
My config is:
```
    --Neorg
    use({
        "nvim-neorg/neorg",
        -- tag = "*",
        -- ft = "norg",
        after = "nvim-treesitter", -- You may want to specify Telescope here as well
        run = ":Neorg sync-parsers",
        config = function()
            require("neorg").setup({
                load = {
                    ["core.defaults"] = {},
                    ["core.norg.dirman"] = {
                        config = {
                            workspaces = {
                                work = "~/notes/work",
                                home = "~/notes/home",
                                gtd = "~/notes/gtd",
                            },
                        },
                    },
                    ["core.gtd.base"] = {
                        config = {
                            workspace = "gtd",
                        },
                    },
                    ["core.integrations.telescope"] = {},
                },
            })
        end,
        requires = "nvim-neorg/neorg-telescope", -- Be sure to pull in the repo
    })
```

**Comment by danymat** [comment]
Hello everyone, is this issue still a problem in your config or everything is good now ? If not, please reach out here so I can take a look

**Comment by rheajt** [comment]
> Hello everyone, is this issue still a problem in your config or everything is good now ? If not, please reach out here so I can take a look

I think adding the `index.norg` to my gtd workspace worked. Thanks!

 I do still see :NeorgStart referenced in the wiki though.

https://github.com/nvim-neorg/neorg/wiki/Getting-Things-Done#overview
