### ISSUE TITLE
Tables and embeds aren't exported in markdown

### ISSUE THREAD

**Issue by JCapucho** [nvim-neorg/neorg#594]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.8.0-dev

### Neorg setup

```lua
require("neorg").setup({
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {},
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp",
            },
        },
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    work = "~/notes/work",
                    home = "~/notes/home",
                },
            },
        },
        ["core.gtd.base"] = {
            config = {
                workspace = "work",
            },
        },
        ["core.export"] = {},
        ["core.export.markdown"] = {
            config = {
                extensions = "all",
            }
        },
    },
})
```

### Actual behavior

When i try to export the following repro case:
```norg
@code python
@end

@table
Expr | value
-
1 + 2 * 5 |  11
@end

@embed image
./graph00.png
@end
```
And the try to convert it to markdown
```
:Neorg export to-file test.nd
```
I get a file with just:
````
```python
```
````

### Expected behavior

I expected to a get a file like
````
```python
```

| Expr | value |
| --- | --- |
| 1 + 2 * 5 |  11 |

![](./graph00.png)
````

### Steps to reproduce

Detailed in the actual behavior section

### Potentially conflicting plugins

None

### Other information

The problem with the table is related to the code block before it, removing it does export the table as is (it still needs to be transformed after that which isn't being done).

The embed seems to just not be supported.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I would be happy to implement the embed but I have questions with how the path should be handled, for example I have a setup where I export to a `build` directory so the path wouldn't point to the correct file if it was just copy pasted, a first version could obviously skip that for now.

I could also try to figure out why the code block affects the table being outputted, as for the table transformations I'm confused because the syntax from the help file seems to be different to that from the specification.

**Comment by max397574** [comment]
tables and embeds aren't implemented yet

**Comment by d-r-a-b** [comment]
The table and image syntaxes described here are no longer relevant with norg-spec 1.0. Can we close this issue?

**Comment by vhyrro** [comment]
Yep, post `1.0` quite a few bits have changed. Tables are still far from done, so it's not even worth thinking about export capabilities for those imo. Image syntaxes are yet to be entirely finalized, as the macro system is continually in-the-works.
