### ISSUE TITLE
Brackets on metadata aren't exported to markdown

### ISSUE THREAD

**Issue by ghaetinger** [nvim-neorg/neorg#598]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0-dev-1183-ge6c214033

### Neorg setup

```lua
require'neorg'.setup {
    load = {
        ['core.defaults'] = {},
        ['core.export'] = {},
        ['core.norg.completion'] = {
            config = {engine = 'nvim-cmp'}
        },
        ['core.export.markdown'] = {
            config = {extensions = {'metadata'}}
        }
    }
}
```

### Actual behavior

I'm trying to move away from my `orgmode` setup, which is very PDF/LaTeX oriented. Thus, I decided to try and use the markdown export + pandoc translation to `.tex` to see if I could create a decent looking documents. Markdown allows us to add arbitrary headers that once translated to `.tex`, would allow me to add packages and customize my final document.

However, if I have a very simple file such as:

```
@document.meta
title: Simple Title
header-includes: \usepackage[margin=.5in]{geometry}
@end

...
```

and I apply `:Neorg export to-file test.md`, I get this:

```markdown
---
title: Simple Title
header-includes: \usepackage
---

...
```

### Expected behavior

I'd expect the resulting markdown to be

```markdown
---
title: Simple Title
header-includes: \usepackage[margin=.5in]{geometry}
---

...

```

### Steps to reproduce

1. Create simple metadata tag with values containing `[` or `{`
2. Export to `.md`

**Comment by vhyrro** [comment]
Oh this is an error in the document metadata parser. I hope this is an easy fix 😳

**Comment by vhyrro** [comment]
This should now be fixed! Update your parsers with `:Neorg sync-parsers`, restart Neovim and try exporting again! :D

**Comment by ghaetinger** [comment]
I've just tried it out and it didn't seem to work. It is worth saying that the Treesitter parser seems to be failing at the start of `[`, as you can see from the "author" item below it and the quote marks around it.

![image](https://user-images.githubusercontent.com/23220288/194968115-2721f474-c953-438f-a205-d50fe9defe48.png)

**Comment by max397574** [comment]
are you sure you have norg_meta isntalled?

**Comment by ghaetinger** [comment]
> are you sure you have norg_meta isntalled?

Yup. 
![image](https://user-images.githubusercontent.com/23220288/195089971-513d2ba8-bfcd-4438-8fd8-db3a6d29b014.png)
 
Does it work for you guys? If so, I'll just assume it's on my end and reinstall my environment.

**Comment by vhyrro** [comment]
Oh, this is my bad! The Neorg plugin locks the revision for the parser and I didn't update it.

After these steps it should work now:
- Update Neorg
- Reenter Neovim
- Run `:Neorg sync-parsers`
- Reenter Neovim again
- Enjoy!

**Comment by vhyrro** [comment]
![image](https://user-images.githubusercontent.com/76052559/195145582-fb78a643-baa6-431a-b854-d64754e6ab0c.png)

Looks as intended now on my machine.

**Comment by ghaetinger** [comment]
Ayy it worked! Thanks! I can only use one latex package though, so in the future I might open an issue for multiline strings. It should be easy, but I have no need for it right now. Thank you very much, I really appreciate all the work being done on Neorg 😄
