### ISSUE TITLE
spell does not work in norg mode

### ISSUE THREAD

**Issue by dstadelm** [nvim-neorg/neorg#611]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0-1210-gd367ed9b2

### Neorg setup

```lua
require('neorg').setup {
}
```

### Actual behavior

when activating spell

```bash
:set spell! spelllang=en
```

no spelling checks are performed

### Expected behavior

highlight spelling mistakes

### Steps to reproduce

enable spell?

### Potentially conflicting plugins

I've tried it with nothing but neorg installed and spell does not work. As soon as neorg is uninstalled spell works

### Help

No

**Comment by dstadelm** [comment]
Might it have something to do with treesitter disabeling spell in code?

**Comment by jghauser** [comment]
Yeah, it might have to do with missing `@spell` in the `highlights.scm` (see this [neovim pr](https://github.com/neovim/neovim/pull/19419)).

**Comment by max397574** [comment]
yes that's the problem
feel free to open a pr

**Comment by vhyrro** [comment]
This should be now fixed in the latest commit! I named the commit wrongly but hey it works so that's what matters :p

If there are still any issues then feel free to reopen the issue.
