### ISSUE TITLE
Done and undone symbols are swapped in concealer module

### ISSUE THREAD

**Issue by greenspaceexplorer** [nvim-neorg/neorg#615]
### Prerequisites

- [x] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

v0.8.0-1210-gd367ed9b2

### Neorg setup

```lua
require('neorg').setup {
        load = {
                ["core.defaults"] = {},
                ["core.norg.completion"] = {
                        config = {
                                engine = 'nvim-cmp'
                        },
                },
                ["core.integrations.nvim-cmp"] = {},
                ["core.integrations.telescope"] = {},
                ["core.norg.concealer"] = {},
                ["core.norg.dirman"] = {
                        config = {
                                workspaces = {
                                        research = "~/iCloud/Research/Research_stow/Notes/Research", 
                                },
                                autochdir = true, -- Automatically change the directory to the current workspace's root every time
                                index = "index.norg", -- The name of the main (root) .norg file
                        }
                },
        }
}
```

### Actual behavior

The done and undone symbols are swapped in the concealer module.
<img width="377" alt="Screen Shot 2022-10-08 at 9 03 22 PM" src="https://user-images.githubusercontent.com/16415256/194732926-e9fcd603-155e-49e8-94ca-03505e9130c1.png">

### Expected behavior

`- [ ] incomplete`
`- [x] complete`

...not the other way around.

### Steps to reproduce

* Install concealer module
* Make a to-do list in any .norg file

### Help

Yes

**Comment by max397574** [comment]
this is expected
it looks like a font issue
the done tasks should display a tick

**Comment by greenspaceexplorer** [comment]
Was getting fooled by my terminal choice (Alacritty). Also, fooled by `U+00D7` being "incomplete" when `- [x]` is complete.  Changed to OSX terminal to see the following:

<img width="272" alt="Screen Shot 2022-10-09 at 11 12 40 AM" src="https://user-images.githubusercontent.com/16415256/194764895-5bd7f798-df51-424d-bc32-96eca2b25eda.png">

**Comment by max397574** [comment]
looks like your font is missing some symbols then
ig this issue can be closed?

**Comment by greenspaceexplorer** [comment]
Sure, since it's a different issue. Seems to be consistent across all of my fonts. I think I've seen some of the intended symbols in my use elsewhere (e.g. Julia editing and Packer loading). Will open another issue if it turns out to be a collision in my neovim configuration and not something with my system.

**Comment by greenspaceexplorer** [comment]
Yup, confusion was: default icon choice preference different from what I expected + dependency on non-standard icons in fonts. Already covered in #59 and #535. Maybe put [nerd fonts](https://github.com/ryanoasis/nerd-fonts) dependency in [concealer](https://github.com/nvim-neorg/neorg/wiki/Concealer) wiki?
