### ISSUE TITLE
Parsers are downloaded and installed every time I open a norg file

### ISSUE THREAD

**Issue by oblitzitate** [nvim-neorg/neorg#620]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-47-gcfdb4cbad

### Neorg setup

My `lang.neorg` module:

```fennel
(local neorg (require :neorg))

(neorg.setup 
  {:configure_parsers true
   :load
    {"core.defaults" {}
     "core.norg.concealer" {}
     "core.norg.dirman" 
       {:config 
          {:workspaces 
            {:my_workspace "~/neorg"}}}}})
```

### Actual behavior

Any time I open a norg file, it will always download and install `norg` and `norg_meta` parsers. This will freeze the UI until it's finished installing.

The following messages are shown every time:
```
Downloading tree-sitter-norg...                                                                                                                                                                               
Creating temporary directory                                                                                                                                                                                  
Extracting tree-sitter-norg...                                                                                                                                                                                
Compiling...                                                                                                                                                                                                  
Treesitter parser for norg has been installed                                                                                                                                                                 
Downloading tree-sitter-norg_meta...                                                                                                                                                                          
Creating temporary directory                                                                                                                                                                                  
Extracting tree-sitter-norg_meta...                                                                                                                                                                           
Compiling...                                                                                                                                                                                                  
Treesitter parser for norg_meta has been installed 
```

### Expected behavior

I expected it to only download and install the parsers once.

### Steps to reproduce

I use the following packer config for neorg:

```fennel
   ["nvim-neorg/neorg"
    {:requires ["nvim-lua/plenary.nvim"
                "nvim-treesitter/nvim-treesitter"]
     ;:ft "norg"
     :after "nvim-treesitter"
     :config #(require :lang.neorg)}]
```

**Comment by vhyrro** [comment]
Hey, could you update Neorg to the latest version and try again please? At the cost of some performance I made the check much more reliable :)

**Comment by oblitzitate** [comment]
It's not bothering me with the downloading and installing of the parsers anymore on file open, but I have to run `:Neorg sync-parsers` in order to properly color highlight the syntax (e.g. heading color, priority checkbox background color). Maybe it's not permanently installing correctly?

Also the warning/error message `[null-ls] failed to attach buffer 1` shows up twice in a norg file compared to other filetypes where it only shows up once. I'm still looking for a way to fix it so that the message doesn't show up at all, but it's weird that it shows up twice in a norg file compared to once only.

**Comment by umiswing** [comment]
I have the same problem with the latest stable version of neorg and nvim v0.8.0-1210-gd367ed9b2. Following is the packer config:
```shell
use {
	"nvim-neorg/neorg",
	tag = "*",
	-- ft = "norg",
	after = "nvim-treesitter", 
	run = ":Neorg sync-parsers", 
	config = function()
		require('neorg').setup {
			load = {
				["core.defaults"] = {},
				["core.norg.dirman"] = {
					config = {
						workspaces = {
							plan = "~/neorg/plan"
						}
					}
				}
			}
		}
	end
}

```
Do you find anyway to fix this?

**Comment by vhyrro** [comment]
I'll be taking a look at this again soon-ish. It's weird to me that this problem exists at all, as Neorg's using the native `vim.treesitter.get_parser` API to find whether or not the treesitter parser exists. If *that* doesn't work then I don't know what would 🤷

**Comment by katawful** [comment]
For `external.helpers.get_language_list()`, I used `vim.api,nvim_get_runtime_file` to directly see if the parser binary exists

The built in way to check for it never seemed to always behave weirdly

**Comment by vhyrro** [comment]
Okay, switched to using `get_runtime_file` instead. Thanks for the info @katawful! Could you lot update and see if the problem is gone please?

**Comment by oblitzitate** [comment]
This seems to have been fixed for me. Thanks!
