### ISSUE TITLE
Error because of unsatisfied core.integrations.treesitter dependency

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#622]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0

### Neorg setup

```
require("neorg").setup({
  load = {
    ["core.defaults"] = {}, -- Load all the default modules
    ["core.integrations.treesitter"] = {},
    ["core.norg.esupports.indent"] = {
      config = {
        tweaks = {
          heading2 = 1,
          heading3 = 2,
          heading4 = 3,
          heading5 = 4,
          heading6 = 5,
          unordered_list2 = 1,
          unordered_list3 = 2,
          unordered_list4 = 3,
          unordered_list5 = 4,
          unordered_list6 = 5,
          unordered_list7 = 6,
          ordered_list2 = 1,
          ordered_list3 = 2,
          ordered_list4 = 3,
          ordered_list5 = 4,
          ordered_list6 = 5,
          ordered_list7 = 6,
          todo_item2 = 1,
          todo_item3 = 2,
          todo_item4 = 3,
          todo_item5 = 4,
          todo_item6 = 5,
          todo_item7 = 6,
        },
      },
    },
  },
})
```

### Actual behavior

Often but not always I get the following error on startup (I don't think it actually affects anything).

```
[neorg] (19:24:57)
...re/nvim/site/pack/packer/opt/neorg/lua/neorg/modules.lua:111
Unable to load module core.norg.esupports.indent, wanted dependency core.integrations.treesitter was not satisfied. Be sure to load the module and its appropriate config too!

[neorg] (19:24:57)
...ocal/share/nvim/site/pack/packer/opt/neorg/lua/neorg.lua:99
Recovering from error...
```

### Expected behavior

No error.

### Steps to reproduce

Now that lazy-loading isn't a thing anymore, it's enough to just open neovim a few times ;). As it seems to be some race condition, it doesn't happen always, but on my system and with the above config, it happens roughly 50% of the time.

### Other information

This has been happening for a long time, but I've mostly ignored it (also because there was some PR to manage module precedence). Now that Neorg loads not just with `.norg` files, it's gotten a bit out of hand and I've finally written the bug report. :)

I also noticed the issue form is a bit out of date (it asks whether I'm using neovim 0.7 instead of 0.8).

Also, congrats on all the recent changes! Neorg has really come a long way! Thanks!

**Comment by vhyrro** [comment]
Hi, should be fixed now after the latest update! Check it out :)

Also thank you! Yeah we really have come a long way, it's been a really fun journey and there's still so much left to do. The form isn't broken btw, it asks whether you're on 0.7 with the `0.0.12` tag *or* on the latest version of Neovim. It's a bit weirdly worded but hey it gets the job done :p

**Comment by jghauser** [comment]
Works perfectly, thanks! And yeah, I skimmed over that a little too quickly... ;)
