### ISSUE TITLE
Tune autoindentation behavior

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/neorg#624]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I open this topic first in the discussions #614, but have no responses. So, I assume, that this does not implemented yet, and open a feature request. Copy it here.

I like to structure definitions in a way similar as Vim documentation do:

```
* Head 1
** Head 2

   $$ Definition
                               Multiline descripton: Lorem ipsum dolor sit amet,
                               officia officia excepteur ex fugiat reprehenderit
                               enim labore culpa sint ad nisi Lorem pariatur
                               mollit ex esse exercitation amet. Nisi anim
                               cupidatat excepteur officia.
                               $$
```

But on every Enter press or if a enter insert mode anywhere inside indented line, when I press Esc, the line jump to posotion under Head level:

```
* Head 1
** Head 2

   $$ Definition
   Multiline descripton: Lorem ipsum dolor sit amet,
   officia officia excepteur ex fugiat reprehenderit
   enim labore culpa sint ad nisi Lorem pariatur
   mollit ex esse exercitation amet. Nisi anim
   cupidatat excepteur officia.
   $$
```

Since Neorg is indentation agnostic, is it possible to tune the autocommands behavior the next way: check the structure level and if it less than the threshold, shift the line to the right. But if indentation level is bigger than the threshold --- do nothing.

### Help

No

**Comment by vhyrro** [comment]
Took me a while to get around to this feature, but it's now implemented as part of `5.0.0`! Set the `dedent_excess` option in `core.esupports.indent` to `false` to get the behaviour you want :)
