### ISSUE TITLE
Code Blocks background is not working

### ISSUE THREAD

**Issue by TheSafdarAwan** [nvim-neorg/neorg#628]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

 NVIM v0.8.0-dev-1112-g6d557e324

### Neorg setup

require("neorg").setup({
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {
             dim_code_blocks = {
                    enabled = true,
                    content_only = true,
                    width = "content",
                    padding = {
                        left = 0,
                        right = 5,
                    },
                    conceal = false,
                },
        },
    }
})

### Actual behavior

Today suddenly code blocks background is not working i have 
setup the `["core.norg.concealer"]` module but it does not seems to work

### Expected behavior

`  

### Steps to reproduce

`     

### Potentially conflicting plugins

`

### Other information

`   

### Help

No

### Implementation help

`

**Comment by vhyrro** [comment]
With the whole concealer rewrite that happened 5 days ago and the fixes to highlights not being applied this has been fixed, closing!
