### ISSUE TITLE
Validate toc status

### ISSUE THREAD

**Issue by TheSafdarAwan** [nvim-neorg/neorg#629]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

It's not kind of a feature because i have a suggestion to improve the existing feature.

The thing is when we use the `["core.norg.qol.toc"]` module we get the options of `:Neorg toc split|inline` but if we open it with the `split` option then we can delete the buffer by `bd` command. If we do that actually `Neorg` does not recognize that the buffer has been deleted. And if we again do the `Neorg toc split` then it gives us error that the toc is already active.
So I came with an idea which you developers of the **neorg** can improve or completely write you own solution to the problem but this is my idea.

I am new to `lua` and `vim` in general so i didn't know how to do thing's properly but through some google searches and reading `vim.api` documentations i came to this this logic which checks if the buffer with the name `neorg://norg/Neorg Toc.norg` exists or not if yes then don't  execute the `Neorg toc split`(or actually we can say switch to it's split if already active but not in focus).
And by the way i couldn't find how you were implementing the `inline` toc viewer. I tried to look into the source code but i was confused. so maybe you can help me by directing me where you implemented it.
```lua
function ValidateNeorgTocStatus(command)
    local buffers = {}
    for buf = 1, vim.fn.bufnr("$") do
        local buffer = vim.fn.bufname(buf)
        table.insert(buffers, buffer)
    end
    for _, buf in pairs(buffers) do
        if buf == "neorg://norg/Neorg Toc.norg" then
            api.nvim_command(command)
        end
    end
end
vim.api.nvim_set_keymap("n", "gts", ":lua NeorgMappingsHelper('Neorg toc split')<CR>", { noremap = true, silent = true })
```
I know 

### Help

No

### Implementation help

I am new to lua. So i cant be a bit of help but i will try if you guide me where to look for in order to implement this feature. :)

**Comment by vhyrro** [comment]
With the somewhat recent rewrite of the TOC module this issue has been fixed! Closing :)
