### ISSUE TITLE
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node _text

### ISSUE THREAD

**Issue by TheSafdarAwan** [nvim-neorg/neorg#630]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0-dev-1112-g6d557e324

### Neorg setup

if i require the `["core.norg.concealer"]` module i get the error that
```
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node _text
```
treesitter is now using the nvim core options so there is a need to update the `["core.norg.concealer"]` config for `nvim-treesitter.ts_utils.get_node_text ` to `vim.treesitter.query.get_node _text`

### Actual behavior

`

### Expected behavior

`

### Steps to reproduce

`

### Potentially conflicting plugins

`

### Other information

`

### Help

No

### Implementation help

`

**Comment by vhyrro** [comment]
The issue was with a very old implementation of the `__` horizontal rule. I don't use those a lot which is why I didn't catch the bug :p

Please reopen if something's still broken!
