### ISSUE TITLE
GTD Project view only detects with tasks with `time`/`waiting.for` attributes

### ISSUE THREAD

**Issue by LoipesMas** [nvim-neorg/neorg#631]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0

### Neorg setup

```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.keybinds"] = {
            config = {
                neorg_leader = "<Space>",
            },
        },
        ["core.norg.concealer"] = {},
        ["core.norg.completion"] = {
            config = { engine="nvim-cmp" }
        },
        ["core.integrations.nvim-cmp"] = {},
        ["core.gtd.base"] = {
            config = {
                workspace = "gtd",
            }
        },
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    misc = "~/neorg/misc",
                    gtd = "~/neorg/gtd",
                }
            }
        },
    ["core.integrations.telescope"] = {},
    }
}

```

### Actual behavior

GTD Project view only detects tasks that have an attribute (such as `#time.start` or `#waiting.for`, but not `#context`). It ignores the rest.
For example if you have: 
```
- [ ] Task A
* Project Foo
  - [ ] Task B
  #waiting.for godot
  - [ ] Task C
```
then project view (`<Localleader>tv p`) will only detect `Task C`, and it will show `Project Foo (0/1 done)`.
(However the "all tasks" view will correctly detect all three tasks (but B and C are "unclarified") 

### Expected behavior

GTD Project view detects all tasks in a project

### Steps to reproduce

Create a project with tasks that don't have any attributes
Open project view
See that your project has 0 tasks and is "unclarified"

### Other information

Adding the attribute to the project makes all the tasks in the project detectable (which is what I will be doing as a workaround for the time being)
And, as I mentioned, `#context` attribute does nothing here

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I would gladly help out, but I just started using neorg, so I have no idea how things work internally.

**Comment by danymat** [comment]
Hello, thank you for submissing for issue. I'm closing it, for reference: https://github.com/nvim-neorg/neorg/issues/695
