### ISSUE TITLE
Consecutive projects on same level with attributes are counted as sub-projects

### ISSUE THREAD

**Issue by LoipesMas** [nvim-neorg/neorg#632]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM 0.8.0

### Neorg setup

```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.keybinds"] = {
            config = {
                neorg_leader = "<Space>",
            },
        },
        ["core.norg.concealer"] = {},
        ["core.norg.completion"] = {
            config = { engine="nvim-cmp" }
        },
        ["core.integrations.nvim-cmp"] = {},
        ["core.gtd.base"] = {
            config = {
                workspace = "gtd",
            }
        },
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    misc = "~/neorg/misc",
                    gtd = "~/neorg/gtd",
                }
            }
        },
    ["core.integrations.telescope"] = {},
    }
}
```

### Actual behavior

Projects are counted to the previous project
![image](https://user-images.githubusercontent.com/46327403/196056757-16bcd49d-1a18-41a3-b0bb-3fc2297455b0.png)
(Note the task counts on each project)

### Expected behavior

Projects are counted separately

### Steps to reproduce

```
* Project Foo
  - [ ] task A


  #context home
* Project Bar
  - [x] task B

  #time.start 2020-02-20
* Project Baz
  - [ ] task C
```

### Other information

On "project" view it works as expected.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

Again, I don't even know what module is responsible for this text ;/

**Comment by d-r-a-b** [comment]
Hi there! Just a community member going through the old issues. It looks like this refers to features of the GTD module which was dropped recently. Would you mind closing this issue?

#695 provides rationale for the change and a plan for moving forward as the devs/contributers make sure to get things *right* before committing the community in a bad direction at this alpha stage. Lists and TODOs still work great and there is really cool work going on right now to advance the macro system, so there's lots of exciting stuff down the pipeline!

**Comment by LoipesMas** [comment]
Thanks for the info @d-r-a-b 
Closing this then
