### ISSUE TITLE
First header not highlighted

### ISSUE THREAD

**Issue by ignamartinoli** [nvim-neorg/neorg#636]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0

### Neorg setup

```lua
use {
	'nvim-neorg/neorg',
	after = 'nvim-treesitter',
	config = function ()
		vim.cmd [[PackerLoad LuaSnip]]
		vim.cmd [[PackerLoad lspkind-nvim]]
		vim.cmd [[PackerLoad nvim-autopairs]]
		vim.cmd [[PackerLoad nvim-cmp]]
		vim.cmd [[PackerLoad nvim-treesitter]]
		vim.cmd [[PackerLoad TrueZen.nvim]]

		require 'neorg'.setup {
			load = {
				['core.defaults'] = {},
				['core.norg.completion'] = {
					config = { engine = 'nvim-cmp' }
				},
				['core.norg.concealer'] = {},
				['core.presenter'] = {
					config = { zen_mode = 'truezen' }
				}
			}
		}
	end,
	ft = 'norg',
	requires = {
		'nvim-lua/plenary.nvim',
		{
			'Pocco81/TrueZen.nvim',
			config = function ()
				require 'true-zen'.setup {
					integrations = {
						kitty = { enabled = true },
						lualine = true
					}
				}
			end,
			opt = true
		}
	}
}
```

### Actual behavior

The first header isn't highlighted.

### Expected behavior

The first header highlighted as shown in the example.

### Steps to reproduce

Mentioned above.

### Potentially conflicting plugins

- [`catppuccin/nvim`](https://github.com/catppuccin/nvim)

### Other information

![20221019214219](https://user-images.githubusercontent.com/103866722/196830199-8c1921b5-5baa-441f-8e77-dbc143fb33ab.png)

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I'm not familiar with the code-base.

**Comment by igorlfs** [comment]
I'm also having this issue, using catppuccin too. Notice other odd-level headers are also not being highlighted, as well as math mode:
![image](https://user-images.githubusercontent.com/84649544/197243623-a227b253-7de2-4581-83d9-2dad23f0ca79.png)

**Comment by max397574** [comment]
is the `@attribute` highlight group defined?

**Comment by vhyrro** [comment]
This seems to be a catppuccin issue - they are omitting a lot of highlight definitions, including `@attribute`. That's why a lot of things just appear blank :(

Perhaps try making an issue on their repo so they're aware?

**Comment by katawful** [comment]
nvim-treesitter removed all `TSGroup` hl-groups a few days ago, many color schemes have not updated with this in mind. Try nvim-treesitter before this breakage

**Comment by vhyrro** [comment]
From what I can see they fixed that here: https://github.com/catppuccin/nvim/commit/c9c272f8f53968473873478591bfb4f5c1418370. They just don't support all highlight groups.

**Comment by max397574** [comment]
reference for highlight groups
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights
(notice that not all of them are used rn)

**Comment by ignamartinoli** [comment]
So, should I open an _Issue_ on `catppuccin/nvim`?

**Comment by max397574** [comment]
yes

**Comment by ignamartinoli** [comment]
Please, leave this issue opened until the **Catppuccin** Team doesn't fix the problem, so that other users who have this problem can easily keep track on when the solution is delivered.

**Comment by ignamartinoli** [comment]
The _Issue_ was solved on [`catppuccin/nvim`](https://github.com/catppuccin/nvim)'s end and I can confirm it

**Comment by stephenprater** [comment]
I know this is closed, but I'm not sure this _is_ a catppuccin problem.  `@attribute` is not a "base" Highlight Group (see `:help group-name`) so you can't _really_ count on it being defined.  Neorg should probably set a base highlight group that's guaranteed to exist.
