### ISSUE TITLE
Markup problems

### ISSUE THREAD

**Issue by Srinath-Anand** [nvim-neorg/neorg#644]
OS: Linux
Neovim version: 0.8 (stable)
Terminal Emulator: WezTerm

I can't get bold, italic, underline to render at all
They work well in Markdown files, but not in Norg files

For eg, *something* looks like /something/ -  just adds '/' to the end and beginning of the word something - it doesn't render it using italics.

**Comment by NTBBloodbath** [comment]
Is your `conceallevel` option set to `2`? It should be working for you.

You can check what your `conceallevel` value is by using `:set conceallevel?`.

**Comment by Srinath-Anand** [comment]
Yes, `conceallevel` is set to 2.
![2022-10-27-093204_1920x1080_scrot](https://user-images.githubusercontent.com/71964994/198188359-93fbb620-9343-4c16-bd61-6bdeb9de6ebe.png)

**Comment by max397574** [comment]
could you sent the output of treesitter playground?

**Comment by Srinath-Anand** [comment]
![2022-10-27-100327_1920x1080_scrot](https://user-images.githubusercontent.com/71964994/198192164-d2f7956f-8286-48bd-be7e-526b719f47d4.png)

**Comment by Srinath-Anand** [comment]
**Note: I solved the problem:**

I added 
```lua
require('nvim-treesitter.configs').setup{
	ensure_installed = {'norg'},
	highlight = {
		enable = true,
	}
}
``` 
to my treesitter configuration file .

![2022-10-27-115813_1920x1080_scrot](https://user-images.githubusercontent.com/71964994/198208169-9cd3b0b8-920e-4bc4-87e1-2150b28c0ac1.png)

So does that mean the tree-sitter parser wasn't installed properly?
I tried `:TSInstall norg` and `:TSInstall norg_meta` and those parsers were already installed 🤷🏻

**Comment by Srinath-Anand** [comment]
Thanks @NTBBloodbath  and @max397574 !

**Comment by max397574** [comment]
but you still don't have conceals?

**Comment by Srinath-Anand** [comment]
I don't understand
What was I expected to get ?

**Comment by max397574** [comment]
no it's not what I mean

**Comment by max397574** [comment]
![Screenshot 2022-10-27 at 11 56 41](https://user-images.githubusercontent.com/81827001/198254279-735aa5e3-cc4b-40d6-881f-0d6dea422673.png)
as you can see the `/`, `*` etc are hidden

**Comment by Srinath-Anand** [comment]
No
I am not able to get them working 😭

**Comment by MPWrobel** [comment]
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/20567620/199848991-10491315-bb54-4120-9fac-5fef99de76ed.png">
I am having the same issue on macOS using iTerm. Bold and italic work in markdown files just fine. The aforementioned solution doesn't help

**Comment by max397574** [comment]
`:hi @neorg.markup.bold` and `:hi @neorg.markup.italic` ?

**Comment by Srinath-Anand** [comment]
Do you have the treesitter parser installed?

**Comment by MPWrobel** [comment]
@max397574 
`@neorg.markup.bold xxx links to @text.strong`
`@neorg.markup.italic xxx links to @text.emphasis`

@Srinath-Anand Yes, I do

**Comment by max397574** [comment]
and how do the highlight groups look?
are the bold/italic?
if not
it's a colorscheme issue
you could change the highlights yourself

**Comment by MPWrobel** [comment]
@max397574 You're right, it's a colorscheme issue. Thanks a lot!

**Comment by jneidel** [comment]
> @max397574 `@neorg.markup.bold xxx links to @text.strong` `@neorg.markup.italic xxx links to @text.emphasis`

In my case it was also a colorscheme issue and I solved it by mapping `@text.strong` and `@text.emphasis` to bold/italic functionality. [see my colorscheme](https://github.com/jneidel/dotfiles/blob/62bccfc1b19658a606c2c9e636e4b338193f4e24/.config/nvim/colors/old-hope.vim#L168)
