### ISSUE TITLE
No filetype in presenter buffer

### ISSUE THREAD

**Issue by Sup3Legacy** [nvim-neorg/neorg#645]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0 Build type: Release LuaJIT 2.1.0-beta3

### Neorg setup

```
require('neorg').setup({
    load = {
        ["core.defaults"] = {},
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    home = "~/Nextcloud/Notes",
                },
                default_workspace = "home",
                autochdir = true,
            }
        },
        ["core.highlights"] = {},
        ["core.gtd.base"] = {
            config = {
                workspace = "home"
            }
        },
        ["core.norg.journal"] = {},
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp"
            }
        },
        ["core.presenter"] = {
            config = {
                zen_mode = "zen-mode"
            }
        },
        ["core.ui"] = {},
        ["core.queries.native"] = {},
    }
}
```

### Actual behavior

When executing the command `:Neorg presenter start`, the presentation starts but with highlighting disabled. Turns out the `filetype` is not set anymore, while it was working correctly before the command.

### Expected behavior

Correctly highlighted `presenter` buffer.

### Steps to reproduce

```
:Neorg workspace [something]<CR>
:e [anyfile].norg<CR>
:Neorg presenter start
```

### Other information

Thank you for this amazing tool! Another suggestion: add a wiki entry discussing colorscheme compatibility. I was using [neovim-ayu](https://github.com/Shatur/neovim-ayu) and spent a lot of time trying to investigate my issues with highlighting only to discover this scheme doesn't support all required groups! Maybe list a few colorschemes that are known to work.

Maybe such an entry already exists but I couldn't find it. 

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

If this issue really originates from a bug in the source, I could help fixing it.

**Comment by TornaxO7** [comment]
This can be closed now @vhyrro it refers to the same issue which I created :P https://github.com/nvim-neorg/neorg/issues/670

**Comment by vhyrro** [comment]
Ah true, thanks :)
