### ISSUE TITLE
Expose generate_display in the GTD UI module

### ISSUE THREAD

**Issue by stickperson** [nvim-neorg/neorg#650]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

It would be great to expose `generate_display` from `core.gtd.ui` as a public function. This would enable users to filter tasks as they wish and display the results in a consistent manner. For example, the `core.gtd.queries` module has a `sort_by` function which supports sorting by `status`. Even if a user wants to use that, there's currently no easy way to pipe those tasks into the same built-in display.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I looked through the code briefly. It looks like it's not quite as simple as moving the function from `private` to `public` because there are calls to other private methods/variables. I'm not aware of the implications of making _everything_ public.

**Comment by danymat** [comment]
For reference: https://github.com/nvim-neorg/neorg/issues/695.
