### ISSUE TITLE
Keep checkboxes with core.itero

### ISSUE THREAD

**Issue by JacobusH** [nvim-neorg/neorg#663]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Thanks so much for the core.itero module! It makes working with neorg much smoother. 

One extra thing I would ask is for checkboxes to be maintained in the lists. 

Current behaviour:
```
- [x]  (press <M-RET>)
-
```

Expected behaviour:
```
- [x] (press <M-RET>)
- [ ]
```

If you are ok with it working like this I will see about submitting a PR this weekend.

### Help

Yes

### Implementation help

Just a review of the code and suggestions if it is not the way you want it written. 
I have already hacked together some extra functionality for my own use cases.

**Comment by vhyrro** [comment]
Hey, now with the new syntax out of the question I was finally free to implement it!

**Comment by JacobusH** [comment]
Oh awesome thank you!
