### ISSUE TITLE
Closing bracket in code is marked red

### ISSUE THREAD

**Issue by roland-5** [nvim-neorg/neorg#667]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-5e1687e-dirty

### Neorg setup
```
  use {
    "nvim-neorg/neorg",
    run = ":Neorg sync-parsers", -- This is the important bit!
    config = function()
        require("neorg").setup {
	    -- Tell Neorg what modules to load
    load = {
        ["core.defaults"] = {}, -- Load all the default modules
	["core.gtd.base"] = {
            config = {
                -- workspace =   "example_gtd" , -- assign the workspace,
                workspace = "dokumenty",
                exclude = { "notatki/" }, -- Optional: all excluded files from the workspace are not part of the gtd workflow
                projects = {
                show_completed_projects = true,
                show_projects_without_tasks = true,
                },
                custom_tag_completion = true,
            },
	    inbox = "inbox.norg",
        },
	["core.keybinds"] = {
            config = {
                default_keybinds = true,
            }
        },
	["core.norg.dirman"] = {
            config = {
                workspaces = {
                    dokumenty = "~/Dokumenty/neorg",
                }
	    }
        },
        ["core.norg.concealer"] = {}, -- Allows for use of icons
	["core.norg.concealer"] = {
            config = {
                width = "content"
                }
            },
	["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp"
                }
            },
	["core.norg.journal"] = {}
    },
        }
    vim.api.nvim_set_hl(0, "@neorg.tags.ranged_verbatim.code_block", {bg="#504945"})
    end,
  }
```
### Actual behavior

![ps_20221120133007](https://user-images.githubusercontent.com/44477799/202908710-fb134d9c-1ff7-40c1-8abf-fee0713e54a0.png)

### Expected behavior

Not red?

### Steps to reproduce

I just copied raw neorg.norg from repository to file on my computer and I think previously it was normal.

### Help

No

**Comment by max397574** [comment]
I'm quite sure this is a treesitter thing
all the highlighting inside the codeblock is done with treesitter injections
perhaps you could look at the treesitter playground?

**Comment by roland-rollo** [comment]
I'm note sure how to use it correctly. I installed `playground` and copied defaults from readme. This is what it show for this
![ps_20230204172732](https://user-images.githubusercontent.com/44477799/216778702-af7e1e05-fc52-4d96-9188-d4cbe59945bb.png)

**Comment by vhyrro** [comment]
This stems from the first generation `tree-sitter-norg` parser not understanding standard ranged tag boundaries properly and descending into madness a few lines later. To prevent clutter I'll close this issue, because a lot of these problems stem from the same soil - many of these sorts of parser bugs will be fixed after `tree-sitter-norg2` becomes the mainline parser :)
