### ISSUE TITLE
Error running config for neorg: ...er/start/neorg/lua/neorg/modules/core /storage/module.lua:44: incomplete msgpack string

### ISSUE THREAD

**Issue by Namefailed** [nvim-neorg/neorg#680]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

0.7

### Neorg setup

```
      { "nvim-neorg/neorg", -- Neorg "org-like" mode for neovim inspired by emacs org-mode
        config = function() require("neorg").setup {
            load = { -- Tell Neorg what modules to load
              ["core.defaults"] = {}, -- Load all the default modules
              -- ["core.norg.concealer"] = {}, -- Allows use of icons for headlines and checkboxes
              ["core.norg.journal"] = {
                config = { -- Configure the journal module
                  journal_folder = "/home/grey/dir/neorg/journal", -- Set the journal directory
                },
              },
              ["core.norg.completion"] = { -- Allows the use of completion
                config = {
                  engine = "nvim-cmp", -- Set the engine to use for completion
                },
              },
              ["core.norg.dirman"] = { -- Manage your neorg directories
                config = {
                  workspaces = { -- Set workspace locations
                    development = "/home/grey/dir/neorg/development", -- Set the development workspace
                    todo = "/home/grey/dir/neorg/todo", -- Set gtd todo workspace
                  },
                },
              },
              ["core.gtd.base"] = { -- GTD (todo) module
                config = {
                  workspace = "todo", -- Set the default workspace
                },
              },
            },
          }
        end,
      },
```

### Actual behavior

Error message when starting

 ERROR packer.nvim: Error running config for neorg: ...er/start/neorg/lua/neorg/modules/core
/storage/module.lua:44: incomplete msgpack string

Neorg commands not functioning

### Expected behavior

No error messages when starting and Neorg commands functioning properly

### Steps to reproduce

- Install neorg on stable nvim via packer.
- Start up

### Potentially conflicting plugins

I've added no plugins since it worked last, and not modified my config apart from comments.

### Other information

 ERROR packer.nvim: Error running config for neorg: ...er/start/neorg/lua/neorg/modules/core
/storage/module.lua:44: incomplete msgpack string

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

Where to start looking.

**Comment by Namefailed** [comment]
Error happens with and without my own config options enabled.

I've tried uninstalling and reinstalling the plugin through packer.

**Comment by Namefailed** [comment]
Closing the issue. Got help in discord. rm ~/.local/share/nvim/neorg.mpack

**Comment by HalibutGitWiz** [comment]
I got this exact error with Neovim 0.9.4 and Neorg 6.2.0 (except it was now on line 45 of `core/storage/module.lua` instead of line 44).

The solution above worked, but the file was located in `~/.config/local/share/nvim/neorg.mpack` and not `~/.local/share/nvim/neorg.mpack`.

**Comment by benatouba** [comment]
Bumping this because I had the same error neorg 8.2.1 (line 45)  and nvim 0.10 and it helped me solve it.
