### ISSUE TITLE
Missing syntax highlight in all neorg files

### ISSUE THREAD

**Issue by shofel** [nvim-neorg/neorg#682]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev Build type: Release LuaJIT 2.1.0-beta3 Compiled by nixbld  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /nix/store/d4rj6nw6hd1fk944z1r32z1pfd72l1l4-neovim-unwrapped-master/share/nvim "  Run :checkhealth for more info

### Neorg setup

``` fnl
 {:config (call-setup :neorg {:load {:core.defaults {}
                                      :core.norg.dirman {:config {:workspaces {:knowledge "~/10-19-Computer/14-Notes"
                                                                               :gtd "~/10-19-Computer/15-GTD"}}}
                                      :core.gtd.base {:config {:workspace :gtd}}}})
```

### Actual behavior

The text is not highlighted

### Expected behavior

A proper syntax highlighting

### Steps to reproduce

Open any norg file

### Potentially conflicting plugins

catppuccin

### Other information

- `:TSPlayground` shows a proper ast, but `:TSCaptureUnderCursor` shows `no highlight groups found`.

- `:filter Neorg hi` outputs nothing

![image](https://user-images.githubusercontent.com/1355255/204094520-b035097c-5176-4bff-af49-1c75d7e60292.png)

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by vhyrro** [comment]
Hey, do you get any sort of errors in `:messages` when you start Neovim in a `.norg` file? Also, are you using a colourscheme that officially supports Treesitter highlight groups?

**Comment by shofel** [comment]
Yes, the colorscheme is [catppuccin](https://github.com/catppuccin/nvim), and it officially supports treesitter.

And on the screenshot the TS Playground is properly highlighted.

**Comment by shofel** [comment]
I updated everything again (plugins and neovim), and it works now :tada: 

And now I can not find what and when was broken :shrug:

**Comment by shofel** [comment]
@bangedorrunt It makes sense. What kind of rework do you mean? What I can come up with is:
- reduce number of plugins
- specify `:after` for more plugins

**Comment by shofel** [comment]
Ok, I see. More lazy loading triggered by an event, and less plugin-ordering. Thank for the useful input :heart:
