### ISSUE TITLE
File linkables do not open ("Link not found")

### ISSUE THREAD

**Issue by svenXY** [nvim-neorg/neorg#688]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-1583+gf1b88ced0-dirty

### Neorg setup
```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        --[[ ["core.keybinds"] = {}, ]]
        ["core.norg.concealer"] = {}, -- Allows for use of icons
        ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
                workspaces = {
                    private = "~/neorg/private",
                    wac = "~/neorg/dm/wac",
                },
                autodetect = true,
                autochdir = true,
            }
        },
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp"
            }
        }
    }
}
```

### Actual behavior

 ` - [test]{:testme:}`in index.norg should - to my understanding - open the file testme.norg in the same directory, but pressing `<CR>` opens the "Link not found" dialog instead (where any attempt at pressing 'f' to fix it fails with another error, but that's a different thing)

Links within the same file and URLs work fine, though `[filesystem]{/ /Users/me/a_file.txt}` also doesn't (Link not found...)

## summary:
```
* level1
  - [test]{:testme:}                                 # does not work while ./testme.norg exists
  - [internal]{# level1}                            # works
  - [external_file]{/ /Users/me/bla.lua} # does not work
  - [github]{https://www.web.de}         # works

```

### Expected behavior

it should open the file testme.norg as well es the non-norg file

### Steps to reproduce

see neorg file content above

### Help

No

**Comment by vhyrro** [comment]
Hey, this should now be fixed! Sorry for taking a while, a lot of issues seemed to have gone under the radar.

If there are any further bugs related to this then feel free to reopen!
