### ISSUE TITLE
readd highlight groups for todo item status

### ISSUE THREAD

**Issue by max397574** [nvim-neorg/neorg#697]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

![Screenshot 2022-12-25 at 18 41 46](https://user-images.githubusercontent.com/81827001/209477402-5cf12b2b-35a6-4176-be76-93f29297100b.png)
read title

### Help

No

**Comment by danymat** [comment]
Seems to work, but if we follow these highlights, it'll take a lot of space. @vhyrro thoughts ?
![image](https://user-images.githubusercontent.com/5306901/209661637-94752a9a-1bb5-41e2-b7c5-8d35aac2eb23.png)

**Comment by Apeiros-46B** [comment]
I would also like them to be re-added

**Comment by vhyrro** [comment]
They've now been added in the latest `main`! :)
