### ISSUE TITLE
Better-looking concealer folds

### ISSUE THREAD

**Issue by musjj** [nvim-neorg/neorg#699]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I think a couple of small improvements can be made to the default looks of the folds:
- Make the default ellipsis (`.......`) at the end of a fold customizable
- Retain the highlight color of the heading even when the header is folded

It seems that this is possible using [kevinhwang91/nvim-ufo](https://github.com/kevinhwang91/nvim-ufo), but unfortunately this breaks the behavior of neorg folds.

### Help

No

**Comment by benlubas** [comment]
Neorg uses neovim's builtin folding features. So, just customize default folds and you will reap the benefits in neorg too!

If you don't want to use nvim-ufo (understandably) I use these settings without ufo:

```lua
-- these three are the most important
vim.o.foldmethod = "expr"
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.o.foldtext = ""

vim.o.foldcolumn = "1"
vim.o.foldlevel = 99
vim.o.foldlevelstart = 99
vim.o.foldenable = true

vim.opt.fillchars = {
  eob = " ",
  foldopen = "󰍝",
  foldclose = "󰍟",
  foldsep = " ",
  fold = " ",
}
```

and have folds that look like this:
![image](https://github.com/user-attachments/assets/39a99713-0d39-4b93-bdf5-eb28997baf8c)
