### ISSUE TITLE
Neorg inject metadata still points to version 1.0.0

### ISSUE THREAD

**Issue by aladante** [nvim-neorg/neorg#708]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.0-dev-116-g190019dd7

### Neorg setup
``` lua
require('neorg').setup {
	-- Tell Neorg what modules to load
	load = {
		["core.defaults"] = {}, -- Load all the default modules
		["core.norg.concealer"] = {}, -- Allows for use of icons
		["core.norg.dirman"] = { -- Manage your directories with Neorg
			config = {
				workspaces = {
					home = "~/ToDoList/home/",
					work = "~/ToDoList/werk/",
				},
				autodetect = true,
				autochdir = true,
			}
		},
		["core.integrations.nvim-cmp"] = {
			config = { -- Note that this table is optional and doesn't need to be provided
				-- Configuration here
			}
		}
	},
}
```

### Actual behavior

`Neorg inject-metadata` injects version 1.0.0 instead of version 2.0.0

### Expected behavior

Correct version

### Steps to reproduce

Run `Neorg inject-metadata` 

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

Correct the version specifier

**Comment by vhyrro** [comment]
Thanks for the heads up! The `version` key in the metadata signifies the current Norg version, or in other words the version of the file format, not Neorg itself. It was however still incorrect. It now points to the correct revision, which is `1.1.1` :)
