### ISSUE TITLE
`&variable&` modifier is not highlighted

### ISSUE THREAD

**Issue by xfzv** [nvim-neorg/neorg#710]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3

### Neorg setup

```lua
return {
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    dependencies = "nvim-lua/plenary.nvim",
    config = function()
	require("neorg").setup({
	    load = {
	        ["core.defaults"] = {},
		["core.clipboard"] = {},
		["core.clipboard.code-blocks"] = {},
		["core.norg.concealer"] = {
		    config = {
		        dim_code_blocks = {
			    enabled = true,
			    conceal = true,
			    content_only = true,
			    adaptive = true,
			},
			icon_preset = "diamond",
	            },
                },
            },
        })
    end,
}
```

### Actual behavior

All modifiers are highlighted except `&variable&`:
![image](https://user-images.githubusercontent.com/78810647/211881506-cc637b1d-e2d3-4679-9bc1-32c111d56e31.png)

I did run `:Neorg sync-parsers`.

### Expected behavior

`&variable&` is highlighted.

### Steps to reproduce

1. Open any `.norg` file
2. Paste the following from [`specification.norg`](https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg#L1110-L1120):
```
  - \*bold\*: *bold*
  - \/italic\/: /italic/
  - \_underline\_: _underline_
  - \-strike-through\-: -strike-through-
  - \!spoiler\!: !spoiler!
  - \^superscript\^: ^superscript^ (cannot be nested into `subscript`)
  - \,subscript\,: ,subscript, (cannot be nested into `superscript`)
  - \`inline code\`: `inline code` (disables any nested markup - verbatim)
  - \%{** Null Modifier}[null modifier]\%: %null modifier%
  - \$inline math\$: $f(x) = y$ (verbatim)
  - \&variable\&: &variable& (verbatim)
```
3. All modifiers are highlighted except `&variable&` like on screenshot

### Help

None

**Comment by vhyrro** [comment]
This has been fixed now in the latest main!
