### ISSUE TITLE
Mismatch between documentation and implementation for Neorg toc commands

### ISSUE THREAD

**Issue by haoming-li-ling** [nvim-neorg/neorg#717]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

0.8.2

### Neorg setup

Not necessary here. Problem unrelated to the config.

### Actual behavior

`Neorg toc toqflist/inline/split/left/right` all do the same thing, i.e., open a split of the toc on the left.

### Expected behavior

`Neorg toc inline` should generate inline TOC; `Neorg toc right` should generate TOC on the right. Clearly, in the module file, only two commands have the corresponding implementation `Neorg toc left` and `Neorg toc qflist`. The wiki for table of contents generation is outdated (none of the three commands exist in the implementation), and the implementation of `Neorg toc right` is hinted at in the module code but in fact not present.

### Steps to reproduce

Just run those commands from any `norg` file.

### Help

None

**Comment by vhyrro** [comment]
Hey! There was a breaking change to the TOC module a while back, which is why some of the commands no longer exist. The wiki page shows the correct documentation: https://github.com/nvim-neorg/neorg/wiki/TOC. Closing!
