### ISSUE TITLE
Command `:Neorg journal today` throws error `Vim(Write):E212: Can't open file for writing: no such file or directory`

### ISSUE THREAD

**Issue by piyushdivyankar1994** [nvim-neorg/neorg#728]
### Discussed in https://github.com/nvim-neorg/neorg/discussions/725

<div type='discussions-op-text'>

<sup>Originally posted by **piyushdivyankar1994** January 31, 2023</sup>
```
use {
    "nvim-neorg/neorg",
    config = function()
        require('neorg').setup {
            load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.norg.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "~/notes",
                        },
                    },
                },
            },
        }
    end,
    run = ":Neorg sync-parsers",
    requires = "nvim-lua/plenary.nvim",
}
```

This is my config. </div>

**Comment by piyushdivyankar1994** [comment]
PS: I looked in the code, the command doesn't work even when I try to run in directly. Is there an issue with my setup or is this some idiosyncrasy of windows.

**Comment by TheLeoP** [comment]
I'm having this exact same problem and added some details [on the discussion](https://github.com/nvim-neorg/neorg/discussions/725#discussioncomment-4965971)
