### ISSUE TITLE
[BUG] Neorg complains that compe isn't installed, but I don't want it installed

### ISSUE THREAD

**Issue by katawful** [nvim-neorg/neorg#73]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.5.0

### Log Output

Neorg never starts due to this bug so there is no log. The following is the message when opening a neorg file:

```
Error detected while processing /home/kat/.local/share/nvim/site/pack/packer/start/aniseed/plugin/aniseed
.vim:                                                                                                    
line    2:                                                                                               
E5108: Error executing lua [string "luaeval()"]:1: Vim(echoerr):E15: Invalid expression: ...ua/neorg/modu
les/core/integrations/nvim-compe/module.lua:22: nvim-compe not found, aborting...
```

### Branch

master

### Loaded modules

Lua compiled from fennel
```lua
(require("neorg")).setup( {load = {
  ["core.defaults"] = {}, 
  ["core.keybinds"] = {config = {default_keybinds = true, neorg_leader = "<Leader>n"}}, 
  ["core.norg.concealer"] = {}, 
  ["core.norg.dirman"] = {config = {autochdir = true, autodetect = true, workspaces = {my_workspace = "~/neorg"}}}}})
```

### Expected behavior

Neorg should start without nvim-compe just fine

### Actual behavior

Neorg never starts because it expects nvim-compe

### Other information

I am compiling from fennel, but I cannot see a way for the fennel compilation to interfere with Neorg

### Help

Yes

**Comment by quantum-booty** [comment]
I'm getting this error as well, even after :TSUpdate

**Comment by quantum-booty** [comment]
> Experiencing another bug about the parser with the unstable branch:
> 
> ```
> E5108: Error executing lua [string "luaeval()"]:1: Vim(echoerr):E121: Undefined variable: Failed                                                                                                                    
> Error detected while processing BufEnter Autocommands for "*.norg":                                                                                                                                                 
> E5108: Error executing lua Failed to load parser: uv_dlopen: /home/kat/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/norg.so: undefined symbol: tree_sitter_norg_external_scanner_create          
> Error detected while processing BufEnter Autocommands for "*":                                                                                                                                                      
> E5108: Error executing lua Failed to load parser: uv_dlopen: /home/kat/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/norg.so: undefined symbol: tree_sitter_norg_external_scanner_create          
> Error detected while processing CursorMoved Autocommands for "*":                                                                                                                                                   
> E5108: Error executing lua ...start/nvim-treesitter-context/lua/treesitter-context.lua:236: Vim(lua):E5108: Error executing lua Failed to load parser: uv_dlopen: /home/kat/.local/share/nvim/site/pack/packer/start
> /nvim-treesitter/parser/norg.so: undefined symbol: tree_sitter_norg_external_scanner_create                                                                                                                         
> Error detected while processing WinScrolled Autocommands for "*":                                                                                                                                                   
> E5108: Error executing lua Failed to load parser: uv_dlopen: /home/kat/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/norg.so: undefined symbol: tree_sitter_norg_external_scanner_create          
> Failed to get context: Failed to load parser: uv_dlopen: /home/kat/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/norg.so: undefined symbol: tree_sitter_norg_external_scanner_create     
> ```
> 
> I initially just updated the plugin, but even deleting my plugin path and starting them all from scratch I still get this

@vhyrro I'm getting this error as well, even after :TSUpdate, :PluginUpdate, and updating to the latest nightly nvim.

**Comment by quantum-booty** [comment]
I just read this thread: https://github.com/vhyrro/neorg/issues/74
After following the instruction, uninstalling and installing the parser fixed it.
