### ISSUE TITLE
Term link throws a treesitter query "invalid structure" error

### ISSUE THREAD

**Issue by fkkehlet** [nvim-neorg/neorg#733]
### Prerequisites

- [x] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

v0.8.1

### Neorg setup

require'neorg'.setup {
    load = {
        ['core.defaults'] = {},
    },
}

### Actual behavior

$ Term
Lorem ipsum

{$ Term}

When pressing enter on a term link as written above, this error appears:

<img width="1680" alt="Screenshot 2023-02-04 at 01 32 54" src="https://user-images.githubusercontent.com/107796071/216735077-0136635b-1a57-4cb3-8fb2-14ff1ae746ba.png">

### Expected behavior

Go to the term definition

### Steps to reproduce

It happens in all of my files, even newly created ones

### Other information

MacOS !!

### Help

None

**Comment by fkkehlet** [comment]
Looks like I was using Neovim 0.8.1, I will try updating to 0.8.3 to see if it helps.

**Comment by fkkehlet** [comment]
So it seems footnotes aren't working either, but headings do? When running sync-parsers, I get a host of errors, it may be related to this...

<img width="1680" alt="Screenshot 2023-02-04 at 01 58 20" src="https://user-images.githubusercontent.com/107796071/216736605-f90fbda6-96cb-4195-82f5-9d515b020cb2.png">

**Comment by fkkehlet** [comment]
Even after a successful compilation following the advice from https://github.com/nvim-neorg/tree-sitter-norg/issues/7#issuecomment-1291508121 the error still persists.

**Comment by Chris-Mooney852** [comment]
I'm getting the same error
![image](https://user-images.githubusercontent.com/37582214/217107126-47c3debd-06b8-4c02-ba9d-090beb999282.png)

**Comment by vhyrro** [comment]
Sorry for taking so long for a fix! Should be good now as of `3.2.2`, works on my end at least :)

**Comment by fkkehlet** [comment]
Thanks vhyrro! I really do appreciate all the work you do, so don't worry about it taking long!
