### ISSUE TITLE
Range width for code blocks doesn't work

### ISSUE THREAD

**Issue by roland-5** [nvim-neorg/neorg#735]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-869+g964ae205a5

### Neorg setup

```
	use({
		"nvim-neorg/neorg",
		run = ":Neorg sync-parsers", -- This is the important bit!
		config = function()
			require("neorg").setup({
				load = {
					["core.defaults"] = {},
					["core.norg.dirman"] = {
						config = {
							workspaces = {
								dokumenty = "/home/roland/Dokumenty/neorg",
							},
						},
					},
					["core.norg.completion"] = {
						config = {
							engine = "nvim-cmp",
						},
					},
					["core.norg.concealer"] = {
						config = {
							width = "content",
						},
					},
				},
			})
			vim.api.nvim_set_hl(0, "@neorg.tags.ranged_verbatim.code_block", { bg = "#504945" })
		end,
	})
```

### Actual behavior

![ps_20230204165745](https://user-images.githubusercontent.com/44477799/216778851-415a5f55-c233-47ee-b9cb-325e50360e38.png)
![ps_20230204171614](https://user-images.githubusercontent.com/44477799/216778856-877f9e0c-4837-4cfb-8913-2301ba220e47.png)

### Expected behavior

Does anyone else have problem with code blocks lengths? If I understand it correctly (or not :P) if I set `content` for `width` in `dim_code_blocks` configuration section, it should cut all background to text only.

### Steps to reproduce

I tried it on neorg.norg from examples.

### Help

None

**Comment by andreadev-it** [comment]
Hi, in your configuration (as you've posted it) is missing the "dim_code_blocks" section. Try with this concealer configuration:
```lua
       ['core.norg.concealer'] = {
          config = {
             dim_code_blocks = {
               width = 'content'
             }
          }
       },
```

Hope this helped 🙂

**Comment by roland-5** [comment]
Sweet Jesus and for God love... You don't even know how long I was wondering about it. Thank you so much!
