### ISSUE TITLE
Typo in wiki entry on indentation: `core.norg.esupport.indent` -> `core.norg.esupports.indent`

### ISSUE THREAD

**Issue by maxmahlke** [nvim-neorg/neorg#737]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

not applicable

### Neorg setup

not applicable

### Actual behavior

On the wiki page describing the indentation settings

https://github.com/nvim-neorg/neorg/wiki/Indent

Under the header `Overview`, the module is given as `core.norg.esupport.indent`. 

### Expected behavior

It should be `core.norg.esupports.indent` instead.

### Steps to reproduce

not applicable

### Help

None

**Comment by vhyrro** [comment]
Ah yeah, good catch! Fixed it :)
