### ISSUE TITLE
Neorg export to markdown breaks links

### ISSUE THREAD

**Issue by B4mbus** [nvim-neorg/neorg#740]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-843+g860fea1a3 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-10  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -st d=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-co mmon -fdiagnostics-color=always -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_ GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work /neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/wo rk/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src Compiled by runner@fv-az198-341  Features: +acl +tui See ":help feature-compile"     system vimrc file: "$VI

### Neorg setup

```lua
      opts = {
        load = {
          ["core.defaults"] = {}, -- Loads default behaviour
          ["core.highlights"] = {
            config = {
              highlights = {
                modifiers = { escape = "+@spell" },
              }
            },
          },
          ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
          ["core.norg.dirman"] = { -- Manages Neorg workspaces
            config = {
              workspaces = {
                notes = "~/Notes",
              },
            },
          },
          ["core.norg.esupports.metagen"] = {
            config = {
              type = 'auto',
              template = {
                { 'title', '' },
                { 'description', '' },
                { 'authors', 'B4mbus (Daniel Zaradny)' },
                { 'categories', 'notes' },
                { 'created', function() return os.date('%Y-%m-%d') end },
                { 'updated', function() return os.date('%Y-%m-%d') end },
                { 'version', '0.1.0' },
              }
            }
          },
          ["core.export"] = {}
        },
      },
```

### Actual behavior

Sample line:
```norg
  > /It is advised to use 2 or 4 spaces insted of a tab, see {https://fennel-lang.org/style#spacing/}[Fennel style recommendations on spacing]./
```
I am able to open it from neovim with neorg, but once it's exported to markdown, `#` is converted to `%23` and the link is broken. Changing it manually to `#` in the address bar fixes the issue.

### Expected behavior

The hash should probably not be converted.

### Steps to reproduce

Create a link with a hash inside, export the file to markdown, the link will be broken.

### Help

No

**Comment by d-r-a-b** [comment]
#807 is a dupe of this issue, but I would prefer closing this issue since the other one also has a PR associated with it.

Can you please close this when you have the time?

**Comment by B4mbus** [comment]
Sure!
