### ISSUE TITLE
links in the table of contents generated by Neorg toc don't work 

### ISSUE THREAD

**Issue by dark-ether** [nvim-neorg/neorg#742]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-08ebf8d Build type: Release LuaJIT 2.1.0-beta3 Compiled by nixbld  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /nix/store/nk2i6fz6jxcivz94igdyqzxxliy07jm0-neovim-unwrapped-08ebf8d/share/nvim "  Run :checkhealth for more info

### Neorg setup

{
      load = {
        ["core.defaults"] = {},
        ["core.norg.dirman"] = {
          config = {
            workspaces = {
              notes = "\~/.local/share/neorg/notes",
              wiki = "\~/.local/share/neorg/wiki"
            }
          }
        },
        ["core.keybinds"] = {
          config = {
            default_keybinds = false,
          }
        },
        ["core.norg.journal"] = {
          config = {
            workspace = "notes",
          }
        },
      },
    }

### Actual behavior

links on the table of contents generated by Neorg toc can't be followed by calling :Neorg keybind all core.norg.esupports.hop.hop-link

### Expected behavior

links in the toc should link to the relevant heading and be followable

### Steps to reproduce

1. open a norg file with some headings. 
2. generate a toc with :Neorg toc  and 
3. try to follow any link with :Neorg keybind all core.norg.esupports.hop.hop-link

### Potentially conflicting plugins

i have various plugins but none should interfere as none of them modify treesitter
● gitsigns.nvim 8.25ms  start
    ● hydra.nvim 0.29ms  start
    ● lazy.nvim 10.48ms   init.lua
    ● lualine.nvim 12.61ms  start
    ● neoconf.nvim 0.11ms   neodev.nvim
    ● neodev.nvim 0.18ms   init.lua
    ● nvim-lspconfig 4.06ms   neodev.nvim
    ● nvim-treesitter 8.29ms  start
    ● nvim-web-devicons 0.58ms  start
    ● tokyonight.nvim 5.98ms  start
  
  Not Loaded (14)
    ○ LuaSnip 
    ○ hop.nvim 
    ○ instant.nvim 
    ○ leap.nvim   gs
    ○ navigator.lua 
    ○ neogen   Neogen
    ○ neogit 
    ○ neorg   Neorg   norg
    ○ nvim-dap 
    ○ nvim-surround 
    ○ plenary.nvim   telescope.nvim
    ○ sniprun 
    ○ ssr.nvim 
    ○ telescope.nvim 

### Other information

a error message generated from line 129 of the lua/neorg/modules/core/norg/esupports/hop/module.lua file is shown whenever i reproduce the bug 

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by max397574** [comment]
perhaps this is what you're looking for
![image](https://user-images.githubusercontent.com/81827001/218192995-20d7d27e-d323-42c3-9f4b-937c22b726f3.png)

because for me with the default keybindings everything works just fine

**Comment by dark-ether** [comment]
for some reason when i try to call :Neorg keybind all core.norg.qol.toc.hop-toc-link it says that the keybind doesn't exist but if i press CR it indeed does send me to the right heading

**Comment by danymat** [comment]
Hello, that's normal, `core.norg.qol.toc.hop-toc-link` keybind does not exist. It should have been deleted during a refactor.
