### ISSUE TITLE
Link for Binx account is broken

### ISSUE THREAD

**Issue by roland-5** [nvim-neorg/neorg#762]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

...

### Neorg setup

...

### Actual behavior

There is no https://github.com/TheChoudo account. I think his/her(?) account back to old name?

### Expected behavior

...

### Steps to reproduce

...

### Help

None

**Comment by vhyrro** [comment]
You're right! I updated it now to the correct link :)
