### ISSUE TITLE
Promote and Demote Modify Nested Task Levels

### ISSUE THREAD

**Issue by TJ-Adams** [nvim-neorg/neorg#764]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-2204+ge8540c31a-dirty Build type: Release LuaJIT 2.1.0-beta3 Compiled by tj@TJs-Mac-mini.attlocal.net  Features: +acl +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-e8540c3/share/nvim"  Run :checkhealth for more info

### Neorg setup

local status_ok, neorg = pcall(require, "neorg")
if not status_ok then
    return
end

neorg.setup(
    {
        load = {
            ["core.defaults"] = {},
            ["core.norg.concealer"] = {},
            ["core.integrations.telescope"] = {},
            ["core.norg.manoeuvre"] = {},

            ["core.export"] = {
                config = {
                    export_dir = "/tmp/neorg_export/"
                }
            },
            ["core.norg.completion"] = {
                config = {
                    engine = "nvim-cmp",
                }
            },
            ["core.norg.dirman"] = {
                config = {
                    workspaces = {
                        work = "~/.local/notes/work",
                        personal = "~/.local/notes/personal",
                    }
                }
            },
            ["core.keybinds"] = {
                    config = {
                            hook = function(keybinds)
                                    -- Keybinds to make moving sections up and down easily
                                    keybinds.map("norg", "n", "gj", "<cmd>Neorg keybind norg core.norg.manoeuvre.item_down<cr>")
                                    keybinds.map("norg", "n", "gk", "<cmd>Neorg keybind norg core.norg.manoeuvre.item_up<cr>")
                                    keybinds.map("norg", "n", "]s", "<cmd>Neorg keybind norg core.integrations.treesitter.next.heading<cr>")
                                    keybinds.map("norg", "n", "[s", "<cmd>Neorg keybind norg core.integrations.treesitter.previous.heading<cr>")
                            end,
                    }
            }
        }
    }
)

### Actual behavior

When promoting or demoting a header (marked by *), any subtask levels get modified when they shouldn't. Please see attached video. My attached video only shows a level 1 heading being increased to a level 2, but the same is true if you go in reverse direction.

https://user-images.githubusercontent.com/38332172/221453143-a4d6af1c-d4dd-4a4d-9819-412b263c5774.mov

### Expected behavior

I expect that if you promote or demote a heading that the subtask level will remain unchanged.

### Steps to reproduce

You can use a simple example consisting of

```
* Test Heading
- ( ) Task
-- ( ) Subtask
```

Following that move the cursor to the heading and run the command `:Neorg keybind norg core.promo.promote nexted<CR>` and then see the bug.

### Help

Yes

### Implementation help

If you'd like me to fix it, I can take a crack at it. It won't be tomorrow though, and may even have to be at the weekend, but I'd be willing. The bug I'm assuming is somewhere in `lua/neorg/modules/core/promo/module.lua`.  I may have questions as I look through, but I can message you on the Discord.

**Comment by vhyrro** [comment]
This has been fixed as the promo module has received a rewrite, closing! :)
