### ISSUE TITLE
Concealer doesn't work for specific things

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [nvim-neorg/neorg#769]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

v0.8.3

### Neorg setup

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {},
    ["core.norg.concealer"] = {},
    ["core.norg.dirman"] = { 
      config = {
        workspaces = { notes = "~/notes" },
        default_workspace = "notes",
      }
    }
  }
}
```

### Actual behavior

The concealer works for only a few things.

![image](https://user-images.githubusercontent.com/44822875/221870760-ddbf861c-26fa-4aa8-863d-83c2789ee5f6.png)

This is what I have, and the only thing that actually changes are the underline under well the word "underline" and "link". 

### Expected behavior

I expect concealer to work just fine. Not just for underlines. As you can see in the image, only an underline is seen in the screenshot.

### Steps to reproduce

1. Install via packer with this
```lua
	use {
		"nvim-neorg/neorg",
		requires = "nvim-lua/plenary.nvim",
	}
```

2. Create a config file name it whatever you want and place this code in.

```lua
require('neorg').setup {
  load = {
    ["core.defaults"] = {},
    ["core.norg.concealer"] = {},
    ["core.norg.dirman"] = { 
      config = {
        workspaces = { notes = "~/notes" },
        default_workspace = "notes",
      }
    }
  }
}
```

3. Quit and enter nvim then run `:Neorg sync-parsers`.

### Other information

When I copy and pasted the installation example in the README for packer.nvim and installed it, the error I get is that the command `:Neorg sync-parsers` doesn't exist. This is the exact error message.
```
[packer.nvim] [ERROR 21:48:11] async.lua:20: Error in coroutine: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:236: Vim:E4
92: Not an editor command: Neorg sync-parsers
```
Because of this error, I have to manually run the command. I tried following various other issues but it didn't help. I found and issue that talked about colorscheme issues and I use Kanagawa, one of the maintainers also use Kanagawa so I don't see why I have this issue.

### Help

None

**Comment by max397574** [comment]
:h conceallevel

**Comment by AlphabetsAlphabets** [comment]
> :h conceallevel

Set it to 2 and that works, thanks.
