### ISSUE TITLE
Renaming links when file name changes.

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [nvim-neorg/neorg#772]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

This one is pretty obvious. So, when you change a file name, all existing links just break. It just creates a new file, with the original name. Instead, have every link be updated to the new file name. This should also apply when the path of the file changes as well.

This was brought up [here](https://github.com/nvim-neorg/neorg/issues/513#issuecomment-1182066892) in the last point. I figured that this would need more attention. FYI I wrote this because I had to rename a file and needed to change the name of the link everywhere.

### Help

No

**Comment by d-r-a-b** [comment]
Temporary workaround using neovim base features. Some limitations but covers a very useful subset.

#### Assumptions
- Single workspace
- Flat directory structure (no subdirs)
- Only concerned about relinking norg links

#### Procedure
- `mv name.norg new_name1.norg`
- `nvim *.norg`
- `:argdo %s/\v\{:name:/{:new_name:/g`

It's useful to combine this with `git`. Commit everything, then do the above, then `git diff` to see the changes.

**Comment by benlubas** [comment]
https://github.com/benlubas/neorg-interim-ls

@AlphabetsAlphabets
