### ISSUE TITLE
Open looking glass in tangled code block deletes the @code line

### ISSUE THREAD

**Issue by sbstratos79** [nvim-neorg/neorg#777]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"        System vimrc: "$VIM/sysinit.vim"        Default $VIM: "/usr/share/nvim"

### Neorg setup

```
return {
    "nvim-neorg/neorg",
    lazy = false,
    -- tag = "v2.0.1",
    build = ":Neorg sync-parsers",
    ft = "norg",
    opts = {
        load = {
            ["core.defaults"] = {}, -- Loads default behaviour
            ["core.norg.concealer"] = {
                config = {
                    icon_preset = "diamond",
                }
            },                       -- Adds pretty icons to your documents
            ["core.norg.dirman"] = { -- Manages Neorg workspaces
                config = {
                    workspaces = {
                        notes = "~/Documents/neorg",
                    },
                    default_workspace = "notes",
                },
            },
            ["core.keybinds"] = {       -- Custom keybinds
                config = {
                    neorg_leader = ",", -- Set custom neorg leader key
                    hook = function(keybinds)
                        keybinds.map("norg", "n", "<C-c><C-c>",
                            "<cmd>Neorg keybind all core.looking-glass.magnify-code-block<cr>")
                    end,
                },
            },
            ["core.norg.qol.todo_items"] = {
                config = {
                    create_todo_items = true,
                }
            }
        },
    },
    dependencies = { { "nvim-lua/plenary.nvim" } },
}
```
### Actual behavior

Opening the looking glass deletes the `@code` line from the code block.

https://user-images.githubusercontent.com/4395586/224987338-a05d3847-d54d-4b68-8a20-fb9b8583efc4.mp4

### Expected behavior

`@code` line shouldn't be deleted.

### Steps to reproduce

- Create a tangled code block.
- Use `:Neorg keybind all core.looking-glass.magnify-code-block` or a hotkey to open the code block in a looking glass.
- `@code` line is removed.

### Other information

Also, for some reason, tangling a code block also makes the `@code` line visible in the code block. `conceallevel` is set to 1.
A normal code block doesn't exhibit this behavior. If this is a bug, please let me know so I can create a new issue.

### Help

No

**Comment by danymat** [comment]
Hello, this bug should be fixed. Can you try and see it everything is working ?
