### ISSUE TITLE
Add option to disable notifications

### ISSUE THREAD

**Issue by dm9pZCAq** [nvim-neorg/neorg#778]
### Issues

- [x] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Currently when I do `:Neor workspace something` it notifies me without any conditions.

https://github.com/nvim-neorg/neorg/blob/532548b9f444bd1ae6f2efd3edd842282cc79659/lua/neorg/modules/core/norg/dirman/module.lua#L483-L506

I would like to somehow disable this and possibly other `vim.notify`

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by danymat** [comment]
Hello, 

I suggest installing Nvim-notify, that provides a wrapper around the default notify function, with fancy UI. They have an option [here](https://github.com/rcarriga/nvim-notify/blob/50d037041ada0895aeba4c0215cde6d11b7729c4/doc/nvim-notify.txt#L183) allowing you to only show levels above a certain log level.

If more people want a neorg native notification handler, I will consider adding it. Nevertheless, I will update the log level for error notifications.

Please reopen the issue if this don't suffice you :)
regards !
