### ISSUE TITLE
Basic Markup not rendering.

### ISSUE THREAD

**Issue by ola037** [nvim-neorg/neorg#779]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

v0.8.3

### Neorg setup

```
  use {
      "nvim-neorg/neorg",
      config = function()
          require('neorg').setup {
              load = {
                  ["core.defaults"] = {}, -- Loads default behaviour
                  ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
                  ["core.norg.dirman"] = { -- Manages Neorg workspaces
                      config = {
                          workspaces = {
                              notes = "~/notes",
                          },
                          default_workspace = "notes",
                      },
                  },
              },
          }
      end,
      run = ":Neorg sync-parsers",
      requires = "nvim-lua/plenary.nvim",
  }
```

### Actual behavior

Standard markup doesn't render.

![image](https://user-images.githubusercontent.com/120390061/225898776-c5ffe41c-c4a5-4fe2-989e-e02b146879c2.png)

### Expected behavior

For italic/bold and friends to actually render.

### Steps to reproduce

I've tried with empty config except for Neorg + Treesitter with the same result using 2 different computers.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

A place to start, where to look for relevant code and tools/commands to troubleshoot.

**Comment by ola037** [comment]
Fairly likely I'm just missing something obvious.

**Comment by max397574** [comment]
could you try a different colorscheme?

**Comment by ola037** [comment]
Tried removing my colorscheme:

```
--  -- Let's get Solarized.
  use  {
    'svrana/neosolarized.nvim',
    requires = {
      'tjdevries/colorbuddy.nvim'
    },

```

But no change .. ;/ .. Also tried changing between some of the built-in schemes but sadly no change to the markup.

**Comment by ola037** [comment]
Followed a Treesitter troubleshooting tip and did `edit | TSBufEnable highlight`. 

Gave this result:

![image](https://user-images.githubusercontent.com/120390061/226148773-b23996a7-d581-4eab-bb8b-963208ef2135.png)


Aside from still showing the **, /// etc. it looks a fair bit better .. 

Any idea how I could avoid running that magic command on the buffer?

**Comment by ola037** [comment]
Figured it out, was me not configuring Treesitter properly ... Still need to figure out why the **, // etc. still shows and why italic shows as bold.

**Comment by danymat** [comment]
Hello, I'm closing out this issue as it seems resolved and outside of neorg scope. Please reopen it if I'm wrong.
Have a nice day!
