### ISSUE TITLE
Close TOC after jumping to header

### ISSUE THREAD

**Issue by bR3iN** [nvim-neorg/neorg#785]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

While I find the table of contents generated by the `Neorg toc <...>` commands useful for quickly navigating a file, I find it hindering that it the TOC stays open after jumping to a header and continues to take space. I would find it useful if there would be an option to automatically close it after use (or at least to toggle the TOC, so that I don't have to manually navigate back to it to close it).

I would also find it useful if I could open the TOC of the current buffer _in_ the current buffer; this would make TOC-based navigation much more ergonomic without needing space for additional buffers.

I think the situation is very similar to file explorer plugins where there are project drawer plugins like `nerdtree` which provide an interface closer to what other editors/application provide, but also split explorers like [`vim-vinegar`](https://github.com/tpope/vim-vinegar), [`lir.nvim`](https://github.com/tamago324/lir.nvim) and [`oil.nvim`](https://github.com/stevearc/oil.nvim) which focus more on integrating into (Neo)vim's split based interface (with a popular entrypoint into the topic being [this blog post](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/)). Neorg's current TOC interface seems to be focused predominately on a "project drawer"-like workflow.

### Help

Yes

### Implementation help

If we clarify the feature's scope, I could implement it. Since I'm not familiar with the plugin's internals, a few hints on what existing functionality I can/should use and where to find it would be appreciated.

**Comment by vhyrro** [comment]
Hey, this has now been implemented!

Set the `close_after_use` option to `true` in the config to enable the functionality:
```lua
["core.norg.qol.toc"] = {
	config = {
		close_after_use = true,
	},
}
```

If something doesn't work then let me know :)
