### ISSUE TITLE
E492: Not an editor command: Neorg

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neorg/neorg#789]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-1338+g9e7426718

### Neorg setup

```lua
return {
	'nvim-neorg/neorg',
	run = ':Neorg sync-parsers',
	event = 'VeryLazy',
	enabled = true,
	version = '2.0.1',
	setup = function()
		require('neorg').setup({
			load = {
				['core.defaults'] = {},
				['core.norg.concealer'] = {},
				['core.norg.completion'] = {
					config = {
						engine = 'nvim-cmp',
					},
				},
				['core.norg.dirman'] = {
					config = {
						workspaces = {
							notes = '~/Workspace/notes',
						},
					},
				},
			},
		})
	end,
}
```

### Actual behavior

:Neorg throws `E492: Not an editor command: Neorg` error

### Expected behavior

`:Neorg` to prompt to select a sub command

### Steps to reproduce

1) Install the plugin using Lazy.nvmi
2) Fire up Neovim
3) Run `:Lazy` and make sure the plugin is loaded
4) Run `:Neorg`

### Help

No

**Comment by d-r-a-b** [comment]
This is probably a config issue with your plugin manager. `lazy.nvim` doesn't have a `setup` key like packer, instead it uses `config`. Can you see if changing `setup = function` to `config = function` solves your issue?

**Comment by Charging1948** [comment]
_lazy.nvim_ provides a migration guide for _packer.nvim_ users. You can find it [here](https://github.com/folke/lazy.nvim#packernvim)

As @d-r-a-b pointed out, you are using the wrong properties for the _lazy.nvim_ package manager.

**Comment by s1n7ax** [comment]
Sorry. Closing the issue. It should be `config` as mentioned.
