### ISSUE TITLE
Links Don't Seem to Collapse

### ISSUE THREAD

**Issue by xllvrr** [nvim-neorg/neorg#800]
Just trying out Neorg for the first time and tried to use links but it seems like there's an issue with links on my end:

# Plugin Version
- [X] Using latest version of Plugin

# Neovim Version
- [X] Using Neovim 0.8.3-1

# Expected Behavior
'Link to Heading Two' appears as the sole text, which functions as a link

# Actual Behavior
It doesn't really collapse into the link and remains as two separate portions. The link itself does work but it just doesn't collapse properly.

![image](https://user-images.githubusercontent.com/35357732/232206855-8a56d0a1-9a38-42d9-a027-d8d35b9b985c.png)

# Loaded Modules
```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {
            -- config = {
            --     icon_preset = "diamond"
            -- }
        },
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp",
                name = "[Neorg]"
            }
        },
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    Christian = "/mnt/media/Notes/Christian",
                    DnD = "/mnt/media/Notes/DnD",
                    Personal = "/mnt/media/Notes/Personal",
                },
                default_workspace = "Christian"
            }
        }
    }
}
```

**Comment by d-r-a-b** [comment]
`core.norg.concealer` just applies the `conceal` properties, it's up to your neovim config what is actually done to text with the `conceal` property.

`:h conceallevel` and `:h concealcursor`. You probably want `:set conceallevel=2`

**Comment by xllvrr** [comment]
That worked! I wasn't even aware that neovim had a conceal property so it seemed mine wasn't set (and reverted to the default).
Thanks very much for the prompt response
