### ISSUE TITLE
Persistent core.norg.concealer is deprecated in Neorg v3.0.0+ warning

### ISSUE THREAD

**Issue by sergiornelas** [nvim-neorg/neorg#808]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.0

### Neorg setup

local M = {
	"nvim-neorg/neorg",
	ft = "norg",
	cmd = "Neorg",
	dependencies = { "nvim-neorg/neorg-telescope" },
	-- commit = "764dec5de14947f2f5d08bd3e0452324538e9a4d",
}

function M.config()
	-- https://github.com/nvim-neorg/neorg/wiki
	local neorg_ok, neorg = pcall(require, "neorg")
	if not neorg_ok then
		return
	end

	neorg.setup({
		load = {
			["core.defaults"] = {},
			["core.keybinds"] = {
				config = {
					neorg_leader = ",",
					hook = function(keybinds)
						keybinds.remap_event("norg", "n", "\\e", "core.integrations.treesitter.previous.heading")
						keybinds.remap_event("norg", "n", "\\f", "core.integrations.treesitter.next.heading")
						keybinds.remap_event("norg", "n", "g<space>", "core.looking-glass.magnify-code-block")
						keybinds.remap_event("norg", "n", "\\v", "core.itero.next-iteration")
						keybinds.remap_event("norg", "n", ",e", "core.integrations.telescope.find_linkable") -- go to other header from current workspace
						keybinds.remap_event("norg", "n", ",l", "core.integrations.telescope.insert_file_link") -- insert file link from current workspace
						keybinds.remap_event("norg", "n", ",f", "core.integrations.telescope.search_headings") -- current file headers
						keybinds.remap_event("norg", "n", ",nf", "core.integrations.telescope.find_norg_files") -- find files in current workspace, not useful
						keybinds.remap_event("norg", "n", ",s", "core.integrations.telescope.switch_workspace") -- not useful
						keybinds.remap_event("norg", "n", ",L", "core.integrations.telescope.insert_link") -- not working
					end,
					-- default_keybinds = false,
				},
			},
			["core.dirman"] = {
				config = {
					workspaces = {
						wiki = "~/notes/wiki",
						todo = "~/notes/todo",
						data = "~/notes/data",
					},
					-- default_workspace = "wiki",
					-- index = "index.norg",
					-- open_last_workspace = false,
				},
			},
			["core.concealer"] = {
				config = {
					dim_code_blocks = {
						conceal = true,
					},
					icon_preset = "varied",
					icons = {
						todo = {
							cancelled = {
								icon = "❌",
							},
							done = {
								icon = "✅",
							},
							on_hold = {
								icon = "⏸️",
							},
							pending = {
								icon = "🕒",
							},
							recurring = {
								icon = "🔄",
							},
							uncertain = {
								icon = "❔",
							},
							urgent = {
								icon = "⚠️",
							},
						},
					},
				},
			},
			["core.completion"] = {
				config = {
					engine = "nvim-cmp",
				},
			},
			["core.qol.toc"] = {
				config = {
					default_toc_mode = "split",
					toc_split_placement = "right",
				},
			},
			["core.integrations.telescope"] = {},
			["external.context"] = {},
		},
	})
end

return M

### Actual behavior

Even when I updated `["core.norg.concealer"]` to `["core.concealer"]`, the warning message _core.norg.concealer is deprecated_ still appears.

### Expected behavior

Not warning messages once I update `["core.norg.concealer"]` to `["core.concealer"]`.

### Steps to reproduce

Open any neorg file.

### Help

None

**Comment by pysan3** [comment]
It’s actually not your config, nor Neorg but coming from external Neorg-context where that warning is coming from. 

Sry im on the phone and can’t link it correctly but it’s line 44 in the code. 

https://github.com/max397574/neorg-contexts/blob/master/lua/neorg/modules/external/context/module.lua

You’d better create an issue over there. 

Besides, that module does not seem to set `module.setup().requires` correctly (line 15) since it should make concealer a dependency as well.

**Comment by sergiornelas** [comment]
Understood, I created the issue over there. Thanks.
