### ISSUE TITLE
[BUG] Assortment of bugs

### ISSUE THREAD

**Issue by mrossinek** [nvim-neorg/neorg#81]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.6.0-dev+1667-g32024787b

### Log Output

Not applicable

### Branch

unstable

### Loaded modules

Here is my setup:
```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.highlights"] = {},
        ["core.integrations.telescope"] = {},
        ["core.integrations.treesitter"] = {
            config = {
                highlights = {
                    Heading = {
                        ["1"] = {
                            Title = "+TSTitle",
                            Prefix = "+TSTitle",
                        },
                    },
                },
            },
        },
        ["core.keybinds"] = {},
        ["core.norg.concealer"] = {
            config = {
                icons = {
                    heading = {
                        level_1 = {
                            icon = "◉",
                        },
                        level_2 = {
                            icon = "◎",
                        },
                        level_3 = {
                            icon = "○",
                        },
                        level_4 = {
                            icon = "✺",
                        },
                    },
                },
            },
        },
        ["core.norg.completion"] = {
            config = {
                engine = "nvim-cmp",
            },
        },
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    org = "~/Org",
                },
                autodetect = true,
                autochdir = true,
            },
        },
        ["core.norg.esupports"] = {},
    },
}
```

### Expected behavior

This is an assortment of bugs which I encountered while working on #80.

### Escaped markup not always respected
The vim-regex responsible for highlighting attached modifiers can break in cases
where the char is actually escaped:
![screenshot_1630081877](https://user-images.githubusercontent.com/21973473/131167697-43a05d37-f270-45a9-b4e3-c40a5b00e183.png)
- [x] Fixed in #84 

### Concealing of `-` broken
`-` chars at the beginning of lines are being consumed. This breaks unordered
lists, tasks and links as well as the `---` delimiting modifier' appearances.
![screenshot_1630085927](https://user-images.githubusercontent.com/21973473/131167708-d54b715c-5fd1-43ec-a7bb-bded0ca4de57.png)

I believe the reason for this is that pairs like `--` are seen as empty
strikethrough objects which the vim regex then hides.
- [x] Fixed in #84 

### Link modifier should be concealed
I think the link modifier should generally be hidden, otherwise output like the
following is rather illegibile:
![screenshot_1630081956](https://user-images.githubusercontent.com/21973473/131167701-31e938ae-0bd8-4738-b10a-774dfcb88266.png)
- [x] Fixed in #101 

### Nested quotes are not concealed
Nested quotes do not get concealed:
![screenshot_1630085934](https://user-images.githubusercontent.com/21973473/131167709-cbe7dde7-aeca-4ad0-a573-234b439786d6.png)

If we decide to do this, however, we need to discuss how to differentiate a
two-level quote from a drawer. One possibility is to use the box-drawing char
`│` for quotes instead of the pipe. This looks quite nice, especially for
multi-line quotes like this one:
![screenshot_1630085389](https://user-images.githubusercontent.com/21973473/131167702-3eb46ff0-20af-4951-bf00-66691c97100e.png)
- [x] Fixed in #96 

### Missing highlighting for `@embed`
When encountering an `@embed` tag the TS parser outputs `ERROR` as seen below on
the bottom left:
![screenshot_1630085725](https://user-images.githubusercontent.com/21973473/131167706-41acd8ed-680d-41fd-a19a-ae32b5a6d5d3.png)
- [x] Fixed in https://github.com/vhyrro/tree-sitter-norg/pull/11

### ~~Drawers cannot be folded~~
~~I expected drawers to be one of the first objects to be foldable but this does not work right now.~~
Update (07. Sep 2021): Drawers are now a thing of the past. We may however introduce a `@fold` tag in the future.

### Link following partially broken
`<CR>` on links does not work when the link is immediately preceded by an
opening parenthesis like this:
```
My awesome text ([and this reference](https://github.com/)).
```
- [x] Fixed in https://github.com/vhyrro/tree-sitter-norg/pull/11

### Actual behavior

Inlined above

### Help

Yes

### Implementation help

I think with some minor pointers I will be able to address some of these issues.

**Comment by vhyrro** [comment]
i think the best course of action right now is for me to start implementing attached modifiers into the parser (finally lol). That way pretty much all of the problems you described should go away :). I'll start work on this today

**Comment by mrossinek** [comment]
This has now all bugs resolved except for the link modifier, `:`, not being concealed yet (which is more a missing feature than a bug). Do you want to close this in favor of a separate issue to track the status of the link modifier implementation (which is still completely missing from the TS parser)?

**Comment by vhyrro** [comment]
I think we should keep this up for a while longer. It is an assortment of bugs after all :)
