### ISSUE TITLE
Formatting bug when vim.opt.wrap is true

### ISSUE THREAD

**Issue by stickperson** [nvim-neorg/neorg#819]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.0

### Neorg setup

```
  {
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    keys = {
      { "<leader>ni", "<cmd> Neorg index <cr>", "Neorg index" },
    },
    opts = {
      load = {
        ["core.defaults"] = {}, -- Loads default behaviour
        ["core.concealer"] = {
          config = {
            icon_preset = "diamond",
          },
        }, -- Adds pretty icons to your documents
        ["core.dirman"] = { -- Manages Neorg workspaces
          config = {
            default_workspace = "notes",
            workspaces = {
              notes = "~/notes",
            },
          },
        },
      },
    },
    dependencies = { { "nvim-lua/plenary.nvim" } },
  }
```

### Actual behavior

When `vim.opt.wrap` is set to `true`, long links can cause weird formatting issues.

<img width="985" alt="Screenshot 2023-04-26 at 9 53 45 AM" src="https://user-images.githubusercontent.com/3304073/234648036-ab628538-f647-47a2-a279-f418d7fed60e.png">

<img width="538" alt="Screenshot 2023-04-26 at 9 53 32 AM" src="https://user-images.githubusercontent.com/3304073/234648051-3b8b3b0b-f43c-4ccb-9ff6-a104f272af47.png">

### Expected behavior

Links should appear like so:

<img width="236" alt="Screenshot 2023-04-26 at 9 54 13 AM" src="https://user-images.githubusercontent.com/3304073/234648152-3f31933e-ae22-4e15-925c-60ba8a3683a4.png">

### Steps to reproduce

1. Set `vim.opt.wrap` to `true`
2. Create a link with a very long url. See the example in the "Actual Behavior" section.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by d-r-a-b** [comment]
This is not a neorg bug, this is a neovim bug. Please close this issue and see https://www.github.com/neovim/neovim/pull/9496.

**Comment by d-r-a-b** [comment]
Thanks for closing this!

In the meantime, you may find the `{** Anchors}` features of [norg-spec](https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg) helpful to provide a better editing experience. A side benefit of using anchors is that the reading experience is also much improved when reading a plain-text version of your file outside of an editor with `norg` support. This is an example of a recent note I made.

```
@document.meta
title: prg.learn.ci.example.wezterm_repo
description:
authors:
categories:
created: 2023-04-26
updated: 2023-04-26
version: 1.1.1
@end

* The Wezterm Repo
  An amazing role model of CI/CD architecture, encapsulated mostly in the [workflows]

** CD builds on every pull to main, for many Linux distros, MacOS, Windows
   Three builds for each platform: /default/ (for PRs), continuous (nightly), and tag (specific tags)
   - {https://github.com/wez/wezterm/blob/main/.github/workflows/gen_centos9.yml}
   - {https://github.com/wez/wezterm/blob/main/.github/workflows/gen_centos9_continuous.yml}
   - {https://github.com/wez/wezterm/blob/main/.github/workflows/gen_centos9_tag.yml}

   These use the `actions/upload-artifact@v3` action to upload the resulting package file to the workflow

   Examples of how to build on MacOS and Windows in a workflow:
   - {https://github.com/wez/wezterm/blob/main/.github/workflows/gen_macos.yml}
   - {https://github.com/wez/wezterm/blob/main/.github/workflows/gen_windows.yml}

** Helpers for managing issues
   - [no-response] allows you to mark an issue with `label:more-information-needed` and will auto-close the issue if there is no timely response
   -- uses a [.github/no-response.yml] that is outside of `.github/workflows` to configure
   - [lock] locks an issue if it has been closed for more than X days
   -- often users who pile onto a bug report do not provide more information (like OS, commit, software versions, logs) that would help move the issue forward

** Linter for PRs
   - {https://github.com/wez/wezterm/blob/main/.github/workflows/fmt.yml}

  ===

Links
[workflows]{https://github.com/wez/wezterm/tree/main/.github/workflows}
[no-reponse]{https://github.com/wez/wezterm/blob/main/.github/workflows/no-response.yml}
[lock]{https://github.com/wez/wezterm/blob/main/.github/workflows/lock.yml}
[.github/no-response.yml]
```

By putting your links as anchors at the bottom of the doc, you can always `:h G` to go to them. `:h CTRL-O` to jump back to where you were editing. It's not ideal, but it's the best way I've found to work so far if you do want to use conceal heavily. Because neovim only has to hide `[` and `]` characters, the reflow problems are much less apparent.

If you are using softwrap, the following will also improve your experience:

```lua
-- setup softwrap, breaking between words and
-- indenting nicely paragraphs, lists, TODO
vim.opt.wrap = true
vim.opt.linebreak = true -- break on words
vim.opt.breakindent = true -- align wrapped line with previous indent level
vim.opt.breakindentopt = 'list:-1'
vim.opt.formatlistpat = '^\\s*[-~>]\\+\\s\\((.)\\s\\)\\?'
```
