### ISSUE TITLE
concealer broken when promoting first element

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#821]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.0

### Neorg setup

```lua
require('neorg').setup {
	load = {
		["core.defaults"] = {}, -- Loads default behaviour
		["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
		["core.norg.dirman"] = { -- Manages Neorg workspaces
			config = {
				workspaces = {
					notes = "~/notes",
				},
			},
		},
	},
}
```

### Actual behavior

With cursor on the first line with 'a', press '>>' to promote it, then the text becomes messed up:
```
** ◉
   1
***  ◎
    2
******    ✺
```
With the patch of the promo module from https://github.com/nvim-neorg/neorg/pull/817, the text will still be messed up but slightly differently:
```
*◉ a
   1
* ◎ b
    2
*   ✺ c
```
so this is more likely a concealer issue.

### Expected behavior

not messed up:
```
 ◎ a
   1
  ○ b
    2
     ⤷ c
```

Note that, if an empty line is inserted before the first line so that everything starts from the second line:
```

** a
   1
*** b
    2
****** c
```
promoting on the second line with 'a' won't reproduce the bug and everything behaves as expected.

### Steps to reproduce

Open test.norg, type
```
* a
  1
** b
   2
**** c
```
then ESC to enter normal mode, the text being concealed to
```
◉ a
  1
 ◎ b
   2
   ✺ c
```

### Other information

related: https://github.com/nvim-neorg/neorg/issues/292#issuecomment-1523194575

### Help

Yes

**Comment by champignoom** [comment]
The reason seems to be that the "bufwinenter" event is artificially considered to be at position (1,0), which costs the concealing quota on the first line.

**Comment by champignoom** [comment]
[A bigger problem might ](https://github.com/nvim-neorg/neorg/blob/3009adf2cf48aedcbb309d0765e0fbbb64a0fdf4/lua/neorg/modules/core/concealer/module.lua#L1552-L1554)

This is likely not achieving what it's supposed to achieve, because it's located under the `if event.type == "core.autocommands.events.bufwinenter"` branch, where `event.cursor_position` is always `{1,0}`.

Maybe it was meant to be `module.private.debounce_counters[start + 1]`?

**Comment by vhyrro** [comment]
Okay I pushed a commit that (at least on my end) fixes this problem, that was in fact the issue! Please do reopen if it's still broken for you :)
