### ISSUE TITLE
Journal TOC generates wrong paths on Windows

### ISSUE THREAD

**Issue by SteveWolligandt** [nvim-neorg/neorg#830]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-857+g2c5906b55

### Neorg setup

   ``` lua
require('neorg').setup {
 load = {
      ["core.defaults"] = {},
      ["core.autocommands"] = {},
      ["core.export"] = {config={}},
      ["core.export.markdown"] = {config={}},
      ["core.integrations.treesitter"] = {config={}},
      -- ["core.completion"] = {config = {engine="nvim-cmp"}},
      ["core.dirman"] = {
        config = {
          workspaces = {
            notes = "~/notes",
          },
          default_workspace='notes'
        }
      },
      ["core.qol.todo_items"] = {config = {}},
      ["core.esupports.hop"] = {config = {}},
      ["core.concealer"] = {config={}},["core.keybinds"] = {
        config = {}
      },
      ["core.presenter"] = {
        config = { zen_mode = "zen-mode" }
      }
    }
  }
}
```

### Actual behavior

When doing `:Neorg journal today` a file `~\notes\journal\2023\05\02.norg` is being created.

When doing `:Neorg journal toc update` it generates a file like this:

``` lua
* 2023
** May
{:$\journal\2023\05\01:}[01]
{:$\journal\2023\05\02:}[02]
```

Unfortunately when I open one of the links it opens the file `~\notes\journal\$\journal\2023\05\02.norg`

### Expected behavior

Neorg's TOC of the journal should create correct links to individual journals

### Steps to reproduce

``` vim
:Neorg journal today
:Neorg journal toc update
:Neorg journal toc open
```

### Help

No

**Comment by vhyrro** [comment]
Hey, this should be fixed now! It wasn't a bug in the journal per se, but rather in the function that handles expanding the `$` to your desired workspace name.

If it works then feel free to close the issue :)

**Comment by SteveWolligandt** [comment]
Works, awesome! Thanks for the quick help!
