### ISSUE TITLE
undo leaves concealer artifact

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#833]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.0

### Neorg setup

```lua
require('neorg').setup {
	load = {
		["core.defaults"] = {}, -- Loads default behaviour
		["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
		["core.norg.dirman"] = { -- Manages Neorg workspaces
			config = {
				workspaces = {
					notes = "~/notes",
				},
			},
		},
	},
}
```

### Actual behavior

```
◉
```
One header1 icon remains.

### Expected behavior

Buffer should become empty.

### Steps to reproduce

type `* a<Esc>u`

### Other information

Similar to https://github.com/nvim-neorg/neorg/issues/831,, this problem doesn't exist prior to https://github.com/nvim-neorg/neorg/commit/3009adf2cf48aedcbb309d0765e0fbbb64a0fdf4.

### Help

Yes

**Comment by vhyrro** [comment]
This will be a very difficult problem to solve because `nvim_buf_attach` does not properly report undo operations, and this is a known issue without a real expected fix on the Neovim side iirc as it would require a large refactor in the codebase :|
