### ISSUE TITLE
Neorg Concealer does not Conceal

### ISSUE THREAD

**Issue by khazixi** [nvim-neorg/neorg#853]
### Prerequisites

- [x] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"  Run :checkhealth for more info

### Neorg setup

{
    -- BUG: Neorg Concealer is not filling in all symbols
    'nvim-neorg/neorg',
    ft = 'norg',
    build = ":Neorg sync-parsers",
    opts = {
      load = {
        ['core.defaults'] = {},
        ['core.integrations.nvim-cmp'] = {},
        ['core.integrations.treesitter'] = {},
        ['core.completion'] = {
          config = { engine = 'nvim-cmp' }
        },
        ['core.export'] = {},
        ['core.concealer'] = {},
        ['core.highlights'] = {},
        -- ['core.autocommands'] = {},
      }
    },
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-treesitter/nvim-treesitter'
    }
  }

### Actual behavior

Concealer will not display any symbols when toggled on.

### Expected behavior

Concealer should work on all of my .norg files, with the syntax, as it worked perfectly a few days ago (around 3 days ago), this was before the v4.0.0 update though

### Steps to reproduce

I open a Norg file. Concealer was usually on by default, but is not working when I open by default. I then toggle on concealer in order to get it working, and then nothin happens after I run the command.

### Help

No

### Implementation help

How would I get my Neorg Concealer to start displaying correctly again?

**Comment by d-r-a-b** [comment]
Hello! Very hard to tell what could be going wrong with your setup as concealing and highlighting depends on every step in the chain of dependencies working. Since it was working before, it's probably not a terminal issue, but it could still easily be a tree-sitter setup with the compilation of the parser or correctly enabling the modules.

The new wiki doc at https://github.com/nvim-neorg/neorg/wiki/Dependencies is meant to help provide some troubleshooting steps. If that doesn't help out, provide the output of each troubleshooting step from that doc and maybe we can figure out what's going on.

**Comment by d-r-a-b** [comment]
Is this still an open issue for you @khazixi?

**Comment by khazixi** [comment]
I apologize for the late response, I have been busy with exams.

My config for Neorg looks like the following:

```lua
  {
    'nvim-neorg/neorg',
    ft = 'norg',
    build = ":Neorg sync-parsers",
    init = function ()
      vim.o.conceallevel = 2
    end,
    opts = {
      load = {
        ['core.defaults'] = {},
        ['core.concealer'] = {
          config = {
            folds = true,
          }
        },
        ['core.integrations.nvim-cmp'] = {},
        ['core.integrations.treesitter'] = {},
        ['core.completion'] = {
          config = { engine = 'nvim-cmp' }
        },
        -- ['core.export'] = {},
        ['core.highlights'] = {},
        -- ['core.autocommands'] = {},
      }
    },
    dependencies = {
      'nvim-lua/plenary.nvim',
    }
  },
```

I have tried manually setting the conceal level because there is an issue where my concealer does not automatically conceal. It only works when I do one of two things

1) I need to run `:Neorg toggle-concealer` 2 times
2) I need to manually set the conceal level

Granted, once the following steps are run, the concealer works perfectly, however, going through this step previously for concealing is pretty annoying, thus, I was wondering if there was a fix.

**Comment by khazixi** [comment]
UPDATE:

Only the checkboxes seem to not be working

**Comment by max397574** [comment]
can you send the document you're using?

**Comment by khazixi** [comment]
```
* Tech Goals 2023
  ** Steps
     ~ *Core Technologies* - should provide framewoek agnostic skills
     ~ *Frontend Framework* - should give the ability to make complex UIs
     ~ Backend General
     -- *Meta-Frameworks* - completes their respective frontend frameworks
     -- *Backend Framework* - provides the ability to make a dedicated API server
     ~ *Extra* - should be added on need to fix backend issues

  ** Book Todo List
     ~ (x) Eloquent Javascript
     ~ ( ) Refactoring UI


  ** Spring Tech Todo List (Finish by May 30th?)
     ~ (x) HTML Basics
     ~ (x) CSS Basics
     ~ (x) Tailwind Baiscs
     ~ (x) Vite Basics
     ~ (x) Devtools
     ~ (x) Javascript Fundamentals
     --- (x) Classes
     --- (x) Generators
     --- (x) Async Await
     ~ (?) Typescript Basics
     ~ (x) JS Browser API
     ~ (x) NodeJS
 ```

**Comment by vhyrro** [comment]
Hey! In the latest `main` branch the concealer was rewritten from the ground up and is now much more stable. Could you confirm once again if this is still an issue plz?

**Comment by khazixi** [comment]
Concealer does seem to be fixed as it now:

- Conceals on file open
- Fills in bullet points after I leave the line
- Conceals irregardless of the conceal level (conceal level was set to 0)
- Icons no longer bug out after text is deleted

Great job on the concealer fix! It seems that you have fixed a lot of the issues that I have encountered, will report if there is anything else!
