### ISSUE TITLE
`* heading` being always continued even on <cr> 

### ISSUE THREAD

**Issue by hacker-DOM** [nvim-neorg/neorg#857]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.0

### Neorg setup

```lua
    opts = {
      load = {
        ["core.defaults"] = {}, -- Loads default behaviour
        ["core.concealer"] = {}, -- Adds pretty icons to your documents
        ["core.dirman"] = { -- Manages Neorg workspaces
          config = {
            workspaces = {
              notes = "~/Dropbox/notes/neorg",
            },
            default_workspace = "notes",
          },
        },
      },
    },
```

### Actual behavior

I am getting some unexpected behavior. Let me explain:

On nvim --clean, neither headings nor lists have continuation (a la core.itero)

I tried to isolate neorg. The furthest I got was to have just lazy.nvim, lazyvim and neorg. I would have tried only neorg with packadd, but I think lazy's package format is not really compatible with vim8 packages, so I don't think this would work.

So with just these three packages (and the options as above), I get:
- lists are continued only on `<M-CR>` (expected behavior)
- top-level headings are always continued (basically if I have `* hello` and hit enter I get a star)

I tried to disable this by adding

```lua
        ["core.itero"] = {
          config = {
            iterables = {
              "unordered_list%d",
              "ordered_list%d",
              "quote%d",
            },
          },
        },
```

Then Enter still continues them, but now `<M-CR>` throws: "No object to continue! Make sure you're under an iterable item like a list or heading."

It seems like there is some code in lazy.nvim, lazyvim or neorg that is causing these lines beginning with `*` to be continued even on enter. Maybe it's fiddling with some internal vim thing like comment continuation.....

Any ideas?

### Expected behavior

see above.

### Steps to reproduce

see above

### Help

None

**Comment by aldanor** [comment]
Just out of wonder, what happens if you `:setlocal fo-=cro`?

**Comment by alexjp** [comment]
thanks @aldanor !!

reading up on https://neovim.io/doc/user/change.html#fo-table , seems setting fo-=r is what does the trick!
