### ISSUE TITLE
Add Generated Content

### ISSUE THREAD

**Issue by enderger** [nvim-neorg/neorg#86]
In formats such as Org-Mode and RMarkdown, it is possible to use a syntax for generating and displaying data as E.G. tables and graphs. Neorg lacks such functionality, forcing the external creation and embedding of information into a document. In the spirit of avoiding unneeded dependencies, I propose that we use the Lua engine built into Neovim to allow execution of tagged code blocks which generate Neorg markup to e.g. display a generated image.

**Comment by vhyrro** [comment]
This is actually a thing that we have on our TODOs. I know that the format doesn't have inherent support for editing tables and executing code blocks yet. This is actually one of the first features that we have planned for 0.2 :)

**Comment by gzagatti** [comment]
I'm quite excited about this project!

Based on the documentation and this thread, I'm not sure whether you plan to have a feature similar to [Org Babel](https://orgmode.org/worg/org-contrib/babel/intro.html). 

If so, how would the syntax for the results would look like? I can imagine two solutions:

1. A special tag for results like `@results`.

2. Incorporate the results in the same `@code` tag in which the code is defined, perhaps using some breaking syntax eg . `---`

I want to start experimenting with literate programming in `norg` so it would be great to know your views on that.

**Comment by danymat** [comment]
Hello @vhyrro, this feature can directly be related to the new glass module. Is code execution a planned feature ?

**Comment by danymat** [comment]
Closing this as it is (quite) duplicate of #323 (the notable difference is in what do we do with executed code block)
