### ISSUE TITLE
Docs: Inaccurate help tag for Tables

### ISSUE THREAD

**Issue by jakebrinkmann** [nvim-neorg/neorg#885]
https://github.com/nvim-neorg/neorg/blob/238152ab40ec1fb293fae75744942146876ed08f/doc/tags#L33

Hi, I was exploring the docs and `:help neorg-tables` seems to bring me to a page that doesn't talk about tables. I'm not a nvim/lua expert, so I'm not sure how to fix that. 

Seems `doc/tables.norg` has the information I was seeking

**Comment by d-r-a-b** [comment]
Unfortunately, that file should probably be deleted as it was written 2 years ago and does not reflect the current state of Neorg tables, which is: kinda not well-defined atm.

https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg#L446-L463 for the spec. Note that the semantics document still is a major WIP and so there is basically just a small example table in that doc at the moment. These are the pitfalls of working with a young format. I'm not completely sure if there is a good table spec in someone's mind and it just needs to be documented or if it still needs to be designed in a robust way to consider the edge cases appropriately. I know that a major focus of the intent for the table syntax is for it to be much, much more powerful and flexible than markdown-like approaches that attempt to simulate a table-appearance in the text document, but at the cost of nice appearance. I imagine that a faar, faaaaaar, distant feature will be using virtual text to interpret the table syntax and give a nicer preview, but let's not get ahead of things just yet.

**Comment by pysan3** [comment]
> virtual text to interpret the table syntax 

Nui has got a new table feature. It would be nice if we could edit the table with it interactively. 

https://www.reddit.com/r/neovim/comments/13zqq8y/nuinvim_update_nuitable_for_rendering_tablelike/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

**Comment by vhyrro** [comment]
Hi! I removed the tables.norg file and the entry in the help pages. Tables are still largely WIP so there's no point to keep outdated information there :p

@pysan3 nui's table feature looks pretty neat! Unsure if it'll integrate nicely with our usecase, but time will tell. Closing!
