### ISSUE TITLE
Copy and paste does not recognize devicon upon escape

### ISSUE THREAD

**Issue by jakejasey** [nvim-neorg/neorg#892]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0

### Neorg setup

  {
    "nvim-neorg/neorg",
    run = ":Neorg sync-parsers",
    opts = {
      load = {
        ["core.defaults"] = {}, -- Loads default behaviour
        ["core.concealer"] = {}, -- Adds pretty icons to your documents
        ["core.dirman"] = { -- Manages Neorg workspaces
          config = {
            workspaces = {
              notes = "~/notes",
            },
          },
        },
      },
    },
    dependencies = { { "nvim-lua/plenary.nvim" } },
  },

### Actual behavior

When I copy and paste from another norg file into current norg file, the asterisk are not converted to devicon symbols upon hitting escape. 

### Expected behavior

The expected behavior is to be able to copy and paste from other norg files and the devicon recognition to be preserved, and not have to manually retype all the asterisks. 

### Steps to reproduce

Copy and paste sections with asterisks headings from one norg file to another. 

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by champignoom** [comment]
Does https://github.com/nvim-neorg/neorg/pull/834 solves the problem?
