### ISSUE TITLE
Fitting Code Block Width Doesn't Work

### ISSUE THREAD

**Issue by sdifru** [nvim-neorg/neorg#921]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.1

### Neorg setup

```
["core.concealer"] = {
  config = {
    folds = false,
    dim_code_blocks = {
      width = "content",
    },
  },
},
```

### Actual behavior

![2023-05-31_21-05-1685542945](https://github.com/nvim-neorg/neorg/assets/123437835/32122249-360e-4749-a948-20479a6d325d)

### Expected behavior

The code block width should match the content.

### Steps to reproduce

Set the neorg config as the neorg setup above.

### Help

None

**Comment by champignoom** [comment]
This is part of the breaking change:
```lua
["core.defaults"] = {},
["core.concealer"] = {
    config = {
        icons = {
            code_block = {
                width = "content"
            }
        }
    }
},
```
and it's still not yet stable

**Comment by sdifru** [comment]
@champignoom Got it. I'll close this issue.

**Comment by vhyrro** [comment]
The wiki should soon reflect the new config options that were introduced in the breaking change but there's a bug that I have to fix in it first :)
