### ISSUE TITLE
Concealer rewrite affecting the ability to leverage custom icons

### ISSUE THREAD

**Issue by sLLiK** [nvim-neorg/neorg#922]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.0

### Neorg setup

require("neorg").setup {
        load = {
          ["core.defaults"]                 = {},
          ["core.integrations.treesitter"]  = {},
          ["core.export"]                   = {},
          ["core.export.markdown"]          = {},
          ["core.highlights"]               = {},
          ["core.keybinds"]                 = {},
          ["core.mode"]                     = {},
          ["core.neorgcmd"]                 = {},
          ["core.dirman"]                   = { config = { workspaces = { brain = "~/Neorg", } }, default_workspace = "brain" },
          ["core.concealer"]                = { config = { icons = { todo = { cancelled = { icon = "✗" }},
                                                                            { done      = { icon = "✔" }},
                                                                            { enabled   = { icon = ">" }},
                                                                            { on_hold   = { icon = "" }},
                                                                            { pending   = { icon = "." }},
                                                                            { recurring = { icon = "@" }},
                                                                            { uncertain = { icon = "?" }},
                                                                            { undone    = { icon = "_" }},
                                                                            { urgent    = { icon = "!" }}}}},
          ["core.presenter"]                = { config = { zen_mode   = 'truezen' } }
}

### Actual behavior

![image](https://github.com/nvim-neorg/neorg/assets/458595/5917da58-7a5f-4cab-9e34-7600ea375ece)

### Expected behavior

Continued usage of custom-configured icons by Concealer, with no errors.

### Steps to reproduce

The included config chokes on the concealer directives.  If I comment it out entirely and replace it with ["core.concealer"] = {}, the error goes away and concealer performs normally, with the expected default symbols for tasks.  

My config was working without issues up until very recently.  The latest breaking_changes file states that Concealer was rewritten and that we should review its documentation for new structure, but unless I'm missing something obvious, close inspection shows removal of the "enabled" option under "todo" to be the only applicable change for the config I'm using.  

Simply removing the one line in my Neorg config related to "enabled" does not resolve the issue either, however - I still get the error in the included screenshot.

### Help

None

**Comment by champignoom** [comment]
```lua
["core.concealer"] = {
    config = {
        icons = {
            todo = {
                cancelled = { icon = "✗" },
                done = { icon = "✔" }, -- no wrapping brackets here
                -- enabled = { icon = ">" },  -- no such todo type
                on_hold = { icon = "" }, -- no wrapping brackets here
                pending = { icon = "." }, -- no wrapping brackets here
                recurring = { icon = "@" }, -- no wrapping brackets here
                uncertain = { icon = "?" }, -- no wrapping brackets here
                undone = { icon = "_" }, -- no wrapping brackets here
                urgent = { icon = "!" }, -- no wrapping brackets here
            }
        }
    }
}
```

More informative warning should appear soon.
