### ISSUE TITLE
Concealing of links not correct if link is too long

### ISSUE THREAD

**Issue by tilupe** [nvim-neorg/neorg#929]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.0

### Neorg setup

return {
  {

    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    opts = {
      load = {
        ["core.defaults"] = {},
        ["core.concealer"] = {},
        ["core.dirman"] = {
          config = {
            workspaces = {
              notes = "~/notes",
            },
            default_workspace = "notes",
          },
        },
        ["core.integrations.telescope"] = {},
        ["core.export.markdown"] = {
          extensions = "md",
        },
        ["core.completion"] = {
          engine = "nvim-cmp",
        },
        ["core.manoeuvre"] = {},
        -- ["core.ui.calendar"] = {},
      },
    },
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-neorg/neorg-telescope",
    },
    keys = {
      { "<leader>nl", "<cmd>Telescope neorg insert_file_link<cr>", desc = "Insert file link" },
      { "<leader>nw", "<cmd>Neorg workspace<cr>", desc = "workspace" },
      { "<leader>nn", "<cmd>Neorg keybind<cr>", desc = "New Note" },
      { "<leader>nr", "<cmd>Neorg return<cr>", desc = "Close & return" },
      { "<leader>nt", "<cmd>Telescope neorg<cr>", desc = "Telescope" },
    },
  },
}

### Actual behavior

When a link is longer than the buffer (window) size than the description text will be on the next line

### Expected behavior

No matter how long the inserted link is the "description" should always be at the place where the link was inserted

### Steps to reproduce

Insert a link with a description in a list for example and make the width of the buffer(window) shorter the link

### Help

None

**Comment by champignoom** [comment]
Probably wontfix as it's a problem of neovim itself, see https://github.com/nvim-neorg/neorg/wiki/Dependencies#ugly-line-wraps-when-concealing-text.

**Comment by vhyrro** [comment]
As champignoom said, this is an upstream Neovim issue that unfortunately can't be resolved on our side.
