### ISSUE TITLE
core.journal doesn’t respect flat strategy

### ISSUE THREAD

**Issue by snomics** [nvim-neorg/neorg#930]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-411+g9dd48f783

### Neorg setup

```
require('neorg').setup {
  load = {
    ['core.defaults'] = {},
    ['core.ui.calendar'] = {},
    ['core.highlights'] = {},
    ['core.dirman'] = {
      config = {
        workspaces = {
          perso = '~/neorg/perso',
        },
      },
    },
    ['core.concealer'] = {
      config = {
        icons = {
          heading = {
            icons = { "◉", "○", "󰝣", "▶", "󰔷", "󰁕" },
          },
          code_block = {
            content_only = true,
            width = 'content',
            padding = {
              left = 0,
              right = 0,
            },
            conceal = true,
          },
        },
      },
    },
    ['core.journal'] = {
      config = {
        strategy = flat,
      },
    },
 },
}
```
Edit: fix typo

### Actual behavior

`:Neorg journal` use nested strategy

### Expected behavior

`Neorg journal` use flat strategy to create the journal file

### Steps to reproduce

Set `strategy = 'flat'` in core.journal config = {} according to wiki instruction and launch `:Neorg journal` with custom|today|yesturday|… argument.

### Other information

I’m pretty sure that the flat strategy worked before, but I didn’t use journal lately…

`:Neorg journal custom|today|…` doesn’t detect existing file created with flat strategy.
`:Neorg journal toc open` create a toc with the right files (but only years are displayed with heading)

Not sure it doesn’t come from my config with all the big changes of these days ! Maybe I’ve missed an important change ?

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by snomics** [comment]
I’m really s

**Comment by snomics** [comment]
I’m really sorry for the noise. The problem was from my config. I’ve tested a lot of things and I lost track of changes…
It was just a typo in my config…

**Comment by vhyrro** [comment]
Ah no worries! Happens to the best of us :p
