### ISSUE TITLE
neorg calendar: Make calendar work with smaller resolutions

### ISSUE THREAD

**Issue by TJ-Adams** [nvim-neorg/neorg#941]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-2980+gb8a2220f5-Homebrew Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-b8a2220/share/nvim"  Run :checkhealth for more info

### Neorg setup

neorg.setup(
    {
        load = {
            ["core.defaults"] = {},
            ["core.concealer"] = {},
            ["core.integrations.telescope"] = {},
            ["core.manoeuvre"] = {},
            ["core.journal"] = {},
            ["core.ui.calendar"] = {},

            ["core.export"] = {
                config = {
                    export_dir = "/tmp/neorg_export/"
                }
            },
            ["core.completion"] = {
                config = {
                    engine = "nvim-cmp",
                }
            },
            ["core.dirman"] = {
                config = {
                    workspaces = {
                        work = "~/.local/notes/work",
                        personal = "~/.local/notes/personal",
                    }
                }
            },
            ["core.keybinds"] = {
                    config = {
                            hook = function(keybinds)
                                    -- Keybinds to make moving sections up and down easily
                                    keybinds.map("norg", "n", "gj", "<cmd>Neorg keybind norg core.manoeuvre.item_down<cr>")
                                    keybinds.map("norg", "n", "gk", "<cmd>Neorg keybind norg core.manoeuvre.item_up<cr>")
                                    keybinds.map("norg", "n", "]s", "<cmd>Neorg keybind norg core.integrations.treesitter.next.heading<cr>")
                                    keybinds.map("norg", "n", "[s", "<cmd>Neorg keybind norg core.integrations.treesitter.previous.heading<cr>")

                                    -- Keybinds for the journal module
                                    keybinds.map("norg", "n", "<leader>njc", '<cmd>Neorg journal custom<cr>')
                                    keybinds.map("norg", "n", "<leader>njf", '<cmd>Neorg journal tomorrow<cr>')
                                    keybinds.map("norg", "n", "<leader>njy", '<cmd>Neorg journal yesterday<cr>')

                                    -- Keybinds for the calendar module
                                    keybinds.map("norg", "n", "<leader>nc", '<cmd>:lua neorg.modules.get_module("core.ui.calendar").select_date({})<cr>')
                            end,
                    }
            }
        }
    }
)

### Actual behavior

When opening the Calendar UI I get this error:

E5108: Error executing lua ...org/lua/neorg/modules/core/ui/calendar/views/monthly.lua:266: Invalid 'col': out of range                                       
stack traceback:                                                                                                                                              
        [C]: in function 'nvim_buf_set_extmark'                                                                                                               
        ...org/lua/neorg/modules/core/ui/calendar/views/monthly.lua:266: in function 'render_month'                                                           
        ...org/lua/neorg/modules/core/ui/calendar/views/monthly.lua:296: in function 'render_month_array'                                                     
        ...org/lua/neorg/modules/core/ui/calendar/views/monthly.lua:406: in function 'render_view'                                                            
        ...org/lua/neorg/modules/core/ui/calendar/views/monthly.lua:582: in function 'setup'                                                                  
        ...lazy/neorg/lua/neorg/modules/core/ui/calendar/module.lua:112: in function 'select_date'    
        [string ":lua"]:1: in main chunk          

I did a little digging and the failure occuring on line 266 of the monthly.lua file occurs right when it tries to render day 26. If you look at the screenshot below you'll see that there's no more room for 26 so the failure makes sense.

<img width="391" alt="image" src="https://github.com/nvim-neorg/neorg/assets/38332172/97507388-438e-4788-a758-526dcbec0fb5">

This works on my two other setups but not on my computer connected to my TV. A quick test proved that if I increase the resolution on my Mac Mini to (1920x1080) the problem is fixed. Currently I have it set to (1504x846).

It seems like the UI window set aside to render the calendar just isn't big enough. It's not a huge issue at all but I thought it would be good to have it documented.

### Expected behavior

I expect the full days of the month to render and not stop short prior to then.

### Steps to reproduce

I think the easiest way would be to lower your resolution and/or increase the font size in your terminal so you can't fit as much information on your screen and eventually you should run into this error.

The command to invoke the calendar that I have is.
`:lua neorg.modules.get_module("core.ui.calendar").select_date({})`

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I'd be willing to fix it, but I would mainly like guidance on how you'd want it to be fixed so I don't make a change that you end up having to toss anyways. But I've done a quick initial look and I see that the UI information is passed in to the `render_month` function that has height and width. So we could know prior to rendering the month if we even have enough space to render it.

My initial thought is prior to passing in that UI information to render month when it's decided what the window size will be we check if it's big enough and if not grow it even if it means covering up more of the screen and whatever buffer the user has showing.

Let me know your thoughts and thank you!

**Comment by TJ-Adams** [comment]
Also if anyone else is facing this issue and doesn't want to change their resolution on their screen because that's what they're used to you can use the temp fix that I'm using for now:

You'll have to modify your neorg source. Lazy Nvim installs Neorg by default in: `~/.local/share/nvim/lazy/neorg`

But open up this file: `lua/neorg/modules/core/ui/calendar/module.lua`

In the function `open_window` change the 0.3 to a bigger number to generate a bigger window where you're calendar can fit. You can just play around with the numbers. I only needed a bit more space to show all weeks so I settled on 0.35.

**Comment by vhyrro** [comment]
I can reproduce. Your idea of resizing the window for as many columns as is required is a good idea! Instead of using a set multiplier for the size we could use an algorithm like `minimum_required_columns + padding`. That way the calendar is always sized appropriately, and the user can decide how much top/bottom padding they need with a configurable variable. I'm currently busy with other things, so if you could make a PR that would be fantastic!

**Comment by TJ-Adams** [comment]
I created a pull request [here](https://github.com/nvim-neorg/neorg/pull/950), whenever you have time. No rush!

**Comment by TJ-Adams** [comment]
The fix has now been merged. Closing!
