### ISSUE TITLE
generate-workspace-summary generating erroneous links

### ISSUE THREAD

**Issue by theherk** [nvim-neorg/neorg#952]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Neorg setup

```lua
{
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.concealer"] = {},
          ["core.dirman"] = {
            config = {
              workspaces = {
                main = "~/org/neorg",
                icloud = "~/Library/Mobile Documents/com~apple~CloudDocs/neorg",
                onedrive = os.getenv("NEORG_ONEDRIVE") or "~/Library/CloudStorage/OneDrive/neorg"
              },
              default_workspace = os.getenv("NEORG_DEFAULT_WORKSPACE") or "main"
            },
          },
          ["core.export"] = {
            config = {
              export_dir = "~/org/export/<language>"
            }
          },
          ["core.export.markdown"] = {},
          ["core.integrations.telescope"] = {},
          ["core.journal"] = {
            config = {
              workspace = os.getenv("NEORG_DEFAULT_WORKSPACE") or "main"
            }
          },
          ["core.keybinds"] = {
            config = {
              hook = function(keybinds)
                keybinds.remap_event("norg", "i", "<C-CR>", "core.itero.next-iteration")
                keybinds.remap_event("norg", "n", "<C-CR>", "core.itero.next-iteration")
              end,
            }
          },
          ["core.presenter"] = {
            config = {
              zen_mode = "zen-mode"
            }
          },
          ["core.summary"] = {},
        },
      }
    end,
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      { "nvim-neorg/neorg-telescope" },
    },
  }
```

### Actual behavior

Links generated by `generate-workspace-summary` are as:

```norg
* Index
** Category (with unilateral capitalization convention)
   - {:$/full/basepath:}[Title with unilateral capitalization convention]
```

### Expected behavior

Links generated by `generate-workspace-summary` are as:

```norg
* Index
** Category (with unilateral capitalization convention)
   - {:/full/basepath:}[Title with unilateral capitalization convention]
```

Notice the `$` being removed. These links work. With the dollar sign, they seem to concatenate the path twice first, and the links do not work.

### Steps to reproduce

`:Neorg generate-workspace-summary`

### Other information

As an aside, I don't understand why you don't just accept the capitalization as set by the user. Abbreviations like "ABC" becoming "Abc" by default is an odd choice.

### Help

None

**Comment by laher** [comment]
The `$` is a reference to the workspace root. Its use here was recommended by the project owner, for the case where a summary is generated from a subdirectory.

So, the problem is the link-following code rather than the summary generation. 

I'm not personally familiar enough to know how to debug this part of the code - just that these links are working for me, and I'm using the same version of nvim as you & a recent neorg. 

Maybe try `:Neorg sync-parsers`, in case you've been using a version with a bug in it.

**Comment by theherk** [comment]
I have no idea if something has changed that would address this, but I can say that with the same version, this is no longer an issue for me. The links generated are the same, but the follow correctly. Still feel the same about the capitalization though. I'll close since there doesn't seem to be any work to track here.
