### ISSUE TITLE
insert blank lines when tangling

### ISSUE THREAD

**Issue by rileyshahar** [nvim-neorg/neorg#955]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

By default, when emacs tangles org-mode files, it inserts blank lines between code which originates in different blocks. This behavior makes for more readable output files---not the biggest deal with literate programming, but definitely useful. It's also probably good for the defaults to line up unless there's a reason for them not to.

Thanks for the great software--I'm currently trying to convert my ~2000 line config to norg so I'll probably have more issues to come. Happy to write a PR for this, doesn't seem too difficult.

### Help

Yes

**Comment by jonathf** [comment]
What do we think about expanding upon this idea and have closest heading in a comment as the delimiter where that makes sense?

**Comment by nihilistkitten** [comment]
That requires knowing something about the syntax of the target language, since we need to know what its comments look like, which definitely isn't possible in general. It might make sense as a default-off option for supported filetypes.

**Comment by jonathf** [comment]
You are absolutely right. Limiting the support for this to supported languages makes sense, yes.

I was thinking we on demand temporarily load tangle targets into buffer memory which triggers ftplugin and sets `commentstring`.

**Comment by nihilistkitten** [comment]
Ah, I see. Yeah, seems like it would be cool!

**Comment by jonathf** [comment]
I've pushed out an suggestion in #981 if you're interested.

Continued thought in the same direction:
Since the `commentstring` is available, adding a top-header to the tangled file with information about the tangle job would be nice.

**Comment by vhyrro** [comment]
I like the idea of adding information about a tangle job! @jonathf any extra behaviour with delimiters should definitely be put behind config flags where possible (most likely in the document metadata). The default behaviour should be as simple as can be :)
