### ISSUE TITLE
dirman: `default_workspace` not opening the default workspace

### ISSUE THREAD

**Issue by UtkarshVerma** [nvim-neorg/neorg#966]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.1

### Neorg setup

```lua
{
      load = {
        ["core.defaults"] = {},
        ["core.concealer"] = {},
        ["core.dirman"] = {
          config = {
            workspaces = {
              personal = "~/notes/personal",
              gsoc = "~/notes/gsoc",
            },
            default_workspace = "personal",
          },
        },
      },
    }
```

### Actual behavior

I open a new nvim instance, type "Neorg workspace" but the workspace does not open. I am greeted by a notification though, but no index file is opened.

### Expected behavior

Running `:Neorg workspace` should switch to the default workspace I've set and open the index file.

### Steps to reproduce

- Open nvim
- Run `:Neorg workspace`

https://github.com/nvim-neorg/neorg/assets/31820255/c9f33455-8c03-461a-a86d-bd0356c60707

### Help

No

**Comment by esquires** [comment]
I think you may be looking for `:Neorg index`. This is the command that opens the index file for a workspace. `:Neorg workspace` sets the active workspace if you give it an extra argument or prints out the current workspace without an extra argument. Both of the commands are provided by the [dirman](https://github.com/nvim-neorg/neorg/wiki/Dirman) module.

Here is the source code implementation of these two commands:

`:Neorg workspace`
https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/dirman/module.lua#L453

`:Neorg index`
https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/dirman/module.lua#L479
