### ISSUE TITLE
[SUGGESTION] Reuse selection popup 

### ISSUE THREAD

**Issue by fdschmidt93** [nvim-neorg/neorg#98]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hi there!

Cool project :) I've recently migrated and liking it a lot so far.

One thought I've had looking at #60 is to maybe reuse neogits popup builder system, which looks amazing. Ideally, the system could be upstreamed to plenary such that other projects (including neorg) can lever it. I'm suggesting this of course hoping neogit's maintainer would be OK with this (cc @TimUntersberger)

As initial references:

* Base module: https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/lib/popup/builder.lua
* Push popup: https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/popups/push.lua

### Help

No

### Implementation help

I'd be able to, but helping to maintain and adding features to telescope already takes a lot of my time :sweat_smile: 

But maybe I can look into this some time :)

**Comment by danymat** [comment]
Hello, do you have an example view of this popup, and what are the advantages of using it vs the custom made by @vhyrro ?

**Comment by vhyrro** [comment]
We do actually have our own selection popup already implemented if you weren't aware @fdschmidt93 :D

Neogit's popups look amazing but from what I remember they use raw text in a buffer and functions to add highlights whilst Neorg uses pure extmarks to render the text in the popups. I do agree that extracting such a selection popup into plenary would be great though. Neogit's API for constructing popups seems much nicer than Neorg's too so we may be able to mix the best of both worlds into one.

**Comment by fdschmidt93** [comment]
> We do actually have our own selection popup already implemented if you weren't aware :D

Yes, I'm aware :) Sorry if this is a too ambitious suggestion :sweat_smile: I was raising this because over time upstreaming an abstraction to plenary gets ever more difficult. Again, 100% suggestion, just throw this out the window if this is out-of-scope/too ambitious.

> Neogit's popups look amazing but from what I remember they use raw text in a buffer and functions to add highlights whilst Neorg uses pure extmarks to render the text in the popups. 

Also agree extmarks are preferred :)

> Neogit's API for constructing popups seems much nicer than Neorg's too so we may be able to mix the best of both worlds into one.

I fully agree. That's why I brought this up.

Apologies, I do not mean to take away from your work. I was hoping to get a good discussion rolling into creating the right abstractions  (for the broader community) :)

**Comment by vhyrro** [comment]
> Apologies, I do not mean to take away from your work

No worries dude, you didn't take a single thing away from my work haha

A generic API for all people sounds real awesome. I think people would benefit from it because there are a lot of scenarios where you would like to give the user a choice. I don't know when exactly I'd be able to start work because there's just a tonne of stuff to do and continuously less and less time because of school (not epic). I'll definitely be doing this as kind of like a side project - I'll fork plenary and just start i guess. I'll gladly start on saturday unless someone starts work on it before me in which case I'll just make PRs to that :)

Before that though we should definitely discuss the API itself as you said so we don't get mixed messages lmao.
We should probably stick to the builder philosophy in the way Neogit does it. It's easy to read and easy to make callbacks for, it's also simple to distinguish switches and actual pressable elements in code. We could also then fully use extmarks which would most definitely help in terms of speed and flexibility. I think we could also utilize the Neorg way of using `vim.fn.getchar()` rather than creating 20 keybinds for a buffer to capture input (lmk what you think of this one).

**Comment by fdschmidt93** [comment]
> I think we could also utilize the Neorg way of using vim.fn.getchar() rather than creating 20 keybinds for a buffer to capture input (lmk what you think of this one).

Not sure I agree. It seems too straightforward to have a "mappings manager" ala neogit or telescope that makes it easier to attach your own actions (something like telescope's `attach_mappings` is not yet possible but easily added at first glance). Further, I'm not sure, but i think also UX is better if multiple actions are ran, as the cursor is not locked up (allowing you to e.g. jump back and forth). What would be the benefits over that of `vim.fn.getchar`? 

I'll look at Neogit / neorgs implementations in full detail tomorrow evening and try to share more thoughts here :)

> I'll gladly start on saturday unless someone starts work on it before me in which case I'll just make PRs to that :)

With regards to writing up a PR, I would maybe have time for this to get started next week. Nevertheless, I'm afraid most of my available open source time is spent on telescope (and related plenary) with issues/reviews/and my own PRs there (https://github.com/nvim-telescope/telescope.nvim/pull/1168 will be cool for neorg :)) I'd also be happy to join neorg discord, but the link seems to have vanished from README?

**Comment by vhyrro** [comment]
The link is still there, it's at the top of the README. Just press the discord shield and it'll process the invite :)

> It seems too straightforward to have a "mappings manager" ala neogit or telescope that makes it more ergonomic (flexibility in keybindings, primarily) to attach your own actions (something like telescope's attach_mappings is not yet possible but easily added at first glance).

Yeah I see what you mean regarding keybind flexbility, that's a good point. We might wanna do that in that case then.

**Comment by fdschmidt93** [comment]
> The link is still there, it's at the top of the README. Just press the discord shield and it'll process the invite :)

:facepalm: thanks :D

**Comment by TimUntersberger** [comment]
> One thought I've had looking at #60 is to maybe reuse neogits popup builder system,

Our popup system is very tailored towards our own use case, but I'd be willing to help getting a more generic solution down with a better implementation.

> Neogit's popups look amazing but from what I remember they use raw text in a buffer and functions to add highlights whilst Neorg uses pure extmarks to render the text in the popups.

I'd prefer extmarks 👍

**Comment by danymat** [comment]
You can have a look at https://github.com/nvim-neorg/neorg/pull/99#issuecomment-933011578 for actual implementation of the new UI

**Comment by danymat** [comment]
Since the UI stuff is stable, what are your views of moving it elsewhere ? @vhyrro ?

**Comment by max397574** [comment]
I extracted the selection popup to a separate plugin
can we close this issue @vhyrro ?

**Comment by max397574** [comment]
https://github.com/max397574/selection_popup.nvim

**Comment by vhyrro** [comment]
Yup given that plenary doesn't really want it and that it's extracted into a separate plugin i'd say we can close this issue :)
