### ISSUE TITLE
E434: Can't find tag pattern when using :h neorg + something

### ISSUE THREAD

**Issue by Fissium** [nvim-neorg/neorg#994]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Neorg setup

``` lua
return {
  "nvim-neorg/neorg",
  build = ":Neorg sync-parsers",
  dependencies = { "nvim-lua/plenary.nvim" },
  event = "VeryLazy",
  opts = {
    load = {
      ["core.defaults"] = {}, -- Loads default behaviour
      ["core.concealer"] = {}, -- Adds pretty icons to your documents
      ["core.keybinds"] = {}, -- Adds default keybindings
      ["core.completion"] = {
        config = {
          engine = "nvim-cmp",
        },
      }, -- Enables support for completion plugins
      ["core.journal"] = {}, -- Enables support for the journal module
      ["core.dirman"] = { -- Manages Neorg workspaces
        config = {
          workspaces = {
            notes = "~/Documents/Notes",
          },
          default_workspace = "notes",
        },
      },
    },
  },
}
```

### Actual behavior

![image](https://github.com/nvim-neorg/neorg/assets/35971213/41358455-6661-456c-8878-d370b88c0b46)

### Expected behavior

No errors

### Steps to reproduce

run h: neorg

### Other information

I use Astronvim Neovim config

### Help

None

**Comment by vhyrro** [comment]
Hey, this should now be fixed! If there's still anything wrong then feel free to reopen :)
